/*
 * 運送会社帳票用SQL
 *
 * entityName=CarryListForReport
 * packageName=carrylistforreport
 * methodName=getListForReport
 *
 */

SELECT
  CARRY.CARRY_CD
, CARRY.CARRY_NAME1
, CARRY.CARRY_NAME2
, CARRY.ABBREVIATION
, CARRY.ZIPCODE_NO
, CARRY.TEL_NO
, CARRY.FAX_NO
, CARRY.ADDRESS1
, CARRY.ADDRESS2
, CARRY.ADDRESS3
, CARRY.FLAN_TRANS_SHOP_CD
, CARRY.BC_PUBLISH_DIVISION
, CARRY.BC_HEADER
, CARRY.BC_FOOTER
, CARRY.BC_NUMBER_OF_DIGIT
, CARRY.REMARKS
, CARRY.TRANCEPORT_LEAD_TIME
, CARRY.COMPANY_CD
, CARRY.LABEL_PUBLISH
, CARRY.INPUTOR_CD
, CARRY.UPDATOR_CD
, CARRY.INPUT_DATE
, CARRY.UPDATE_DATE
, CARRY.LABEL_CD
, CARRY.REPOTR_OUTPUT_NUM
,  USER_SEQUENCES.MIN_VALUE AS BC_NUM_START
,  USER_SEQUENCES.MAX_VALUE AS BC_NUM_END
,  USER_SEQUENCES.LAST_NUMBER AS BC_NUM_PRESENT
,  CASE WHEN USER_SEQUENCES.LAST_NUMBER IS NULL THEN NULL ELSE
	CARRY.BC_HEADER || LPAD( CASE WHEN USER_SEQUENCES.LAST_NUMBER + USER_SEQUENCES.INCREMENT_BY > USER_SEQUENCES.MAX_VALUE 
							THEN USER_SEQUENCES.MIN_VALUE ELSE USER_SEQUENCES.LAST_NUMBER + USER_SEQUENCES.INCREMENT_BY 
							END 
        , CARRY.BC_NUMBER_OF_DIGIT , '0' ) || CARRY.BC_FOOTER
	END AS BC_NUM_NEXT_PUBLISH
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM CARRY
, LOGIN INPUTOR
, LOGIN UPDATOR
, USER_SEQUENCES
WHERE CARRY.CARRY_CD IS NOT NULL

/*IF (condition.srhCarryCd != null) && (condition.srhCarryCd != "")*/
AND (CARRY.CARRY_CD LIKE /*condition.srhCarryCd*/'%' OR CARRY.CARRY_NAME1 LIKE /*condition.srhCarryCd*/'%')
/*END*/

AND CARRY.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND CARRY.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND FUN_GET_CARRY_BC_SEQ_NAME(CARRY.CARRY_CD) = USER_SEQUENCES.SEQUENCE_NAME(+)

ORDER BY CARRY.CARRY_CD


