/*
 * 入金勘定科目一覧検索用SQL
 *
 * entityName=DepositCredit
 * packageName=deposit
 * methodName=getClassificationAccountsList
 *
 */

SELECT MAX(ACCOUNTS.ACCOUNTS_CD) ACCOUNTS_CD, MAX(ACCOUNTS.ACCOUNTS_NAME) ACCOUNTS_NAME
FROM CLASSIFICATION, ACCOUNTS
WHERE CLASSIFICATION.DATA_TYPE = 2 -- 入金
AND CLASSIFICATION.DEBIT_ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD
GROUP BY CLASSIFICATION.DEBIT_ACCOUNTS_CD
ORDER BY CLASSIFICATION.DEBIT_ACCOUNTS_CD
