/*
 * 入金詳細検索用SQL
 *
 * entityName=DepositCredit
 * packageName=deposit
 * methodName=findByCreditNo
 *
 */

SELECT CREDIT.*, ACCOUNTS_NAME, DEBIT_ACCOUNTS_CD ACCOUNTS_CD
FROM CREDIT, ACCOUNTS, CLASSIFICATION
WHERE CREDIT_NO = /*creditNo*/'%'
AND CLASSIFICATION.DATA_TYPE(+) = 2
AND CREDIT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION(+)
AND CLASSIFICATION.DEBIT_ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
ORDER BY ROW_NO
