/*
 * 受払月報
 *
 * entityName=RepInoutMonthlyReport
 * packageName=inoutmonthlyreportforreport
 * methodName=getListForReport
 *
 */

SELECT
	LOCATION_CD
,	LOCATION_NAME
,	FINANCIAL_CLASS_CD
,	ITEM_CD
,	ITEM_NAME
,	STYLE_OF_PACKING
,	KG_OF_FRACTION_MANAGEMENT
,	LM_1, LM_2, LM_3, LM_4
,	IN_1, IN_2, IN_3, IN_4, IN_1+IN_2+IN_3+IN_4 AS IN_ALL
,	OUT_1, OUT_2, OUT_3, OUT_4, OUT_5, OUT_6,OUT_7, OUT_1+OUT_2+OUT_3+OUT_4+OUT_5+OUT_6+OUT_7 AS OUT_ALL
,	NM_1, NM_2, NM_3, NM_4

FROM
(
----全社
SELECT
	'1'	AS LOCATION_CD
,	'全社'	AS LOCATION_NAME
,	ATQ.FINANCIAL_CLASS_CD
,	ITM.ITEM_CD
,	ITM.ITEM_NAME
,	ITM.STYLE_OF_PACKING
,	ITM.KG_OF_FRACTION_MANAGEMENT

	--前月末残
,	nvl((SELECT SUM(LM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS LM_1		--完成在庫
,	0		AS LM_2		--検査待在庫
,	nvl((SELECT SUM(LM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = 'BZ'),0)
			AS LM_3		--返品
,	0		AS LM_4		--検品在庫

	--受入
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=11
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS IN_1		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=12
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS IN_2		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=13
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS IN_3		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=14
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS IN_4		--
	--払出
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=21
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_1	--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=22
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_2
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=23
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S')
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_3
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=24
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_4
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=25
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S')
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_5
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=26
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_6
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=27
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS OUT_7
	--在庫高
,	nvl((SELECT SUM(NM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND (UPPER_LOCATION_CD IN ('BK','B7','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')),0)
			AS NM_1		--完成在庫
,	0		AS NM_2		--検査待在庫
,	nvl((SELECT SUM(NM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = 'BZ'),0)
			AS NM_3		--返品
,	0		AS NM_4		--検品在庫

FROM
	(SELECT * FROM ITEM WHERE ITEM_CD IN 
		(SELECT DISTINCT ITEM_CD FROM REP_MONTHLY_INOUT_RECORD
			WHERE (TARGET_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND TARGET_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM'))
			AND (UPPER_LOCATION_CD IN ('BK','B7','BZ','S') 
			OR   UPPER_LOCATION_CD LIKE 'G%' OR LOCATION_CD LIKE 'E%')
		)
	) ITM
,	ARTICLE_ATTRIBUTE_QUEUE	ATQ

WHERE
	ITM.ITEM_CD = ATQ.ITEM_CD
AND	ITM.VERSION = ATQ.VERSION
AND	ITM.TYPE_DIVISION IN (0,5,6,7)


UNION ALL

-----------------------------------------------------------------------------------
----堺物流センター
SELECT
	'2'			AS LOCATION_CD
,	'堺物流センター'	AS LOCATION_NAME
,	ATQ.FINANCIAL_CLASS_CD
,	ITM.ITEM_CD
,	ITM.ITEM_NAME
,	ITM.STYLE_OF_PACKING
,	ITM.KG_OF_FRACTION_MANAGEMENT

	--前月末残
,	nvl((SELECT SUM(LM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7') ),0)		--
			AS LM_1		--完成在庫
,	0		AS LM_2		--検査待在庫
,	0		AS LM_3		--返品
,	0		AS LM_4		--検品在庫

	--受入
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=11
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS IN_1		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=12
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS IN_2		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=13
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS IN_3		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=14
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS IN_4		--
	--払出
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=21
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_1	--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=22
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_2
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=23
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_3
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=24
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_4
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=25
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_5
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=26
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_6
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=27
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7')),0)
			AS OUT_7
	--在庫高
,	nvl((SELECT SUM(NM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BK','B7') ),0)		--
			AS NM_1		--完成在庫
,	0		AS NM_2		--検査待在庫
,	0		AS NM_3		--返品
,	0		AS NM_4		--検品在庫

FROM
	(SELECT * FROM ITEM WHERE ITEM_CD IN 
		(SELECT DISTINCT ITEM_CD FROM REP_MONTHLY_INOUT_RECORD
			WHERE (TARGET_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND TARGET_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM'))
			AND UPPER_LOCATION_CD IN ('BK','B7') 
		)
	) ITM
,	ARTICLE_ATTRIBUTE_QUEUE	ATQ

WHERE
	ITM.ITEM_CD = ATQ.ITEM_CD
AND	ITM.VERSION = ATQ.VERSION
AND	ITM.TYPE_DIVISION IN (0,5,6,7)

UNION ALL

-----------------------------------------------------------------------------------
----堺物流Ｃ（花王）
SELECT
	'3'			AS LOCATION_CD
,	'堺物流Ｃ（花王）'	AS LOCATION_NAME
,	ATQ.FINANCIAL_CLASS_CD
,	ITM.ITEM_CD
,	ITM.ITEM_NAME
,	ITM.STYLE_OF_PACKING
,	ITM.KG_OF_FRACTION_MANAGEMENT

	--前月末残
,	nvl((SELECT SUM(LM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS LM_1		--完成在庫
,	0		AS LM_2		--検査待在庫
,	0		AS LM_3		--返品
,	0		AS LM_4		--検品在庫

	--受入
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=11
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS IN_1		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=12
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS IN_2		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=13
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS IN_3		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=14
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS IN_4		--
	--払出
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=21
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_1	--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=22
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_2
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=23
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_3
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=24
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_4
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=25
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_5
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=26
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_6
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=27
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS OUT_7
	--在庫高
,	nvl((SELECT SUM(NM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD IN ('BA') ),0)
			AS NM_1		--完成在庫
,	0		AS NM_2		--検査待在庫
,	0		AS NM_3		--返品
,	0		AS NM_4		--検品在庫

FROM
	(SELECT * FROM ITEM WHERE ITEM_CD IN 
		(SELECT DISTINCT ITEM_CD FROM REP_MONTHLY_INOUT_RECORD
			WHERE (TARGET_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND TARGET_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM'))
			AND UPPER_LOCATION_CD IN ('BA')
		)
	) ITM
,	ARTICLE_ATTRIBUTE_QUEUE	ATQ

WHERE
	ITM.ITEM_CD = ATQ.ITEM_CD
AND	ITM.VERSION = ATQ.VERSION
AND	ITM.TYPE_DIVISION IN (0,5,6,7)


UNION ALL

-----------------------------------------------------------------------------------
----ロケーションGとE
SELECT
	TO_CHAR(LOC.LOCATION_CD)	AS LOCATION_CD
,	TO_CHAR(LOC.LOCATION_NAME)	AS LOCATION_NAME
,	ATQ.FINANCIAL_CLASS_CD
,	ITM.ITEM_CD
,	ITM.ITEM_NAME
,	ITM.STYLE_OF_PACKING
,	ITM.KG_OF_FRACTION_MANAGEMENT

	--前月末残
,	nvl((SELECT SUM(LM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)		--
			AS LM_1		--完成在庫
,	0		AS LM_2		--検査待在庫
,	0		AS LM_3		--返品
,	0		AS LM_4		--検品在庫

	--受入
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=11
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS IN_1		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=12
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD= LOC.LOCATION_CD),0)
			AS IN_2		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=13
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS IN_3		--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=14
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS IN_4		--
	--払出
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=21
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_1	--
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=22
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_2
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=23
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_3
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=24
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_4
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=25
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_5
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=26
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_6
,	nvl((SELECT SUM(INOUT_QTY) FROM REP_MONTHLY_INOUT_REPORT A 
		WHERE A.ITEM_CD = ITM.ITEM_CD AND KBN=27
			AND TARGET_MONTH BETWEEN TO_CHAR(TO_DATE(/*dateFrom*/'2009/05','YYYY/MM'),'YYYYMM')
								AND  TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS OUT_7
	--在庫高
,	nvl((SELECT SUM(NM_INVENTORY_QTY) FROM REP_MONTHLY_INOUT_RECORD A 
		WHERE A.ITEM_CD = ITM.ITEM_CD
			AND TARGET_MONTH = TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM')
			AND UPPER_LOCATION_CD = LOC.LOCATION_CD),0)
			AS NM_1		--完成在庫
,	0		AS NM_2		--検査待在庫
,	0		AS NM_3		--返品
,	0		AS NM_4		--検品在庫


FROM
	(SELECT * FROM ITEM WHERE ITEM_CD IN 
		(SELECT DISTINCT ITEM_CD FROM REP_MONTHLY_INOUT_RECORD
			WHERE (TARGET_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2009/09','YYYY/MM'),'YYYYMM')
			AND TARGET_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2009/09','YYYY/MM'),'YYYYMM'))
			AND (UPPER_LOCATION_CD LIKE 'G%' OR UPPER_LOCATION_CD LIKE 'E%')
		)
	) ITM
,	ARTICLE_ATTRIBUTE_QUEUE	ATQ
,	(SELECT DISTINCT ML.UPPER_LOCATION_CD AS LOCATION_CD,LOCATION_NAME
		FROM REP_MONTHLY_INOUT_RECORD ML, LOCATION
		WHERE LOCATION.LOCATION_CD = ML.UPPER_LOCATION_CD
		AND (TARGET_MONTH>=TO_CHAR(TO_DATE(/*dateFrom*/'2009/01','YYYY/MM'),'YYYYMM')
		  OR TARGET_MONTH<=TO_CHAR(TO_DATE(/*dateTo*/'2009/06','YYYY/MM'),'YYYYMM'))
		AND	(ML.UPPER_LOCATION_CD LIKE 'G%' OR ML.UPPER_LOCATION_CD LIKE 'E%')
		ORDER BY ML.UPPER_LOCATION_CD) LOC

WHERE
	ITM.ITEM_CD = ATQ.ITEM_CD
AND	ITM.VERSION = ATQ.VERSION
AND	ITM.TYPE_DIVISION IN (0,5,6,7)

)

WHERE
	LM_1>0 OR LM_2>0 OR LM_3>0 OR LM_4>0
OR	IN_1>0 OR IN_2>0 OR IN_3>0 OR IN_4>0
OR	OUT_1>0 OR OUT_2>0 OR OUT_3>0 OR OUT_4>0 OR OUT_5>0 OR OUT_6>0 OR OUT_7>0
OR	NM_1>0 OR NM_2>0 OR NM_3>0 OR NM_4>0 

ORDER BY
	LOCATION_CD
,	FINANCIAL_CLASS_CD
,	ITEM_CD

