/**
 *
 *
 *
 * entityName=ShippingAutoMake
 * packageName=shipping
 * methodName=getShippingAutoMakeList
 *
*/
SELECT
	ORDER_HEAD.ORDER_NO,
	ORDER_DETAIL.ROW_NO,
	ORDER_DETAIL.ITEM_CD
FROM
	ORDER_HEAD,
	ORDER_DETAIL
WHERE ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO 
--	AND ORDER_DETAIL.ITEM_CD = ITEM.ITEM_CD 
--	AND ITEM.ITEM_CD = ARTICLE_ATTRIBUTE_QUEUE.ITEM_CD 
--	AND ITEM.VERSION = ARTICLE_ATTRIBUTE_QUEUE.VERSION 
--	AND ARTICLE_ATTRIBUTE_QUEUE.KEEP_DIVISION = '1'		-- 預り品では無い場合
--	AND ITEM.DEFAULT_LOCATION NOT LIKE 'G%'				-- 基準保管場所が[外部倉庫]では無い場合
	AND (ORDER_HEAD.ORDER_DIVISION = 1 OR ORDER_HEAD.ORDER_DIVISION = 2)	-- 受注区分が 1:在庫引当 か 2:受注生産の場合
	AND ORDER_DETAIL.SHIPPING_NO IS NULL
	AND (ORDER_HEAD.SCHEDULED_SHIPPING_DATE >= /*shippingDateFrom*/ AND ORDER_HEAD.SCHEDULED_SHIPPING_DATE <= /*shippingDateTo*/)
ORDER BY ORDER_HEAD.CARRY_CD,ORDER_HEAD.ORDER_NO,ORDER_DETAIL.ROW_NO
