/**
 * 出荷指図一覧用SQL
 *
 * @author tosco
 *
 * entityName=ShippingDetailOtherEntity
 * packageName=shipping
 * methodName=getItem
 *
 */
SELECT
    ITEM.ITEM_NAME
,   ITEM.OTHER_COMPANY_CD1
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   ITEM.STYLE_OF_PACKING
,   ARTICLE_ATTRIBUTE_QUEUE.KEEP_DIVISION
FROM
    ITEM ITEM
,   ARTICLE_ATTRIBUTE_QUEUE
WHERE
    ITEM.ITEM_CD = /*itemCd*/
AND ITEM.ITEM_CD = ARTICLE_ATTRIBUTE_QUEUE.ITEM_CD(+)
AND ITEM.VERSION = ARTICLE_ATTRIBUTE_QUEUE.VERSION(+)
