/*
 * Created on 2009/02/18
 *
 * $copyright$
 *
*/

/**
 * 出荷指図入力SQL
 *
 * @author tosco
 *
 * entityName=ShippingDetailOtherEntity
 * packageName=shipping
 * methodName=getEntity
 *
 */
SELECT
    SHEAD.SHIPPING_NO
,   SHEAD.SHIPPING_INSTRUCT_DATE
,   SHEAD.SCHEDULED_SHIPPING_DATE
,   SHEAD.TANTO_CD
,   SHEAD.ORDER_NO
,   SHEAD.ORDER_ROW_NO
,   SHEAD.VENDER_DIVISION
,   SHEAD.VENDER_CD
,   SHEAD.DELIVERY_CD
,   SHEAD.SHIPPING_STATUS
,   SHEAD.ITEM_CD
,   SHEAD.SUMMERY
,   SHEAD.DELIVERY_COMP
,   SHEAD.SHIPPING_RESULT_DATE
,   SHEAD.SHIPPING_SLIP_NO
,   SHEAD.SHIPPING_SLIP_ROW_NO
,   SHEAD.SLIP_PUBLISH_COMP
,   SHEAD.SLIP_PUBLISH_DATE
,   SHEAD.SLIP_SHIPPING_ORDER_COMP
,   SHEAD.SLIP_SHIPPING_ORDER_DATE
,   SHEAD.SLIP_SHIPPING_SCHEDULE_COMP
,   SHEAD.SLIP_SHIPPING_SCHEDULE_DATE
,   SHEAD.SLIP_SHIPPING_TAG_COMP
,   SHEAD.SLIP_SHIPPING_TAG_DATE
,   SHEAD.SLIP_SHIPPING_REQUEST_COMP
,   SHEAD.SLIP_SHIPPING_REQUEST_DATE
,   SHEAD.CARRY_CD
,   SHEAD.SUGGESTED_DELIVERLIMIT
,   SHEAD.CARRY_FARE
,   SHEAD.SENDING_OFF_NUMBER
,   SHEAD.INPUT_DATE
,   SHEAD.INPUTOR_CD
,   SHEAD.UPDATE_DATE
,   SHEAD.UPDATOR_CD
,	DELIVERY.SEARCH_KANA AS DELIVERY_NAME1
,   ITEM.ITEM_NAME
,   ITEM.OTHER_COMPANY_CD1
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   ITEM.STYLE_OF_PACKING
FROM
    SHIPPING SHEAD
,   DELIVERY
,   ITEM ITEM
WHERE
	SHEAD.SHIPPING_NO = /*shippingNo*/
AND	SHEAD.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
AND ITEM.ITEM_CD(+) = SHEAD.ITEM_CD
