/*
 * Created on 2009/01/15
 *
 * $copyright$
 *
*/

/**
 * 各種名称マスタ一覧用SQL
 *
 * @author tosco
 *
 * entityName=MgrecipeName
 * packageName=mgrecipe
 * methodName=getSearchList
 *
 */
SELECT	
		NAMES.NAME_DIVISION
	,	NAMES.NAME_CD
	,	NAMES.NAME01
	,	NAMES.NAME02
	,	NAMES.NAME03
	,	NAMES.NMQTY01
	,	NAMES.NMQTY02
	,	NAMES.NMQTY03
	,	NAMES.NMEFLG1
	,	NAMES.NMEFLG2
	,	NAMES.NMEFLG3
	,	NAMES.NMEFLG4
	,	NAMES.NMEFLG5
	,	NAMES.NMEKBN1
	,	NAMES.NMEKBN2
	,	NAMES.NMEKBN3
	,	NAMES.NMEKBN4
	,	NAMES.NMEKBN5
	,	NAMES.NMEDATE1
	,	NAMES.NMEDATE2
	,	NAMES.NMEDATE3
	,	NAMES.NMEDATE4
	,	NAMES.NMEDATE5
	,	NAMES.NMETIME1
	,	NAMES.NMETIME2
	,	NAMES.NMETIME3
	,	NAMES.NMETIME4
	,	NAMES.NMETIME5
	,	NAMES.NMENUM1
	,	NAMES.NMENUM2
	,	NAMES.NMENUM3
	,	NAMES.NMENUM4
	,	NAMES.NMENUM5
	,	NAMES.NMEVALUE1
	,	NAMES.NMEVALUE2
	,	NAMES.NMEVALUE3
	,	NAMES.NMEVALUE4
	,	NAMES.NMEVALUE5
	,	NAMES.INPUT_DATE
	,	NAMES.INPUTOR_CD
	,	NAMES.UPDATE_DATE
	,	NAMES.UPDATOR_CD
FROM
	NAMES
WHERE
	NAMES.NAME_DIVISION IS NOT NULL
/*IF (( division != null ) && ( division != "" ))*/
	AND NAME_DIVISION = /*division*/'RSTS'
/*END*/

ORDER BY
	NAMES.NAME_DIVISION,
	NAMES.NAME_CD
