/*
 * Created on 2009/01/27
 *
 * $copyright$
 *
*/

/**
 * 各タブの共通ヘッダーデータを主キーで処方ヘッダから取得用SQL
 *
 * @author tosco
 *
 * entityName=RecipeHeader
 * packageName=mgrecipe
 * methodName=getCommonHeader
 *
 */
SELECT
	 RHEAD.RECIPE_CD AS            RECIPE_CD
	,RHEAD.RECIPE_VERSION AS       RECIPE_VERSION
	,RHEAD.RECIPE_NAME AS          RECIPE_NAME
	,RHEAD.ITEM_CD AS              ITEM_CD
    ,ITEM.ITEM_NAME AS             ITEM_NAME
	,RHEAD.PRODUCTION_LINE AS      PRODUCTION_LINE
    ,LINE.PRODUCTION_LINE_NAME AS  PRODUCTION_LINE_NAME
    ,RHEAD.RECIPE_STATUS AS        RECIPE_STATUS
    ,RHEAD.APPROVAL_STATUS AS      APPROVAL_STATUS
    ,RHEAD.ORIGINAL_RECIPE_ID AS   ORIGINAL_RECIPE_ID
    ,RHEAD.RECIPE_USE AS           RECIPE_USE
    ,ITEM.STYLE_OF_PACKING AS      STYLE_OF_PACKING,

    CASE APPROVAL_STATUS
    	WHEN 1 THEN '入力中'
    	WHEN 2 THEN '承認依頼中'
    	WHEN 3 THEN '承認済み'
    	ELSE NULL
    END APPROVAL_STATUS_NAME
FROM
    VALID_ITEM_QUEUE MAX_ITEM,
    LINE LINE,
    VALID_ITEM_QUEUE ITEM,
	RECIPE_HEADER RHEAD
WHERE
		RHEAD.RECIPE_ID = /*recipeId*/30759
    AND RHEAD.RECIPE_TYPE = /*recipeType*/'3'	    --3:基本処方,1:原処方
    AND MAX_ITEM.ITEM_CD(+) = RHEAD.ITEM_CD
    AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITEM.VERSION(+) = MAX_ITEM.VERSION
    AND LINE.PRODUCTION_LINE(+) = RHEAD.PRODUCTION_LINE
