/*
 * Created on 2009/01/14
 *
 * $copyright$
 *
*/

/**
 * 処方ヘッダー情報表示用SQL
 *
 * @author tosco
 *
 * entityName=RecipeHeader
 * packageName=mgrecipe
 * methodName=findByPrimaryKey
 *
 */
SELECT
	 RHEAD.RECIPE_ID AS            RECIPE_ID
	,RHEAD.RECIPE_CD AS            RECIPE_CD
	,RHEAD.RECIPE_VERSION AS       RECIPE_VERSION
	,RHEAD.RECIPE_TYPE AS          RECIPE_TYPE
	,RHEAD.RECIPE_DESCRIPTION AS   RECIPE_DESCRIPTION
	,RHEAD.RECIPE_MEMO AS          RECIPE_MEMO
	,RHEAD.RECIPE_STATUS AS        RECIPE_STATUS
	,RHEAD.RECIPE_USE AS           RECIPE_USE
	,RHEAD.RECIPE_PRIORITY AS      RECIPE_PRIORITY
	,RHEAD.ORIGINAL_RECIPE_ID AS   ORIGINAL_RECIPE_ID
	,RHEAD.PRODUCTION_LINE AS      PRODUCTION_LINE
	,RHEAD.ITEM_CD AS              ITEM_CD
	,RHEAD.MIN_QTY AS              MIN_QTY
	,RHEAD.MAX_QTY AS              MAX_QTY
	,RHEAD.STD_QTY AS              STD_QTY
	,RHEAD.UNIT_QTY AS             UNIT_QTY
	,RHEAD.COST AS                 COST
	,RHEAD.PROCESS_LOSS AS         PROCESS_LOSS
	,RHEAD.SECTION_CD AS           SECTION_CD
	,BUMON.SECTION_NAME AS         SECTION_NAME
	,RHEAD.START_DATE AS           START_DATE
	,RHEAD.END_DATE AS             END_DATE
	,RHEAD.DELETE_FLAG AS          DELETE_FLAG
	,RHEAD.PRINT_FLAG AS           PRINT_FLAG
	,RHEAD.PRINT_DATE AS           PRINT_DATE
	,RHEAD.PRINT_TANTO_CD AS       PRINT_TANTO_CD
	,RHEAD.APPROVAL_STATUS AS      APPROVAL_STATUS
	,RHEAD.APP_TANTO_CD AS         APP_TANTO_CD
	,RHEAD.APP_DATE AS             APP_DATE
	,RHEAD.LAST_APP_TANTO_CD AS    LAST_APP_TANTO_CD
	,RHEAD.LAST_APP_DATE AS        LAST_APP_DATE
	,RHEAD.RECIPE_NAME AS          RECIPE_NAME
	,RHEAD.INPUTOR_CD AS           INPUTOR_CD
	,RHEAD.INPUT_DATE AS           INPUT_DATE
	,RHEAD.UPDATOR_CD AS           UPDATOR_CD
	,RHEAD.UPDATE_DATE AS          UPDATE_DATE
    ,ITEM.ITEM_NAME AS             ITEM_NAME
    ,NAME.NAME01 AS                STATUS_NAME
    ,NAME2.NAME01 AS               UNIT_NAME
    ,LINE.PRODUCTION_LINE_NAME AS  PRODUCTION_LINE_NAME
    ,FORMULA.QTY AS                SUM_QTY
    ,PROC.WATER_WEIGHT AS          WATER_WEIGHT
    ,ITEM.STYLE_OF_PACKING AS      STYLE_OF_PACKING
    ,ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION,

    CASE APPROVAL_STATUS
    	WHEN 1 THEN '入力中'
    	WHEN 2 THEN '承認依頼中'
    	WHEN 3 THEN '承認済み'
    	ELSE NULL
    END APPROVAL_STATUS_NAME
FROM
    (
        SELECT
             RECIPE_ID AS RECIPE_ID
            ,SUM(QTY) AS QTY
        FROM
            RECIPE_FORMULA
        WHERE
                RECIPE_ID = /*recipeId*/30759
            AND LINE_TYPE = -1
        GROUP BY
            RECIPE_ID

    ) FORMULA,
    (
        SELECT
             RECIPE_ID AS RECIPE_ID
            ,SUM(WATER_WEIGHT) AS WATER_WEIGHT
        FROM
            RECIPE_PROCEDURE
        WHERE
            RECIPE_ID = /*recipeId*/30759
        GROUP BY
            RECIPE_ID
    ) PROC,
    VALID_ITEM_QUEUE MAX_ITEM,
    LINE LINE,
    NAMES NAME,
    NAMES NAME2,
    VALID_ITEM_QUEUE ITEM,
	RECIPE_HEADER RHEAD,
	BUMON
WHERE
		RHEAD.RECIPE_ID = /*recipeId*/30759
    AND RHEAD.RECIPE_TYPE = /*recipeType*/'3'	    --3:基本処方,1:原処方
    AND MAX_ITEM.ITEM_CD(+) = RHEAD.ITEM_CD
    AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITEM.VERSION(+) = MAX_ITEM.VERSION
    AND NAME.NAME_DIVISION(+) = 'RSTS'
    AND NAME.NAME_CD(+) = RHEAD.RECIPE_STATUS
    AND LINE.PRODUCTION_LINE(+) = RHEAD.PRODUCTION_LINE
    AND NAME2.NAME_DIVISION(+) = 'UNIT'
    AND NAME2.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
    AND FORMULA.RECIPE_ID(+) = RHEAD.RECIPE_ID
    AND PROC.RECIPE_ID(+) = RHEAD.RECIPE_ID
    AND RHEAD.SECTION_CD = BUMON.SECTION_CD(+)
