/*
 * Created on 2009/02/03
 *
 * $copyright$
 *
*/

/**
 * 処方プロシージャ-工程詳細検索用SQL
 *
 * @author tosco
 *
 * entityName=RecipeProcedure
 * packageName=mgrecipe
 * methodName=getEntity
 *
 */
SELECT
	RECIPE_PROCEDURE.RECIPE_ID
,	RECIPE_PROCEDURE.STEP_NO
,	RECIPE_PROCEDURE.SEQ
,	RECIPE_PROCEDURE.OPERATION_CD
,	RECIPE_PROCEDURE.CONDITION
,	RECIPE_PROCEDURE.REMARK
,	RECIPE_PROCEDURE.NOTES
,	RECIPE_PROCEDURE.MACHINE_TIME
,	RECIPE_PROCEDURE.MAN_TIME
,	RECIPE_PROCEDURE.WORK_TIME
,	RECIPE_PROCEDURE.CONDITION_TEMP
,	RECIPE_PROCEDURE.CONDITION_TIME
,	RECIPE_PROCEDURE.STIR_SPEED1
,	RECIPE_PROCEDURE.STIR_SPEED2
,	RECIPE_PROCEDURE.WATER_WEIGHT
,	RECIPE_PROCEDURE.MAIN_STREAM
--,	RECIPE_PROCEDURE.FILLING_QTY
--,	RECIPE_PROCEDURE.WRAPPING_QTY
,	RECIPE_PROCEDURE.NET
,	RECIPE_PROCEDURE.WEIGHT_MIN
,	RECIPE_PROCEDURE.WEIGHT_MAX
,	RECIPE_PROCEDURE.FILTER
,	RECIPE_PROCEDURE.MESH
,	RECIPE_PROCEDURE.AUTO_CHECKER_MIN
,	RECIPE_PROCEDURE.AUTO_CHECKER_MAX
,	RECIPE_PROCEDURE.GROSS_CHECKER_MIN
,	RECIPE_PROCEDURE.GROSS_CHECKER_MAX
,	RECIPE_PROCEDURE.AUTO_CHECKER_AVE
,	RECIPE_PROCEDURE.GROSS_CHECKER_AVE
,	RECIPE_PROCEDURE.OPENING_TORQUE_MIN
,	RECIPE_PROCEDURE.OPENING_TORQUE_MAX
,	RECIPE_PROCEDURE.CLOSING_TORQUE_MIN
,	RECIPE_PROCEDURE.CLOSING_TORQUE_MAX
,	RECIPE_PROCEDURE.TORQUE_PRESSURE
,	RECIPE_PROCEDURE.AIR_PRESSURE
,	RECIPE_PROCEDURE.VCLOSE_TIME
,	RECIPE_PROCEDURE.HOT_AIR_PRESET_TEMP
,	RECIPE_PROCEDURE.HOT_AIR_PRESSURE
,	RECIPE_PROCEDURE.FIRST_HEAT_SEAL
,	RECIPE_PROCEDURE.SECOND_HEAT_SEAL
,	RECIPE_PROCEDURE.INPUTOR_CD
,	RECIPE_PROCEDURE.INPUT_DATE
,	RECIPE_PROCEDURE.UPDATOR_CD
,	RECIPE_PROCEDURE.UPDATE_DATE
,   OPERATION.OPERATION_NAME
--,	ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT AS JYUTEN_UNIT_DIV		-- 端数管理単位(充填)
--,	ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT AS PACKAGE_UNIT_DIV		-- 運用管理単位(包装)
--,	NAMES_JYUTEN.NAME01 AS JYUTEN_UNIT								-- 充填単位
--,	NAMES_PACKAGE.NAME01 AS PACKAGE_UNIT							-- 包装単位
FROM
    RECIPE_HEADER RECIPE_HEADER
,   RECIPE_PROCEDURE RECIPE_PROCEDURE
,   OPERATION
,	VALID_ITEM_QUEUE ITEM_QUEUE
,	VALID_ITEM_QUEUE MAX_ITEM
,	(SELECT NAME_CD
	 ,		NAME01
	 FROM NAMES
	 WHERE	NAME_DIVISION = 'UNIT'
	) NAMES_JYUTEN
,	(SELECT NAME_CD
	 ,		NAME01
	 FROM NAMES
	 WHERE	NAME_DIVISION = 'UNIT'
	) NAMES_PACKAGE
WHERE
    RECIPE_HEADER.RECIPE_ID = /*recipeId*/30718
AND RECIPE_PROCEDURE.RECIPE_ID = /*recipeId*/30718
AND RECIPE_PROCEDURE.STEP_NO = /*stepNo*/1
AND RECIPE_HEADER.RECIPE_ID = RECIPE_PROCEDURE.RECIPE_ID
AND RECIPE_PROCEDURE.OPERATION_CD = OPERATION.OPERATION_CD(+)
AND RECIPE_HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD(+) 
AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = MAX_ITEM.VERSION(+)
AND ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT = NAMES_JYUTEN.NAME_CD(+)
AND ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT = NAMES_PACKAGE.NAME_CD(+)
