/*
 * Created on 2009/02/03
 *
 * $copyright$
 *
*/

/**
 * 処方フォーミュラ-詳細検索用SQL
 *
 * @author tosco
 *
 * entityName=RecipeFormula
 * packageName=mgrecipe
 * methodName=getEntity
 *
 */
SELECT
	FORMULA.RECIPE_ID
,	FORMULA.STEP_NO
,	FORMULA.LINE_NO
,	FORMULA.SEQ
,	PROCEDURE.SEQ PRO_SEQ
,	FORMULA.LINE_TYPE
,	FORMULA.ITEM_CD
,	FORMULA.QTY
,	FORMULA.COST
,	FORMULA.COST_UNIT
,	FORMULA.REMARK
,	FORMULA.NOTES
,	FORMULA.TONYU
,	FORMULA.TONYUSOKUDO
,	FORMULA.DATAREAD
,	FORMULA.INPUTOR_CD
,	FORMULA.INPUT_DATE
,	FORMULA.UPDATOR_CD
,	FORMULA.UPDATE_DATE
,   ITEM.ITEM_NAME                    AS ITEM_NAME
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   NAME.NAME01                       AS UNIT_NAME
FROM
    RECIPE_PROCEDURE PROCEDURE, RECIPE_FORMULA FORMULA,
    VALID_ITEM_QUEUE MAX_ITEM,
    VALID_ITEM_QUEUE ITEM,
    NAMES NAME
WHERE
	    FORMULA.RECIPE_ID = /*recipeId*/30809
	AND FORMULA.STEP_NO = /*stepNo*/1
	AND FORMULA.LINE_NO = /*lineNo*/1
    AND PROCEDURE.RECIPE_ID = FORMULA.RECIPE_ID
    AND PROCEDURE.STEP_NO = FORMULA.STEP_NO
    AND MAX_ITEM.ITEM_CD(+) = FORMULA.ITEM_CD
    AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITEM.VERSION(+) = MAX_ITEM.VERSION
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
