/*
 * Created on 2009/02/04
 *
 * $copyright$
 *
*/

/**
 * 処方検査-検査タブ検索用SQL
 *
 * @author tosco
 *
 * entityName=RecipeInspection
 * packageName=mgrecipe
 * methodName=getSearchList
 *
 */
SELECT
	RECIPE_INSPECTION.RECIPE_ID
,	RECIPE_INSPECTION.STEP_NO
,	RECIPE_INSPECTION.LINE_NO
,	RECIPE_INSPECTION.SEQ
,	RECIPE_INSPECTION.INSPECTION_CD
,	RECIPE_INSPECTION.DIVISION
,	RECIPE_INSPECTION.VALUE_TYPE
,	RECIPE_INSPECTION.VALUE1
,	RECIPE_INSPECTION.VALUE2
,	RECIPE_INSPECTION.CONDITION
,	RECIPE_INSPECTION.REMARK
,	RECIPE_INSPECTION.NOTES
,	RECIPE_INSPECTION.INPUTOR_CD
,	RECIPE_INSPECTION.INPUT_DATE
,	RECIPE_INSPECTION.UPDATOR_CD
,	RECIPE_INSPECTION.UPDATE_DATE
,	NAMES.NAME01 INSPECTION_NAME
FROM
	RECIPE_INSPECTION
,	NAMES
WHERE RECIPE_INSPECTION.RECIPE_ID = /*recipeId*/
  AND RECIPE_INSPECTION.STEP_NO = /*stepNo*/
  AND NAMES.NAME_DIVISION(+) = 'STDV'
  AND RECIPE_INSPECTION.INSPECTION_CD = NAMES.NAME_CD(+)

ORDER BY
	RECIPE_INSPECTION.SEQ