/*
 * Created on 2009/01/26
 *
 * $copyright$
 *
*/

/**
 * 処方ASPROVA一覧用SQL
 *
 * @author tosco
 *
 * entityName=RecipeAsprova
 * packageName=mgrecipe
 * methodName=findByRecipeId
 *
 */
SELECT
	RECIPE_ASPROVA.RECIPE_ID
,	RECIPE_ASPROVA.RESOUCE_GROUP_CD
,   RECIPE_ASPROVA.OPERATION_GROUP_CD
,	RECIPE_ASPROVA.RESOUCE_CD
,	RECIPE_ASPROVA.YOUINSU
,	RECIPE_ASPROVA.MAEJIKAN
,	RECIPE_ASPROVA.ATOJIKAN
,	RECIPE_ASPROVA.PROCESS_WORK_TIME1
,	RECIPE_ASPROVA.PROCESS_WORK_TIME2
,	RECIPE_ASPROVA.MACHINE_WORK_TIME1
,	RECIPE_ASPROVA.MACHINE_WORK_TIME2
,	RECIPE_ASPROVA.MAN_WORK_TIME1
,	RECIPE_ASPROVA.MAN_WORK_TIME2
,	RECIPE_ASPROVA.RECIPE_PRIORITY
,	RECIPE_ASPROVA.INPUTOR_CD
,	RECIPE_ASPROVA.INPUT_DATE
,	RECIPE_ASPROVA.UPDATOR_CD
,	RECIPE_ASPROVA.UPDATE_DATE
FROM
	RECIPE_ASPROVA
WHERE
	RECIPE_ASPROVA.RECIPE_ID IS NOT NULL
/*IF (( recipeId != null ) && ( recipeId != "" ))*/
	AND	RECIPE_ASPROVA.RECIPE_ID = /*recipeId*/
/*END*/
/*IF (( groupCd != null ) && ( groupCd != "" ))*/
	AND	RECIPE_ASPROVA.RESOUCE_GROUP_CD = /*groupCd*/
/*END*/
/*IF (( resourceCd != null ) && ( resourceCd != "" ))*/
	AND	RECIPE_ASPROVA.RESOUCE_CD = /*resourceCd*/
/*END*/

ORDER BY
      RECIPE_ASPROVA.RECIPE_ID
    , RECIPE_ASPROVA.RESOUCE_GROUP_CD
    , RECIPE_ASPROVA.RESOUCE_CD
