/*
 * 品目詳細用SQL
 *
 * entityName=ConvInventoryItemDetail
 * packageName=convinventory
 * methodName=getEntity
 *
 */

/* Upd 2022.05.19 取得内容の見直し T.Sato Start */
/* SELECT ITEM.ITEM_CD, TYPE_DIVISION, UNIT_OF_OPERATION_MANAGEMENT, KG_OF_FRACTION_MANAGEMENT, KG_CONVERSION_COEFFICIENT */
SELECT ITEM.ITEM_CD
, TYPE_DIVISION
, UNIT_OF_OPERATION_MANAGEMENT
, UNIT_OF_STOCK_CONTROL
, UNIT_OF_FRACTION_MANAGEMENT
, KG_OF_FRACTION_MANAGEMENT
, KG_CONVERSION_COEFFICIENT
/* Upd 2022.05.19 取得内容の見直し T.Sato End   */
FROM ITEM
WHERE ITEM.ITEM_CD = /*itemCd*/'%'


