/*
 * メニューマスタ検索SQL
 *
 * entityName=Menu
 * packageName=menu
 * methodName=getSearchList
 *
 */
SELECT	MENU_HEAD.MENU_ID
,		CASE
			WHEN MENU_HEAD.MENU_TYPE_ID = '1' THEN MENU_HEAD.MENU_NAME
			ELSE 
				CASE
					WHEN PARENT.PARENT_MENU_NAME IS NULL THEN MENU_HEAD.MENU_NAME
					ELSE PARENT.PARENT_MENU_NAME || '：' || MENU_HEAD.MENU_NAME
				END
		END MENU_NAME
FROM	MENU_HEAD 
		LEFT JOIN
			(
			SELECT	MENU_HEAD.MENU_ID
			,		MENU_HEAD.MENU_NAME PARENT_MENU_NAME
			FROM	MENU_HEAD
			WHERE	MENU_HEAD.MENU_TYPE_ID = '1'
			) PARENT
			ON MENU_HEAD.PARENT_MENU_ID = PARENT.MENU_ID
ORDER BY MENU_HEAD.SORT_NO
,		 MENU_HEAD.MENU_TYPE_ID DESC
,		 MENU_HEAD.MENU_ID
