/*
 * 所属・ロール組合せマスタ詳細用SQL
 *
 * entityName=BelongRoleDetail
 * packageName=belongroledetail
 * methodName=getEntity
 *
 */

SELECT BELONG_ROLE.ORGANIZATION_CD, ORGANIZATION_NAME, BELONG_ROLE.POST_ID, POST_NAME, BELONG_ROLE.ROLE_ID, ROLE_NAME
FROM BELONG_ROLE, ORGANIZATION, POST, ROLE
WHERE BELONG_ROLE.ORGANIZATION_CD = /*organizationCd*/'%'
AND	BELONG_ROLE.POST_ID = /*postId*/'1'

AND BELONG_ROLE.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND BELONG_ROLE.POST_ID = POST.POST_ID(+)
AND BELONG_ROLE.ROLE_ID = ROLE.ROLE_ID(+)
