/*
 * entityName=SalesListForReport
 * packageName=saleslistforreport
 * methodName=getListForReport
 *
 */
SELECT
	SALES.SALES_DATE
,	SALES.SALES_NO
,	SALES.CANCEL_SALES_NO
,	SALES.ITEM_CD
,	ITEM.ITEM_NAME
,	ITEM.STYLE_OF_PACKING
,	ITEM.OTHER_COMPANY_CD1
,	SALES.ORGANIZATION_CD
,	ORGANIZATION.ORGANIZATION_NAME
,	SALES.VENDER_CD
,	VENDER.VENDER_NAME1
,	VENDER.VENDER_SHORTED_NAME
,	FNC_GET_UPPER_VENDER(SALES.BALANCE_CD,2) as SEC_VENDER_CD
,	FNC_GET_UPPER_VENDER(SALES.BALANCE_CD,3) as TRD_VENDER_CD
,	SALES.BALANCE_CD
,	SALES.INPUT_TANTO_CD
,	INPUT_LOGIN.TANTO_NM AS INPUT_TANTO_NAME
,	SALES.SALES_TANTO_CD
,	SALES_LOGIN.TANTO_NM AS SALES_TANTO_NAME
,	SALES.PRODUCT_LOTNO
,	SALES.ORDER_NO
,	SALES.ORDER_ROW_NO
,   ORDER_DATA.CUSTOMER_ORDER_NO
,	SALES.SALES_QUANTITY
,	SALES.SALES_UNITPRICE
,	SALES.STANDARD_UNITPRICE
,	SALES.STANDARD_DISCOUNT
,	SALES.SPECIAL_DISCOUNT
,	SALES.TMP_UNITPRICE_FLG
,	SALES.REMARK
,	SALES.DISBURSEMENT_LOCATION_CD
,	DISBURSEMENT_LOCATION.LOCATION_NAME
,	SALES.DELIVERY_COMP
,	SALES.DELIVERY_UPDATE_DATE
,	SALES.INVOICE_UPDATE_DATE
,	SALES.INPUT_DIVISION
,	SALES.DELIVERY_CD
,	DELIVERY.DELIVERY_NAME1
,	DELIVERY.SEARCH_KANA
,	SALES.TAX_DIVISION
,	SALES.TAX_AMOUNT
,	SALES.TAX_CD
,	SALES.INVOICE_CD
,	INVOICE_VENDER.VENDER_NAME1 AS INVOICE_NAME
,	SALES.SALES_AMOUNT
,	SALES.SALES_BASIC
,	SALES.TAX_RATIO
,	SALES.UPDATE_FLG
,	SALES.CONFIG_EXP_RATIO
,	SALES.RATIO_NOTAPPLY_SALES_UNITPRICE
,	SALES.SHIPPING_NO
,	SALES.SALES_SLIP_NO
,	SALES.SALES_SLIP_ROW_NO
,	SALES.SLIP_PUBLISH_COMP
,	SALES.SLIP_PUBLISH_DATE
,	SALES.TRANSMISSION_DATE
,	SALES.LEDGER_POST_DATE
,	SALES.LEDGER_POST_NO
,	SALES.SALES_CONVERT_QUANTITY
,	SALES.ACCEPT_CONVERT_QUANTITY
,	SALES.DATA_TYPE
,	SALES.DATA_TOTAL_DIVISION
,	SALES.CATEGORY_DIVISION
,	SALES.ACCOUNT_YEARS
,	SALES.ACCOUNT_DEBIT_SECTION_CD
,	ACCOUNT_DEBIT_SECTION.SECTION_NAME AS ACCOUNT_DEBIT_SECTION_NAM
,	SALES.ACCOUNT_CREDIT_SECTION_CD
,	ACCOUNT_CREDIT_SECTION.SECTION_NAME AS ACCOUNT_CREDIT_SECTION_NAME
,	SALES.DEBIT_TITLE_CD
,	DEBIT_TITLE_CD.ACCOUNTS_NAME AS DEBIT_TITLE_NAME
,	SALES.DEBIT_SUB_TITLE_CD
,	DEBIT_SUB_TITLE_CD.ACCOUNTS_NAME AS DEBIT_SUB_TITLE_NAME
,	SALES.CREDIT_TITLE_CD
,	CREDIT_TITLE_CD.ACCOUNTS_NAME AS CREDIT_TITLE_NAME
,	SALES.CREDIT_SUB_TITLE_CD
,	CREDIT_SUB_TITLE_CD.ACCOUNTS_NAME AS CREDIT_SUB_TITLE_NAME
,	SALES.DEPOSIT_TARGET_DIVISION
,	SALES.CLAIM_TARGET_DIVISION
,	SALES.SUMMARY_CD
,	SALES.SUMMARY
,	SALES.DEPOSIT_UPDATE_DIVISION
,	SALES.DEPOSIT_NO
,	SALES.CLAIM_UPDATE_DIVISION
,	SALES.CLAIM_NO
,	SALES.ERASER_COMPLETE_DIVISION
,	SALES.ERASER_COMPLETE_DATE
,	SALES.APPROVAL_STATUS
,	SALES.APPROVEDBY
,	SALES.APPROVALDATE
,	SALES.CHARGE_ORGANIZATION_CD
,	CHARGE_ORGANIZATION.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME
,	SALES.KEEP_FLAG
,	SALES.RY_CD
,	REASON.RY_DESCRIPTION
,	SALES.HOUSING_LOCATION_CD
,	HOUSING_LOCATION.LOCATION_NAME AS HOUSING_LOCATION_NAME
,	SALES.PACKAGE_DIRECTION_NO
,	VENDER.SALES_MAIL_OUTPUT
,	VENDER.SALES_FAX_OUTPUT
,	SALES.INPUT_DATE
,	SALES.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	SALES.UPDATE_DATE
,	SALES.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM	SALES
,   (SELECT
           CATEGORY_DIVISION
         , MIN(DATA_TOTAL_DIVISION) AS DATA_TOTAL_DIVISION
      FROM CLASSIFICATION
     WHERE DATA_TYPE = '1'
     GROUP BY CATEGORY_DIVISION
    ) CLASSIFICATION_MIN
,   CLASSIFICATION
,   VENDER
,   VALID_ITEM_QUEUE MAX_ITEM
,   VALID_ITEM_QUEUE ITEM
,	ORGANIZATION
,	ORGANIZATION CHARGE_ORGANIZATION
,	LOGIN INPUT_LOGIN
,	LOGIN SALES_LOGIN
,	LOCATION DISBURSEMENT_LOCATION
,	DELIVERY
,	VENDER INVOICE_VENDER
,	BUMON ACCOUNT_DEBIT_SECTION
,	BUMON ACCOUNT_CREDIT_SECTION
,	ACCOUNTS DEBIT_TITLE_CD
,	ACCOUNTS DEBIT_SUB_TITLE_CD
,	ACCOUNTS CREDIT_TITLE_CD
,	ACCOUNTS CREDIT_SUB_TITLE_CD
,	REASON
,	LOCATION HOUSING_LOCATION
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,   (SELECT ORDER_DETAIL.ORDER_NO,ORDER_DETAIL.ROW_NO,ORDER_HEAD.CUSTOMER_ORDER_NO FROM ORDER_HEAD,ORDER_DETAIL WHERE ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO) ORDER_DATA

WHERE	SALES.SALES_NO IS NOT NULL
AND SALES.ACCOUNT_DEBIT_SECTION_CD = ACCOUNT_DEBIT_SECTION.SECTION_CD(+)
AND SALES.ACCOUNT_CREDIT_SECTION_CD = ACCOUNT_CREDIT_SECTION.SECTION_CD(+)
AND SALES.DEBIT_TITLE_CD = DEBIT_TITLE_CD.ACCOUNTS_CD(+)
AND SALES.DEBIT_SUB_TITLE_CD = DEBIT_SUB_TITLE_CD.ACCOUNTS_CD(+)
AND SALES.CREDIT_TITLE_CD = CREDIT_TITLE_CD.ACCOUNTS_CD(+)
AND SALES.CREDIT_SUB_TITLE_CD = CREDIT_SUB_TITLE_CD.ACCOUNTS_CD(+)
AND SALES.CHARGE_ORGANIZATION_CD = CHARGE_ORGANIZATION.ORGANIZATION_CD(+)
AND SALES.RY_CD = REASON.RY_CD(+)
AND SALES.HOUSING_LOCATION_CD = HOUSING_LOCATION.LOCATION_CD(+)
AND SALES.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND SALES.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND CLASSIFICATION_MIN.CATEGORY_DIVISION(+) = SALES.CATEGORY_DIVISION
AND CLASSIFICATION.DATA_TYPE(+) = '1'
AND CLASSIFICATION.CATEGORY_DIVISION(+)   = CLASSIFICATION_MIN.CATEGORY_DIVISION
AND CLASSIFICATION.DATA_TOTAL_DIVISION(+) = CLASSIFICATION_MIN.DATA_TOTAL_DIVISION
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND VENDER.VENDER_CD(+) = SALES.VENDER_CD
AND DELIVERY.DELIVERY_CD(+) = SALES.DELIVERY_CD
AND MAX_ITEM.ITEM_CD(+) = SALES.ITEM_CD
AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
AND ITEM.VERSION(+) = MAX_ITEM.VERSION
AND SALES.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND SALES.INPUT_TANTO_CD = INPUT_LOGIN.TANTO_CD(+)
AND SALES.SALES_TANTO_CD = SALES_LOGIN.TANTO_CD(+)
AND SALES.DISBURSEMENT_LOCATION_CD = DISBURSEMENT_LOCATION.LOCATION_CD(+)
AND SALES.INVOICE_CD = INVOICE_VENDER.VENDER_CD(+) AND INVOICE_VENDER.VENDER_DIVISION(+) = 'TS'
AND SALES.ORDER_NO = ORDER_DATA.ORDER_NO(+)
AND SALES.ORDER_ROW_NO = ORDER_DATA.ROW_NO(+)

/*IF (( condition.srhSalesNo != null ) && ( condition.srhSalesNo != "" ))*/
	AND	SALES.SALES_NO LIKE /*condition.srhSalesNo*/''
/*END*/

/*IF (( condition.srhCategoryDivision != null ) && ( condition.srhCategoryDivision != "" ))*/
	/*IF (condition.srhCategoryDivision == "0")*/
		/*IF (condition.srhCancelFlg)*/
			AND	SALES.CATEGORY_DIVISION < 0 
		/*END*/
		/*IF (!condition.srhCancelFlg)*/
			AND	SALES.CATEGORY_DIVISION <> 0 
		/*END*/
	/*END*/
	/*IF (condition.srhCategoryDivision != "0")*/
		/*IF (condition.srhCancelFlg)*/
			/*IF (condition.srhCategoryDivision == "1")*/
				AND	(SALES.CATEGORY_DIVISION = -1 OR SALES.CATEGORY_DIVISION = -11)
			/*END*/
			/*IF (condition.srhCategoryDivision == "2")*/
				AND	(SALES.CATEGORY_DIVISION = -2 OR SALES.CATEGORY_DIVISION = -12)
			/*END*/
			/*IF (condition.srhCategoryDivision == "3")*/
				AND	(SALES.CATEGORY_DIVISION = -3 OR SALES.CATEGORY_DIVISION = -13)
			/*END*/
			/*IF (condition.srhCategoryDivision == "4")*/
				AND	(SALES.CATEGORY_DIVISION = -4 OR SALES.CATEGORY_DIVISION = -14)
			/*END*/
			/*IF (condition.srhCategoryDivision == "9")*/
				AND	(SALES.CATEGORY_DIVISION = -9 OR SALES.CATEGORY_DIVISION = -19)
			/*END*/
		/*END*/
		/*IF (!condition.srhCancelFlg)*/
			/*IF (condition.srhCategoryDivision == "1")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 1 OR ABS(SALES.CATEGORY_DIVISION) = 11)
			/*END*/
			/*IF (condition.srhCategoryDivision == "2")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 2 OR ABS(SALES.CATEGORY_DIVISION) = 12)
			/*END*/
			/*IF (condition.srhCategoryDivision == "3")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 3 OR ABS(SALES.CATEGORY_DIVISION) = 13)
			/*END*/
			/*IF (condition.srhCategoryDivision == "4")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 4 OR ABS(SALES.CATEGORY_DIVISION) = 14)
			/*END*/
			/*IF (condition.srhCategoryDivision == "9")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 9 OR ABS(SALES.CATEGORY_DIVISION) = 19)
			/*END*/
		/*END*/
	/*END*/
/*END*/

/*IF (( condition.srhOrderNoFrom != null ) && ( condition.srhOrderNoFrom != "" ))*/
	AND	SALES.ORDER_NO >= /*condition.srhOrderNoFrom*/''
/*END*/

/*IF (( condition.srhOrderNoTo != null ) && ( condition.srhOrderNoTo != "" ))*/
	AND	SALES.ORDER_NO <= /*condition.srhOrderNoTo*/''
/*END*/

/*IF (( condition.srhSalesDateFrom != null ) && ( condition.srhSalesDateFrom != "" ))*/
	AND	TO_CHAR(SALES.SALES_DATE, 'YYYY/MM/DD') >= /*condition.srhSalesDateFrom*/''
/*END*/

/*IF (( condition.srhSalesDateTo != null ) && ( condition.srhSalesDateTo != "" ))*/
	AND	TO_CHAR(SALES.SALES_DATE, 'YYYY/MM/DD') <= /*condition.srhSalesDateTo*/''
/*END*/

/*IF (( condition.srhAccountYears != null ) && ( condition.srhAccountYears != "" ))*/
	AND	SALES.ACCOUNT_YEARS >= /*condition.srhAccountYears*/
/*END*/

/*IF (( condition.srhAccountYearsTo != null ) && ( condition.srhAccountYearsTo != "" ))*/
	AND	SALES.ACCOUNT_YEARS <= /*condition.srhAccountYearsTo*/
/*END*/
	

/*IF (condition.srhTmpUnitpriceFlg)*/
	AND	SALES.TMP_UNITPRICE_FLG = 1
/*END*/

/*IF (condition.srhKeepFlag)*/
	AND	SALES.KEEP_FLAG = 2
/*END*/

/*IF (condition.srhMonthlyUpdateFlag)*/
	AND	(SALES.DEPOSIT_UPDATE_DIVISION = 1 OR SALES.CLAIM_UPDATE_DIVISION = 1)
/*END*/

/*IF (( condition.srhVenderCd != null ) && ( condition.srhVenderCd != "" ))*/
	AND(	SALES.VENDER_CD LIKE /*condition.srhVenderCd*/'' OR VENDER.VENDER_SHORTED_NAME LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

/*IF (( condition.srhChargeOrganizationCd != null ) && ( condition.srhChargeOrganizationCd != "" ))*/
	AND	SALES.CHARGE_ORGANIZATION_CD LIKE /*condition.srhChargeOrganizationCd*/''
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	SALES.ITEM_CD LIKE /*condition.srhItemCd*/''
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
    AND SALES.ITEM_CD IN (SELECT ITEM_CD
                          FROM   VALID_ITEM_QUEUE
                          WHERE  OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'')
/*END*/

/*IF (( condition.srhDeliveryCd != null ) && ( condition.srhDeliveryCd != "" ))*/
	AND	SALES.DELIVERY_CD LIKE /*condition.srhDeliveryCd*/
/*END*/

/*IF (( condition.srhCustomerOrderNo != null ) && ( condition.srhCustomerOrderNo != "" ))*/
	AND	ORDER_DATA.CUSTOMER_ORDER_NO = /*condition.srhCustomerOrderNo*/
/*END*/

ORDER BY SALES_NO


