/*
 * ＦＢデータ作成 ＦＢデータ用SQL
 *
 * entityName=FbdataMakingData
 * packageName=payment.fbdatamaking
 * methodName=getSearchPaymentInfo
 *
 */
SELECT MAX(DATA_DIVISION) DATA_DIVISION
, BANK_MASTER_CD
, MAX(BANK_KANA_NAME) BANK_KANA_NAME
, BRANCH_CD
, MAX(BRANCH_KANA_NAME) BRANCH_KANA_NAME
, MAX(CLEARINGHOUSE) CLEARINGHOUSE
, DEPOSIT_DIVISION
, ACCOUNT_NO
, MAX(ACCOUNT_STOCKHOLD) ACCOUNT_STOCKHOLD
, TRIM(TO_CHAR(SUM(TRANSFER_AMOUNT_N),'0000000000')) TRASFER_AMOUNT
, MAX(NEW_CD) NEW_CD
, MAX(CUSTOMER_CD1) CUSTOMER_CD1
, MAX(CUSTOMER_CD2) CUSTOMER_CD2
, MAX(TRANSFER_DIVISION) TRANSFER_DIVISION
, MAX(DUMMY) DUMMY
, SUM(TRANSFER_AMOUNT_N) TRANSFER_AMOUNT_N
, PAYMENT_DATE
FROM
(
SELECT
	'2'													AS DATA_DIVISION,		-- データ区分（データレコード：2固定）
	BANK.BANK_CD										AS BANK_MASTER_CD,		-- 被仕向金融機関番号
	SUBSTR(BANK.BANK_KANA_NAME, 1, 15)					AS BANK_KANA_NAME,		-- 被仕向金融機関名(左詰スペース埋め)
	BANK.BRANCH_CD										AS BRANCH_CD,			-- 被仕向支店番号
	SUBSTR(BANK.BRANCH_KANA_NAME, 1, 15)				AS BRANCH_KANA_NAME,	-- 被仕向支店名(左詰スペース埋め)
	'0000'												AS CLEARINGHOUSE,		-- 手形交換所番号(省略：0000固定)
	TRIM(TO_CHAR(VENDER.OTHER_ACCOUNT_DIVISION,'0'))	AS DEPOSIT_DIVISION,	-- 預金種目
	LPAD(SUBSTR(VENDER.OTHER_ACCOUNT_NO, 1, 7), 7, '0')	AS ACCOUNT_NO,			-- 口座番号(右詰・ゼロ埋め）
	SUBSTR(VENDER.OTHER_ACCOUNT_STOCKHOLD, 1, 30)		AS ACCOUNT_STOCKHOLD,	-- 受取人名
	TRIM(TO_CHAR(TRANSFER.TRANSFER_AMOUNT_N,'0000000000'))	
														AS TRASFER_AMOUNT ,		-- 振込金額(右詰・ゼロ埋め）
	' '													AS NEW_CD,				-- 新規コード(ゼロ埋め)
	'          '										AS CUSTOMER_CD1,        -- 顧客コード１(スペース埋め)
	'          '										AS CUSTOMER_CD2,        -- 顧客コード２(スペース埋め)
	'7'													AS TRANSFER_DIVISION,	-- 振込指定(7固定)
	'        '											AS DUMMY,				-- ダミー(スペース)
	TRANSFER.TRANSFER_AMOUNT_N							AS TRANSFER_AMOUNT_N,	-- 振込金額(数値）
	TRANSFER.TRANSFER_DATE								AS PAYMENT_DATE			-- 振込日付(YYYYMMDD)
FROM
	VENDER,BANK,
	(
		SELECT	
			TO_CHAR(PAYMENT_DATE,'YYYYMMDD') AS TRANSFER_DATE, 
			SUPPLIER_CD AS SUPPLIER_CD,
			SUM(NVL(PAYMENT_AMOUNT, 0)) AS TRANSFER_AMOUNT_N
		FROM
			PAYMENT
		WHERE
			DATA_TYPE = 4										-- 支払
		AND	CATEGORY_DIVISION = 3								-- 振込
		AND	PAYMENT_DATE = TO_DATE(/*paymentDate*/'20090430')
		AND	APPROVAL_STATUS = 3									-- 承認済
		GROUP BY TO_CHAR(PAYMENT_DATE,'YYYYMMDD'), SUPPLIER_CD
	) TRANSFER
WHERE
	VENDER.BANK_CD = /*bankMasterCd*/'0005520'					-- 支払用銀行口座
AND	BANK.BANK_MASTER_CD = LPAD(VENDER.OTHER_BANK_CD, 7, '0')	-- 現状の0漏れ対策
AND	VENDER.VENDER_DIVISION = 'SI'
AND	VENDER.VENDER_CD = TRANSFER.SUPPLIER_CD
AND	TRANSFER.TRANSFER_AMOUNT_N > 0
)
GROUP BY PAYMENT_DATE, BANK_MASTER_CD, BRANCH_CD, DEPOSIT_DIVISION, ACCOUNT_NO
ORDER BY BANK_MASTER_CD, BRANCH_CD, DEPOSIT_DIVISION, ACCOUNT_NO
