/*
 * ＦＢデータ作成 ＦＢデータ用SQL
 *
 * entityName=FbdataMakingData
 * packageName=payment.fbdatamaking
 * methodName=getSearchFbData
 *
 */
SELECT 	DATA_DIVISION
,		BANK_MASTER_CD
,		BANK_KANA_NAME
,		BRANCH_CD
,		BRANCH_KANA_NAME
,		CLEARINGHOUSE
,		DEPOSIT_DIVISION
,		ACCOUNT_NO
,		ACCOUNT_STOCKHOLD
,		TRASFER_AMOUNT
,		NEW_CD
,		CUSTOMER_CD1
,		CUSTOMER_CD2
,		TRANSFER_DIVISION
,		DUMMY
,		TRANSFER_AMOUNT_N
,		PAYMENT_DATE
,		INPUT_DATE
,		INPUTOR_CD
,		UPDATE_DATE
,		UPDATOR_CD
FROM 	FB_DATA
WHERE	PAYMENT_DATE = /*paymentDate*/'20090901'
ORDER BY BANK_MASTER_CD, BRANCH_CD, DEPOSIT_DIVISION, ACCOUNT_NO
