/**
 *
 * @author t1344224
 *
 * entityName=DirectionResultProcedureListForReport
 * packageName=rdirectionorderforreport
 * methodName=getProcedureReportList
 *
 */
SELECT
	PROCEDURE.DIRECTION_DIVISION
,	PROCEDURE.DIRECTION_NO
,	PROCEDURE.STEP_NO
,	PROCEDURE.SEQ
,	PROCEDURE.OPERATION_CD
,	OPERATION.OPERATION_NAME
,	PROCEDURE.CONDITION
,	PROCEDURE.REMARK
,	PROCEDURE.NOTES
,	PROCEDURE.LEADTIME
,	PROCEDURE.START_DATE
,	PROCEDURE.END_DATE
,	PROCEDURE.RESULT_SDATE
,	PROCEDURE.RESULT_EDATE
,	PROCEDURE.CONDITION_TEMP
,	PROCEDURE.CONDITION_TIME
,	PROCEDURE.STIR_SPEED1
,	PROCEDURE.STIR_SPEED2
,	PROCEDURE.WATER_WEIGHT
,	PROCEDURE.MAIN_STREAM
,	PROCEDURE.PH
,	PROCEDURE.RESULT_CONDITION_TEMP
,	PROCEDURE.RESULT_STIR_SPEED
,	PROCEDURE.RESULT_PH
,	PROCEDURE.FILLING_QTY
,	PROCEDURE.FILLING_UNIT
,	PROCEDURE.NET
,	PROCEDURE.WEIGHT_MIN
,	PROCEDURE.WEIGHT_MAX
,	PROCEDURE.FILTER
,	PROCEDURE.AUTO_CHECKER_MIN
,	PROCEDURE.AUTO_CHECKER_MAX
,	PROCEDURE.GROSS_CHECKER_MIN
,	PROCEDURE.GROSS_CHECKER_MAX
,	PROCEDURE.OPENING_TORQUE_MIN
,	PROCEDURE.OPENING_TORQUE_MAX
,	PROCEDURE.HOT_AIR_PRESET_TEMP
,	PROCEDURE.HOT_AIR_PRESSURE
,	PROCEDURE.MESH
,	PROCEDURE.AUTO_CHECKER_AVE
,	PROCEDURE.GROSS_CHECKER_AVE
,	PROCEDURE.CLOSING_TORQUE_MIN
,	PROCEDURE.CLOSING_TORQUE_MAX
,	PROCEDURE.TORQUE_PRESSURE
,	PROCEDURE.AIR_PRESSURE
,	PROCEDURE.VCLOSE_TIME
,	PROCEDURE.FIRST_HEAT_SEAL
,	PROCEDURE.SECOND_HEAT_SEAL
,	PROCEDURE.INPUT_DATE
,	PROCEDURE.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	PROCEDURE.UPDATE_DATE
,	PROCEDURE.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM
    VALID_ITEM_QUEUE MAX_ITEM,
	LINE LINE,
	NAMES NAME,
	VALID_ITEM_QUEUE ITEM,
	RECIPE_RESOUCE RECIPE_RESOUCE,
	DIRECTION_HEADER HEAD
,	DIRECTION_PROCEDURE PROCEDURE
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,	OPERATION

WHERE
        HEAD.DIRECTION_DIVISION = '1'
    AND HEAD.DIRECTION_NO = PROCEDURE.DIRECTION_NO
    AND MAX_ITEM.ITEM_CD(+) = HEAD.ITEM_CD
    AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITEM.VERSION(+) = MAX_ITEM.VERSION
    AND LINE.PRODUCTION_LINE(+) = HEAD.PRODUCTION_LINE
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
    AND HEAD.COMPOUND_TANK_NO = RECIPE_RESOUCE.RESOUCE_CD(+)

AND	PROCEDURE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND PROCEDURE.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND	PROCEDURE.OPERATION_CD = OPERATION.OPERATION_CD(+)
/*IF (( condition.directionNo != null ) && ( condition.directionNo != "" ))*/
	AND	HEAD.DIRECTION_NO LIKE /*condition.directionNo*/'O%'
/*END*/
/*IF (( condition.productionLine != null ) && ( condition.productionLine != "" ))*/
	AND	HEAD.PRODUCTION_LINE = /*condition.productionLine*/'O%'
/*END*/
/*IF ( condition.directionStatus != 0 )*/
	AND	HEAD.DIRECTION_STATUS = /*condition.directionStatus*/'O%'
/*END*/
/*IF ( condition.directionStatus == 0 )*/
	AND	HEAD.DIRECTION_STATUS IN (6,7,8)
/*END*/
/*IF (( condition.itemCd != null ) && ( condition.itemCd != "" ))*/
	AND	(HEAD.ITEM_CD LIKE /*condition.itemCd*/'O%' OR ITEM.ITEM_NAME LIKE /*condition.itemCd*/'O%')
/*END*/
/*IF (( condition.otherCompanyCd1 != null ) && ( condition.otherCompanyCd1 != "" ))*/
	AND	ITEM.OTHER_COMPANY_CD1 LIKE /*condition.otherCompanyCd1*/'O%'
/*END*/
/*IF (( condition.resultSdateDateFrom != null ) && ( condition.resultSdateDateFrom != "" ))*/
	AND TO_CHAR(HEAD.RESULT_SDATE,'YYYY/MM/DD HH24:MI') >= /*condition.resultSdateDateFrom*/''
/*END*/
/*IF (( condition.resultSdateDateTo != null ) && ( condition.resultSdateDateTo != "" ))*/
	AND TO_CHAR(HEAD.RESULT_SDATE,'YYYY/MM/DD HH24:MI') <= /*condition.resultSdateDateTo*/''
/*END*/
/*IF (( condition.resultEdateDateFrom != null ) && ( condition.resultEdateDateFrom != "" ))*/
	AND TO_CHAR(HEAD.RESULT_EDATE,'YYYY/MM/DD HH24:MI') >= /*condition.resultEdateDateFrom*/''
/*END*/
/*IF (( condition.resultEdateDateTo != null ) && ( condition.resultEdateDateTo != "" ))*/
	AND TO_CHAR(HEAD.RESULT_EDATE,'YYYY/MM/DD HH24:MI') <= /*condition.resultEdateDateTo*/''
/*END*/
/*IF (( condition.compoundTankNo != null ) && ( condition.compoundTankNo != "" ))*/
	AND	HEAD.COMPOUND_TANK_NO LIKE /*condition.compoundTankNo*/'EE'
/*END*/

ORDER BY
     HEAD.COMPOUND_TANK_NO
    ,HEAD.RESULT_SDATE
    ,HEAD.DIRECTION_NO
    ,HEAD.ITEM_CD
    ,PROCEDURE.STEP_NO




