/**
 *
 * @author t1344224
 *
 * entityName=DirectionResultHeaderListForReport
 * packageName=rdirectionorderforreport
 * methodName=getHeaderReportList
 *
 */
SELECT
	HEAD.DIRECTION_DIVISION
,	HEAD.DIRECTION_NO
,	HEAD.DIRECTION_DATE
,	HEAD.ASP_ORDER_NO
,	HEAD.DIRECTION_STATUS
,	CASE HEAD.DIRECTION_STATUS
		WHEN 1 THEN '未確定'
		WHEN 2 THEN '指図書発行済'
		WHEN 3 THEN '製造開始'
		WHEN 4 THEN '中間品最終検査待'
		WHEN 5 THEN '中間品最終検査済'
		WHEN 6 THEN 'FA受信'
		WHEN 7 THEN '製造記録出力済'
		WHEN 8 THEN '完了'
	END AS DIRECTION_STATUS_NAME
,	HEAD.RECIPE_ID
,	HEAD.RECIPE_CD
,	HEAD.RECIPE_VERSION
,	HEAD.PRODUCTION_LINE
,	LINE.PRODUCTION_LINE_NAME
,	HEAD.COMPOUND_TANK_NO
,	COMPOUND_TANK.RESOUCE_NAME AS COMPOUND_TANK_NAME
,	HEAD.HOLD_TANK_NO
,	HOLD_TANK.RESOUCE_NAME AS HOLD_TANK_NAME
,	HEAD.DISSOLUTION_TANK_NO
,	DISSOLUTION_TANK.RESOUCE_NAME AS DISSOLUTION_TANK_NAME
,	HEAD.FILLTANK_NO
,	FILLTANK.RESOUCE_NAME AS FILLTANK_NAME
,	HEAD.PACKAGE_LINE
,	PACKAGE_LINE.RESOUCE_NAME AS PACKAGE_LINE_NAME
,	HEAD.CURRENT_STEP_NO
,	HEAD.ITEM_CD
,	ITEM.ITEM_NAME
,	NAME.NAME01
,	HEAD.PLANED_QTY
,	HEAD.RESULT_QTY
,	HEAD.DIVIDE_FLAG
,	HEAD.NEXT_PLANED_QTY
,	HEAD.PDW_RESULT
,	HEAD.PEOCESS_LOSS
,	HEAD.LOT_NO
,	HEAD.PLANED_SDATE
,	HEAD.PLANED_EDATE
,	HEAD.RESULT_SDATE
,	HEAD.RESULT_EDATE
,	HEAD.STERIT_SDATE
,	HEAD.STERIT_EDATE
,	HEAD.MEKKIN_TANK_TEMP_MIN
,	HEAD.MEKKIN_TANK_TEMP_MAX
,	HEAD.HAISUI_CHECK
,	HEAD.STAMP_FLAG
,	HEAD.STAMP_DATE
,	HEAD.STAMP_TANTO_CD
,	STAMP_TANTO.TANTO_NM AS STAMP_TANTO_NAME
,	HEAD.PRODUCT_LABEL_FLAG
,	HEAD.PRODUCT_LABEL_DATE
,	HEAD.PRODUCT_LABEL_TANTO_CD
,	PRODUCT_LABEL.TANTO_NM AS PRODUCT_LABEL_TANTO_NAME
,	HEAD.PRODUCT_RECORD_FLAG
,	HEAD.PRODUCT_RECORD_DATE
,	HEAD.PRODUCT_RECORD_TANTO_CD
,	PRODUCT_RECORD.TANTO_NM AS PRODUCT_RECORD_TANTO_NAME
,	HEAD.STOCKDISS_LABEL_FLAG
,	HEAD.STOCKDISS_LABEL_DATE
,	HEAD.STOCKDISS_LABEL_TANTO_CD
,	STOCKDISS_LABEL.TANTO_NM AS STOCKDISS_LABEL_TANTO_NAME
,	HEAD.CERTIFICATION_FLAG
,	HEAD.CERTIFICATION_DATE
,	HEAD.REMARK
,	HEAD.NOTES
,	HEAD.DELETE_FLAG
,	HEAD.SEIZOTANTOCODE
,	SEIZOTANTO.TANTO_NM AS SEIZOTANTO_NAME
,	HEAD.SENJOTANTOCODE
,	SENJOTANTO.TANTO_NM AS SENJOTANTO_NAME
,	HEAD.MEKKINTANTOCODE
,	MEKKINTANTO.TANTO_NM AS MEKKINTANTO_NAME
,	HEAD.CHOGOTANKCONDI
,	HEAD.YOBIYOKAICONDI
,	HEAD.HOLDTANKCONDI
,	HEAD.TOTAL_JOBTIME
,	HEAD.ENPLOY_JOBTIME
,	HEAD.COOPER_JOBTIME
,	HEAD.APP_TANTO_CD
,	APP.TANTO_NM AS APP_TANTO_NAME
,	HEAD.APP_DATE
,	HEAD.LAST_APP_TANTO_CD
,	LAST_APP.TANTO_NM AS LAST_APP_TANTO_NAME
,	HEAD.LAST_APP_DATE
,	HEAD.INPUT_DATE
,	HEAD.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	HEAD.UPDATE_DATE
,	HEAD.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
FROM
    VALID_ITEM_QUEUE MAX_ITEM,
	LINE LINE,
	NAMES NAME,
	VALID_ITEM_QUEUE ITEM,
	RECIPE_RESOUCE RECIPE_RESOUCE,
	DIRECTION_HEADER HEAD

,	LOGIN STAMP_TANTO
,	LOGIN PRODUCT_LABEL
,	LOGIN PRODUCT_RECORD
,	LOGIN STOCKDISS_LABEL
,	LOGIN APP
,	LOGIN LAST_APP
,	LOGIN SEIZOTANTO
,	LOGIN MEKKINTANTO
,	LOGIN SENJOTANTO
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,	RECIPE_RESOUCE COMPOUND_TANK
,	RECIPE_RESOUCE HOLD_TANK
,	RECIPE_RESOUCE DISSOLUTION_TANK
,	RECIPE_RESOUCE FILLTANK
,	RECIPE_RESOUCE PACKAGE_LINE


WHERE
        HEAD.DIRECTION_DIVISION = '1'
    AND MAX_ITEM.ITEM_CD(+) = HEAD.ITEM_CD
    AND ITEM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITEM.VERSION(+) = MAX_ITEM.VERSION
    AND LINE.PRODUCTION_LINE(+) = HEAD.PRODUCTION_LINE
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
    AND HEAD.COMPOUND_TANK_NO = RECIPE_RESOUCE.RESOUCE_CD(+)

AND	HEAD.STAMP_TANTO_CD = STAMP_TANTO.TANTO_CD(+)
AND	HEAD.PRODUCT_LABEL_TANTO_CD = PRODUCT_LABEL.TANTO_CD(+)
AND	HEAD.PRODUCT_RECORD_TANTO_CD = PRODUCT_RECORD.TANTO_CD(+)
AND	HEAD.STOCKDISS_LABEL_TANTO_CD = STOCKDISS_LABEL.TANTO_CD(+)
AND	HEAD.APP_TANTO_CD = APP.TANTO_CD(+)
AND	HEAD.LAST_APP_TANTO_CD = LAST_APP.TANTO_CD(+)
AND	HEAD.SEIZOTANTOCODE = SEIZOTANTO.TANTO_CD(+)
AND	HEAD.MEKKINTANTOCODE = MEKKINTANTO.TANTO_CD(+)
AND	HEAD.SENJOTANTOCODE = SENJOTANTO.TANTO_CD(+)
AND	HEAD.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	HEAD.UPDATOR_CD = UPDATOR.TANTO_CD(+)

AND	HEAD.COMPOUND_TANK_NO = COMPOUND_TANK.RESOUCE_CD(+)
AND	HEAD.HOLD_TANK_NO = HOLD_TANK.RESOUCE_CD(+)
AND	HEAD.DISSOLUTION_TANK_NO = DISSOLUTION_TANK.RESOUCE_CD(+)
AND	HEAD.FILLTANK_NO = FILLTANK.RESOUCE_CD(+)
AND	HEAD.PACKAGE_LINE = PACKAGE_LINE.RESOUCE_CD(+)

/*IF (( condition.directionNo != null ) && ( condition.directionNo != "" ))*/
	AND	HEAD.DIRECTION_NO LIKE /*condition.directionNo*/'O%'
/*END*/
/*IF (( condition.productionLine != null ) && ( condition.productionLine != "" ))*/
	AND	HEAD.PRODUCTION_LINE = /*condition.productionLine*/'O%'
/*END*/
/*IF ( condition.directionStatus != 0 )*/
	AND	HEAD.DIRECTION_STATUS = /*condition.directionStatus*/'O%'
/*END*/
/*IF ( condition.directionStatus == 0 )*/
	AND	HEAD.DIRECTION_STATUS IN (6,7,8)
/*END*/
/*IF (( condition.itemCd != null ) && ( condition.itemCd != "" ))*/
	AND	(HEAD.ITEM_CD LIKE /*condition.itemCd*/'O%' OR ITEM.ITEM_NAME LIKE /*condition.itemCd*/'O%')
/*END*/
/*IF (( condition.otherCompanyCd1 != null ) && ( condition.otherCompanyCd1 != "" ))*/
	AND	ITEM.OTHER_COMPANY_CD1 LIKE /*condition.otherCompanyCd1*/'O%'
/*END*/
/*IF (( condition.resultSdateDateFrom != null ) && ( condition.resultSdateDateFrom != "" ))*/
	AND TO_CHAR(HEAD.RESULT_SDATE,'YYYY/MM/DD HH24:MI') >= /*condition.resultSdateDateFrom*/''
/*END*/
/*IF (( condition.resultSdateDateTo != null ) && ( condition.resultSdateDateTo != "" ))*/
	AND TO_CHAR(HEAD.RESULT_SDATE,'YYYY/MM/DD HH24:MI') <= /*condition.resultSdateDateTo*/''
/*END*/
/*IF (( condition.resultEdateDateFrom != null ) && ( condition.resultEdateDateFrom != "" ))*/
	AND TO_CHAR(HEAD.RESULT_EDATE,'YYYY/MM/DD HH24:MI') >= /*condition.resultEdateDateFrom*/''
/*END*/
/*IF (( condition.resultEdateDateTo != null ) && ( condition.resultEdateDateTo != "" ))*/
	AND TO_CHAR(HEAD.RESULT_EDATE,'YYYY/MM/DD HH24:MI') <= /*condition.resultEdateDateTo*/''
/*END*/
/*IF (( condition.compoundTankNo != null ) && ( condition.compoundTankNo != "" ))*/
	AND	HEAD.COMPOUND_TANK_NO LIKE /*condition.compoundTankNo*/'EE'
/*END*/

ORDER BY
     HEAD.COMPOUND_TANK_NO
    ,HEAD.RESULT_SDATE
    ,HEAD.DIRECTION_NO
    ,HEAD.ITEM_CD
    ,HEAD.DIRECTION_NO






