/*
 * 外注原材料投入実績入力画面_ロット検索ポップアップ画面検索用SQL
 *
 * entityName=MaterialRinputLotInventorySearchList
 * packageName=materialrinput
 * methodName=getList
 *
 */

SELECT
	LOT_INVENTORY.LOCATION_CD			-- ロケーションコード
,	LOT_INVENTORY.ITEM_CD				-- 品目コード
,	LOT_INVENTORY.LOT_NO				-- 入荷ロット番号/包装指図番号
,	LOT_INVENTORY.ALIAS_LOT_NO			-- 原料ロット番号/製品ロット番号
,	LOT_INVENTORY.INVENTORY_QTY			-- 在庫数量
,	LOT_INVENTORY.INOUT_QTY				-- 荷姿数
,	LOT_INVENTORY.FRACTION				-- 端数
,	ITEM.ITEM_NAME						-- 品目名称
,	ITEM.STYLE_OF_PACKING			 	-- 荷姿
,	ITEM.KG_OF_FRACTION_MANAGEMENT		-- Kg換算係数（在庫）
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT 	-- 運用管理単位
,	LOCATION.LOCATION_NAME				-- ロケーション名称
,   NAME.NAME01 AS UNIT_NAME			-- 単位
FROM
	LOT_INVENTORY
,	ITEM
,	LOCATION
,	NAMES NAME
WHERE
	LOT_INVENTORY.ITEM_CD = /*condition.itemCd*/
AND LOT_INVENTORY.INVENTORY_QTY > 0
AND	LOT_INVENTORY.ITEM_CD = ITEM.ITEM_CD(+)
AND	LOT_INVENTORY.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND LOCATION.STOCK_DIVISION != 3 /* 在庫区分|1:通常,2:預かり在庫,3:在庫引当対象外 */
AND NAME.NAME_DIVISION(+) = 'UNIT'
AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
ORDER BY
	LOT_INVENTORY.LOCATION_CD
,	LOT_INVENTORY.LOT_NO
,	LOT_INVENTORY.ALIAS_LOT_NO
