/*
 * Created on 2009/03/30
 *
 * $copyright$
 *
*/

/**
 * 外注原材料投入実績入力 処方フォームラ一覧取得用SQL
 *
 * @author tosco
 *
 * entityName=MaterialRinputRecipeFormulaList
 * packageName=materialrinput
 * methodName=getFormulaList
 *
 */
SELECT
	RECIPE_FORMULA.RECIPE_ID AS      RECIPE_ID
,	RECIPE_HEADER.RECIPE_CD AS       RECIPE_CD
,	RECIPE_HEADER.RECIPE_VERSION AS  RECIPE_VERSION
,	RECIPE_FORMULA.STEP_NO AS        STEP_NO
,	RECIPE_FORMULA.LINE_NO AS        LINE_NO
,	RECIPE_FORMULA.LINE_TYPE AS      LINE_TYPE
,	RECIPE_FORMULA.ITEM_CD AS        ITEM_CD
,	RECIPE_FORMULA.QTY AS            QTY
,	ITEM.ITEM_NAME AS                ITEM_NAME		-- 品目名称
,	DECODE(RECIPE_HEADER.RECIPE_USE, 3, 'Kg',
									 4, NAMES.NAME01,
									 	''
		  ) AS                       UNIT			-- 単位
,	RECIPE_HEADER.RECIPE_NAME AS     RECIPE_NAME	-- 基本処方名称
FROM
	RECIPE_FORMULA
,	RECIPE_HEADER
,	RECIPE_PROCEDURE
,	ITEM
,	(SELECT NAME_CD
	 ,		NAME01
	 FROM NAMES
	 WHERE	NAME_DIVISION = 'UNIT'
	) NAMES
WHERE
	RECIPE_FORMULA.RECIPE_ID = /*recipeId*/30732
AND	RECIPE_FORMULA.RECIPE_ID = RECIPE_HEADER.RECIPE_ID(+)
AND	RECIPE_FORMULA.RECIPE_ID = RECIPE_PROCEDURE.RECIPE_ID(+)
AND	RECIPE_FORMULA.STEP_NO = RECIPE_PROCEDURE.STEP_NO(+)
AND	RECIPE_FORMULA.ITEM_CD = ITEM.ITEM_CD(+)
AND	ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
ORDER BY RECIPE_PROCEDURE.SEQ
,		 RECIPE_FORMULA.SEQ
