/*
 * Created on 2009/03/27
 *
 * $copyright$
 *
*/

/**
 * 外注原材料投入実績入力(明細部)用SQL
 *
 * @author tosco
 *
 * entityName=MaterialRinputDetailList
 * packageName=materialrinput
 * methodName=getDetailList
 *
 */
SELECT	PURCHASE_MATE_INJECTION.BUY_SUBCONTRACT_ORDER_NO
,		PURCHASE_MATE_INJECTION.RECIPE_ID
,		PURCHASE_MATE_INJECTION.RECIPE_CD
,		PURCHASE_MATE_INJECTION.RECIPE_VERSION
,		PURCHASE_MATE_INJECTION.STEP_NO
,		PURCHASE_MATE_INJECTION.LINE_NO
,		PURCHASE_MATE_INJECTION.SEQ
,		PURCHASE_MATE_INJECTION.LOT_NO
,		PURCHASE_MATE_INJECTION.LOCATION_CD
,		PURCHASE_MATE_INJECTION.MANUFACTURER_LOT_NO
,		PURCHASE_MATE_INJECTION.ITEM_CD
,		PURCHASE_MATE_INJECTION.QTY
,		PURCHASE_MATE_INJECTION.RESULT_QTY
,		PURCHASE_MATE_INJECTION.SAMPLE_QTY
,		PURCHASE_MATE_INJECTION.LOSS_QTY
,		PURCHASE_MATE_INJECTION.DEFECT_QTY
,		PURCHASE_MATE_INJECTION.ADJUST_QTY
,		ITEM.ITEM_NAME						-- 品目名称
,		NAMES.NAME01 AS UNIT				-- 単位
,		RECIPE_HEADER.RECIPE_NAME			-- 基本処方名称
,		RECIPE_HEADER.RECIPE_USE			-- 用途
,		DECODE(NVL(INVENTORY_LOT.LOT_STOCK_COUNT, 0), 0, '0', '1') STOCKPD_FLG	-- 在庫引落フラグ
FROM	PURCHASE_MATE_INJECTION
,		ITEM
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'UNIT'
		) NAMES
,		RECIPE_HEADER
,		RECIPE_PROCEDURE
,		RECIPE_FORMULA
,		(SELECT COUNT(*) LOT_STOCK_COUNT
		 ,		STEP_NO
		 ,		LINE_NO
		 FROM PURCHASE_MATE_INJECTION
		 WHERE BUY_SUBCONTRACT_ORDER_NO = /*buySubcontractOrderNo*/
		   AND SEQ <> 0
		 GROUP BY STEP_NO, LINE_NO) INVENTORY_LOT
WHERE	PURCHASE_MATE_INJECTION.BUY_SUBCONTRACT_ORDER_NO IS NOT NULL
AND		PURCHASE_MATE_INJECTION.BUY_SUBCONTRACT_ORDER_NO = /*buySubcontractOrderNo*/
AND		PURCHASE_MATE_INJECTION.ITEM_CD = ITEM.ITEM_CD(+)
AND		ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND		PURCHASE_MATE_INJECTION.RECIPE_ID = RECIPE_HEADER.RECIPE_ID(+)
AND		PURCHASE_MATE_INJECTION.RECIPE_ID = RECIPE_PROCEDURE.RECIPE_ID(+)
AND		PURCHASE_MATE_INJECTION.STEP_NO = RECIPE_PROCEDURE.STEP_NO(+)
AND		PURCHASE_MATE_INJECTION.RECIPE_ID = RECIPE_FORMULA.RECIPE_ID(+)
AND		PURCHASE_MATE_INJECTION.STEP_NO = RECIPE_FORMULA.STEP_NO(+)
AND		PURCHASE_MATE_INJECTION.LINE_NO = RECIPE_FORMULA.LINE_NO(+)
AND		PURCHASE_MATE_INJECTION.STEP_NO = INVENTORY_LOT.STEP_NO(+)
AND		PURCHASE_MATE_INJECTION.LINE_NO = INVENTORY_LOT.LINE_NO(+)
AND		PURCHASE_MATE_INJECTION.SEQ = 0
ORDER BY RECIPE_PROCEDURE.SEQ
,		 RECIPE_FORMULA.SEQ
