/*
 * Created on 2009/02/17
 *
 * $copyright$
 *
*/

/**
 * 中間品検査完了入力画面用SQL
 *
 * @author tosco
 *
 * entityName=MidInspectCompList
 * packageName=midinspectcomp
 * methodName=getSearchList
 *
 */
SELECT	DIRECTION_HEADER.DIRECTION_DIVISION
,	DIRECTION_HEADER.DIRECTION_NO
,	DIRECTION_HEADER.DIRECTION_DATE
,	DIRECTION_HEADER.ASP_ORDER_NO
,	DIRECTION_HEADER.DIRECTION_STATUS
,	DIRECTION_HEADER.RECIPE_ID
,	DIRECTION_HEADER.RECIPE_CD
,	DIRECTION_HEADER.RECIPE_VERSION
,	DIRECTION_HEADER.PRODUCTION_LINE
,	DIRECTION_HEADER.COMPOUND_TANK_NO
,	DIRECTION_HEADER.HOLD_TANK_NO
,	DIRECTION_HEADER.DISSOLUTION_TANK_NO
,	DIRECTION_HEADER.FILLTANK_NO
,	DIRECTION_HEADER.PACKAGE_LINE
,	DIRECTION_HEADER.CURRENT_STEP_NO
,	DIRECTION_HEADER.ITEM_CD
,	DIRECTION_HEADER.PLANED_QTY
,	DIRECTION_HEADER.RESULT_QTY
,	DIRECTION_HEADER.DIVIDE_FLAG
,	DIRECTION_HEADER.NEXT_PLANED_QTY
,	DIRECTION_HEADER.PDW_RESULT
,	DIRECTION_HEADER.PEOCESS_LOSS
,	DIRECTION_HEADER.LOT_NO
,	DIRECTION_HEADER.PLANED_SDATE
,	DIRECTION_HEADER.PLANED_EDATE
,	DIRECTION_HEADER.RESULT_SDATE
,	DIRECTION_HEADER.RESULT_EDATE
,	DIRECTION_HEADER.STERIT_SDATE
,	DIRECTION_HEADER.STERIT_EDATE
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MIN
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MAX
,	DIRECTION_HEADER.HAISUI_CHECK
,	DIRECTION_HEADER.STAMP_FLAG
,	DIRECTION_HEADER.STAMP_DATE
,	DIRECTION_HEADER.STAMP_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_LABEL_FLAG
,	DIRECTION_HEADER.PRODUCT_LABEL_DATE
,	DIRECTION_HEADER.PRODUCT_LABEL_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_RECORD_FLAG
,	DIRECTION_HEADER.PRODUCT_RECORD_DATE
,	DIRECTION_HEADER.PRODUCT_RECORD_TANTO_CD
,	DIRECTION_HEADER.STOCKDISS_LABEL_FLAG
,	DIRECTION_HEADER.STOCKDISS_LABEL_DATE
,	DIRECTION_HEADER.STOCKDISS_LABEL_TANTO_CD
,	DIRECTION_HEADER.CERTIFICATION_FLAG
,	DIRECTION_HEADER.CERTIFICATION_DATE
,	DIRECTION_HEADER.REMARK
,	DIRECTION_HEADER.NOTES
,	DIRECTION_HEADER.DELETE_FLAG
,	DIRECTION_HEADER.SEIZOTANTOCODE
,	DIRECTION_HEADER.SENJOTANTOCODE
,	DIRECTION_HEADER.MEKKINTANTOCODE
,	DIRECTION_HEADER.CHOGOTANKCONDI
,	DIRECTION_HEADER.YOBIYOKAICONDI
,	DIRECTION_HEADER.HOLDTANKCONDI
,	DIRECTION_HEADER.TOTAL_JOBTIME
,	DIRECTION_HEADER.ENPLOY_JOBTIME
,	DIRECTION_HEADER.COOPER_JOBTIME
,	DIRECTION_HEADER.APP_TANTO_CD
,	DIRECTION_HEADER.APP_DATE
,	DIRECTION_HEADER.LAST_APP_TANTO_CD
,	DIRECTION_HEADER.LAST_APP_DATE
,	DIRECTION_HEADER.INPUT_DATE
,	DIRECTION_HEADER.INPUTOR_CD
,	DIRECTION_HEADER.UPDATE_DATE
,	DIRECTION_HEADER.UPDATOR_CD


,	ITEM_NAMES.ITEM_NAME
,	LINE.PRODUCTION_LINE_NAME
,	OPERATION.OPERATION_NAME
,	RECIPE_RESOUCE.ORDER_PUBLISH_FLG AS ORDER_PUBLISH_FLG
FROM	DIRECTION_HEADER
,	VALID_ITEM_QUEUE ITEM_NAMES
,	LINE
,	OPERATION
,	RECIPE_RESOUCE RECIPE_RESOUCE

WHERE	DIRECTION_HEADER.DIRECTION_DIVISION = '1'

AND		DIRECTION_HEADER.ITEM_CD = ITEM_NAMES.ITEM_CD(+)
AND		DIRECTION_HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND		DIRECTION_HEADER.CURRENT_STEP_NO = OPERATION.OPERATION_CD(+)
AND		DIRECTION_HEADER.COMPOUND_TANK_NO = RECIPE_RESOUCE.RESOUCE_CD(+)

/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
	AND	DIRECTION_HEADER.DIRECTION_NO LIKE /*condition.srhDirectionNo*/
/*END*/

/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	AND	DIRECTION_HEADER.PRODUCTION_LINE = /*condition.srhProductionLine*/
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	DIRECTION_HEADER.ITEM_CD LIKE /*condition.srhItemCd*/
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/
/*END*/

/*IF (( condition.srhPlanedSdateFrom != null ) && ( condition.srhPlanedSdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE >= /*condition.srhPlanedSdateFrom*/
/*END*/

/*IF (( condition.srhPlanedSdateTo != null ) && ( condition.srhPlanedSdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE <= /*condition.srhPlanedSdateTo*/
/*END*/

/*IF (( condition.srhPlanedEdateFrom != null ) && ( condition.srhPlanedEdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE >= /*condition.srhPlanedEdateFrom*/
/*END*/

/*IF (( condition.srhPlanedEdateTo != null ) && ( condition.srhPlanedEdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE <= /*condition.srhPlanedEdateTo*/
/*END*/

/*IF (( condition.srhDirectionStatus != null ) && ( condition.srhDirectionStatus != "" ))*/
	/*IF (condition.srhDirectionStatus == "0")*/
			AND	DIRECTION_HEADER.DIRECTION_STATUS IN ('4','5')
	/*END*/
	/*IF (condition.srhDirectionStatus != "0")*/
			AND	DIRECTION_HEADER.DIRECTION_STATUS = /*condition.srhDirectionStatus*/
	/*END*/		
/*END*/

ORDER BY	DIRECTION_HEADER.RESULT_SDATE
,			DIRECTION_HEADER.DIRECTION_NO
,			DIRECTION_HEADER.ITEM_CD
