/*
 * 販売品扱い属性検索用SQL
 *
 * entityName=ArticleAttributeQueueDetail
 * packageName=articleattributequeuedetail
 * methodName=getEntity
 *
 */

SELECT ITEM_CD, VERSION, STATUS ARTICLE_STATUS, PRICE_CALC_DIVISION ARTICLE_PRICE_CALC_DIVISION, SELLING_PRICE, PALETTE_PRODUCTS, JAN_CD, ITF_CD, SAFETY_LEAD_TIME, QUEUE.SECTION_CD ARTICLE_SECTION_CD, SECTION_NAME ARTICLE_SECTION_NAME, QUEUE.ACCOUNTS_CD ARTICLE_ACCOUNTS_CD, ACCOUNTS_NAME ARTICLE_ACCOUNTS_NAME, TAX_DIVISION ARTICLE_TAX_DIVISION, QUEUE.FINANCIAL_CLASS_CD, FINANCIAL_CLASS_NAME, KEEP_DIVISION, QUEUE.UPDATE_DATE ARTICLE_UPDATE_DATE
FROM ARTICLE_ATTRIBUTE_QUEUE QUEUE, BUMON, ACCOUNTS, FINANCIAL_CLASS
WHERE ITEM_CD = /*itemCd*/'%'
AND VERSION = /*version*/1
AND QUEUE.SECTION_CD = BUMON.SECTION_CD(+)
AND QUEUE.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
AND QUEUE.FINANCIAL_CLASS_CD = FINANCIAL_CLASS.FINANCIAL_CLASS_CD(+)


