/*
 * 
 *
 * entityName=RepShippingSlipOrderList
 * packageName=repShippingSlipOrderList
 * methodName=getShippingList
 *
 */
SELECT	SHIPPING.SHIPPING_NO
,	NVL(TO_CHAR(SHIPPING.SCHEDULED_SHIPPING_DATE,'YYYY/MM/DD'),'null') AS SCHEDULED_SHIPPING_DATE
,	NVL(SHIPPING_DETAIL_LOCATION.UPPER_LOCATION_CD,'null') AS UPPER_LOCATION_CD
,	NVL(ORDER_DATA.ORDER_NO,'null') AS ORDER_NO
,	NVL(SHIPPING.DELIVERY_CD,'null') AS DELIVERY_CD
,	NVL(SHIPPING.VENDER_CD,'null') AS VENDER_CD
,	NVL(TO_CHAR(ORDER_DATA.DELIVERY_EXPECTED_DATE,'YYYY/MM/DD'),'null') AS DELIVERY_EXPECTED_DATE
,	NVL(SHIPPING.CARRY_CD,'null') AS CARRY_CD
,	SHIPPING.UPDATE_DATE
,	SHIPPING.SHIPPING_SLIP_NO
,   SHIPPING.CARRY_BC
FROM
	SHIPPING
,	CARRY
,	(SELECT
		ORDER_HEAD.ORDER_NO
	,	ORDER_HEAD.DELIVERY_EXPECTED_DATE
	,	ORDER_DETAIL.SHIPPING_NO
	FROM
		ORDER_HEAD
	,	ORDER_DETAIL
	WHERE
		ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
	)ORDER_DATA

,	(SELECT
		SHIPPING_DETAIL.SHIPPING_NO
	,	MAX(UPPER_LOCATION.UPPER_LOCATION_CD) as UPPER_LOCATION_CD
	FROM
		SHIPPING_DETAIL
	,	(SELECT
			LOCA1.LOCATION_CD
		,	NVL(LOCA2.UPPER_LOCATION_CD,LOCA2.LOCATION_CD) as UPPER_LOCATION_CD
		FROM
			LOCATION LOCA1
		,	LOCATION LOCA2
		WHERE
			NVL(LOCA1.UPPER_LOCATION_CD,LOCA1.LOCATION_CD) = LOCA2.LOCATION_CD(+)
		AND	(LOCA1.LOCATION_LEVEL = '1' OR LOCA1.LOCATION_LEVEL = '4')
		AND	LOCA1.LOCATION_CD <> 'K'
		)UPPER_LOCATION
	
	WHERE
		SHIPPING_DETAIL.LOCATION_CD = UPPER_LOCATION.LOCATION_CD
	
	GROUP BY
		SHIPPING_DETAIL.SHIPPING_NO
	ORDER BY SHIPPING_DETAIL.SHIPPING_NO ASC
	)SHIPPING_DETAIL_LOCATION

WHERE
	SHIPPING.CARRY_CD = CARRY.CARRY_CD(+)
AND	SHIPPING.SHIPPING_NO = SHIPPING_DETAIL_LOCATION.SHIPPING_NO(+)
AND	SHIPPING.SHIPPING_NO = ORDER_DATA.SHIPPING_NO(+)
AND	SHIPPING_DETAIL_LOCATION.UPPER_LOCATION_CD IS NOT NULL
AND	SHIPPING.SHIPPING_NO IN /*shippingNo*/('')
ORDER BY 
	SHIPPING.SHIPPING_SLIP_NO,
	CARRY.REPOTR_OUTPUT_NUM,
	SHIPPING.CARRY_CD,
	ORDER_DATA.ORDER_NO,
	SHIPPING.VENDER_CD,
	SHIPPING.SCHEDULED_SHIPPING_DATE,
	SHIPPING.DELIVERY_CD,
	SHIPPING_DETAIL_LOCATION.UPPER_LOCATION_CD,
	ORDER_DATA.DELIVERY_EXPECTED_DATE,
	SHIPPING.SHIPPING_NO ASC

