/*
 * 仕入先別単価マスタ詳細検索SQL
 * entityName=UnitpriceDetailList
 * packageName=unitpricedetaillist
 * methodName=getList
 *
 */
SELECT	UNITPRICE.VENDER_DIVISION
,		UNITPRICE.UNITPRICE_DIVISION
,		UNITPRICE.VENDER_CD
,		UNITPRICE.ITEM_CD
,		OTHER_COMPANY_CD1
,		STYLE_OF_PACKING
,		MATERIAL_MAKER_NAME
,		QUANTITY_FROM
,		QUANTITY_TO
,		UNITPRICE
,		UNITPRICE.VALID_DATE
,		UNITPRICE.CONSECUTIVE_NO
,		UNITPRICE.REMARKS
,		UNITPRICE.UPDATE_DATE
,		VENDER.VENDER_SHORTED_NAME AS VENDER_NAME1
,		ITEM_QUEUE.ITEM_NAME
,		ITEM_QUEUE.VERSION
,		SMALLNUM_LENGTH
,		ROUND_DIVISION
,CASE TO_NUMBER(UNITPRICE_DIVISION)
	WHEN 1 THEN '円/個'
	WHEN 2 THEN '円/Kg'
	ELSE NULL
END UNITPRICE_DIVISION_NAME
,	UNIT_OF_OPERATION_MANAGEMENT
,	'SITANKA' UNIT_DIVISION_SITANKA

FROM	UNITPRICE, VENDER, VALID_ITEM_QUEUE ITEM_QUEUE, PURCHASE_ATTRIBUTE_QUEUE, NUMBER_CHKDISIT

WHERE UNITPRICE.VENDER_DIVISION = /*venderDivision*/'SI'
AND	UNITPRICE.VENDER_CD = /*venderCd*/'%'
AND UNITPRICE.ITEM_CD = /*itemCd*/'%'
AND UNITPRICE.VERSION = /*version*/1

AND	VENDER.VENDER_DIVISION(+) = UNITPRICE.VENDER_DIVISION
AND UNITPRICE.VENDER_CD = VENDER.VENDER_CD(+)
AND UNITPRICE.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE_ATTRIBUTE_QUEUE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE_ATTRIBUTE_QUEUE.VERSION(+)
AND NUMBER_CHKDISIT.UNIT_DIVISION(+) = 'SITANKA'
AND NUMBER_CHKDISIT.VENDER_DIVISION(+) = ' '
AND NUMBER_CHKDISIT.VENDER_CD(+) = ' '

ORDER BY UNITPRICE.CONSECUTIVE_NO
