/*
 * 納期連絡表ヘッダ用SQL
 *
 * entityName=RepDeliveryDateContactHeader
 * packageName=repdeliverydatecontactheader
 * methodName=getEntity
 *
 */
WITH TMP AS (
	SELECT
		  RDDCH.KEY
		, RDDCH.FRST_ORDER_NO AS PK_NO
		, RDDCH.FRST_ORDER_ROW_NO AS PK_ROW
		, RDDCH.VENDER_CD
		, RDDCH.VENDER_NAME
		, RDDCH.VENDER_FULL_ADDRESS_1
		, RDDCH.VENDER_FULL_ADDRESS_2
		, RDDCH.VENDER_TEL_NO
		, RDDCH.VENDER_FAX_NO
		, RDDCH.CTM_VENDER_CD
		, RDDCH.CTM_VENDER_NAME
		, RDDCH.DELIVERY_CD
		, RDDCH.DELIVERY_NAME
		, RDDCH.DELIVERY_FULL_ADDRESS_1
		, RDDCH.DELIVERY_FULL_ADDRESS_2
		, RDDCH.DELIVERY_ADDRESS
		, RDDCH.DELIVERY_TEL_NO
		, RDDCH.DELIVERY_FAX_NO
		, RDDCH.CTM_DELIVERY_CD
		, RDDCH.CTM_DELIVERY_NAME
		, RDDCH.CTM_DELIVERY_FULL_ADDRESS
		, RDDCH.CTM_DELIVERY_TEL_NO
		, RDDCH.CTM_DELIVERY_FAX_NO
		, RDDCH.CTM_DELIVERY_ZIP_CD
		, RDDCH.CTM_ORDER_NO
		, RDDCH.CTM_ORDER_DATE
		, RDDCH.DELIVERY_EXPECTED_DATE
		, RDDCH.SALES_TANTO_CD
		, RDDCH.SALES_TANTO_NAME
		, RDDCH.ORDER_NO
		, RDDCH.CARRY_CD
		, RDDCH.CARRY_NAME
		, RDDCH.CARRY_FARE
		, RDDCH.PRINT_SUMMERY
		, RDDCH.DELIVERY_SLIP_SUMMERY
		, RDDCH.SCHEDULED_SHIPPING_DATE
        , RDDCH.INPUT_DIVISION
        , RDDCH.UPDATE_DATE
        , RDDCH.ORG_ZIPCODE
        , RDDCH.ORG_ADDRESS
        , RDDCH.ORG_TEL_NO
        , RDDCH.ORG_FAX_NO
        , RDDCH.SEC_VENDER_CD
        , RDDCH.THI_VENDER_CD  -- 20210908 Asclab Saita 納期連絡表改修対応
        , RDDCH.FOU_VENDER_CD  -- 20210908 Asclab Saita 納期連絡表改修対応
        , RDDCH.FIF_VENDER_CD  -- 20210908 Asclab Saita 納期連絡表改修対応
		, RDDCH.DELIVERY_EXPECTED_TIME
        , RDDCH.DELIVERYDATE_CONTACT_SUMMERY  -- 20210908 Asclab Saita 納期連絡表改修対応
        FROM REP_DEL_DATE_CONTACT_HEADER RDDCH
	WHERE
	    FRST_ORDER_NO IS NOT NULL
    --客先注文番号
     /*IF (orderNo != null) */
	    AND	RDDCH.ORDER_NO = /*orderNo*/'00000000'
     /*END*/
     /*IF (pkNo != null) && ( orderNo == null ) */
	    AND RDDCH.FRST_ORDER_NO = /*pkNo*/'LK000000079'
    /*END*/
) , LOG_TMP AS (
	-- 履歴から過去の告知納期を取得
	SELECT
		OI_LOG.FRST_ORDER_NO AS PK_NO
		, RANK() OVER( PARTITION BY OI_LOG.FRST_ORDER_NO ORDER BY OI_LOG.FRST_ORDER_LOG_NO DESC , OI_LOG.DELIVERY_EXPECTED_DATE DESC ) AS I_RANK
		, OI_LOG.DELIVERY_EXPECTED_DATE
	FROM
		FRST_ORDER_HEAD_LOG OI_LOG
	WHERE
	    FRST_ORDER_LOG_NO IN (
			SELECT
			    MAX( CASE WHEN LOG_1 > LOG_2 THEN LOG_1 ELSE LOG_2 END  ) AS FRST_ORDER_LOG_NO
			FROM
			(
			    SELECT
			         MAX( CASE WHEN FRST_ORDER_HEAD_LOG.DELIVERY_EXPECTED_DATE <> FRST_ORDER_HEAD.DELIVERY_EXPECTED_DATE THEN FRST_ORDER_HEAD_LOG.FRST_ORDER_LOG_NO ELSE 0 END ) AS LOG_1
			        , MAX( CASE WHEN FRST_ORDER_DETAIL_LOG.ORDER_QTY <> FRST_ORDER_DETAIL.ORDER_QTY THEN FRST_ORDER_DETAIL_LOG.FRST_ORDER_LOG_NO ELSE 0 END ) AS LOG_2
			    FROM
			        FRST_ORDER_HEAD
			    INNER JOIN
			        FRST_ORDER_DETAIL
			    ON
			        FRST_ORDER_HEAD.FRST_ORDER_NO = FRST_ORDER_DETAIL.FRST_ORDER_NO
			    LEFT JOIN
			        FRST_ORDER_HEAD_LOG
			    ON
			        FRST_ORDER_HEAD_LOG.FRST_ORDER_NO = FRST_ORDER_HEAD.FRST_ORDER_NO
			        AND FRST_ORDER_HEAD_LOG.LOG_CLS = '20'
			    LEFT JOIN
			        FRST_ORDER_DETAIL_LOG
			    ON
			        FRST_ORDER_DETAIL_LOG.FRST_ORDER_NO = FRST_ORDER_DETAIL.FRST_ORDER_NO
			        AND FRST_ORDER_DETAIL_LOG.FRST_ORDER_ROW_NO = FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO
			        AND FRST_ORDER_DETAIL_LOG.LOG_CLS = '20'
			    WHERE
			        FRST_ORDER_HEAD.FRST_ORDER_NO IN ( /*pkNo*/ )
			)
	    )
), FILE_CHECK AS (
	-- 同一受注内でファイル読込品番があった場合、告知文言を追加
    SELECT
          TMP.ORDER_NO
        , CASE WHEN MAX( CASE WHEN TMP.INPUT_DIVISION = 1 THEN 1 ELSE 0 END ) = 1
            THEN '※品目はファイル読込から登録された品目です。運賃は返信ファイルと受注連絡表の両方に記載しています。' END AS HEADER_REMARK
    FROM
        TMP
    GROUP BY
        TMP.ORDER_NO
)
SELECT
		  TMP.KEY
		, TMP.PK_NO
		, TMP.PK_ROW
		, TMP.VENDER_CD
		, TMP.VENDER_NAME
		, TMP.VENDER_FULL_ADDRESS_1
		, TMP.VENDER_FULL_ADDRESS_2
		, TMP.VENDER_TEL_NO
		, TMP.VENDER_FAX_NO
		, TMP.CTM_VENDER_CD
		, TMP.CTM_VENDER_NAME
		, TMP.DELIVERY_CD
		, TMP.DELIVERY_NAME
		, TMP.DELIVERY_FULL_ADDRESS_1
		, TMP.DELIVERY_FULL_ADDRESS_2
		, TMP.DELIVERY_ADDRESS
		, TMP.DELIVERY_TEL_NO
		, TMP.DELIVERY_FAX_NO
		, TMP.CTM_DELIVERY_CD
		, TMP.CTM_DELIVERY_NAME
		, TMP.CTM_DELIVERY_FULL_ADDRESS
		, TMP.CTM_DELIVERY_TEL_NO
		, TMP.CTM_DELIVERY_FAX_NO
		, TMP.CTM_DELIVERY_ZIP_CD
		, TMP.CTM_ORDER_NO
		, TMP.CTM_ORDER_DATE
		, TO_CHAR( TMP.DELIVERY_EXPECTED_DATE , 'FMyyyy/MM/dd' )
		  || CASE WHEN NVL(LENGTH(TRIM(TMP.DELIVERY_EXPECTED_TIME)),0) <> 0 THEN ' ' || TMP.DELIVERY_EXPECTED_TIME ELSE NULL END
		  || CASE
			WHEN LOG_TMP.DELIVERY_EXPECTED_DATE IS NOT NULL
					AND TO_CHAR( LOG_TMP.DELIVERY_EXPECTED_DATE , 'yyyy/MM/dd' ) <> TO_CHAR( TMP.DELIVERY_EXPECTED_DATE , 'yyyy/MM/dd' ) THEN
               '(前回:' || TO_CHAR( LOG_TMP.DELIVERY_EXPECTED_DATE , 'FMyyyy/MM/dd' ) || ')'
          END AS  DELIVERY_EXPECTED_DATE
		, TMP.SALES_TANTO_CD
		, TMP.SALES_TANTO_NAME
		, TMP.ORDER_NO
		, TMP.CARRY_CD
		, TMP.CARRY_NAME
		, TMP.CARRY_FARE
		, TMP.PRINT_SUMMERY
		, TMP.DELIVERY_SLIP_SUMMERY
		, TMP.SCHEDULED_SHIPPING_DATE
        , FILE_CHECK.HEADER_REMARK
        , TMP.ORG_ZIPCODE
        , TMP.ORG_ADDRESS
        , TMP.ORG_TEL_NO
        , TMP.ORG_FAX_NO
        , TMP.SEC_VENDER_CD -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(VENDER.VENDER_NAME1,VENDER.VENDER_NAME2) AS SEC_VENDER_NAME
		, CONCAT(CONCAT(VENDER.ADDRESS1,VENDER.ADDRESS2),VENDER.ADDRESS3) AS SEC_VENDER_ADDRESS
		, VENDER.TEL_NO AS SEC_VENDER_TEL_NO
		, VENDER.FAX_NO AS SEC_VENDER_FAX_NO
        , TMP.THI_VENDER_CD -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(VEN_THI.VENDER_NAME1,VEN_THI.VENDER_NAME2) AS THI_VENDER_NAME -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(CONCAT(VEN_THI.ADDRESS1,VEN_THI.ADDRESS2),VEN_THI.ADDRESS3) AS THI_VENDER_ADDRESS -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_THI.TEL_NO AS THI_VENDER_TEL_NO -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_THI.FAX_NO AS THI_VENDER_FAX_NO -- 20210908 Asclab Saita 納期連絡表改修対応
        , TMP.FOU_VENDER_CD -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(VEN_FOU.VENDER_NAME1,VEN_FOU.VENDER_NAME2) AS FOU_VENDER_NAME -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(CONCAT(VEN_FOU.ADDRESS1,VEN_FOU.ADDRESS2),VEN_FOU.ADDRESS3) AS FOU_VENDER_ADDRESS -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_FOU.TEL_NO AS FOU_VENDER_TEL_NO -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_FOU.FAX_NO AS FOU_VENDER_FAX_NO -- 20210908 Asclab Saita 納期連絡表改修対応
        , TMP.FIF_VENDER_CD -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(VEN_FIF.VENDER_NAME1,VEN_FIF.VENDER_NAME2) AS FIF_VENDER_NAME -- 20210908 Asclab Saita 納期連絡表改修対応
		, CONCAT(CONCAT(VEN_FIF.ADDRESS1,VEN_FIF.ADDRESS2),VEN_FIF.ADDRESS3) AS FIF_VENDER_ADDRESS -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_FIF.TEL_NO AS FIF_VENDER_TEL_NO -- 20210908 Asclab Saita 納期連絡表改修対応
		, VEN_FIF.FAX_NO AS FIF_VENDER_FAX_NO -- 20210908 Asclab Saita 納期連絡表改修対応
		, TMP.DELIVERYDATE_CONTACT_SUMMERY -- 20210908 Asclab Saita 納期連絡表改修対応
FROM
	TMP
LEFT JOIN
	LOG_TMP
ON
	LOG_TMP.PK_NO = TMP.PK_NO
	AND LOG_TMP.I_RANK = 1
LEFT JOIN
    FILE_CHECK
ON
    FILE_CHECK.ORDER_NO = TMP.ORDER_NO
LEFT JOIN
	VENDER
ON
	VENDER.VENDER_DIVISION = 'TS' AND VENDER.VENDER_CD = TMP.SEC_VENDER_CD
 -- 20210908 Asclab Saita 納期連絡表改修対応
LEFT JOIN
	VENDER VEN_THI
ON
	VEN_THI.VENDER_DIVISION = 'TS' AND VEN_THI.VENDER_CD = TMP.THI_VENDER_CD
LEFT JOIN
	VENDER VEN_FOU
ON
	VEN_FOU.VENDER_DIVISION = 'TS' AND VEN_FOU.VENDER_CD = TMP.FOU_VENDER_CD
LEFT JOIN
	VENDER VEN_FIF
ON
	VEN_FIF.VENDER_DIVISION = 'TS' AND VEN_FIF.VENDER_CD = TMP.FIF_VENDER_CD
