/*
 *
 *
 * entityName=RecipeProcedureForReport
 * packageName=recipeforreport
 * methodName=getProcedureList
 *
 */
SELECT 
	RECIPE_PROCEDURE.RECIPE_ID
,	RECIPE_PROCEDURE.STEP_NO
,	RECIPE_PROCEDURE.SEQ
,	RECIPE_PROCEDURE.OPERATION_CD
,	OPERATION.OPERATION_NAME
,	RECIPE_PROCEDURE.CONDITION
,	RECIPE_PROCEDURE.REMARK
,	RECIPE_PROCEDURE.NOTES
,	RECIPE_PROCEDURE.MACHINE_TIME
,	RECIPE_PROCEDURE.MAN_TIME
,	RECIPE_PROCEDURE.WORK_TIME
,	RECIPE_PROCEDURE.CONDITION_TEMP
,	RECIPE_PROCEDURE.CONDITION_TIME
,	RECIPE_PROCEDURE.STIR_SPEED1
,	RECIPE_PROCEDURE.STIR_SPEED2
,	RECIPE_PROCEDURE.WATER_WEIGHT
,	RECIPE_PROCEDURE.MAIN_STREAM
,	RECIPE_PROCEDURE.NET
,	RECIPE_PROCEDURE.WEIGHT_MIN
,	RECIPE_PROCEDURE.WEIGHT_MAX
,	RECIPE_PROCEDURE.FILTER
,	RECIPE_PROCEDURE.MESH
,	RECIPE_PROCEDURE.AUTO_CHECKER_MIN
,	RECIPE_PROCEDURE.AUTO_CHECKER_MAX
,	RECIPE_PROCEDURE.GROSS_CHECKER_MIN
,	RECIPE_PROCEDURE.GROSS_CHECKER_MAX
,	RECIPE_PROCEDURE.AUTO_CHECKER_AVE
,	RECIPE_PROCEDURE.GROSS_CHECKER_AVE
,	RECIPE_PROCEDURE.OPENING_TORQUE_MIN
,	RECIPE_PROCEDURE.OPENING_TORQUE_MAX
,	RECIPE_PROCEDURE.CLOSING_TORQUE_MIN
,	RECIPE_PROCEDURE.CLOSING_TORQUE_MAX
,	RECIPE_PROCEDURE.TORQUE_PRESSURE
,	RECIPE_PROCEDURE.AIR_PRESSURE
,	RECIPE_PROCEDURE.VCLOSE_TIME
,	RECIPE_PROCEDURE.HOT_AIR_PRESET_TEMP
,	RECIPE_PROCEDURE.HOT_AIR_PRESSURE
,	RECIPE_PROCEDURE.FIRST_HEAT_SEAL
,	RECIPE_PROCEDURE.SECOND_HEAT_SEAL
,	RECIPE_PROCEDURE.INPUTOR_CD
,	RECIPE_PROCEDURE.INPUT_DATE
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	RECIPE_PROCEDURE.UPDATOR_CD
,	RECIPE_PROCEDURE.UPDATE_DATE
,	UPDATOR.TANTO_NM AS UPDATE_NAME
 FROM 
	RECIPE_HEADER
,	RECIPE_PROCEDURE
,	ITEM
,	OPERATION
,	LOGIN INPUTOR
,	LOGIN UPDATOR
WHERE
	RECIPE_HEADER.RECIPE_ID = RECIPE_PROCEDURE.RECIPE_ID
AND	RECIPE_HEADER.ITEM_CD = ITEM.ITEM_CD(+)
AND	RECIPE_PROCEDURE.OPERATION_CD = OPERATION.OPERATION_CD
AND	RECIPE_PROCEDURE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND	RECIPE_PROCEDURE.UPDATOR_CD = UPDATOR.TANTO_CD(+)

AND	RECIPE_HEADER.RECIPE_TYPE = /*condition.recipeType*/'3'

/*IF (( condition.recipeCd != null ) && ( condition.recipeCd != "" ))*/
	AND	RECIPE_HEADER.RECIPE_CD LIKE /*condition.recipeCd*/''
/*END*/

/*IF (( condition.recipeVersion != null ) && ( condition.recipeVersion != "" ))*/
	AND	RECIPE_HEADER.RECIPE_VERSION LIKE /*condition.recipeVersion*/''
/*END*/

/*IF (( condition.recipeStatus != null ) && ( condition.recipeStatus != "" ))*/
	AND	RECIPE_HEADER.RECIPE_STATUS = /*condition.recipeStatus*/''
/*END*/

/*IF (( condition.approvalStatus != null ) && ( condition.approvalStatus != "" ))*/
	AND	RECIPE_HEADER.APPROVAL_STATUS = /*condition.approvalStatus*/''
/*END*/

/*IF (( condition.recipeUse != null ) && ( condition.recipeUse != "" ))*/
	AND	RECIPE_HEADER.RECIPE_USE = /*condition.recipeUse*/''
/*END*/

/*IF (( condition.productionLine != null ) && ( condition.productionLine != "" ))*/
	AND	RECIPE_HEADER.PRODUCTION_LINE = /*condition.productionLine*/''
/*END*/

/*IF (( condition.product != null ) && ( condition.product != "" ))*/
	AND	(RECIPE_HEADER.ITEM_CD LIKE /*condition.product*/'' OR ITEM.ITEM_NAME LIKE /*condition.product*/'')
/*END*/

/*IF (( condition.recipeName != null ) && ( condition.recipeName != "" ))*/
	AND	RECIPE_HEADER.RECIPE_NAME LIKE /*condition.recipeName*/''
/*END*/

/*IF (( condition.otherCompanyCd1 != null ) && ( condition.otherCompanyCd1 != "" ))*/
	AND	ITEM.OTHER_COMPANY_CD1 LIKE /*condition.otherCompanyCd1*/''
/*END*/

ORDER BY
	RECIPE_HEADER.RECIPE_CD,
	RECIPE_HEADER.RECIPE_VERSION,
	RECIPE_PROCEDURE.STEP_NO




