/*
 * 運送会社マスタ用SQL
 *
 * entityName=CarryDetail
 * packageName=carrydetail
 * methodName=getEntity
 *
 */

SELECT 
   CARRY.CARRY_CD
,  CARRY.CARRY_NAME1
,  CARRY.CARRY_NAME2
,  CARRY.ABBREVIATION
,  CARRY.ZIPCODE_NO
,  CARRY.TEL_NO
,  CARRY.FAX_NO
,  CARRY.ADDRESS1
,  CARRY.ADDRESS2
,  CARRY.ADDRESS3
,  CARRY.FLAN_TRANS_SHOP_CD
,  CARRY.BC_PUBLISH_DIVISION
,  CARRY.BC_HEADER
,  CARRY.BC_FOOTER
,  USER_SEQUENCES.MIN_VALUE AS BC_NUM_START
,  USER_SEQUENCES.MAX_VALUE AS BC_NUM_END
,  USER_SEQUENCES.LAST_NUMBER AS BC_NUM_PRESENT
,  FUN_REPLACE_CHECKDIGIT_7DR( CASE WHEN USER_SEQUENCES.LAST_NUMBER IS NULL THEN NULL ELSE
	CARRY.BC_HEADER || LPAD( CASE WHEN USER_SEQUENCES.LAST_NUMBER + USER_SEQUENCES.INCREMENT_BY > USER_SEQUENCES.MAX_VALUE 
							THEN USER_SEQUENCES.MIN_VALUE ELSE USER_SEQUENCES.LAST_NUMBER + USER_SEQUENCES.INCREMENT_BY 
							END 
        , CARRY.BC_NUMBER_OF_DIGIT , '0' ) || CARRY.BC_FOOTER
	END , CARRY.BC_CHECKDIGIT_START , CARRY.BC_CHECKDIGIT_END ) AS BC_NUM_NEXT_PUBLISH
,  CARRY.BC_NUMBER_OF_DIGIT
,  CARRY.BC_CHECKDIGIT_START
,  CARRY.BC_CHECKDIGIT_END
,  CARRY.REMARKS
,  CARRY.LABEL_PUBLISH
,  CARRY.UPDATE_DATE
,  CARRY.REPOTR_OUTPUT_NUM
FROM 
    CARRY
LEFT JOIN
    USER_SEQUENCES
ON
    USER_SEQUENCES.SEQUENCE_NAME = FUN_GET_CARRY_BC_SEQ_NAME(CARRY.CARRY_CD)
WHERE CARRY.CARRY_CD = /*carryCd*/'%'