/*
 * 関連情報原処方一覧用SQL
 *
 * entityName=ItemRelatedGrecipeList
 * packageName=itemrelatedgrecipelist
 * methodName=getList
 */

SELECT HEADER.RECIPE_ID
, HEADER.RECIPE_CD GRECIPE_CD
, HEADER.RECIPE_VERSION GRECIPE_VERSION
, HEADER.ITEM_CD GRECIPE_ITEM_CD
, ITEM_NAME GRECIPE_ITEM_NAME
, HEADER.UPDATE_DATE GRECIPE_UPDATE_DATE

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END GRECIPE_STATUS_NAME

FROM RECIPE_HEADER HEADER
, VALID_ITEM_QUEUE ITEM_QUEUE

WHERE HEADER.ITEM_CD = /*itemCd*/'%'
AND HEADER.RECIPE_TYPE = 1 --原処方
AND HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)

UNION

SELECT HEADER.RECIPE_ID
, HEADER.RECIPE_CD GRECIPE_CD
, HEADER.RECIPE_VERSION GRECIPE_VERSION
, HEADER.ITEM_CD GRECIPE_ITEM_CD
, ITEM_NAME GRECIPE_ITEM_NAME
, HEADER.UPDATE_DATE GRECIPE_UPDATE_DATE

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END GRECIPE_STATUS_NAME

FROM RECIPE_HEADER HEADER
, RECIPE_FORMULA FORMULA
, VALID_ITEM_QUEUE ITEM_QUEUE

WHERE FORMULA.ITEM_CD = /*itemCd*/'%'
AND HEADER.RECIPE_TYPE = 1 --原処方
AND FORMULA.LINE_NO <= 1000 --配合のみ
AND HEADER.RECIPE_ID = FORMULA.RECIPE_ID
AND HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)

ORDER BY RECIPE_ID
