CREATE OR REPLACE PROCEDURE      TESTSEIZO
IS
I_INVENTORY NUMBER :=0;
I_BACKORDER NUMBER:=0;
I_ASSIGN_QTY NUMBER:=0;
I_SALES NUMBER:=0;
I_FINISH NUMBER:=0;
I_INSPECTION NUMBER:=0;
L_INVENTORY NUMBER:=0;
L_BACKORDER NUMBER:=0;
L_ASSIGN_QTY NUMBER:=0;
L_SALES NUMBER:=0;
L_FINISH NUMBER:=0;
L_INSPECTION NUMBER:=0;
LL_INVENTORY NUMBER:=0;
LL_BACKORDER NUMBER:=0;
LL_ASSIGN_QTY NUMBER:=0;
LL_SALES NUMBER:=0;
LL_FINISH NUMBER:=0;
LL_INSPECTION NUMBER:=0;
O_INVENTORY NUMBER:=0;
O_BACKORDER NUMBER:=0;
O_ASSIGN_QTY NUMBER:=0;
O_SALES NUMBER:=0;
O_FINISH NUMBER:=0;
O_INSPECTION NUMBER:=0;
O_QTY NUMBER:=0;
O_FLG NUMBER:=0;
STR_IND NVARCHAR2(20):='';
CT NUMBER:=0;
para NVARCHAR2(1024):='';
ID NVARCHAR2(20):='';
A_LOT  NVARCHAR2(20):='';
BEGIN
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090001' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090001' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090001' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090001' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090001' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090001' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
END IF;

DELETE INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001';
DELETE INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001';
ZAIKOUKEHARAI.RESULT_INJECTION(1,'HT000001060',2249,6,1,'som',para);
 IF para = 'COMPLETE' THEN NULL;
ELSE 
GOTO P_END;
END IF;
ZAIKOUKEHARAI.RESULT_INJECTION(2,'HT000001060',2249,6,1,'som',para);
 IF para = 'COMPLETE' THEN NULL;
ELSE 
GOTO P_END;
END IF;

/*********************/
/* 製造登録          */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造登録');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(1,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 400 AND O_FLG = 0 THEN
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
	DBMS_OUTPUT.PUT_LINE('QTY = ' || TO_CHAR(O_QTY) || ' FLG = ' || TO_CHAR(O_FLG));
/*********************/
/* 配合登録          */
/*********************/
	DBMS_OUTPUT.PUT_LINE('配合登録');
 ZAIKOUKEHARAI.ENTRY_FORMULA(1,'TESTDIRECTION001',1,null,null,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,1,null,null,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = -50 AND O_FLG = 0 THEN
	NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,1,null,null,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
	DBMS_OUTPUT.PUT_LINE('QTY = ' || TO_CHAR(O_QTY) || ' FLG = ' || TO_CHAR(O_FLG));
/*********************/
/* 配合登録取消      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('配合登録取消');
 ZAIKOUKEHARAI.ENTRY_FORMULA(2,'TESTDIRECTION001',1,null,null,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' ;
IF CT > 0 THEN
	para :='ENTRY_FORMULA(2,TESTDIRECTION001,1,null,null,som,para); not DELETE INOUT_SOURCE';
	GOTO P_END;
END IF;
/*********************/
/* 製造登録取消      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造登録取消');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(2,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' ;
IF CT > 0 THEN
	para :='ENTRY_DIRECTION(2,TESTDIRECTION001,1,som,para); not DELETE INOUT_SOURCE';
	GOTO P_END;
END IF;
/*********************/
/* 製造確定　　      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造登録');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(1,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
	DBMS_OUTPUT.PUT_LINE('配合登録');
 ZAIKOUKEHARAI.ENTRY_FORMULA(1,'TESTDIRECTION001',1,null,null,'som',para);
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
	DBMS_OUTPUT.PUT_LINE('製造確定');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(3,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 400 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER + 400 AND O_ASSIGN_QTY = I_ASSIGN_QTY 
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); ' || TO_CHAR(O_BACKORDER) || ',' || TO_CHAR(I_BACKORDER );
	GOTO P_END;
END IF;	
/*********************/
/* 製造確定取消      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造確定取消');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(4,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 400 AND O_FLG = 0 THEN
	NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY 
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_DIRECTION(1,TESTDIRECTION001,som,para); ' || TO_CHAR(O_BACKORDER) || ',' || TO_CHAR(I_BACKORDER );
	GOTO P_END;
END IF;	
/*********************/
/* 配合確定　　      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造確定');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(3,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
	DBMS_OUTPUT.PUT_LINE('配合確定');
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
END IF;
 ZAIKOUKEHARAI.ENTRY_FORMULA(3,'TESTDIRECTION001',1,801,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,1,null,null,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = -50 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,1,null,null,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
ELSE 
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY -50
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
/*********************/
/* 配合確定取消      */
/*********************/
	DBMS_OUTPUT.PUT_LINE('配合確定取消');
 ZAIKOUKEHARAI.ENTRY_FORMULA(4,'TESTDIRECTION001',1,801,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='ENTRY_FORMULA(4,TESTDIRECTION001,1,null,null,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = -50 AND O_FLG = 0 THEN
	NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,1,null,null,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
/*********************/
/* 配合確定　難あり  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('配合確定');
 ZAIKOUKEHARAI.ENTRY_FORMULA(3,'TESTDIRECTION001',1,801,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;

select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '04333333' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '04333333' 
;
END IF;

 ZAIKOUKEHARAI.ENTRY_FORMULA(3,'TESTDIRECTION001',1,401,11,'som',para);
DBMS_OUTPUT.PUT_LINE(para);
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '04333333' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '04333333' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY -250
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,401,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
END IF;

 ZAIKOUKEHARAI.ENTRY_FORMULA(3,'TESTDIRECTION001',1,901,11,'som',para);
DBMS_OUTPUT.PUT_LINE(para);
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
ELSE 
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY -75
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(3,TESTDIRECTION001,401,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
	
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000005' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000005' 
;
END IF;

 ZAIKOUKEHARAI.ENTRY_FORMULA(3,'TESTDIRECTION001',1,601,11,'som',para);
DBMS_OUTPUT.PUT_LINE(para);
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000005' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000005' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY -25
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(3,TESTDIRECTION001,601,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
/*********************/
/* 配合実績          */
/*********************/

	DBMS_OUTPUT.PUT_LINE('配合実績');
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
L_INVENTORY:=0;
L_BACKORDER:=0;
L_ASSIGN_QTY:=0;
L_SALES:=0;
L_FINISH:=0;
L_INSPECTION:=0;
LL_INVENTORY:=0;
LL_BACKORDER:=0;
LL_ASSIGN_QTY:=0;
LL_SALES:=0;
LL_FINISH:=0;
LL_INSPECTION:=0;

select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
END IF;
 ZAIKOUKEHARAI.RESULT_FORMULA(1,'TESTDIRECTION001',1,801,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT COUNT(*) INTO CT FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
IF CT = 1 THEN 
	NULL;
ELSE
	para :='RESULT_FORMULA(1,TESTDIRECTION001,1,801,11,som,para); not Create INOUT_SOURCE';
	GOTO P_END;
END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = '01TESTDIRECTION001' AND ODER_LINE_NO = 8010011;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 5 AND O_FLG = 1  THEN
	NULL;
ELSE
	para :='RESULT_FORMULA(1,TESTDIRECTION001,1,801,11,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = L_INVENTORY-55 AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = LL_INVENTORY-55 AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
ELSE 
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY-55 AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY +50
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :=' ITEM RESULT_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
/*********************/
/* 配合実績取消　　  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('配合実績取消');
 ZAIKOUKEHARAI.RESULT_FORMULA(2,'TESTDIRECTION001',1,801,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='RESULT_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '01000007' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = '12345678'
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :='RESULT_FORMULA(1,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000007' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='RESULT_FORMULA(2,TESTDIRECTION001,801,11,som,para); ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_ASSIGN_QTY );
	GOTO P_END;
END IF;	
/*********************/
/* 配合完了　　　　  */
/*********************/

	DBMS_OUTPUT.PUT_LINE('配合完了');
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;

select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
END IF;

 ZAIKOUKEHARAI.RESULT_FORMULA(1,'TESTDIRECTION001',1,901,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
 ZAIKOUKEHARAI.RESULT_FORMULA(5,'TESTDIRECTION001',1,901,11,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '01000004' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY -10  AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY +75
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ENTRY_FORMULA(1,TESTDIRECTION001,901,11,som,para); ' || TO_CHAR(O_ASSIGN_QTY) || ',' || TO_CHAR(I_ASSIGN_QTY );
	GOTO P_END;
END IF;	
 ZAIKOUKEHARAI.RESULT_FORMULA(5,'TESTDIRECTION001',1,null,null,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;

/*********************/
/*製造実績　　　　  */
/*********************/

	DBMS_OUTPUT.PUT_LINE('製造仕上');
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
L_INVENTORY:=0;
L_BACKORDER:=0;
L_ASSIGN_QTY:=0;
L_SALES:=0;
L_FINISH:=0;
L_INSPECTION:=0;
LL_INVENTORY:=0;
LL_BACKORDER:=0;
LL_ASSIGN_QTY:=0;
LL_SALES:=0;
LL_FINISH:=0;
LL_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
END IF;
 ZAIKOUKEHARAI.RESULT_DIRECTION(1,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0),ALIAS_LOT_NO 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION ,A_LOT
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = LL_INVENTORY+100 AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION AND A_LOT IS NULL THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); aaa ' || TO_CHAR(LL_INVENTORY) || ',' || TO_CHAR(LL_BACKORDER) || ',' || TO_CHAR(A_LOT);
	DBMS_OUTPUT.PUT_LINE(para);
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = L_INVENTORY+100 AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY+100 AND O_BACKORDER = I_BACKORDER-100 AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	
/*********************/
/*製造実績取消　　  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造仕上取消');
 ZAIKOUKEHARAI.RESULT_DIRECTION(2,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 400 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION  THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(LL_INVENTORY) || ',' || TO_CHAR(LL_BACKORDER );
	DBMS_OUTPUT.PUT_LINE(para);
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	
/*********************/
/*製造完了　　  　　 */
/*********************/
	DBMS_OUTPUT.PUT_LINE('製造完了');
 ZAIKOUKEHARAI.RESULT_DIRECTION(1,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
 ZAIKOUKEHARAI.RESULT_DIRECTION(5,'TESTDIRECTION001',1,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION001' AND ODER_LINE_NO = 1;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 0 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION001'
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = LL_INVENTORY+100 AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = L_INVENTORY+100 AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
ELSE
	GOTO P_END;
END IF;
IF O_INVENTORY = I_INVENTORY+100 AND O_BACKORDER = I_BACKORDER-400 AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	

/*********************/
/*包装実績　　　　  */
/*********************/

	DBMS_OUTPUT.PUT_LINE('包装仕上');
 ZAIKOUKEHARAI.ENTRY_DIRECTION(1,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
 ZAIKOUKEHARAI.ENTRY_DIRECTION(3,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
L_INVENTORY:=0;
L_BACKORDER:=0;
L_ASSIGN_QTY:=0;
L_SALES:=0;
L_FINISH:=0;
L_INSPECTION:=0;
LL_INVENTORY:=0;
LL_BACKORDER:=0;
LL_ASSIGN_QTY:=0;
LL_SALES:=0;
LL_FINISH:=0;
LL_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0)
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
	DBMS_OUTPUT.PUT_LINE('仕上');
 ZAIKOUKEHARAI.RESULT_DIRECTION(1,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION002,2,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION  THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION002,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER-100 AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH+100 AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(I_BACKORDER ) || ',' || TO_CHAR(O_BACKORDER  );
	DBMS_OUTPUT.PUT_LINE(para);
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(I_FINISH ) || ',' || TO_CHAR(O_FINISH   );
	GOTO P_END;
END IF;	
/*********************/
/*包装実績取消　　  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('包装仕上取消');
 ZAIKOUKEHARAI.RESULT_DIRECTION(2,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 400 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION002,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	

/*********************/
/*検査待実績　　　　  */
/*********************/

	DBMS_OUTPUT.PUT_LINE('検査待実績');
 ZAIKOUKEHARAI.RESULT_DIRECTION(1,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;

I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
L_INVENTORY:=0;
L_BACKORDER:=0;
L_ASSIGN_QTY:=0;
L_SALES:=0;
L_FINISH:=0;
L_INSPECTION:=0;
LL_INVENTORY:=0;
LL_BACKORDER:=0;
LL_ASSIGN_QTY:=0;
LL_SALES:=0;
LL_FINISH:=0;
LL_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
 ZAIKOUKEHARAI.RESULT_DIRECTION(3,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION002,2,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_INSPECTION );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_INSPECTION );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH-100 AND O_INSPECTION = I_INSPECTION+100 THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH ) || ',' || TO_CHAR(I_INSPECTION  );
	GOTO P_END;
END IF;	
/*********************/
/*検査待取消　　　  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('検査待取消');
 ZAIKOUKEHARAI.RESULT_DIRECTION(4,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	
/*********************/
/*格付実績　　　　  */
/*********************/

	DBMS_OUTPUT.PUT_LINE('格付実績');
 ZAIKOUKEHARAI.RESULT_DIRECTION(3,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;

I_INVENTORY:=0;
I_BACKORDER:=0;
I_ASSIGN_QTY:=0;
I_SALES:=0;
I_FINISH:=0;
I_INSPECTION:=0;
L_INVENTORY:=0;
L_BACKORDER:=0;
L_ASSIGN_QTY:=0;
L_SALES:=0;
L_FINISH:=0;
L_INSPECTION:=0;
LL_INVENTORY:=0;
LL_BACKORDER:=0;
LL_ASSIGN_QTY:=0;
LL_SALES:=0;
LL_FINISH:=0;
LL_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO I_INVENTORY,I_BACKORDER,I_ASSIGN_QTY,I_SALES,I_FINISH,I_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO L_INVENTORY,L_BACKORDER,L_ASSIGN_QTY,L_SALES,L_FINISH,L_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7'
;
END IF;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO LL_INVENTORY,LL_BACKORDER,LL_ASSIGN_QTY,LL_SALES,LL_FINISH,LL_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
 ZAIKOUKEHARAI.RESULT_DIRECTION(6,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION002,2,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) ,ALIAS_LOT_NO
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION ,A_LOT
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY+100 AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION AND A_LOT = '12345678' THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_INSPECTION );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY+100 AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH) || ',' || TO_CHAR(O_INSPECTION );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY+100 AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION-100 THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_FINISH ) || ',' || TO_CHAR(I_INSPECTION  );
	GOTO P_END;
END IF;	
/*********************/
/*格付取消　　　  */
/*********************/
	DBMS_OUTPUT.PUT_LINE('格付取消');
 ZAIKOUKEHARAI.RESULT_DIRECTION(7,'TESTDIRECTION002',2,'som',para);
 IF para = 'COMPLETE' THEN NULL;ELSE GOTO P_END;END IF;
SELECT INOUT_SOURCE_NO  INTO STR_IND FROM INOUT_SOURCE WHERE ODER_NO = 'TESTDIRECTION002' AND ODER_LINE_NO = 2;
SELECT INOUT_QTY,ASSIGN_FLAG INTO O_QTY,O_FLG FROM INOUT_SOURCE WHERE INOUT_SOURCE_NO  = STR_IND; 
IF O_QTY = 300 AND O_FLG = 1 THEN
	NULL;
ELSE
	para :='RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para); ' || TO_CHAR(O_QTY) || ',' || TO_CHAR(O_FLG);
	GOTO P_END;
END IF;
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOT_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' AND LOT_NO = 'TESTDIRECTION002'
;
END IF;
IF O_INVENTORY = LL_INVENTORY AND O_BACKORDER = LL_BACKORDER AND O_ASSIGN_QTY = LL_ASSIGN_QTY 
   AND O_SALES = LL_SALES AND O_FINISH = LL_FINISH AND O_INSPECTION = LL_INSPECTION THEN
   NULL;
ELSE
	para :=' LOT RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM LOCATION_INVENTORY 
WHERE ITEM_CD = '03090002' AND LOCATION_CD = 'B7-77-77-77-7' 
;
END IF;
IF O_INVENTORY = L_INVENTORY AND O_BACKORDER = L_BACKORDER AND O_ASSIGN_QTY = L_ASSIGN_QTY 
   AND O_SALES = L_SALES AND O_FINISH = L_FINISH AND O_INSPECTION = L_INSPECTION THEN
   NULL;
ELSE
	para :='LOCATION RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER );
	GOTO P_END;
END IF;	
O_INVENTORY:=0;
O_BACKORDER:=0;
O_ASSIGN_QTY:=0;
O_SALES:=0;
O_FINISH:=0;
O_INSPECTION:=0;
select COUNT(*) 
INTO CT 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
IF CT = 1 THEN
select NVL(INVENTORY_QTY,0),NVL(BACKORDER_QTY,0),NVL(ASSIGN_QTY,0),NVL(SALES_ASSIGN_QTY,0),NVL(FINISH_QTY,0),NVL(INSPECTION_QTY,0) 
INTO O_INVENTORY,O_BACKORDER,O_ASSIGN_QTY,O_SALES,O_FINISH,O_INSPECTION 
FROM ITEM_INVENTORY 
WHERE ITEM_CD = '03090002' 
;
END IF;
IF O_INVENTORY = I_INVENTORY AND O_BACKORDER = I_BACKORDER AND O_ASSIGN_QTY = I_ASSIGN_QTY
   AND O_SALES = I_SALES AND O_FINISH = I_FINISH AND O_INSPECTION = I_INSPECTION THEN
   NULL;
ELSE
	para :='ITEM RESULT_DIRECTION(1,TESTDIRECTION001,1,som,para);  ' || TO_CHAR(O_INVENTORY) || ',' || TO_CHAR(O_BACKORDER  );
	GOTO P_END;
END IF;	

	DBMS_OUTPUT.PUT_LINE('終わった');
	ROLLBACK;
<<P_END>>
	DBMS_OUTPUT.PUT_LINE(para);
END;
/
