/*
 * 入金入力（リスト)一覧検索用SQL
 *
 * entityName=DepositCreditListForReport
 * packageName=depositlistforreport
 * methodName=getListForReport
 *
 */
SELECT CRE.*
, CLS.CATEGORY_NAME
, VEN.VENDER_NAME1
, VEN.VENDER_SHORTED_NAME
, ORG.ORGANIZATION_NAME
, BANK.BANK_MASTER_NAME
, DEBIT_SECTION.SECTION_NAME DEBIT_SECTION_NAME
, DEBIT_TITLE.ACCOUNTS_NAME DEBIT_TITLE_NAME
, CREDIT_SECTION.SECTION_NAME CREDIT_SECTION_NAME
, CREDIT_TITLE.ACCOUNTS_NAME CREDIT_TITLE_NAME
, APPROVOR.TANTO_NM APPROVOR_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

, CASE CRE.ACCOUNT_DIVISION
	WHEN 1 THEN '普通'
	WHEN 2 THEN '当座'
	WHEN 3 THEN 'その他'
END ACCOUNT_DIVISION_NAME

, CASE CRE.APPROVAL_STATUS
	WHEN 1 THEN '入力中'
	WHEN 2 THEN '承認依頼中'
	WHEN 3 THEN '承認済'
END APPROVAL_STATUS_NAME

FROM (SELECT CATEGORY_NAME
	, MAX(CATEGORY_DIVISION1) CATEGORY_DIVISION1
	, MAX(DATA_TOTAL_DIVISION1) DATA_TOTAL_DIVISION1
	, MAX(CATEGORY_DIVISION0) CATEGORY_DIVISION0
	, MAX(DATA_TOTAL_DIVISION0) DATA_TOTAL_DIVISION0
	, MAX(CATEGORY_DIVISION2) CATEGORY_DIVISION2
	FROM
		(SELECT CLASS.CATEGORY_NAME
		, DECODE(CLASS.AR_DIVISION, 1, CLASS.CATEGORY_DIVISION, NULL) CATEGORY_DIVISION1
		, DECODE(CLASS.AR_DIVISION, 1, CLASS.DATA_TOTAL_DIVISION, NULL) DATA_TOTAL_DIVISION1
		, DECODE(CLASS.AR_DIVISION, 0, CLASS.CATEGORY_DIVISION, NULL) CATEGORY_DIVISION0
		, DECODE(CLASS.AR_DIVISION, 0, CLASS.DATA_TOTAL_DIVISION, NULL) DATA_TOTAL_DIVISION0
		, DECODE(CLASS.SHOW_FLG ,1 ,CLASS.CATEGORY_DIVISION ,NULL) CATEGORY_DIVISION2
          FROM CLASSIFICATION CLASS
        
        , (SELECT *
        FROM CLASSIFICATION
		WHERE DATA_TYPE = 2 --入金

		/*IF (( condition.categoryDivision != null ) && ( condition.categoryDivision != "" ))*/
		AND CATEGORY_DIVISION = /*condition.categoryDivision*/'1'
		/*END*/
		) CLS
        
        WHERE CLASS.DATA_TYPE = CLS.DATA_TYPE
        AND CLASS.CATEGORY_NAME = CLS.CATEGORY_NAME
        ) CLS
	GROUP BY CATEGORY_NAME
	) CLS

, CLASSIFICATION CLASS
, VENDER VEN
, CREDIT CRE
, ORGANIZATION ORG
, BANK
, BUMON DEBIT_SECTION
, ACCOUNTS DEBIT_TITLE
, BUMON CREDIT_SECTION
, ACCOUNTS CREDIT_TITLE
, LOGIN APPROVOR
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE CRE.DATA_TYPE = /*condition.dataType*/1 --入金
AND VEN.VENDER_DIVISION(+) = 'TS' --得意先
AND CRE.VENDER_CD = VEN.VENDER_CD(+)
AND CLASS.DATA_TYPE(+) = 2 --入金
AND CRE.CATEGORY_DIVISION = CLASS.CATEGORY_DIVISION(+)
AND CRE.ORGANIZATION_CD = ORG.ORGANIZATION_CD(+)
AND CRE.BANK_CD = BANK.BANK_MASTER_CD(+)
AND CRE.DEBIT_SECTION_CD = DEBIT_SECTION.SECTION_CD(+)
AND CRE.DEBIT_TITLE_CD = DEBIT_TITLE.ACCOUNTS_CD(+)
AND CRE.CREDIT_SECTION_CD = CREDIT_SECTION.SECTION_CD(+)
AND CRE.CREDIT_TITLE_CD = CREDIT_TITLE.ACCOUNTS_CD(+)
AND CRE.APPROVEDBY = APPROVOR.TANTO_CD(+)
AND CRE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND CRE.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND (CLASS.CATEGORY_DIVISION = CLS.CATEGORY_DIVISION1
OR CLASS.CATEGORY_DIVISION = CLS.CATEGORY_DIVISION0
OR CLASS.CATEGORY_DIVISION = CLS.CATEGORY_DIVISION2)

/*IF (condition.organizationCd != null && condition.organizationCd != "")*/
AND (CRE.ORGANIZATION_CD LIKE /*condition.organizationCd*/'%' OR ORG.ORGANIZATION_NAME LIKE /*condition.organizationCd*/'%')
/*END*/

/*IF (condition.tantoCd != null && condition.tantoCd != "")*/
AND	(CRE.INPUTOR_CD LIKE /*condition.tantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.tantoCd*/'%')
/*END*/

/*IF (condition.creditDateFrom != null && condition.creditDateFrom != "")*/
AND CRE.CREDIT_DATE >= TO_DATE(/*condition.creditDateFrom*/'2009/06/30','YYYY/MM/DD')
/*END*/

/*IF (condition.creditDateTo != null && condition.creditDateTo != "")*/
AND CRE.CREDIT_DATE <= TO_DATE(/*condition.creditDateTo*/'2009/06/01','YYYY/MM/DD')
/*END*/

/*IF (condition.venderCd != null && condition.venderCd != "")*/
AND (CRE.VENDER_CD LIKE /*condition.venderCd*/'%' OR VEN.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.venderCd*/'%'))
/*END*/

/*IF (condition.creditNoFrom != null && condition.creditNoFrom != "")*/
AND CRE.CREDIT_NO >= /*condition.creditNoFrom*/'%'
/*END*/

/*IF (condition.creditNoTo != null && condition.creditNoTo != "")*/
AND CRE.CREDIT_NO <= /*condition.creditNoTo*/'%'
/*END*/

/*IF (condition.categoryDivision != null && condition.categoryDivision != "")*/
AND CRE.CATEGORY_DIVISION = /*condition.categoryDivision*/'%'
/*END*/

/*IF (condition.approvalStatus != null && condition.approvalStatus != "0")*/
AND CRE.APPROVAL_STATUS = /*condition.approvalStatus*/1
/*END*/

/*IF (condition.issuedDivision != null && condition.issuedDivision != "")*/
AND CRE.ISSUED_DIVISION = /*condition.issuedDivision*/0
/*END*/

ORDER BY CREDIT_DATE, CREDIT_NO, ROW_NO


