/*
 * 支払入力（詳細)支払先取得用SQL
 *
 * entityName=Vender,Payment_Header
 * packageName=payment.payment
 * methodName=getSupplier
 *
 */
SELECT
    VEN.VENDER_CD AS VENDER_CD,
    VEN.VENDER_NAME1 AS VENDER_NAME1,
    VEN.VENDER_SHORTED_NAME AS VENDER_SHORTED_NAME,
    PAY.PAYABLE_AMOUNT AS PAYABLE_AMOUNT
FROM
    PAYMENT_HEADER PAY,
    (SELECT
        PAY2.SUPPLIER_CD AS SUPPLIER_CD,
        MAX(PAY2.PAYABLE_DATE) AS PAYABLE_DATE
    FROM
        PAYMENT_HEADER PAY2,
        VENDER VEN2
    WHERE
		VEN2.VENDER_DIVISION = /*venderDivision*/ AND
		VEN2.VENDER_CD = /*venderCd*/ AND
        ((VEN2.PAYMENT_INVOICE_CD IS NULL) OR (VEN2.PAYMENT_INVOICE_CD = VEN2.VENDER_CD)) AND
        PAY2.SUPPLIER_CD = VEN2.VENDER_CD
    GROUP BY
        SUPPLIER_CD
    ) MPAY,
    VENDER VEN
WHERE
	VEN.VENDER_DIVISION = /*venderDivision*/ AND
	VEN.VENDER_CD = /*venderCd*/ AND
    ((VEN.PAYMENT_INVOICE_CD IS NULL) OR (VEN.PAYMENT_INVOICE_CD = VEN.VENDER_CD)) AND
    MPAY.SUPPLIER_CD(+) = VEN.VENDER_CD AND
    PAY.SUPPLIER_CD(+) = MPAY.SUPPLIER_CD AND
    PAY.PAYABLE_DATE(+) = MPAY.PAYABLE_DATE
ORDER BY
    VENDER_CD
