/*
* 支払額合計検索用SQL
*
* entityName=AltPayment
* packageName=payment
* methodName=getTotalPaymentAmount
*
*/
SELECT NVL(SUM(PAYMENT_AMOUNT), 0) TOTAL_PAYMENT_AMOUNT
FROM   (SELECT SUM(PAYMENT.PAYMENT_AMOUNT) PAYMENT_AMOUNT
		FROM   PAYMENT
		WHERE  PAYMENT.PAYMENT_UPDATE_DIVISION = 1 -- 支払更新済
		AND    PAYMENT.SUPPLIER_CD = /*supplierCd*/'%'
		
		UNION
		
		SELECT SUM(PAYABLE_OFFSET_AMOUNT) PAYABLE_OFFSET_AMOUNT
		FROM   OFFSET_GROUP_DATA
		WHERE  PAYMENT_UPDATE_DIVISION = 1 -- 支払更新済
		AND    VENDER_DIVISION = 'SI' -- 仕入
		AND    VENDER_CD = /*supplierCd*/'%')
