/*
 * 支払入力（詳細)取得用SQL
 *
 * entityName=AltPaymenDao
 * packageName=payment
 * methodName=findBySlipNo
 *
 */
SELECT
	PAYMENT.DATA_TYPE,
	PAYMENT.DATA_TOTAL_DIVISION,
	PAYMENT.CATEGORY_DIVISION,
	PAYMENT.PAYMENT_DATE,
	PAYMENT.SLIP_NO,
	PAYMENT.ROW_NO,
	PAYMENT.SUPPLIER_CD,
	PAYMENT.ORGANIZATION_CD,
	PAYMENT.PAYMENT_AMOUNT,
	PAYMENT.BANK_CD,
	PAYMENT.ACCOUNT_DIVISION,
	PAYMENT.ACCOUNT_NO,
	PAYMENT.NOTE_DIVISION,
	PAYMENT.NOTE_NO,
	PAYMENT.DRAWAL_DATE,
	PAYMENT.NOTE_DATE,
	PAYMENT.DEBIT_SECTION_CD,
	PAYMENT.DEBIT_TITLE_CD,
	PAYMENT.DEBIT_SUB_TITLE_CD,
	PAYMENT.CREDIT_SECTION_CD,
	PAYMENT.CREDIT_TITLE_CD,
	PAYMENT.CREDIT_SUB_TITLE_CD,
	PAYMENT.SUMMARY,
	PAYMENT.DEPOSIT_TARGET_DIVISION,
	PAYMENT.CLAIM_TARGET_DIVISION,
	PAYMENT.PAYABLE_TARGET_DIVISION,
	PAYMENT.PAYMENT_TARGET_DIVISION,
	PAYMENT.ISSUE_DATE,
	PAYMENT.ISSUED_DIVISION,
	PAYMENT.DEPOSIT_UPDATE_DIVISION,
	PAYMENT.DEPOSIT_NO,
	PAYMENT.DELIVERY_UPDATE_DATE,
	PAYMENT.CLAIM_UPDATE_DIVISION,
	PAYMENT.CLAIM_NO,
	PAYMENT.INVOICE_UPDATE_DATE,
	PAYMENT.PAYABLE_UPDATE_DIVISION,
	PAYMENT.PAYABLE_NO,
	PAYMENT.PAYABLE_UPDATE_DATE,
	PAYMENT.PAYMENT_UPDATE_DIVISION,
	PAYMENT.PAYMENT_NO,
	PAYMENT.PAYMENT_UPDATE_DATE,
	PAYMENT.ERASER_COMPLETE_DIVISION,
	PAYMENT.ERASER_COMPLETE_DATE,
	PAYMENT.APPROVAL_STATUS,
	PAYMENT.APPROVEDBY,
	PAYMENT.APPROVALDATE,
	PAYMENT.TRANSMISSION_DATE,
	PAYMENT.INPUT_DATE,
	PAYMENT.INPUTOR_CD,
	PAYMENT.UPDATE_DATE,
	PAYMENT.UPDATOR_CD,	
	PAY.PAYABLE_DATE, -- 支払締日
    PAY.CREDIT_SCHEDULED_DATE,
	PAY.CREDIT_DIVISION AS PAYMENT_DIVISION,				-- 支払分類
	NVL(PAY.NOTE_SIGHT, 0) NOTE_SIGHT, -- 手形サイト
	CLASSIFICATION.CATEGORY_NAME AS PAYMENT_DIVISION_NAME,	-- 支払分類名称
	PAY.CREDIT_SCHEDULED_DATE AS PAYMENT_SCHEDULED_DATE,	-- 支払予定日
	NVL(PAY.BALANCE_FORWARD, 0) AS BALANCE_FORWARD,			-- 差引繰越額
	(NVL(PAY.STOCKING_AMOUNT, 0) + NVL(PAY.OTHER_STOCKING_AMOUNT, 0) + NVL(TAX_AMOUNT, 0))
	- (NVL(PAY.STOCKING_RETURNED_AMOUNT, 0) + NVL(PAY.STOCKING_DISCOUNT_AMOUNT,0))
	AS ACCOUNT_PAYABLE_SUM,									-- 買掛金額合計
	NVL(OFFSET.PAYABLE_OFFSET_AMOUNT, 0) AS OFFSET_AMOUNT,				-- 相殺額
	DECODE(VEN.TRANSFER_COMMISSION_LOAD, 1, NVL(COMPANY.FEE, 0),
										 0) AS COMMISSION,	-- 手数料
	NVL(PAY.STOCK_REDUCTION, 0) PURCHASE_DISCOUNT_AMOUNT -- 仕入割引額
FROM
	PAYMENT PAYMENT,
    PAYMENT_HEADER PAY,
    (SELECT
        PAY2.ORGANIZATION_CD AS ORGANIZATION_CD,
        PAY2.SUPPLIER_CD AS SUPPLIER_CD,
        MAX(PAY2.PAYABLE_DATE) AS PAYABLE_DATE
    FROM
        PAYMENT_HEADER PAY2,
        PAYMENT PAYMENT
    WHERE
		PAYMENT.SLIP_NO = /*slipNo*/'SIH0000208' AND
		PAYMENT.ROW_NO = 1 AND
		PAY2.ORGANIZATION_CD = PAYMENT.ORGANIZATION_CD AND
        PAY2.SUPPLIER_CD = PAYMENT.SUPPLIER_CD AND
        TO_CHAR(PAY2.PAYABLE_DATE, 'YYYYMM') < TO_CHAR(PAYMENT.PAYMENT_DATE, 'YYYYMM')
    GROUP BY
        PAY2.ORGANIZATION_CD, PAY2.SUPPLIER_CD
    ) MPAY,
    VENDER VEN,
	(SELECT
		COMPANY.PRIME,
		BANK.FEE
	FROM 
		BANK, 
		(SELECT
			BANK_MASTER_CD, PRIME
		FROM COMPANY
		WHERE ROWNUM = 1
		ORDER BY COMPANY_CD
		) COMPANY
	WHERE COMPANY.BANK_MASTER_CD = BANK.BANK_MASTER_CD(+)
	) COMPANY,
	(SELECT
		CATEGORY_DIVISION,
		MIN(CATEGORY_NAME) CATEGORY_NAME
	FROM
		CLASSIFICATION
	WHERE DATA_TYPE = 4
	GROUP BY CATEGORY_DIVISION
	) CLASSIFICATION,
	OFFSET_GROUP_DATA OFFSET
WHERE
	PAYMENT.SLIP_NO = /*slipNo*/'SIH0000208' AND
    MPAY.SUPPLIER_CD(+) = PAYMENT.SUPPLIER_CD AND
    MPAY.ORGANIZATION_CD(+) = PAYMENT.ORGANIZATION_CD AND
    PAY.ORGANIZATION_CD(+) = MPAY.ORGANIZATION_CD AND
    PAY.SUPPLIER_CD(+) = MPAY.SUPPLIER_CD AND
    PAY.PAYABLE_DATE(+) = MPAY.PAYABLE_DATE AND
	CLASSIFICATION.CATEGORY_DIVISION(+) = PAY.CREDIT_DIVISION AND
	VEN.VENDER_DIVISION(+) = 'SI' AND
	VEN.VENDER_CD(+) = PAYMENT.SUPPLIER_CD AND
	MPAY.PAYABLE_DATE = OFFSET.OFFSET_DATE(+) AND 
	OFFSET.VENDER_DIVISION(+) = 'SI' AND
	MPAY.SUPPLIER_CD = OFFSET.VENDER_CD(+)
ORDER BY
    PAYMENT.ROW_NO
