/*
* 支払入力(支払予定一覧)検索用SQL
*
* entityName=AltPayment
* packageName=payment
* methodName=getPaymentHeaderList
*
*/
SELECT *
FROM   (SELECT HEADER.SUPPLIER_CD
			  ,HEADER.ORGANIZATION_CD
			  ,HEADER.PAYABLE_DATE
			  ,HEADER.CREDIT_SCHEDULED_DATE
			  ,HEADER.CREDIT_DIVISION
			  ,CLASSIFICATION.CATEGORY_NAME
			  ,NVL(HEADER.BALANCE_FORWARD, 0) BALANCE_FORWARD
			  ,NVL(HEADER.STOCKING_AMOUNT, 0) STOCKING_AMOUNT
			  ,NVL(HEADER.OTHER_STOCKING_AMOUNT, 0) OTHER_STOCKING_AMOUNT
			  ,NVL(HEADER.TAX_AMOUNT, 0) TAX_AMOUNT
			  ,NVL(HEADER.STOCKING_RETURNED_AMOUNT, 0) STOCKING_RETURNED_AMOUNT
			  ,NVL(HEADER.STOCKING_DISCOUNT_AMOUNT, 0) STOCKING_DISCOUNT_AMOUNT
			  ,NVL(HEADER.PAYABLE_AMOUNT, 0) PAYABLE_AMOUNT
			  ,NVL(OFFSET.PAYABLE_OFFSET_AMOUNT, 0) +
			   NVL(OFFSET2.PAYABLE_OFFSET_AMOUNT, 0) OFFSET_AMOUNT
			  ,NVL(HEADER.STOCKING_AMOUNT, 0) +
			   NVL(HEADER.OTHER_STOCKING_AMOUNT, 0) +
			   NVL(HEADER.TAX_AMOUNT, 0) -
			   NVL(HEADER.STOCKING_RETURNED_AMOUNT, 0) +
			   NVL(HEADER.STOCKING_DISCOUNT_AMOUNT, 0) ACCOUNT_PAYABLE_SUM
			  ,HEADER.TRANSFER_FEE COMMISSION
			   
			  ,(SELECT SUM(NVL(PAYABLE_AMOUNT, 0))
				FROM   PAYMENT_HEADER
				WHERE  SUPPLIER_CD = HEADER.SUPPLIER_CD
				AND    CREDIT_SCHEDULED_DATE <= HEADER.CREDIT_SCHEDULED_DATE) TOTAL_PAYABLE_AMOUNT
		FROM   (SELECT PAYMENT_NO
				FROM   PAYMENT_HEADER HEADER
				WHERE  HEADER.SUPPLIER_CD = /*supplierCd*/'%') PAYMENT2
			  ,PAYMENT_HEADER HEADER
			  ,OFFSET_GROUP_DATA OFFSET
			  ,(SELECT *
				FROM   OFFSET_GROUP_DATA OFFSET
				WHERE  VENDER_DIVISION = 'SI') OFFSET2
			  ,CLASSIFICATION
		WHERE  PAYMENT2.PAYMENT_NO = HEADER.PAYMENT_NO
		AND    OFFSET.VENDER_DIVISION(+) = 'SI' -- 仕入
		AND    HEADER.SUPPLIER_CD = OFFSET.VENDER_CD(+)
		AND    CLASSIFICATION.DATA_TYPE(+) = 4 -- 支払
		AND    HEADER.CREDIT_SCHEDULED_DATE = OFFSET.OFFSET_DATE(+)
		AND    HEADER.CREDIT_SCHEDULED_DATE > OFFSET2.OFFSET_DATE(+)
		AND    HEADER.SUPPLIER_CD = OFFSET2.VENDER_CD(+)
		AND    HEADER.PAYABLE_AMOUNT = OFFSET2.PAYABLE_OFFSET_AMOUNT(+)
		AND    HEADER.CREDIT_DIVISION = CLASSIFICATION.CATEGORY_DIVISION(+))
WHERE  TOTAL_PAYABLE_AMOUNT > /*payableAmount*/0
AND    PAYABLE_AMOUNT <> 0
ORDER  BY CREDIT_SCHEDULED_DATE
		 ,PAYABLE_AMOUNT DESC
