/*
 * 運送会社帳票用SQL
 *
 * entityName=CarryFileListForReport
 * packageName=carryfilelistforreport
 * methodName=getListForReport
 *
 */
SELECT 
  CARRY_FILE_LAYOUT.CARRY_CD
, CARRY.CARRY_NAME1 ||  CARRY.CARRY_NAME2 AS CARRY_NAME
, CARRY_FILE_LAYOUT.SEQ
, CARRY_FILE_LAYOUT.HEADER_FLG
, CARRY_FILE_LAYOUT.DATA_CLS
, CARRY_FILE_LAYOUT.TABLE_NAME
, USER_TAB_COMMENTS.COMMENTS AS TABLE_COMMENTS
, CARRY_FILE_LAYOUT.COLUMN_NAME
, USER_COL_COMMENTS.COMMENTS AS COL_COMMENTS
, CARRY_FILE_LAYOUT.HEADER_NAME
, CARRY_FILE_LAYOUT.LINK_FLG
, CARRY_FILE_LAYOUT.DESCRIPTION
, CARRY_FILE_LAYOUT.INPUTOR_CD
, CARRY_FILE_LAYOUT.UPDATOR_CD
, CARRY_FILE_LAYOUT.INPUT_DATE
, CARRY_FILE_LAYOUT.UPDATE_DATE
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME
FROM 
    CARRY_FILE_LAYOUT
INNER JOIN
    CARRY
ON
    CARRY.CARRY_CD = CARRY_FILE_LAYOUT.CARRY_CD
LEFT JOIN
    USER_TAB_COMMENTS
ON
    USER_TAB_COMMENTS.TABLE_NAME = CARRY_FILE_LAYOUT.TABLE_NAME
    AND USER_TAB_COMMENTS.TABLE_NAME = CARRY_FILE_LAYOUT.TABLE_NAME
LEFT JOIN
    USER_COL_COMMENTS
ON
    USER_COL_COMMENTS.TABLE_NAME = CARRY_FILE_LAYOUT.TABLE_NAME
    AND USER_COL_COMMENTS.COLUMN_NAME = CARRY_FILE_LAYOUT.COLUMN_NAME
LEFT JOIN
    LOGIN INPUTOR
ON
    INPUTOR.TANTO_CD = CARRY_FILE_LAYOUT.INPUTOR_CD
LEFT JOIN
    LOGIN UPDATOR
ON
    UPDATOR.TANTO_CD = CARRY_FILE_LAYOUT.UPDATOR_CD
WHERE CARRY.CARRY_CD IS NOT NULL
/*IF (condition.srhCarryCd != null) && (condition.srhCarryCd != "")*/
AND (CARRY.CARRY_CD LIKE /*condition.srhCarryCd*/'%' OR CARRY.CARRY_NAME1 LIKE /*condition.srhCarryCd*/'%')
/*END*/
    ORDER BY 
CARRY_FILE_LAYOUT.CARRY_CD , CARRY_FILE_LAYOUT.SEQ