/*
 * 販売条件詳細用SQL
 *
 * entityName=SalesTermsDetailList
 * packageName=salestermsdetaillist
 * methodName=getList
 *
 */

SELECT SEQ, SALES_TERMS.DELIVERY_CD, DELIVERY.SEARCH_KANA AS DELIVERY_NAME1, SALES_TERMS.BALANCE_CD
, BALANCE.BALANCE_TYPE
,DELIVERY.LEAD_TIME
,DELIVERY.DELIVERY_TIME
,CARRY.CARRY_NAME1 || CARRY.CARRY_NAME2 AS CARRY_NAME
,CASE BALANCE.BALANCE_TYPE
	WHEN 1 THEN '油脂'
	WHEN 2 THEN '化成品'
	ELSE NULL
END BALANCE_TYPE_NAME,
BALANCE.VENDER_CD, VENDER.VENDER_SHORTED_NAME AS VENDER_NAME1, SALES_TERMS.ITEM_CD, ITEM_QUEUE.VERSION, ITEM_QUEUE.OTHER_COMPANY_CD1, ITEM_QUEUE.ITEM_NAME, ITEM_QUEUE.STYLE_OF_PACKING, DELIVERY.TANTO_CD, LOGIN.TANTO_NM, SALES_TERMS.UPDATE_DATE
FROM SALES_TERMS, BALANCE, VENDER, VALID_ITEM_QUEUE ITEM_QUEUE, DELIVERY, LOGIN,CARRY

WHERE SALES_TERMS.DELIVERY_CD = /*deliveryCd*/'%'
AND SALES_TERMS.BALANCE_CD = /*balanceCd*/'%'
AND SALES_TERMS.BALANCE_CD = BALANCE.BALANCE_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)
AND SALES_TERMS.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND SALES_TERMS.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
AND DELIVERY.TANTO_CD = LOGIN.TANTO_CD(+)
AND DELIVERY.CARRY_CD = CARRY.CARRY_CD(+)
ORDER BY ITEM_CD
