/**
 *
 * @author t1344224
 *
 * entityName=SlipSalesListForReport
 * packageName=slipsalesforreport
 * methodName=getSearchList
 *
 */
SELECT
	SALES.SALES_DATE
,	SALES.SALES_NO
,	SALES.CANCEL_SALES_NO
,	SALES.ITEM_CD
,	ITEM.ITEM_NAME
,	ITEM.STYLE_OF_PACKING
,	ITEM.OTHER_COMPANY_CD1
,	SALES.ORGANIZATION_CD
,	ORGANIZATION.ORGANIZATION_NAME
,	SALES.VENDER_CD
,	VENDER.VENDER_SHORTED_NAME AS VENDER_NAME1
,	SALES.BALANCE_CD
,	SALES.INPUT_TANTO_CD
,	INPUT_LOGIN.TANTO_NM AS INPUT_TANTO_NAME
,	SALES.SALES_TANTO_CD
,	SALES_LOGIN.TANTO_NM AS SALES_TANTO_NAME
,	SALES.PRODUCT_LOTNO
,	SALES.ORDER_NO
,	SALES.ORDER_ROW_NO
,	SALES.SALES_QUANTITY
,	SALES.SALES_UNITPRICE
,	SALES.STANDARD_UNITPRICE
,	SALES.STANDARD_DISCOUNT
,	SALES.SPECIAL_DISCOUNT
,	SALES.TMP_UNITPRICE_FLG
,	SALES.REMARK
,	SALES.DISBURSEMENT_LOCATION_CD
,	DISBURSEMENT_LOCATION.LOCATION_NAME
,	SALES.DELIVERY_COMP
,	SALES.DELIVERY_UPDATE_DATE
,	SALES.INVOICE_UPDATE_DATE
,	SALES.INPUT_DIVISION
,	SALES.DELIVERY_CD
,	DELIVERY.SEARCH_KANA AS DELIVERY_NAME1
,	SALES.TAX_DIVISION
,	SALES.TAX_AMOUNT
,	SALES.TAX_CD
,	SALES.INVOICE_CD
,	INVOICE_VENDER.VENDER_NAME1 AS INVOICE_NAME
,	SALES.SALES_AMOUNT
,	SALES.SALES_BASIC
,	SALES.TAX_RATIO
,	SALES.UPDATE_FLG
,	SALES.CONFIG_EXP_RATIO
,	SALES.RATIO_NOTAPPLY_SALES_UNITPRICE
,	SALES.SHIPPING_NO
,	SALES.SALES_SLIP_NO
,	SALES.SALES_SLIP_ROW_NO
,	SALES.SLIP_PUBLISH_COMP
,	SALES.SLIP_PUBLISH_DATE
,	SALES.TRANSMISSION_DATE
,	SALES.LEDGER_POST_DATE
,	SALES.LEDGER_POST_NO
,	SALES.SALES_CONVERT_QUANTITY
,	SALES.ACCEPT_CONVERT_QUANTITY
,	SALES.DATA_TYPE
,	SALES.DATA_TOTAL_DIVISION
,	SALES.CATEGORY_DIVISION
,	SALES.ACCOUNT_YEARS
,	SALES.ACCOUNT_DEBIT_SECTION_CD
,	ACCOUNT_DEBIT_SECTION.SECTION_NAME AS ACCOUNT_DEBIT_SECTION_NAM
,	SALES.ACCOUNT_CREDIT_SECTION_CD
,	ACCOUNT_CREDIT_SECTION.SECTION_NAME AS ACCOUNT_CREDIT_SECTION_NAME
,	SALES.DEBIT_TITLE_CD
,	DEBIT_TITLE_CD.ACCOUNTS_NAME AS DEBIT_TITLE_NAME
,	SALES.DEBIT_SUB_TITLE_CD
,	DEBIT_SUB_TITLE_CD.ACCOUNTS_NAME AS DEBIT_SUB_TITLE_NAME
,	SALES.CREDIT_TITLE_CD
,	CREDIT_TITLE_CD.ACCOUNTS_NAME AS CREDIT_TITLE_NAME
,	SALES.CREDIT_SUB_TITLE_CD
,	CREDIT_SUB_TITLE_CD.ACCOUNTS_NAME AS CREDIT_SUB_TITLE_NAME
,	SALES.DEPOSIT_TARGET_DIVISION
,	SALES.CLAIM_TARGET_DIVISION
,	SALES.SUMMARY_CD
,	SALES.SUMMARY
,	SALES.DEPOSIT_UPDATE_DIVISION
,	SALES.DEPOSIT_NO
,	SALES.CLAIM_UPDATE_DIVISION
,	SALES.CLAIM_NO
,	SALES.ERASER_COMPLETE_DIVISION
,	SALES.ERASER_COMPLETE_DATE
,	SALES.APPROVAL_STATUS
,	SALES.APPROVEDBY
,	SALES.APPROVALDATE
,	SALES.CHARGE_ORGANIZATION_CD
,	CHARGE_ORGANIZATION.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME
,	SALES.KEEP_FLAG
,	SALES.RY_CD
,	REASON.RY_DESCRIPTION
,	SALES.HOUSING_LOCATION_CD
,	HOUSING_LOCATION.LOCATION_NAME AS HOUSING_LOCATION_NAME
,	SALES.PACKAGE_DIRECTION_NO
,	VENDER.SALES_MAIL_OUTPUT
,	VENDER.SALES_FAX_OUTPUT
,	SALES.INPUT_DATE
,	SALES.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	SALES.UPDATE_DATE
,	SALES.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
,	SHIPPING_DETAIL_LOCATION.UPPER_LOCATION_CD as LOCATION_CD
FROM
	SALES
,	VALID_ITEM_QUEUE
,	VALID_ITEM_QUEUE ITEM
,	VENDER
,	DELIVERY
,	(SELECT
		CATEGORY_DIVISION
	,	MIN(DATA_TOTAL_DIVISION) AS DATA_TOTAL_DIVISION
	FROM	CLASSIFICATION
	WHERE	DATA_TYPE = '1'
	GROUP BY
		CATEGORY_DIVISION
	)CLASSIFICATION_MIN
,	CLASSIFICATION
,	(SELECT
		SHIPPING_DETAIL.SHIPPING_NO
	,	MAX(UPPER_LOCATION.UPPER_LOCATION_CD) as UPPER_LOCATION_CD
	FROM
		SHIPPING_DETAIL
	,	(SELECT
			LOCA1.LOCATION_CD
		,	NVL(LOCA2.UPPER_LOCATION_CD,LOCA2.LOCATION_CD) as UPPER_LOCATION_CD
		FROM
			LOCATION LOCA1
		,	LOCATION LOCA2
		WHERE
			NVL(LOCA1.UPPER_LOCATION_CD,LOCA1.LOCATION_CD) = LOCA2.LOCATION_CD(+)
		AND	(LOCA1.LOCATION_LEVEL = '1' OR LOCA1.LOCATION_LEVEL = '4')
		AND	LOCA1.LOCATION_CD <> 'K'
		)UPPER_LOCATION
	
	WHERE
		SHIPPING_DETAIL.LOCATION_CD = UPPER_LOCATION.LOCATION_CD
	
	GROUP BY
		SHIPPING_DETAIL.SHIPPING_NO
	)SHIPPING_DETAIL_LOCATION
,	SHIPPING
,	ORDER_HEAD
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,	LOCATION HOUSING_LOCATION
,	REASON
,	ORGANIZATION
,	ORGANIZATION CHARGE_ORGANIZATION
,	BUMON ACCOUNT_DEBIT_SECTION
,	BUMON ACCOUNT_CREDIT_SECTION
,	ACCOUNTS DEBIT_TITLE_CD
,	ACCOUNTS DEBIT_SUB_TITLE_CD
,	ACCOUNTS CREDIT_TITLE_CD
,	ACCOUNTS CREDIT_SUB_TITLE_CD
,	VENDER INVOICE_VENDER
,	LOCATION DISBURSEMENT_LOCATION
,	LOGIN INPUT_LOGIN
,	LOGIN SALES_LOGIN
,	SALES_EXTENDED

WHERE
	VALID_ITEM_QUEUE.ITEM_CD(+) = SALES.ITEM_CD
AND	ITEM.ITEM_CD(+) = VALID_ITEM_QUEUE.ITEM_CD
AND	ITEM.VERSION(+) = VALID_ITEM_QUEUE.VERSION

AND	VENDER.VENDER_DIVISION(+) = 'TS'
AND	VENDER.VENDER_CD(+) = SALES.VENDER_CD

AND	DELIVERY.DELIVERY_CD(+) = SALES.DELIVERY_CD

AND	CLASSIFICATION_MIN.CATEGORY_DIVISION(+) = SALES.CATEGORY_DIVISION
AND	CLASSIFICATION.DATA_TYPE(+) = '1'
AND	CLASSIFICATION.CATEGORY_DIVISION(+)   = CLASSIFICATION_MIN.CATEGORY_DIVISION
AND	CLASSIFICATION.DATA_TOTAL_DIVISION(+) = CLASSIFICATION_MIN.DATA_TOTAL_DIVISION

AND	SALES.SHIPPING_NO = SHIPPING_DETAIL_LOCATION.SHIPPING_NO(+)

AND	SALES.SHIPPING_NO = SHIPPING.SHIPPING_NO(+)

AND	SALES.ORDER_NO = ORDER_HEAD.ORDER_NO(+)
AND 	SALES.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	SALES.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND 	SALES.HOUSING_LOCATION_CD = HOUSING_LOCATION.LOCATION_CD(+)
AND 	SALES.RY_CD = REASON.RY_CD(+)
AND 	SALES.CHARGE_ORGANIZATION_CD = CHARGE_ORGANIZATION.ORGANIZATION_CD(+)
AND 	SALES.ACCOUNT_DEBIT_SECTION_CD = ACCOUNT_DEBIT_SECTION.SECTION_CD(+)
AND 	SALES.ACCOUNT_CREDIT_SECTION_CD = ACCOUNT_CREDIT_SECTION.SECTION_CD(+)
AND 	SALES.DEBIT_TITLE_CD = DEBIT_TITLE_CD.ACCOUNTS_CD(+)
AND 	SALES.DEBIT_SUB_TITLE_CD = DEBIT_SUB_TITLE_CD.ACCOUNTS_CD(+)
AND 	SALES.CREDIT_TITLE_CD = CREDIT_TITLE_CD.ACCOUNTS_CD(+)
AND 	SALES.CREDIT_SUB_TITLE_CD = CREDIT_SUB_TITLE_CD.ACCOUNTS_CD(+)
AND 	SALES.INVOICE_CD = INVOICE_VENDER.VENDER_CD(+) AND INVOICE_VENDER.VENDER_DIVISION(+) = 'TS'
AND 	SALES.DISBURSEMENT_LOCATION_CD = DISBURSEMENT_LOCATION.LOCATION_CD(+)
AND 	SALES.INPUT_TANTO_CD = INPUT_LOGIN.TANTO_CD(+)
AND 	SALES.SALES_TANTO_CD = SALES_LOGIN.TANTO_CD(+)
AND 	SALES.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND	SALES.SALES_NO = SALES_EXTENDED.SALES_NO(+)

/*IF (( condition.srhSalesNo != null ) && ( condition.srhSalesNo != "" ))*/
	AND	SALES.SALES_NO LIKE /*condition.srhSalesNo*/'%'
/*END*/

/*IF (( condition.srhCategoryDivision != null ) && ( condition.srhCategoryDivision != "" ))*/
	/*IF (condition.srhCategoryDivision == "0")*/
		/*IF (condition.srhCancelFlg)*/
			AND	SALES.CATEGORY_DIVISION < 0 
		/*END*/
		/*IF (!condition.srhCancelFlg)*/
			AND	SALES.CATEGORY_DIVISION <> 0 
		/*END*/
	/*END*/
	/*IF (condition.srhCategoryDivision != "0")*/
		/*IF (condition.srhCancelFlg)*/
			/*IF (condition.srhCategoryDivision == "1")*/
				AND	(SALES.CATEGORY_DIVISION = -1 OR SALES.CATEGORY_DIVISION = -11)
			/*END*/
			/*IF (condition.srhCategoryDivision == "2")*/
				AND	(SALES.CATEGORY_DIVISION = -2 OR SALES.CATEGORY_DIVISION = -12)
			/*END*/
			/*IF (condition.srhCategoryDivision == "3")*/
				AND	(SALES.CATEGORY_DIVISION = -3 OR SALES.CATEGORY_DIVISION = -13)
			/*END*/
			/*IF (condition.srhCategoryDivision == "4")*/
				AND	(SALES.CATEGORY_DIVISION = -4 OR SALES.CATEGORY_DIVISION = -14)
			/*END*/
			/*IF (condition.srhCategoryDivision == "9")*/
				AND	(SALES.CATEGORY_DIVISION = -9 OR SALES.CATEGORY_DIVISION = -19)
			/*END*/
		/*END*/
		/*IF (!condition.srhCancelFlg)*/
			/*IF (condition.srhCategoryDivision == "1")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 1 OR ABS(SALES.CATEGORY_DIVISION) = 11)
			/*END*/
			/*IF (condition.srhCategoryDivision == "2")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 2 OR ABS(SALES.CATEGORY_DIVISION) = 12)
			/*END*/
			/*IF (condition.srhCategoryDivision == "3")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 3 OR ABS(SALES.CATEGORY_DIVISION) = 13)
			/*END*/
			/*IF (condition.srhCategoryDivision == "4")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 4 OR ABS(SALES.CATEGORY_DIVISION) = 14)
			/*END*/
			/*IF (condition.srhCategoryDivision == "9")*/
				AND	(ABS(SALES.CATEGORY_DIVISION) = 9 OR ABS(SALES.CATEGORY_DIVISION) = 19)
			/*END*/
		/*END*/
	/*END*/
/*END*/

/*IF (( condition.srhOrderNoFrom != null ) && ( condition.srhOrderNoFrom != "" ))*/
	AND	SALES.ORDER_NO >= /*condition.srhOrderNoFrom*/'%'
/*END*/

/*IF (( condition.srhOrderNoTo != null ) && ( condition.srhOrderNoTo != "" ))*/
	AND	SALES.ORDER_NO <= /*condition.srhOrderNoTo*/'%'
/*END*/

/*IF (( condition.srhSalesDateFrom != null ) && ( condition.srhSalesDateFrom != "" ))*/
	AND	SALES.SALES_DATE >= /*condition.srhSalesDateFrom*/'%'
/*END*/

/*IF (( condition.srhSalesDateTo != null ) && ( condition.srhSalesDateTo != "" ))*/
	AND	SALES.SALES_DATE <= /*condition.srhSalesDateTo*/'%'
/*END*/

/*IF (( condition.srhAccountYears != null ) && ( condition.srhAccountYears != "" ))*/
	AND	SALES.ACCOUNT_YEARS = /*condition.srhAccountYears*/'%'
/*END*/

/*IF (condition.srhTmpUnitpriceFlg)*/
	AND	SALES.TMP_UNITPRICE_FLG = 1
/*END*/

/*IF (condition.srhKeepFlag)*/
	AND	SALES.KEEP_FLAG = 2
/*END*/

/*IF (condition.srhMonthlyUpdateFlag)*/
	AND	(SALES.DEPOSIT_UPDATE_DIVISION = 1 OR SALES.CLAIM_UPDATE_DIVISION = 1)
/*END*/

/*IF (( condition.srhVenderCd != null ) && ( condition.srhVenderCd != "" ))*/
	AND	SALES.VENDER_CD LIKE /*condition.srhVenderCd*/'%'
/*END*/

/*IF (( condition.srhChargeOrganizationCd != null ) && ( condition.srhChargeOrganizationCd != "" ))*/
	AND	SALES.CHARGE_ORGANIZATION_CD LIKE /*condition.srhChargeOrganizationCd*/'%'
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	SALES.ITEM_CD LIKE /*condition.srhItemCd*/'%'
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
    AND SALES.ITEM_CD IN (SELECT ITEM_CD
                          FROM   VALID_ITEM_QUEUE
                          WHERE  OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%')
/*END*/



/*IF (( condition.srhSalesSlipNo != null ) && ( condition.srhSalesSlipNo != "" ))*/
	AND	SALES.SALES_SLIP_NO LIKE /*condition.srhSalesSlipNo*/'%'
/*END*/

/*IF (( condition.srhScheduledShippingDate != null ) && ( condition.srhScheduledShippingDate != "" ))*/
	AND	SHIPPING.SCHEDULED_SHIPPING_DATE = /*condition.srhScheduledShippingDate*/'%'
/*END*/

/*IF (( condition.srhDeliveryExpectedDate != null ) && ( condition.srhDeliveryExpectedDate != "" ))*/
	AND	ORDER_HEAD.DELIVERY_EXPECTED_DATE = /*condition.srhDeliveryExpectedDate*/'%'
/*END*/

/*IF (( condition.srhLocationCd != null ) && ( condition.srhLocationCd != "" ))*/
	AND	SHIPPING_DETAIL_LOCATION.UPPER_LOCATION_CD = /*condition.srhLocationCd*/'%'
/*END*/

/*IF (( condition.srhDeliveryCd != null ) && ( condition.srhDeliveryCd != "" ))*/
	AND	SALES.DELIVERY_CD LIKE /*condition.srhDeliveryCd*/'%'
/*END*/

/*IF (( condition.srhCarryCd != null ) && ( condition.srhCarryCd != "" ))*/
	/*IF (condition.srhCarryCd == "0")*/

	/*END*/
	/*IF (condition.srhCarryCd != "0")*/
		AND	SHIPPING.CARRY_CD = /*condition.srhCarryCd*/'%'
	/*END*/
/*END*/

/*IF (( condition.srhCustomerOrderNo != null ) && ( condition.srhCustomerOrderNo != "" ))*/
	AND	ORDER_HEAD.CUSTOMER_ORDER_NO LIKE /*condition.srhCustomerOrderNo*/'%'
/*END*/
/*IF (( condition.srhSlipPublishComp != null ) && ( condition.srhSlipPublishComp != "" ))*/
	/*IF (condition.srhSlipPublishComp == "1")*/
		AND	SALES.SLIP_PUBLISH_COMP = 0
	/*END*/
/*END*/

/*IF (( condition.srhSlipDateFrom != null ) && ( condition.srhSlipDateFrom != "" ))*/
	AND	TO_CHAR(SALES.SLIP_PUBLISH_DATE,'YYYY/MM/DD') >= /*condition.srhSlipDateFrom*/
/*END*/

/*IF (( condition.srhSlipDateTo != null ) && ( condition.srhSlipDateTo != "" ))*/
	AND	TO_CHAR(SALES.SLIP_PUBLISH_DATE,'YYYY/MM/DD') <= /*condition.srhSlipDateTo*/
/*END*/

/*IF (( condition.srhSlipSendComp != null ) && ( condition.srhSlipSendComp != "" ))*/
	/*IF (condition.srhSlipSendComp == "1")*/
		AND	(SALES_EXTENDED.SLIP_SEND_COMP = 0 OR SALES_EXTENDED.SLIP_SEND_COMP IS NULL)
	/*END*/
/*END*/
/*IF (condition.srhFaxOutput != 0)*/
AND 	VENDER.FAX_OUTPUT = /*condition.srhFaxOutput*/3
/*END*/
/*IF (condition.srhFaxOutput != 0)*/
AND 	VENDER.FAX_OUTPUT = /*condition.srhFaxOutput*/
/*END*/

/*IF (condition.srhSalesMailOutput != 0)*/
AND 	VENDER.SALES_MAIL_OUTPUT = /*condition.srhSalesMailOutput*/
/*END*/

/*IF (condition.srhSalesFaxOutput != 0)*/
AND 	VENDER.SALES_FAX_OUTPUT = /*condition.srhSalesFaxOutput*/
/*END*/

ORDER BY
	SALES.SALES_NO

