/*
 * 開発依頼SQL��
 * 完成品目リスト検索
 * entityName=DevelopItemList
 * packageName=develop
 * methodName=getItemList
 */
SELECT	ITEM_QUEUE.ITEM_CD
,		ITEM_QUEUE.ITEM_NAME
,		MAX(ITEM_QUEUE.VERSION) VERSION
,		DEV.STATUS STATUS
FROM	DEVELOPMENT_REQUEST DEV , ITEM_QUEUE
WHERE		DEV.DEVELOPMENT_REQUEST_NO = /*developmentRequestNo*/'0000000001'
AND			DEV.DEVELOPMENT_REQUEST_NO = ITEM_QUEUE.DEVELOPMENT_REQUEST_NO
GROUP BY	ITEM_QUEUE.ITEM_CD , ITEM_QUEUE.ITEM_NAME , DEV.STATUS
