/*
 * 開発依頼完成品目リストSQL文??
 *
 * entityName=DevelopList
 * packageName=develop
 * methodName=getItemList
 */
SELECT	ITEM_QUEUE.ITEM_CD
,		ITEM_QUEUE.ITEM_NAME
FROM	DEVELOPMENT_REQUEST DEV
LEFT JOIN ITEM_QUEUE
ON	DEV.DEVELOPMENT_REQUEST_NO = ITEM_QUEUE.DEVELOPMENT_REQUEST_NO

WHERE	DEV.DEVELOPMENT_REQUEST_NO = /*developmentRequestNo*/'DV00000001'
AND	ITEM_QUEUE.VERSION = (SELECT MAX(ITEM_QUEUE.VERSION) FROM ITEM_QUEUE WHERE DEV.DEVELOPMENT_REQUEST_NO = ITEM_QUEUE.DEVELOPMENT_REQUEST_NO)
