/*
 * 開発依頼全部のカラム読むSQL文��
 *
 * entityName=DevelopDto
 * packageName=develop
 * methodName=getDevelopmentRequest
 */
SELECT	DEV.DEVELOPMENT_REQUEST_NO
,		DEV.STATUS
,		CASE 
			WHEN DEV.STATUS = 1 THEN '登録済'
			WHEN DEV.STATUS = 2 THEN '開発依頼承認依頼中'
			WHEN DEV.STATUS = 3 THEN '開発依頼承認済'
			WHEN DEV.STATUS = 4 THEN '受付済(開発中)'
			WHEN DEV.STATUS = 5 THEN '責任者承認依頼中'
			WHEN DEV.STATUS = 6 THEN '責任者承認済'
			WHEN DEV.STATUS = 7 THEN '研究開発承認済(開発完了)'
			WHEN DEV.STATUS = 8 THEN '研究開発中止'
			WHEN DEV.STATUS = 50 THEN '開発依頼否認'
			WHEN DEV.STATUS = 51 THEN '研究開発否認'
			ELSE '新規登録'
		END STATUS_NAME
,		DEV.TANTO_DIVISION
,       DEV.HOPE_FINISHED_DATE
,       DEV.VENDER_CD
,       DEV.REQUEST_TANTO_CD
,       DEV.REQUEST_DATE
,       DEV.DEVELOP_ACCEPT_TANTO_CD
,       DEV.DEVELOP_ACCEPT_DATE
,       DEV.REQ_APP_TANTO_CD
,       DEV.REQ_APP_DATE
,       DEV.DEVELOP_APP_TANTO_CD
,       DEV.DEVELOP_APP_DATE
,		DEV.DEVELOPMENT_DIVISION
,       DEV.APPLICATION
,       DEV.PROPERTY
,       DEV.HOPE_COST_FROM
,       DEV.HOPE_COST_TO
,       DEV.SOLVENT_INFORMATION
,       DEV.ALLERGY_INFORMATION
,       DEV.DEVELOPMENT_DETAIL
,       DEV.DEVELOPMENT_PLAN
,       DEV.DEVELOPMENT_PLAN_DATE
,       DEV.VERIFICATION_RESULT
,       DEV.VERIFICATION_RESULT_DATE
,       DEV.REVUE_RESULT
,       DEV.REVUE_RESULT_DATE
,		DEV.FINISHED_DATE
,		DEV.COST
,		DEV.INPUT_DATE
,		DEV.INPUTOR_CD
,		DEV.UPDATE_DATE
,		DEV.UPDATOR_CD
FROM	DEVELOPMENT_REQUEST DEV
WHERE	DEV.DEVELOPMENT_REQUEST_NO = /*developmentRequestNo*/'UVZO37V8O3'
