/*
 * 開発依頼ヘッダー情報SQL文��
 *
 * entityName=DevelopDto
 * packageName=develop
 * methodName=getDevelopHeader
 */
SELECT	DEV.DEVELOPMENT_REQUEST_NO
,		DEV.STATUS
,		CASE 
			WHEN DEV.STATUS = 1 THEN '登録済'
			WHEN DEV.STATUS = 2 THEN '開発依頼承認依頼中'
			WHEN DEV.STATUS = 3 THEN '開発依頼承認済'
			WHEN DEV.STATUS = 4 THEN '受付済(開発中)'
			WHEN DEV.STATUS = 5 THEN '責任者承認依頼中'
			WHEN DEV.STATUS = 6 THEN '責任者承認済'
			WHEN DEV.STATUS = 7 THEN '研究開発承認済(開発完了)'
			WHEN DEV.STATUS = 8 THEN '研究開発中止'
			WHEN DEV.STATUS = 50 THEN '開発依頼否認'
			WHEN DEV.STATUS = 51 THEN '研究開発否認'
			ELSE '新規登録'
		END STATUS_NAME
,		DEV.TANTO_DIVISION
,       DEV.HOPE_FINISHED_DATE
,       DEV.VENDER_CD
,		VENDER.VENDER_NAME
,       DEV.REQUEST_TANTO_CD
,       LOGIN.TANTO_NM REQUEST_TANTO_NAME
,       DEV.REQUEST_DATE
,       DEV.DEVELOP_ACCEPT_TANTO_CD
,		LOGIN2.TANTO_NM DEVELOP_ACCEPT_TANTO_NAME
,       DEV.DEVELOP_ACCEPT_DATE
,       DEV.REQ_APP_TANTO_CD
,       LOGIN3.TANTO_NM REQ_APP_TANTO_NAME
,       DEV.REQ_APP_DATE
,       DEV.DEVELOP_APP_TANTO_CD
,       LOGIN4.TANTO_NM DEVELOP_APP_TANTO_NAME
,       DEV.DEVELOP_APP_DATE
FROM	LOGIN LOGIN
,       LOGIN LOGIN2
,       LOGIN LOGIN3
,       LOGIN LOGIN4
,		DEVELOPMENT_REQUEST DEV
,		VENDER VENDER
WHERE	DEV.DEVELOPMENT_REQUEST_NO = /*developmentRequestNo*/'UVZO37V8O3'
AND		DEV.VENDER_CD = VENDER.VENDER_CD(+)
AND		DEV.REQUEST_TANTO_CD = LOGIN.TANTO_CD(+)
AND		DEV.DEVELOP_ACCEPT_TANTO_CD = LOGIN2.TANTO_CD(+)
AND		DEV.REQ_APP_TANTO_CD = LOGIN3.TANTO_CD(+)
AND		DEV.DEVELOP_APP_TANTO_CD = LOGIN4.TANTO_CD(+)