/*
 * 開発依頼完成品目SQL文
 *
 * entityName=DevelopItem
 * packageName=develop
 * methodName=getDevelopItemVersion
 */
SELECT  ITEM_QUEUE.ITEM_CD
,		ITEM_QUEUE.VERSION
,		ITEM_QUEUE.ACTIVE_DATE
,		ITEM_QUEUE.STATUS
,		ITEM_QUEUE.ITEM_NAME
,		ITEM_QUEUE.ITEM_SUB_NAME
,		ITEM_QUEUE.PRODUCT_DIVISION
,		ITEM_QUEUE.ARTICLE_DIVISION
,		ITEM_QUEUE.PURCHASE_DIVISION
,		ITEM_QUEUE.ITEM_UNIT
,		ITEM_QUEUE.UNIT_WEIGHT
,		ITEM_QUEUE.ITEM_CATEGORY
,		ITEM_QUEUE.SPOT_DIVISION
,		ITEM_QUEUE.STOCK_DIVISION
,		ITEM_QUEUE.BULK_DIVISION
,		ITEM_QUEUE.DEFAULT_LOCATION
,		ITEM_QUEUE.COST_DIVISION
,		ITEM_QUEUE.LOT_DIVISION
,		ITEM_QUEUE.NEW_FLG
,		ITEM_QUEUE.INPUT_DATE
,		ITEM_QUEUE.INPUTOR_CD
,		ITEM_QUEUE.UPDATE_DATE
,		ITEM_QUEUE.UPDATOR_CD
,		ITEM_QUEUE.DEVELOPMENT_REQUEST_NO
FROM    ITEM_QUEUE
WHERE	ITEM_QUEUE.ITEM_CD = /*itemCd*/'P00000001'
AND		ITEM_QUEUE.VERSION = /*version*/'1'
