/*
 * 品目詳細用SQL
 *
 * entityName=ItemDetail
 * packageName=itemdetail
 * methodName=getEntity
 *
 */

SELECT ITEM_CD, VERSION, ITEM_NAME, ITEM_DIVISION, OTHER_COMPANY_CD1, STYLE_OF_PACKING, UNIT_OF_OPERATION_MANAGEMENT,
UNIT_OF_STOCK_CONTROL, KG_OF_FRACTION_MANAGEMENT, UNIT_OF_FRACTION_MANAGEMENT, KG_CONVERSION_COEFFICIENT,
ACTIVE_DATE, TYPE_DIVISION, SALES_TAX_CATEGORY, PURCHASE_TAX_CATEGORY, PARENT_ITEM_CD, LOT_DIVISION
FROM ITEM
WHERE ITEM_CD = /*itemCd*/'%'

/*IF (version != null) && (version != "")*/
AND VERSION = /*version*/1
/*END*/


