/*
 * 作業日報明細一覧用SQL
 *
 * entityName=dairy_report.directionheaderupdate.DirectionHeaderUpdate
 * packageName=dailyreport.directionheaderupdate
 * methodName=update, delete
 *
 */
UPDATE DIRECTION_HEADER SET
(
	 DIRECTION_HEADER.ENPLOY_JOBTIME
	,DIRECTION_HEADER.COOPER_JOBTIME
	,DIRECTION_HEADER.TOTAL_JOBTIME
)=(
	SELECT
	 KEI.ENPLOY_JOBTIME
	,KEI.COOPER_JOBTIME
	,(KEI.ENPLOY_JOBTIME + KEI.COOPER_JOBTIME) AS TOTAL_JOBTIME
	FROM (
		SELECT
		 DIRECTION_HEADER.DIRECTION_DIVISION
		,DIRECTION_HEADER.DIRECTION_NO
		,DIRECTION_HEADER.PRODUCTION_LINE
		,SUM(NVL(AA.ENPLOY,0)) AS ENPLOY_JOBTIME
		,SUM(NVL(AA.COOPER,0)) AS COOPER_JOBTIME
		FROM DIRECTION_HEADER
		LEFT JOIN (
				SELECT
				 DIRECTION_HEADER.DIRECTION_DIVISION
				,DIRECTION_HEADER.DIRECTION_NO
				,DIRECTION_HEADER.PRODUCTION_LINE
				,DRJT.TANTO_DIVISION
				,CASE WHEN DRJT.TANTO_DIVISION = 1 THEN SUM(DRJT.JOB_TIME) ELSE 0 END AS ENPLOY
				,CASE WHEN DRJT.TANTO_DIVISION = 2 THEN SUM(DRJT.JOB_TIME) ELSE 0 END AS COOPER
				FROM DIRECTION_HEADER
				INNER JOIN (
						 SELECT
						 DAILY_REPORT_HEADER.PRODUCTION_LINE
						,DAILY_REPORT_HEADER.PRODUCTION_DATE
						,DAILY_REPORT_HEADER.TANTO_DIVISION
						,DAILY_REPORT.DIRECTION_NO
						,DAILY_REPORT.JOB_TIME
						FROM DAILY_REPORT_HEADER
						INNER JOIN DAILY_REPORT ON DAILY_REPORT_HEADER.PRODUCTION_LINE=DAILY_REPORT.PRODUCTION_LINE
											   AND DAILY_REPORT_HEADER.PRODUCTION_DATE=DAILY_REPORT.PRODUCTION_DATE
											   AND DAILY_REPORT_HEADER.TANTO_DIVISION=DAILY_REPORT.TANTO_DIVISION
											   AND DAILY_REPORT_HEADER.TANTO_CD=DAILY_REPORT.TANTO_CD
						   ) DRJT ON DIRECTION_HEADER.PRODUCTION_LINE=DRJT.PRODUCTION_LINE
							   AND DIRECTION_HEADER.DIRECTION_NO=DRJT.DIRECTION_NO
							   AND TO_CHAR(DRJT.PRODUCTION_DATE,'YYYY/MM/DD')
							   	BETWEEN TO_CHAR(DIRECTION_HEADER.RESULT_SDATE,'YYYY/MM/DD') AND
							   			TO_CHAR(DIRECTION_HEADER.RESULT_EDATE,'YYYY/MM/DD')
				WHERE /*productionDate*/ BETWEEN TO_CHAR(DIRECTION_HEADER.RESULT_SDATE,'YYYY/MM/DD') AND TO_CHAR(DIRECTION_HEADER.RESULT_EDATE,'YYYY/MM/DD')
/*IF (productionLine != null) && (productionLine != "")*/
				  AND DIRECTION_HEADER.PRODUCTION_LINE=/*productionLine*/
/*END*/
				GROUP BY
				 DIRECTION_HEADER.DIRECTION_DIVISION
				,DIRECTION_HEADER.DIRECTION_NO
				,DIRECTION_HEADER.PRODUCTION_LINE
				,DRJT.TANTO_DIVISION
				  ) AA ON DIRECTION_HEADER.DIRECTION_DIVISION=AA.DIRECTION_DIVISION
					  AND DIRECTION_HEADER.DIRECTION_NO=AA.DIRECTION_NO
/*IF (productionLine != null) && (productionLine != "")*/
		WHERE DIRECTION_HEADER.PRODUCTION_LINE=/*productionLine*/
/*END*/
		GROUP BY
		 DIRECTION_HEADER.DIRECTION_DIVISION
		,DIRECTION_HEADER.DIRECTION_NO
		,DIRECTION_HEADER.PRODUCTION_LINE
		 ) KEI
	WHERE KEI.DIRECTION_DIVISION=DIRECTION_HEADER.DIRECTION_DIVISION
	  AND KEI.DIRECTION_NO=DIRECTION_HEADER.DIRECTION_NO
  )
WHERE /*productionDate*/ BETWEEN TO_CHAR(DIRECTION_HEADER.RESULT_SDATE,'YYYY/MM/DD') AND TO_CHAR(DIRECTION_HEADER.RESULT_EDATE,'YYYY/MM/DD')
/*IF (productionLine != null) && (productionLine != "")*/
  AND DIRECTION_HEADER.PRODUCTION_LINE=/*productionLine*/
/*END*/
