/*
 * Created on 2009/03/24
 *
 * $copyright$
 *
*/

/**
 * 製造実績－フォーミュラ-配合タブ検索用SQL
 *
 * @author tosco
 *
 * entityName=RdirectionDirectionFormulaList
 * packageName=rdirection
 * methodName=getSearchList
 *
 */
SELECT
    FORMULA.DIRECTION_DIVISION    AS DIRECTION_DIVISION
    ,FORMULA.DIRECTION_NO          AS DIRECTION_NO
    ,FORMULA.STEP_NO               AS STEP_NO
    ,FORMULA.LINE_NO               AS LINE_NO
    ,FORMULA.SEQ                   AS SEQ
    ,FORMULA.LINE_TYPE             AS LINE_TYPE
    ,FORMULA.ITEM_CD               AS ITEM_CD
,	FORMULA.TONYU
,	FORMULA.DATAREAD
,	FORMULA.TONYUSOKUDO
    ,FORMULA.QTY                   AS QTY
    ,FORMULA.STOCKPD_QTY           AS STOCKPD_QTY
    ,NVL(FORMULA.RESULT_QTY,0)     AS RESULT_QTY
    ,FORMULA.LOSS_QTY              AS LOSS_QTY
    ,FORMULA.ADJUST_QTY            AS ADJUST_QTY
,	FORMULA.COST
,	FORMULA.STEP_CONDITION
,	FORMULA.NOTES
,	FORMULA.LOCATION_CD
    ,FORMULA.LOT_NO                AS LOT_NO
    ,FORMULA.MANUFACTURER_LOT_NO   AS MANUFACTURER_LOT_NO
,	FORMULA.REMARK
    ,FORMULA.INPUTOR_CD            AS INPUTOR_CD
    ,FORMULA.INPUT_DATE            AS INPUT_DATE
    ,FORMULA.UPDATOR_CD            AS UPDATOR_CD
    ,FORMULA.UPDATE_DATE           AS UPDATE_DATE
    ,ITEM.ITEM_NAME                AS ITEM_NAME
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
    ,NAME.NAME01                AS UNIT_NAME
,	ITEM.STOCK_DIVISION               AS STOCK_DIVISION
    ,ITEM.LOT_DIVISION             AS LOT_DIVISION
    ,PROC.SEQ                      AS PROC_SEQ
    ,OPER.OPERATION_NAME           AS OPER_NAME
FROM
    DIRECTION_FORMULA FORMULA,
    DIRECTION_PROCEDURE PROC,
    ITEM ITEM,
    NAMES NAME,
    OPERATION OPER
WHERE
    LINE_TYPE = -1
    AND FORMULA.DIRECTION_DIVISION = 1
    AND FORMULA.DIRECTION_NO = /*directionNo*/'1'
    /*IF ( procStepNo != 0 ) */
    AND FORMULA.STEP_NO = /*procStepNo*/1
    /*END*/
    AND FORMULA.DIRECTION_NO = PROC.DIRECTION_NO
    AND FORMULA.STEP_NO = PROC.STEP_NO
    AND ITEM.ITEM_CD(+) = FORMULA.ITEM_CD
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
    AND PROC.OPERATION_CD = OPER.OPERATION_CD(+)
ORDER BY
    PROC_SEQ,
    SEQ
