/*
 * Created on 2009/03/26
 *
 * $copyright$
 *
*/

/**
 * 製造実績－フォーミュラ-詳細検索用SQL
 *
 * @author tosco
 *
 * entityName=RdirectionDirectionFormulaList
 * packageName=rdirection
 * methodName=getByPrimaryKey
 *
 */
SELECT
	FORMULA.DIRECTION_DIVISION
,	FORMULA.DIRECTION_NO
,	FORMULA.STEP_NO
,	FORMULA.LINE_NO
,	FORMULA.SEQ
,	FORMULA.LINE_TYPE
,	FORMULA.ITEM_CD
,	FORMULA.TONYU
,	FORMULA.DATAREAD
,	FORMULA.TONYUSOKUDO
,	FORMULA.QTY
,	FORMULA.STOCKPD_QTY
,	FORMULA.RESULT_QTY
,	FORMULA.LOSS_QTY
,	FORMULA.ADJUST_QTY
,	FORMULA.COST
,	FORMULA.STEP_CONDITION
,	FORMULA.NOTES
,	FORMULA.LOCATION_CD
,	FORMULA.LOT_NO
,	FORMULA.MANUFACTURER_LOT_NO
,	FORMULA.REMARK
,	FORMULA.INPUTOR_CD
,	FORMULA.INPUT_DATE
,	FORMULA.UPDATOR_CD
,	FORMULA.UPDATE_DATE
,   ITEM.ITEM_NAME                    AS ITEM_NAME
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   NAME.NAME01                       AS UNIT_NAME
,	ITEM.STOCK_DIVISION               AS STOCK_DIVISION
,	ITEM.LOT_DIVISION                 AS LOT_DIVISION
FROM
    DIRECTION_FORMULA FORMULA,
    ITEM ITEM,
    NAMES NAME
WHERE
	    FORMULA.DIRECTION_DIVISION = 1
	AND FORMULA.DIRECTION_NO = /*directionNo*/
	AND FORMULA.STEP_NO = /*stepNo*/1
	AND FORMULA.LINE_NO = /*lineNo*/1
    AND ITEM.ITEM_CD(+) = FORMULA.ITEM_CD
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT