/*
 * ロケーション詳細用SQL
 *
 * entityName=LocationDetail
 * packageName=locationdetail
 * methodName=getEntity
 *
 */

SELECT LOCATION.LOCATION_CD, LOCATION.LOCATION_NAME, LOCATION.UPPER_LOCATION_CD,
UPPER_LOCATION.LOCATION_NAME UPPER_LOCATION_NAME, LOCATION.LOCATION_LEVEL, LOCATION.POSSIBLE_WEIGHT,
LOCATION.CURRENT_WEIGHT, LOCATION.MRP_TARGET_FLG, LOCATION.SECTION_CD, BUMON.SECTION_NAME,
LOCATION.TANTO_CD, LOGIN.TANTO_NM, LOCATION.STOCK_DIVISION, LOCATION.UPDATE_DATE, LOCATION.AVAILABLE_FLG,
LOCATION.COUNT_DIVISION, LOCATION.ITEM_CD, ITEM_NAME, OTHER_COMPANY_CD1
FROM LOCATION, BUMON, LOCATION UPPER_LOCATION, LOGIN, VALID_ITEM_QUEUE ITEM_QUEUE
WHERE LOCATION.LOCATION_CD = /*locationCd*/'%'
AND LOCATION.UPPER_LOCATION_CD = UPPER_LOCATION.LOCATION_CD(+)
AND LOCATION.TANTO_CD = LOGIN.TANTO_CD(+)
AND LOCATION.SECTION_CD = BUMON.SECTION_CD(+)
AND LOCATION.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
