/*
 * Created on 2009/02/17
 *
 * $copyright$
 *
*/

/**
 * 予備溶解ラベル発行画面 一覧用SQL
 *
 * @author tosco
 *
 * entityName=BeforehandMeltLblList
 * packageName=beforehandmeltlbl
 * methodName=getSearchList
 *
 */
SELECT	DIRECTION_HEADER.DIRECTION_DIVISION
,	DIRECTION_HEADER.DIRECTION_NO
,	DIRECTION_HEADER.DIRECTION_DATE
,	DIRECTION_HEADER.ASP_ORDER_NO
,	DIRECTION_HEADER.DIRECTION_STATUS
,	DIRECTION_HEADER.RECIPE_ID
,	DIRECTION_HEADER.RECIPE_CD
,	DIRECTION_HEADER.RECIPE_VERSION
,	DIRECTION_HEADER.PRODUCTION_LINE
,	DIRECTION_HEADER.COMPOUND_TANK_NO
,	DIRECTION_HEADER.HOLD_TANK_NO
,	DIRECTION_HEADER.DISSOLUTION_TANK_NO
,	DIRECTION_HEADER.FILLTANK_NO
,	DIRECTION_HEADER.PACKAGE_LINE
,	DIRECTION_HEADER.CURRENT_STEP_NO
,	DIRECTION_HEADER.ITEM_CD
,	DIRECTION_HEADER.PLANED_QTY
,	DIRECTION_HEADER.RESULT_QTY
,	DIRECTION_HEADER.DIVIDE_FLAG
,	DIRECTION_HEADER.NEXT_PLANED_QTY
,	DIRECTION_HEADER.PDW_RESULT
,	DIRECTION_HEADER.PEOCESS_LOSS
,	DIRECTION_HEADER.LOT_NO
,	DIRECTION_HEADER.PLANED_SDATE
,	DIRECTION_HEADER.PLANED_EDATE
,	DIRECTION_HEADER.RESULT_SDATE
,	DIRECTION_HEADER.RESULT_EDATE
,	DIRECTION_HEADER.STERIT_SDATE
,	DIRECTION_HEADER.STERIT_EDATE
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MIN
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MAX
,	DIRECTION_HEADER.HAISUI_CHECK
,	DIRECTION_HEADER.STAMP_FLAG
,	DIRECTION_HEADER.STAMP_DATE
,	DIRECTION_HEADER.STAMP_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_LABEL_FLAG
,	DIRECTION_HEADER.PRODUCT_LABEL_DATE
,	DIRECTION_HEADER.PRODUCT_LABEL_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_RECORD_FLAG
,	DIRECTION_HEADER.PRODUCT_RECORD_DATE
,	DIRECTION_HEADER.PRODUCT_RECORD_TANTO_CD
,	DIRECTION_HEADER.STOCKDISS_LABEL_FLAG
,	DIRECTION_HEADER.STOCKDISS_LABEL_DATE
,	DIRECTION_HEADER.STOCKDISS_LABEL_TANTO_CD
,	DIRECTION_HEADER.CERTIFICATION_FLAG
,	DIRECTION_HEADER.CERTIFICATION_DATE
,	DIRECTION_HEADER.REMARK
,	DIRECTION_HEADER.NOTES
,	DIRECTION_HEADER.DELETE_FLAG
,	DIRECTION_HEADER.SEIZOTANTOCODE
,	DIRECTION_HEADER.SENJOTANTOCODE
,	DIRECTION_HEADER.MEKKINTANTOCODE
,	DIRECTION_HEADER.CHOGOTANKCONDI
,	DIRECTION_HEADER.YOBIYOKAICONDI
,	DIRECTION_HEADER.HOLDTANKCONDI
,	DIRECTION_HEADER.TOTAL_JOBTIME
,	DIRECTION_HEADER.ENPLOY_JOBTIME
,	DIRECTION_HEADER.COOPER_JOBTIME
,	DIRECTION_HEADER.APP_TANTO_CD
,	DIRECTION_HEADER.APP_DATE
,	DIRECTION_HEADER.LAST_APP_TANTO_CD
,	DIRECTION_HEADER.LAST_APP_DATE
,	DIRECTION_HEADER.INPUT_DATE
,	DIRECTION_HEADER.INPUTOR_CD
,	DIRECTION_HEADER.UPDATE_DATE
,	DIRECTION_HEADER.UPDATOR_CD


,	ITEM_NAMES.ITEM_NAME
,	LINE.PRODUCTION_LINE_NAME
,	DIRECTION_PROCEDURE_COUNT.MAIN_STREAM_COUNT

FROM	DIRECTION_HEADER
,	(SELECT
	    ITEM2.ITEM_CD ,
	    ITEM2.ITEM_NAME,
	    OTHER_COMPANY_CD1
	FROM
		VALID_ITEM_QUEUE ITEM2
	) ITEM_NAMES
,	LINE
,	(SELECT	DIRECTION_PROCEDURE.DIRECTION_DIVISION
	,	DIRECTION_PROCEDURE.DIRECTION_NO
	,	COUNT(*) as MAIN_STREAM_COUNT
	FROM	DIRECTION_PROCEDURE
	
	WHERE	TO_NUMBER(DIRECTION_PROCEDURE.OPERATION_CD) >= 31
	AND	TO_NUMBER(DIRECTION_PROCEDURE.OPERATION_CD) <= 36
	
	GROUP BY	DIRECTION_PROCEDURE.DIRECTION_DIVISION
	,		DIRECTION_PROCEDURE.DIRECTION_NO
	)DIRECTION_PROCEDURE_COUNT

WHERE	DIRECTION_HEADER.DIRECTION_DIVISION = '1'
AND		DIRECTION_HEADER.DIRECTION_STATUS in( '2','3')

AND		DIRECTION_HEADER.ITEM_CD = ITEM_NAMES.ITEM_CD(+)

AND		DIRECTION_HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)

AND		DIRECTION_HEADER.DIRECTION_DIVISION = DIRECTION_PROCEDURE_COUNT.DIRECTION_DIVISION(+)
AND		DIRECTION_HEADER.DIRECTION_NO = DIRECTION_PROCEDURE_COUNT.DIRECTION_NO(+)
AND		DIRECTION_PROCEDURE_COUNT.MAIN_STREAM_COUNT >= 1

/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
	AND	DIRECTION_HEADER.DIRECTION_NO LIKE /*condition.srhDirectionNo*/'%'
/*END*/

/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	AND	DIRECTION_HEADER.PRODUCTION_LINE = /*condition.srhProductionLine*/'%'
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	DIRECTION_HEADER.ITEM_CD LIKE /*condition.srhItemCd*/'%'
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*conditiｗon.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (( condition.srhPlanedSdateFrom != null ) && ( condition.srhPlanedSdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE >= /*condition.srhPlanedSdateFrom*/'2009/01/01'
/*END*/

/*IF (( condition.srhPlanedSdateTo != null ) && ( condition.srhPlanedSdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE <= /*condition.srhPlanedSdateTo*/'2009/12/31'
/*END*/

/*IF (( condition.srhPlanedEdateFrom != null ) && ( condition.srhPlanedEdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE >= /*condition.srhPlanedEdateFrom*/'2009/01/01'
/*END*/

/*IF (( condition.srhPlanedEdateTo != null ) && ( condition.srhPlanedEdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE <= /*condition.srhPlanedEdateTo*/'2009/12/31'
/*END*/

ORDER BY	DIRECTION_HEADER.PLANED_SDATE
,		DIRECTION_HEADER.DIRECTION_NO
,		DIRECTION_HEADER.ITEM_CD
