/*
 * entityName=InquiryInputListForReport
 * packageName=inquiryinputlistforreport
 * methodName=getListForReport
 *
 */

SELECT 

	INVENTORY_COUNT.COUNT_DATE
,	INVENTORY_COUNT.COUNT_DIVISION
,	INVENTORY_COUNT.COUNT_LOCATION
,	LOCATION.LOCATION_NAME
,	INVENTORY_COUNT.ITEM_CD
,	ITEM_NAME
,	INVENTORY_COUNT.LOT_NO
,	INVENTORY_COUNT.ALIAS_LOT_NO
,	NVL(INVENTORY_COUNT.COUNT_QTY, 0) COUNT_QTY
,	NVL(INVENTORY_COUNT.FRACTION_QTY, 0) FRACTION_QTY
,	NVL(DECODE(INVENTORY_COUNT.INPUT_QTY,NULL,INVENTORY_COUNT.COUNT_QTY, INVENTORY_COUNT.INPUT_QTY), 0) INPUT_QTY
,	NVL(DECODE(INVENTORY_COUNT.INPUTFRACTION, NULL, INVENTORY_COUNT.FRACTION_QTY,INVENTORY_COUNT.INPUTFRACTION), 0) INPUTFRACTION
,	INVENTORY_COUNT.COUNT_COST
,	INVENTORY_COUNT.COUNT_UPDATE_DATE
,	NAMES.NAME01
,	INVENTORY_COUNT.INPUT_DATE
,	INVENTORY_COUNT.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	INVENTORY_COUNT.UPDATE_DATE
,	INVENTORY_COUNT.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM 
	INVENTORY_COUNT
,	NAMES
,	LOCATION
,	ITEM
,	LOGIN INPUTOR
,	LOGIN UPDATOR

,	(SELECT ITEM_CD, MAX(VERSION) VERSION
		FROM ITEM
		GROUP BY ITEM_CD) MAX_ITEM

WHERE COUNT_DATE = /*condition.srhCountDate*/'2008/12/07'

AND	INVENTORY_COUNT.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND INVENTORY_COUNT.UPDATOR_CD = UPDATOR.TANTO_CD(+)

AND (COUNT_LOCATION LIKE /*condition.srhLocationCd*/'%' OR LOCATION_NAME LIKE /*condition.srhLocationCd*/'%')

/*IF(condition.srhCountDivision != null) && (condition.srhCountDivision != "")*/
AND INVENTORY_COUNT.COUNT_DIVISION = /*condition.srhCountDivision*/'%'
/*END*/

/*IF(condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (INVENTORY_COUNT.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF(condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF(condition.srhAliasLotNo != null) && (condition.srhAliasLotNo != "")*/
AND ALIAS_LOT_NO LIKE /*condition.srhAliasLotNo*/'%'
/*END*/

AND NAME_DIVISION(+) = 'TANA'
AND INVENTORY_COUNT.COUNT_DIVISION = NAME_CD(+)
AND INVENTORY_COUNT.COUNT_DIVISION = LOCATION.COUNT_DIVISION
AND COUNT_LOCATION = LOCATION_CD(+)
AND INVENTORY_COUNT.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND MAX_ITEM.ITEM_CD = ITEM.ITEM_CD(+)
AND MAX_ITEM.VERSION = ITEM.VERSION(+)

ORDER BY INVENTORY_COUNT.COUNT_DIVISION, COUNT_LOCATION, INVENTORY_COUNT.ITEM_CD, ALIAS_LOT_NO




