/*
 * 
 *
 * entityName=RepSlipShippingNifuda
 * packageName=slipshippinglistforreport
 * methodName=getListForReport
 *
 */


SELECT
	SYUYAKU.LOCATION_CD
	|| TO_CHAR(SYUYAKU.SCHEDULED_SHIPPING_DATE,'YYYYMMDD')
	|| SYUYAKU.DELIVERY_CD
	|| SYUYAKU.ORDER_NO	AS KEY
,	SYUYAKU.DELIVERY_CD
,	SYUYAKU.ORDER_NO
,	SYUYAKU.LOCATION_CD
,	DEL.DELIVERY_NAME1
,	DEL.DELIVERY_NAME2
,	ORDER_HEAD.DELIVERY_ADDRESS
,	DEL.TEL_NO
,	DEL.ZIPCODE_NO
,	DEL.ADDRESS1
,	DEL.ADDRESS2
,	DEL.ADDRESS3
,	TO_CHAR(SYUYAKU.ORDER_QTY)	AS ORDER_QTY
,	TO_CHAR(SYUYAKU.SCHEDULED_SHIPPING_DATE,'YYYYMMDD')	AS SCHEDULED_SHIPPING_DATE

FROM
	ORDER_HEAD
,	DELIVERY	DEL
,	CARRY
,	(
	SELECT 
		HEAD.SCHEDULED_SHIPPING_DATE
	,	SUM(DETAIL.ORDER_QTY) AS ORDER_QTY
	,	HEAD.DELIVERY_CD
	,	HEAD.ORDER_NO
	,	HEAD.CARRY_CD
	,	LOCATION.LOCATION_CD
	,	HEAD.SHIPPING_SLIP_NO
	
	FROM
		SHIPPING HEAD
	,	(SELECT SHIPPING_NO,SUM(SHIPPING_INSTRUCTION) AS ORDER_QTY FROM SHIPPING_DETAIL GROUP BY SHIPPING_NO) DETAIL
	,	LOCATION
	,	CARRY
	,		(SELECT
				SHIPPING_DETAIL.SHIPPING_NO
			,	MAX(UPPER_LOCATION.UPPER_LOCATION_CD) AS UPPER_LOCATION_CD
			FROM
				SHIPPING_DETAIL
			,	(SELECT
					LOCA1.LOCATION_CD
				,	NVL(LOCA2.UPPER_LOCATION_CD,LOCA2.LOCATION_CD) as UPPER_LOCATION_CD
				FROM
					LOCATION LOCA1
				,	LOCATION LOCA2
				WHERE
					NVL(LOCA1.UPPER_LOCATION_CD,LOCA1.LOCATION_CD) = LOCA2.LOCATION_CD(+)
				AND	(LOCA1.LOCATION_LEVEL = '1' OR LOCA1.LOCATION_LEVEL = '4')
				AND	LOCA1.LOCATION_CD <> 'K'
				)UPPER_LOCATION
			
			WHERE
				SHIPPING_DETAIL.LOCATION_CD = UPPER_LOCATION.LOCATION_CD
			
			GROUP BY
				SHIPPING_DETAIL.SHIPPING_NO
			) U_LOCATION
	
	WHERE
		HEAD.SHIPPING_NO = DETAIL.SHIPPING_NO
	AND	HEAD.CARRY_CD = CARRY.CARRY_CD
	AND	HEAD.SHIPPING_NO = U_LOCATION.SHIPPING_NO
	AND	LOCATION.LOCATION_CD = U_LOCATION.UPPER_LOCATION_CD
	AND	CARRY.LABEL_PUBLISH = 2 --2:荷札
	AND	HEAD.SHIPPING_NO IN /*shippingNo*/('SK000000001')	

	GROUP BY
		HEAD.SCHEDULED_SHIPPING_DATE
	,	HEAD.DELIVERY_CD
	,	HEAD.ORDER_NO
	,	HEAD.CARRY_CD
	,	LOCATION.LOCATION_CD
	,	HEAD.SHIPPING_SLIP_NO
	) SYUYAKU

WHERE
	SYUYAKU.DELIVERY_CD = DEL.DELIVERY_CD
AND	SYUYAKU.ORDER_NO = ORDER_HEAD.ORDER_NO
AND	CARRY.CARRY_CD = SYUYAKU.CARRY_CD
ORDER BY
	CARRY.REPOTR_OUTPUT_NUM 
,	SYUYAKU.CARRY_CD
,	SYUYAKU.SHIPPING_SLIP_NO NULLS FIRST


