/*
 * 
 *
 * entityName=RepSlipShippingDirDetail
 * packageName=slipshippinglistforreport
 * methodName=getListForReport
 * 19/11/29 AECS佐藤　原料ロット番号追加・数量のサマリ変更
 * 
 */
SELECT
	*
FROM
	(
	SELECT
		KEY
	,	NULL	AS SHIPPING_NO
	,	NULL	AS SHIPPING_INSTRUCT_DATE
	,	SCHEDULED_SHIPPING_DATE
	,	NULL	AS TANTO_CD
	,	NULL	AS ORDER_NO
	,	NULL	AS ORDER_ROW_NO
	,	NULL	AS VENDER_DIVISION
	,	NULL	AS VENDER_CD
	,	NULL	AS DELIVERY_CD
	,	NULL	AS SHIPPING_STATUS
	,	ITEM_CD
	,	NULL	AS SUMMERY
	,	NULL	AS DELIVERY_COMP
	,	NULL	AS SHIPPING_RESULT_DATE
	,	NULL	AS SHIPPING_SLIP_NO
	,	NULL	AS SHIPPING_SLIP_ROW_NO
	,	NULL	AS SLIP_PUBLISH_COMP
	,	NULL	AS SLIP_PUBLISH_DATE
	,	NULL	AS SLIP_SHIPPING_ORDER_COMP
	,	NULL	AS SLIP_SHIPPING_ORDER_DATE
	,	NULL	AS SLIP_SHIPPING_SCHEDULE_COMP
	,	NULL	AS SLIP_SHIPPING_SCHEDULE_DATE
	,	NULL	AS SLIP_SHIPPING_TAG_COMP
	,	NULL	AS SLIP_SHIPPING_TAG_DATE
	,	NULL	AS SLIP_SHIPPING_REQUEST_COMP
	,	NULL	AS SLIP_SHIPPING_REQUEST_DATE
	,	CARRY_CD
	,	NULL	AS SUGGESTED_DELIVERLIMIT
	,	NULL	AS CARRY_FARE
	,	NULL	AS SENDING_OFF_NUMBER
	,	NULL	AS INPUT_DATE
	,	NULL	AS INPUTOR_CD
	,	NULL	AS UPDATE_DATE
	,	NULL	AS UPDATOR_CD
	,	ITEM_NAME
	,	STYLE_OF_PACKING
	,	ALIAS_LOT_NO
	,	TO_CHAR(SUM(SHIPPING_INSTRUCTION))	AS SHIPPING_INSTRUCTION
	,	LOCATION_CD
	,	TO_CHAR(SUM(CONVERT_QTY))	AS CONVERT_QTY
	
	FROM
	(	SELECT
			U_LOCATION.UPPER_LOCATION_CD || HEAD.CARRY_CD || TO_CHAR(HEAD.SCHEDULED_SHIPPING_DATE,'YYYYMMDD')	AS KEY
		,	TO_CHAR(HEAD.SCHEDULED_SHIPPING_DATE,'YYYYMMDD')	AS SCHEDULED_SHIPPING_DATE
		,	HEAD.ITEM_CD
		,	HEAD.CARRY_CD
		,	ITEM.ITEM_NAME
		,	ITEM.STYLE_OF_PACKING
		,	SHIPPING_DATE.LOCATION_CD
		,	SHIPPING_DATE.SHIPPING_INSTRUCTION
		,	SHIPPING_DATE.ALIAS_LOT_NO
		,	NVL(ITEM.ALL_UP_WEIGHT,0) * SHIPPING_DATE.SHIPPING_INSTRUCTION AS CONVERT_QTY
		
		FROM
			SHIPPING HEAD
		,	ITEM
		,	CARRY
		,		(SELECT
					SHIPPING_DETAIL.SHIPPING_NO
				,	MAX(UPPER_LOCATION.UPPER_LOCATION_CD) AS UPPER_LOCATION_CD
				FROM
					SHIPPING_DETAIL
				,	(SELECT
						LOCA1.LOCATION_CD
					,	NVL(LOCA2.UPPER_LOCATION_CD,LOCA2.LOCATION_CD) as UPPER_LOCATION_CD
					FROM
						LOCATION LOCA1
					,	LOCATION LOCA2
					WHERE
						NVL(LOCA1.UPPER_LOCATION_CD,LOCA1.LOCATION_CD) = LOCA2.LOCATION_CD(+)
					AND	(LOCA1.LOCATION_LEVEL = '1' OR LOCA1.LOCATION_LEVEL = '4')
					AND	LOCA1.LOCATION_CD <> 'K'
					)UPPER_LOCATION
				
				WHERE
					SHIPPING_DETAIL.LOCATION_CD = UPPER_LOCATION.LOCATION_CD
				
				GROUP BY
					SHIPPING_DETAIL.SHIPPING_NO
				) U_LOCATION
				
		,		(SELECT
					SHIPPING.SHIPPING_NO
				,	SHIPPING.SCHEDULED_SHIPPING_DATE
				,	SHIPPING.ITEM_CD
				,	SHIPPING_DETAIL.LOCATION_CD
				,	SHIPPING_DETAIL.LOT_NO
				,	SHIPPING_DETAIL.SHIPPING_INSTRUCTION
				,	NVL((SELECT LOT_INVENTORY.ALIAS_LOT_NO 
						FROM LOT_INVENTORY 
						WHERE LOT_INVENTORY.LOCATION_CD = SHIPPING_DETAIL.LOCATION_CD 
						AND LOT_INVENTORY.ITEM_CD = SHIPPING.ITEM_CD 
						AND LOT_INVENTORY.LOT_NO = SHIPPING_DETAIL.LOT_NO),' ') AS ALIAS_LOT_NO
				FROM
					SHIPPING
				LEFT JOIN SHIPPING_DETAIL ON SHIPPING_DETAIL.SHIPPING_NO = SHIPPING.SHIPPING_NO
				)SHIPPING_DATE
		WHERE
			HEAD.ITEM_CD = ITEM.ITEM_CD(+)
		AND	HEAD.SHIPPING_NO = U_LOCATION.SHIPPING_NO
		AND	HEAD.CARRY_CD = CARRY.CARRY_CD
		AND HEAD.SHIPPING_NO = SHIPPING_DATE.SHIPPING_NO
		AND HEAD.SHIPPING_NO IN /*shippingNo*/('SK000000001')
	)
	
	GROUP BY
		KEY
	,	SCHEDULED_SHIPPING_DATE
	,	ITEM_CD
	,	CARRY_CD
	,	ITEM_NAME
	,	STYLE_OF_PACKING
	,	ALIAS_LOT_NO
	,	LOCATION_CD
	) SHIPPING_D
,	CARRY

WHERE
	CARRY.CARRY_CD = SHIPPING_D.CARRY_CD
	
ORDER BY
	KEY
,	LOCATION_CD
,	REPOTR_OUTPUT_NUM
,	ITEM_CD 
