/*
 * 品目マスタ関連検索帳票用SQL
 *
 * entityName=ItemQueueListForReport
 * packageName=itemqueuelistforreport
 * methodName=getRecipeHeaderListForReport
 *
 */

SELECT *
FROM
(SELECT HEADER.*

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END RECIPE_STATUS_NAME

, ITEM_QUEUE.ITEM_NAME
, LINE.PRODUCTION_LINE_NAME
, PRINTOR.TANTO_NM PRINTOR_NAME
, APPROVOR.TANTO_NM APPROVOR_NAME
, LAST_APPROVOR.TANTO_NM LAST_APPROVOR_NAME
, BUMON.SECTION_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM
(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME

FROM

(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_NAME
, STATUS
, ACTIVE_DATE
, OTHER_COMPANY_CD1
, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2009/01/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2009/12/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
) ITEM_QUEUE

, (SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

, RECIPE_HEADER HEADER
, LINE
, LOGIN PRINTOR
, LOGIN APPROVOR
, LOGIN LAST_APPROVOR
, BUMON
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD
AND HEADER.RECIPE_TYPE = 1 --原処方
AND HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND HEADER.PRINT_TANTO_CD = PRINTOR.TANTO_CD(+)
AND HEADER.APP_TANTO_CD = APPROVOR.TANTO_CD(+)
AND HEADER.LAST_APP_TANTO_CD = LAST_APPROVOR.TANTO_CD(+)
AND HEADER.SECTION_CD = BUMON.SECTION_CD(+)
AND HEADER.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND HEADER.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD
AND ITEM_QUEUE.VERSION = MAX_ITEM.VERSION

UNION

SELECT DISTINCT HEADER.*

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END RECIPE_STATUS_NAME

, HEADER_ITEM.ITEM_NAME
, LINE.PRODUCTION_LINE_NAME
, PRINTOR.TANTO_NM PRINTOR_NAME
, APPROVOR.TANTO_NM APPROVOR_NAME
, LAST_APPROVOR.TANTO_NM LAST_APPROVOR_NAME
, BUMON.SECTION_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM
(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME

FROM

(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_NAME
, STATUS
, ACTIVE_DATE
, OTHER_COMPANY_CD1
, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2009/01/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2009/12/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
) ITEM_QUEUE

, (SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

, ITEM_QUEUE HEADER_ITEM
, RECIPE_HEADER HEADER
, RECIPE_FORMULA FORMULA
, LINE
, LOGIN PRINTOR
, LOGIN APPROVOR
, LOGIN LAST_APPROVOR
, BUMON
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE FORMULA.ITEM_CD = ITEM_QUEUE.ITEM_CD
AND HEADER.RECIPE_TYPE = 1 --原処方
AND FORMULA.LINE_NO <= 1000 --配合のみ
AND HEADER.RECIPE_ID = FORMULA.RECIPE_ID
AND HEADER.ITEM_CD = HEADER_ITEM.ITEM_CD(+)
AND HEADER_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND HEADER_ITEM.VERSION = MAX_ITEM.VERSION
AND HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND HEADER.PRINT_TANTO_CD = PRINTOR.TANTO_CD(+)
AND HEADER.APP_TANTO_CD = APPROVOR.TANTO_CD(+)
AND HEADER.LAST_APP_TANTO_CD = LAST_APPROVOR.TANTO_CD(+)
AND HEADER.SECTION_CD = BUMON.SECTION_CD(+)
AND HEADER.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND HEADER.UPDATOR_CD = UPDATOR.TANTO_CD(+)

UNION

SELECT HEADER.*

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END RECIPE_STATUS_NAME

, ITEM_QUEUE.ITEM_NAME
, LINE.PRODUCTION_LINE_NAME
, PRINTOR.TANTO_NM PRINTOR_NAME
, APPROVOR.TANTO_NM APPROVOR_NAME
, LAST_APPROVOR.TANTO_NM LAST_APPROVOR_NAME
, BUMON.SECTION_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM
(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME

FROM

(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_NAME
, STATUS
, ACTIVE_DATE
, OTHER_COMPANY_CD1
, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2009/01/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2009/12/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
) ITEM_QUEUE

, (SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

, RECIPE_HEADER HEADER
, LINE
, LOGIN PRINTOR
, LOGIN APPROVOR
, LOGIN LAST_APPROVOR
, BUMON
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD
AND HEADER.RECIPE_TYPE = 3 --基本処方
AND HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND HEADER.PRINT_TANTO_CD = PRINTOR.TANTO_CD(+)
AND HEADER.APP_TANTO_CD = APPROVOR.TANTO_CD(+)
AND HEADER.LAST_APP_TANTO_CD = LAST_APPROVOR.TANTO_CD(+)
AND HEADER.SECTION_CD = BUMON.SECTION_CD(+)
AND HEADER.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND HEADER.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD
AND ITEM_QUEUE.VERSION = MAX_ITEM.VERSION

UNION

SELECT DISTINCT HEADER.*

, CASE HEADER.RECIPE_STATUS
    WHEN 1 THEN 'ラボ使用'
    WHEN 2 THEN '試作用'
    WHEN 3 THEN '一般使用'
    WHEN 4 THEN '廃棄'
    WHEN 5 THEN '改訂中'
    WHEN 6 THEN '保留中'
    ELSE NULL
END RECIPE_STATUS_NAME

, HEADER_ITEM.ITEM_NAME
, LINE.PRODUCTION_LINE_NAME
, PRINTOR.TANTO_NM PRINTOR_NAME
, APPROVOR.TANTO_NM APPROVOR_NAME
, LAST_APPROVOR.TANTO_NM LAST_APPROVOR_NAME
, BUMON.SECTION_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM
(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME

FROM

(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_NAME
, STATUS
, ACTIVE_DATE
, OTHER_COMPANY_CD1
, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2009/01/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2009/12/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
) ITEM_QUEUE

, (SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

, ITEM_QUEUE HEADER_ITEM
, RECIPE_HEADER HEADER
, RECIPE_FORMULA FORMULA
, LINE
, LOGIN PRINTOR
, LOGIN APPROVOR
, LOGIN LAST_APPROVOR
, BUMON
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE FORMULA.ITEM_CD = ITEM_QUEUE.ITEM_CD
AND HEADER.RECIPE_TYPE = 3 --基本処方
AND FORMULA.LINE_NO <= 1000 --配合のみ
AND HEADER.RECIPE_ID = FORMULA.RECIPE_ID
AND HEADER.ITEM_CD = HEADER_ITEM.ITEM_CD(+)
AND HEADER_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND HEADER_ITEM.VERSION = MAX_ITEM.VERSION
AND HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND HEADER.PRINT_TANTO_CD = PRINTOR.TANTO_CD(+)
AND HEADER.APP_TANTO_CD = APPROVOR.TANTO_CD(+)
AND HEADER.LAST_APP_TANTO_CD = LAST_APPROVOR.TANTO_CD(+)
AND HEADER.SECTION_CD = BUMON.SECTION_CD(+)
AND HEADER.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND HEADER.UPDATOR_CD = UPDATOR.TANTO_CD(+)
)
ORDER BY RECIPE_TYPE, RECIPE_ID
