/*
 * 品目マスタ検索帳票用SQL(未使用)
 *
 * entityName=ItemQueueListForReport
 * packageName=itemqueuelistforreport
 * methodName=getInactivateListForReport
 *
 */

SELECT *
FROM
(SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME
, ITEM_QUEUE.STATUS
, ITEM_QUEUE.ACTIVE_DATE,

CASE ITEM_QUEUE.STATUS
    WHEN 1 THEN '入力中'
    WHEN 2 THEN '承認依頼中'
    WHEN 3 THEN '承認済み'
    WHEN 4 THEN '研究用'
    ELSE NULL
END STATUS_NAME

, DECODE(ITEM_QUEUE.VERSION, ITEM.VERSION, '○', '×') ACTIVATE
, ITEM_QUEUE.ITEM_TYPE
, ITEM_QUEUE.ITEM_SUB_NAME
, ITEM_QUEUE.PRODUCT_DIVISION
, ITEM_QUEUE.ARTICLE_DIVISION
, ITEM_QUEUE.PURCHASE_DIVISION
, ITEM_QUEUE.PARENT_ITEM_CD
, PARENT_ITEM_NAME
, ITEM_QUEUE.ITEM_CATEGORY
, ITEM_CATEGORY_NAME
, ITEM_QUEUE.PHANTOM_DIVISION
, ITEM_QUEUE.SPOT_DIVISION
, ITEM_QUEUE.STOCK_DIVISION
, ITEM_QUEUE.BULK_DIVISION
, ITEM_QUEUE.DEFAULT_LOCATION
, DEFAULT_LOCATION.LOCATION_NAME DEFAULT_LOCATION_NAME
, ITEM_QUEUE.COST_DIVISION
, ITEM_QUEUE.LOT_DIVISION
, ITEM_QUEUE.NEW_FLG
, ITEM_QUEUE.RESEARCH_ITEM
, ITEM_QUEUE.SHIPPER_DIVISION
, ITEM_QUEUE.TYPE_DIVISION
, ITEM_QUEUE.OTHER_COMPANY_CD1
, ITEM_QUEUE.ORDER_LOCATION
, ORDER_LOCATION.LOCATION_NAME ORDER_LOCATION_NAME
, ITEM_QUEUE.STYLE_OF_PACKING
, ITEM_QUEUE.NUMBER_OF_INSERTIONS
, ITEM_QUEUE.ALL_UP_WEIGHT
, ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT
, OPERATION_MANAGEMENT.NAME01 OPERATION_MANAGEMENT_NAME
, ITEM_QUEUE.UNIT_OF_STOCK_CONTROL
, STOCK_CONTROL.NAME01 UNIT_OF_STOCK_CONTROL_NAME
, ITEM_QUEUE.KG_OF_FRACTION_MANAGEMENT
, ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT
, FRACTION_MANAGEMENT.NAME01 FRACTION_MANAGEMENT_NAME
, ITEM_QUEUE.KG_CONVERSION_COEFFICIENT
, ITEM_QUEUE.WATER_DIVISION
, ITEM_QUEUE.INPUT_DATE
, ITEM_QUEUE.INPUTOR_CD
, INPUTOR.TANTO_NM INPUTOR_NAME
, ITEM_QUEUE.UPDATE_DATE
, ITEM_QUEUE.UPDATOR_CD
, UPDATOR.TANTO_NM UPDATOR_NAME
, ITEM_QUEUE.DEVELOPMENT_REQUEST_NO

FROM

(SELECT ITEM_QUEUE.ITEM_CD, ITEM_QUEUE.VERSION, ITEM_NAME, STATUS, ACTIVE_DATE, OTHER_COMPANY_CD1, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

, ITEM_TYPE
, ITEM_SUB_NAME
, PRODUCT_DIVISION
, ARTICLE_DIVISION
, PURCHASE_DIVISION
, ITEM_CATEGORY
, PHANTOM_DIVISION
, SPOT_DIVISION
, STOCK_DIVISION
, BULK_DIVISION
, DEFAULT_LOCATION
, COST_DIVISION
, LOT_DIVISION
, NEW_FLG
, RESEARCH_ITEM
, SHIPPER_DIVISION
, TYPE_DIVISION
, ORDER_LOCATION
, STYLE_OF_PACKING
, NUMBER_OF_INSERTIONS
, ALL_UP_WEIGHT
, UNIT_OF_OPERATION_MANAGEMENT
, UNIT_OF_STOCK_CONTROL
, KG_OF_FRACTION_MANAGEMENT
, UNIT_OF_FRACTION_MANAGEMENT
, KG_CONVERSION_COEFFICIENT
, WATER_DIVISION
, INPUT_DATE
, INPUTOR_CD
, UPDATE_DATE
, UPDATOR_CD
, DEVELOPMENT_REQUEST_NO

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE
, ITEM_CATEGORY
, LOCATION DEFAULT_LOCATION
, LOCATION ORDER_LOCATION
, NAMES OPERATION_MANAGEMENT
, NAMES STOCK_CONTROL
, NAMES FRACTION_MANAGEMENT
, LOGIN INPUTOR
, LOGIN UPDATOR

, (SELECT ITEM_CD, MAX(ACTIVE_DATE) ACTIVE_DATE
FROM ITEM_QUEUE
WHERE ACTIVE_DATE <= TO_CHAR(SYSDATE, 'YYYY/MM/DD')
GROUP BY ITEM_CD) MAX_ITEM

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2007/07/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2007/07/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD
AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
AND MAX_ITEM.ACTIVE_DATE = ITEM_QUEUE.ACTIVE_DATE
AND ITEM_QUEUE.ITEM_CATEGORY = ITEM_CATEGORY.ITEM_CATEGORY(+)
AND ITEM_QUEUE.DEFAULT_LOCATION = DEFAULT_LOCATION.LOCATION_CD(+)
AND ITEM_QUEUE.ORDER_LOCATION = ORDER_LOCATION.LOCATION_CD(+)
AND OPERATION_MANAGEMENT.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT = OPERATION_MANAGEMENT.NAME_CD(+)
AND STOCK_CONTROL.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_STOCK_CONTROL = STOCK_CONTROL.NAME_CD(+)
AND FRACTION_MANAGEMENT.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT = FRACTION_MANAGEMENT.NAME_CD(+)
AND ITEM_QUEUE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND ITEM_QUEUE.UPDATOR_CD = UPDATOR.TANTO_CD(+)

UNION

SELECT ITEM_QUEUE.ITEM_CD
, ITEM_QUEUE.VERSION
, ITEM_QUEUE.ITEM_NAME
, ITEM_QUEUE.STATUS
, ITEM_QUEUE.ACTIVE_DATE,

CASE ITEM_QUEUE.STATUS
    WHEN 1 THEN '入力中'
    WHEN 2 THEN '承認依頼中'
    WHEN 3 THEN '承認済み'
    WHEN 4 THEN '研究用'
    ELSE NULL
END STATUS_NAME

, DECODE(ITEM_QUEUE.VERSION, ITEM.VERSION, '○', '×') ACTIVATE
, ITEM_QUEUE.ITEM_TYPE
, ITEM_QUEUE.ITEM_SUB_NAME
, ITEM_QUEUE.PRODUCT_DIVISION
, ITEM_QUEUE.ARTICLE_DIVISION
, ITEM_QUEUE.PURCHASE_DIVISION
, ITEM_QUEUE.PARENT_ITEM_CD
, PARENT_ITEM_NAME
, ITEM_QUEUE.ITEM_CATEGORY
, ITEM_CATEGORY_NAME
, ITEM_QUEUE.PHANTOM_DIVISION
, ITEM_QUEUE.SPOT_DIVISION
, ITEM_QUEUE.STOCK_DIVISION
, ITEM_QUEUE.BULK_DIVISION
, ITEM_QUEUE.DEFAULT_LOCATION
, DEFAULT_LOCATION.LOCATION_NAME DEFAULT_LOCATION_NAME
, ITEM_QUEUE.COST_DIVISION
, ITEM_QUEUE.LOT_DIVISION
, ITEM_QUEUE.NEW_FLG
, ITEM_QUEUE.RESEARCH_ITEM
, ITEM_QUEUE.SHIPPER_DIVISION
, ITEM_QUEUE.TYPE_DIVISION
, ITEM_QUEUE.OTHER_COMPANY_CD1
, ITEM_QUEUE.ORDER_LOCATION
, ORDER_LOCATION.LOCATION_NAME ORDER_LOCATION_NAME
, ITEM_QUEUE.STYLE_OF_PACKING
, ITEM_QUEUE.NUMBER_OF_INSERTIONS
, ITEM_QUEUE.ALL_UP_WEIGHT
, ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT
, OPERATION_MANAGEMENT.NAME01 OPERATION_MANAGEMENT_NAME
, ITEM_QUEUE.UNIT_OF_STOCK_CONTROL
, STOCK_CONTROL.NAME01 UNIT_OF_STOCK_CONTROL_NAME
, ITEM_QUEUE.KG_OF_FRACTION_MANAGEMENT
, ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT
, FRACTION_MANAGEMENT.NAME01 FRACTION_MANAGEMENT_NAME
, ITEM_QUEUE.KG_CONVERSION_COEFFICIENT
, ITEM_QUEUE.WATER_DIVISION
, ITEM_QUEUE.INPUT_DATE
, ITEM_QUEUE.INPUTOR_CD
, INPUTOR.TANTO_NM INPUTOR_NAME
, ITEM_QUEUE.UPDATE_DATE
, ITEM_QUEUE.UPDATOR_CD
, UPDATOR.TANTO_NM UPDATOR_NAME
, ITEM_QUEUE.DEVELOPMENT_REQUEST_NO

FROM

(SELECT ITEM_QUEUE.ITEM_CD, ITEM_QUEUE.VERSION, ITEM_NAME, STATUS, ACTIVE_DATE, OTHER_COMPANY_CD1, PARENT_ITEM_CD,

(SELECT ITEM_NAME
FROM ITEM_QUEUE PARENT_ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM_QUEUE
GROUP BY ITEM_CD) MAX_ITEM

WHERE PARENT_ITEM.ITEM_CD = MAX_ITEM.ITEM_CD
AND PARENT_ITEM.VERSION = MAX_ITEM.VERSION
AND PARENT_ITEM.ITEM_CD = ITEM_QUEUE.PARENT_ITEM_CD) PARENT_ITEM_NAME

, ITEM_TYPE
, ITEM_SUB_NAME
, PRODUCT_DIVISION
, ARTICLE_DIVISION
, PURCHASE_DIVISION
, ITEM_CATEGORY
, PHANTOM_DIVISION
, SPOT_DIVISION
, STOCK_DIVISION
, BULK_DIVISION
, DEFAULT_LOCATION
, COST_DIVISION
, LOT_DIVISION
, NEW_FLG
, RESEARCH_ITEM
, SHIPPER_DIVISION
, TYPE_DIVISION
, ORDER_LOCATION
, STYLE_OF_PACKING
, NUMBER_OF_INSERTIONS
, ALL_UP_WEIGHT
, UNIT_OF_OPERATION_MANAGEMENT
, UNIT_OF_STOCK_CONTROL
, KG_OF_FRACTION_MANAGEMENT
, UNIT_OF_FRACTION_MANAGEMENT
, KG_CONVERSION_COEFFICIENT
, WATER_DIVISION
, INPUT_DATE
, INPUTOR_CD
, UPDATE_DATE
, UPDATOR_CD
, DEVELOPMENT_REQUEST_NO

FROM ITEM_QUEUE) ITEM_QUEUE
, ITEM
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE
, ITEM_CATEGORY
, LOCATION DEFAULT_LOCATION
, LOCATION ORDER_LOCATION
, NAMES OPERATION_MANAGEMENT
, NAMES STOCK_CONTROL
, NAMES FRACTION_MANAGEMENT
, LOGIN INPUTOR
, LOGIN UPDATOR

, (SELECT ITEM_CD, MIN(ACTIVE_DATE) ACTIVE_DATE
FROM ITEM_QUEUE
WHERE TO_CHAR(SYSDATE, 'YYYY/MM/DD') <= ACTIVE_DATE
GROUP BY ITEM_CD) MAX_ITEM

WHERE ITEM_QUEUE.ITEM_CD IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (ITEM_QUEUE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_QUEUE.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhParentItemCd != null) && (condition.srhParentItemCd != "")*/
AND (ITEM_QUEUE.PARENT_ITEM_CD LIKE /*condition.srhParentItemCd*/'%' OR PARENT_ITEM_NAME LIKE /*condition.srhParentItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhStatus != 0)*/
AND ITEM_QUEUE.STATUS = /*condition.srhStatus*/1
/*END*/

/*IF (condition.srhDetailStatus != 0)*/
AND (ARTICLE.STATUS = /*condition.srhDetailStatus*/1
OR PRODUCT.STATUS = /*condition.srhDetailStatus*/1
OR PURCHASE.STATUS = /*condition.srhDetailStatus*/1)
/*END*/

/*IF (condition.strSrhActiveDateFrom != null) && (condition.strSrhActiveDateFrom != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') >= /*condition.strSrhActiveDateFrom*/'2007/07/01'
/*END*/

/*IF (condition.strSrhActiveDateTo != null) && (condition.strSrhActiveDateTo != "")*/
AND TO_CHAR(ITEM_QUEUE.ACTIVE_DATE, 'YYYY/MM/DD') <= /*condition.strSrhActiveDateTo*/'2007/07/31'
/*END*/

AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD
AND ITEM_QUEUE.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
AND MAX_ITEM.ACTIVE_DATE <= ITEM_QUEUE.ACTIVE_DATE
AND ITEM_QUEUE.ITEM_CATEGORY = ITEM_CATEGORY.ITEM_CATEGORY(+)
AND ITEM_QUEUE.DEFAULT_LOCATION = DEFAULT_LOCATION.LOCATION_CD(+)
AND ITEM_QUEUE.ORDER_LOCATION = ORDER_LOCATION.LOCATION_CD(+)
AND OPERATION_MANAGEMENT.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_OPERATION_MANAGEMENT = OPERATION_MANAGEMENT.NAME_CD(+)
AND STOCK_CONTROL.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_STOCK_CONTROL = STOCK_CONTROL.NAME_CD(+)
AND FRACTION_MANAGEMENT.NAME_DIVISION(+) = 'UNIT'
AND ITEM_QUEUE.UNIT_OF_FRACTION_MANAGEMENT = FRACTION_MANAGEMENT.NAME_CD(+)
AND ITEM_QUEUE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND ITEM_QUEUE.UPDATOR_CD = UPDATOR.TANTO_CD(+)
) ITEM_QUEUE

ORDER BY ITEM_QUEUE.ITEM_CD, ITEM_QUEUE.VERSION
