/*
 * 規格書一覧用SQL
 *
 * entityName=StandardSheet
 * packageName=master.standardsheet
 * methodName=getDetail
 *
 */
SELECT
    STD.STD_SHEET_CD AS STD_SHEET_CD,
    STD.STD_SHEET_NAME AS STD_SHEET_NAME,
    STD.ITEM_CD AS ITEM_CD,
    STD.CUSTOMER_CD AS CUSTOMER_CD,
    STD.DELIVERY_CD AS DELIVERY_CD,
    STD.LABEL_CD AS LABEL_CD,
    STD.LABEL_ADD_CD AS LABEL_ADD_CD,
    STD.INPUTOR_CD AS INPUTOR_CD,
    STD.INPUT_DATE AS INPUT_DATE,
    STD.UPDATOR_CD AS UPDATOR_CD,
    STD.UPDATE_DATE AS UPDATE_DATE,
    ITM.ITEM_NAME AS ITEM_NAME,
    VEN.VENDER_NAME AS VENDER_NAME,
    DEL.DELIVERY_NAME1 AS DELIVERY_NAME1
FROM
    LABEL LBL,
    DELIVERY DEL,
    VENDER VEN,
    ITEM ITM,
    STANDARD_SHEET STD
WHERE
/*IF (( stdSheetCd != null ) && ( stdSheetCd != "" ))*/
    STD.STD_SHEET_CD = /*stdSheetCd*/'' AND
/*END*/
	ITM.ITEM_CD = STD.ITEM_CD
AND	VEN.VENDER_DIVISION(+) = 'TS'
AND	VEN.VENDER_CD(+) = STD.CUSTOMER_CD
AND	DEL.DELIVERY_CD(+) = STD.DELIVERY_CD
AND	LBL.LABEL_CD(+) = STD.LABEL_CD
