/*
 * 帳合マスタ一覧詳細用SQL
 *
 * entityName=BalanceListDetail
 * packageName=balancelistdetail
 * methodName=getEntity
 *
 */

SELECT PARENT_BALANCE_CD
, /*balanceType*/1 BALANCE_TYPE

, CASE /*balanceType*/1
	WHEN 1 THEN '油脂'
    WHEN 2 THEN '化成品'
    ELSE NULL
END BALANCE_TYPE_NAME

, MAX(DECODE(ROWNUM, 1, VENDER_CD, NULL)) VENDER_CD1
, MAX(DECODE(ROWNUM, 1, VENDER_SHORTED_NAME, NULL)) VENDER_NAME1
, SUBSTR(MAX(DECODE(ROWNUM, 1, VENDER_SHORTED_NAME, NULL)), 0, 7) SHORT_VENDER_NAME1

, MAX(DECODE(ROWNUM, 2, VENDER_CD, NULL)) VENDER_CD2
, MAX(DECODE(ROWNUM, 2, VENDER_SHORTED_NAME, NULL)) VENDER_NAME2
, SUBSTR(MAX(DECODE(ROWNUM, 2, VENDER_SHORTED_NAME, NULL)), 0, 7) SHORT_VENDER_NAME2

, MAX(DECODE(ROWNUM, 3, VENDER_CD, NULL)) VENDER_CD3
, MAX(DECODE(ROWNUM, 3, VENDER_SHORTED_NAME, NULL)) VENDER_NAME3
, SUBSTR(MAX(DECODE(ROWNUM, 3, VENDER_SHORTED_NAME, NULL)), 0, 7) SHORT_VENDER_NAME3

, MAX(DECODE(ROWNUM, 4, VENDER_CD, NULL)) VENDER_CD4
, MAX(DECODE(ROWNUM, 4, VENDER_SHORTED_NAME, NULL)) VENDER_NAME4
, SUBSTR(MAX(DECODE(ROWNUM, 4, VENDER_SHORTED_NAME, NULL)), 0, 7) SHORT_VENDER_NAME4

, MAX(DECODE(ROWNUM, 5, VENDER_CD, NULL)) VENDER_CD5
, MAX(DECODE(ROWNUM, 5, VENDER_SHORTED_NAME, NULL)) VENDER_NAME5
, SUBSTR(MAX(DECODE(ROWNUM, 5, VENDER_SHORTED_NAME, NULL)), 0, 7) SHORT_VENDER_NAME5

, MAX(SHOP_LEVEL) SHOP_LEVEL
, MAX(A.INPUT_DATE) INPUT_DATE
, MAX(A.INPUTOR_CD) INPUTOR_CD
, MAX(INPUTOR.TANTO_NM) INPUTOR_NAME
, MAX(A.UPDATE_DATE) UPDATE_DATE
, MAX(A.UPDATOR_CD) UPDATOR_CD
, MAX(UPDATOR.TANTO_NM) UPDATOR_NAME

FROM

(SELECT DISTINCT LEVEL
, /*balanceCd*/'%' PARENT_BALANCE_CD
, BALANCE.BALANCE_CD
, BALANCE.VENDER_CD
, VENDER.VENDER_SHORTED_NAME
, BALANCE.UPPER_BALANCE_CD
, BALANCE.SHOP_LEVEL
, BALANCE.BALANCE_TYPE
, BALANCE.INPUT_DATE
, BALANCE.INPUTOR_CD
, BALANCE.UPDATE_DATE
, BALANCE.UPDATOR_CD
FROM BALANCE, VENDER
WHERE VENDER.VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)
START WITH BALANCE.BALANCE_CD = /*balanceCd*/'%'
CONNECT BY PRIOR BALANCE.UPPER_BALANCE_CD = BALANCE.BALANCE_CD
ORDER BY LEVEL DESC) A
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE A.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND A.UPDATOR_CD = UPDATOR.TANTO_CD(+)

GROUP BY PARENT_BALANCE_CD


