/*
 * カレンダーマスタ詳細用SQL
 *
 * entityName=CalDetailList
 * packageName=caldetaillist
 * methodName=getList
 *
 */

SELECT CAL_CD, CAL_NAME, CAL_YEAR, TO_CHAR(CAL_DATE, 'YYYY') CAL_YYYY, TO_CHAR(CAL_DATE, 'MM') CAL_MM,
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '01', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '02', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '03', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '04', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '05', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '06', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '07', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '08', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '09', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '10', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '11', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '12', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '13', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '14', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '15', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '16', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '17', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '18', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '19', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '20', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '21', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '22', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '23', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '24', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '25', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '26', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '27', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '28', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '29', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '30', CAL_HOLIDAY, 0)) ||
SUM(DECODE(TO_CHAR(CAL_DATE, 'DD'), '31', CAL_HOLIDAY, 0)) CAL_DD
FROM CAL
WHERE CAL_CD = /*calCd*/'%'
AND CAL_YEAR = /*calYear*/2009
GROUP BY CAL_CD, CAL_NAME, CAL_YEAR, TO_CHAR(CAL_DATE, 'YYYY'), TO_CHAR(CAL_DATE, 'MM')
ORDER BY TO_CHAR(CAL_DATE, 'YYYY'), TO_CHAR(CAL_DATE, 'MM')
