/*
 * ロケーション帳票用SQL
 *
 * entityName=LocationListForReport
 * packageName=locationlistforreport
 * methodName=getListForReport
 *
 */

SELECT LOCATION.*
, UPPER_LOCATION.LOCATION_NAME UPPER_LOCATION_NAME
, BUMON.SECTION_NAME
, LOGIN.TANTO_NM
, ITEM_QUEUE.ITEM_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME
, NAMES.NAME01

FROM LOCATION
, BUMON
, LOCATION UPPER_LOCATION
, LOGIN
, VALID_ITEM_QUEUE ITEM_QUEUE
, LOGIN INPUTOR
, LOGIN UPDATOR
, NAMES

WHERE LOCATION.LOCATION_CD IS NOT NULL

/*IF (condition.srhLocationCd != null) && (condition.srhLocationCd != "")*/
AND (LOCATION.LOCATION_CD LIKE /*condition.srhLocationCd*/'%' OR LOCATION.LOCATION_NAME LIKE /*condition.srhLocationCd*/'%')
/*END*/

AND LOCATION.UPPER_LOCATION_CD = UPPER_LOCATION.LOCATION_CD(+)
AND LOCATION.SECTION_CD = BUMON.SECTION_CD(+)
AND LOCATION.TANTO_CD = LOGIN.TANTO_CD(+)
AND LOCATION.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND LOCATION.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND LOCATION.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND NAMES.NAME_DIVISION(+) = 'TANA'
AND LOCATION.COUNT_DIVISION = NAMES.NAME_CD(+)

ORDER BY LOCATION.LOCATION_CD
