/*
 * 品目別引当明細照会手持在庫数取得用SQL
 *
 * ENTITYNAME=INVENTORYDRAWINGTOTALQTY
 * PACKAGENAME=INVENTORYDRAWINGTOTALQTY
 * METHODNAME=GETTOTALQTY
 *
 */

SELECT 
	INVENTORY_QTY
,	BACKORDER_QTY
,	FINISH_QTY
,	INSPECTION_QTY
,	ASSIGN_QTY
,	SALES_ASSIGN_QTY
-- 2021/3/1 セッツ様からの要望で発注残数を利用可能数に計上しない様に修正
--,	INVENTORY_QTY + BACKORDER_QTY + FINISH_QTY + INSPECTION_QTY + ASSIGN_QTY + SALES_ASSIGN_QTY USEPOSSIBLE_QTY
,	INVENTORY_QTY + FINISH_QTY + INSPECTION_QTY + ASSIGN_QTY + SALES_ASSIGN_QTY USEPOSSIBLE_QTY
,	UNIT_OF_OPERATION_MANAGEMENT,

CASE TYPE_DIVISION
    WHEN 1 THEN N'Kg'
    WHEN 3 THEN N'Kg'
    ELSE NAME01
END NAME01

FROM ITEM_INVENTORY, ITEM, NAMES,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM
GROUP BY ITEM_CD) MAX_ITEM

WHERE ITEM_INVENTORY.ITEM_CD IS NOT NULL

/*IF(ITEMCD != NULL) && (ITEMCD != "")*/
AND (ITEM_INVENTORY.ITEM_CD = /*ITEMCD*/'%' OR ITEM_NAME = /*ITEMCD*/'%')
/*END*/

/*IF(OTHERCOMPANYCD1 != NULL) && (OTHERCOMPANYCD1 != "")*/
AND	ITEM.OTHER_COMPANY_CD1 = /*OTHERCOMPANYCD1*/'%'
/*END*/

AND ITEM_INVENTORY.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND MAX_ITEM.ITEM_CD = ITEM.ITEM_CD(+)
AND MAX_ITEM.VERSION = ITEM.VERSION(+)
AND NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_OPERATION_MANAGEMENT = NAME_CD(+)
