/*
 * 備考詳細用SQL
 *
 * entityName=RemarkDetail
 * packageName=remarkdetail
 * methodName=getEntity
 *
 */

SELECT REMARK.REMARK_NO, REMARK.VENDER_DIVISION, REMARK.VENDER_CD, REMARK.DELIVERY_CD, REMARK.ITEM_CD,
REMARK.REMARK01, REMARK.REMARK11, REMARK.REMARK12, REMARK.REMARK13, REMARK.REMARK06, REMARK.REMARK15, 
REMARK.REMARK16, VENDER_NAME1,
DELIVERY_NAME1, OTHER_COMPANY_CD1, ITEM_NAME, REMARK.UPDATE_DATE
FROM REMARK, VENDER, DELIVERY, VALID_ITEM_QUEUE ITEM_QUEUE
WHERE REMARK_NO = /*remarkNo*/1
AND REMARK.VENDER_DIVISION = VENDER.VENDER_DIVISION(+)
AND REMARK.VENDER_CD = VENDER.VENDER_CD(+)
AND REMARK.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
AND REMARK.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
