/*
 * Created on 2009/02/17
 *
 * $copyright$
 *
*/

/**
 * 製品検査完了入力一覧取得用SQL
 *
 * @author tosco
 *
 * entityName=ProductInspectComp
 * packageName=productinspectcomp
 * methodName=getSearchList
 *
 */
SELECT	DIRECTION_HEADER.DIRECTION_DIVISION
,	DIRECTION_HEADER.DIRECTION_NO
,	DIRECTION_HEADER.DIRECTION_DATE
,	DIRECTION_HEADER.ASP_ORDER_NO
,	DIRECTION_HEADER.DIRECTION_STATUS
,	DIRECTION_HEADER.RECIPE_ID
,	DIRECTION_HEADER.RECIPE_CD
,	DIRECTION_HEADER.RECIPE_VERSION
,	DIRECTION_HEADER.PRODUCTION_LINE
,	DIRECTION_HEADER.COMPOUND_TANK_NO
,	DIRECTION_HEADER.HOLD_TANK_NO
,	DIRECTION_HEADER.DISSOLUTION_TANK_NO
,	DIRECTION_HEADER.FILLTANK_NO
,	DIRECTION_HEADER.PACKAGE_LINE
,	DIRECTION_HEADER.CURRENT_STEP_NO
,	DIRECTION_HEADER.ITEM_CD
,	DIRECTION_HEADER.PLANED_QTY
,	DIRECTION_HEADER.RESULT_QTY
,	DIRECTION_HEADER.DIVIDE_FLAG
,	DIRECTION_HEADER.NEXT_PLANED_QTY
,	DIRECTION_HEADER.PDW_RESULT
,	DIRECTION_HEADER.PEOCESS_LOSS
,	DIRECTION_HEADER.LOT_NO
,	DIRECTION_HEADER.PLANED_SDATE
,	DIRECTION_HEADER.PLANED_EDATE
,	DIRECTION_HEADER.RESULT_SDATE
,	DIRECTION_HEADER.RESULT_EDATE
,	DIRECTION_HEADER.STERIT_SDATE
,	DIRECTION_HEADER.STERIT_EDATE
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MIN
,	DIRECTION_HEADER.MEKKIN_TANK_TEMP_MAX
,	DIRECTION_HEADER.HAISUI_CHECK
,	DIRECTION_HEADER.STAMP_FLAG
,	DIRECTION_HEADER.STAMP_DATE
,	DIRECTION_HEADER.STAMP_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_LABEL_FLAG
,	DIRECTION_HEADER.PRODUCT_LABEL_DATE
,	DIRECTION_HEADER.PRODUCT_LABEL_TANTO_CD
,	DIRECTION_HEADER.PRODUCT_RECORD_FLAG
,	DIRECTION_HEADER.PRODUCT_RECORD_DATE
,	DIRECTION_HEADER.PRODUCT_RECORD_TANTO_CD
,	DIRECTION_HEADER.STOCKDISS_LABEL_FLAG
,	DIRECTION_HEADER.STOCKDISS_LABEL_DATE
,	DIRECTION_HEADER.STOCKDISS_LABEL_TANTO_CD
,	DIRECTION_HEADER.CERTIFICATION_FLAG
,	DIRECTION_HEADER.CERTIFICATION_DATE
,	DIRECTION_HEADER.REMARK
,	DIRECTION_HEADER.NOTES
,	DIRECTION_HEADER.DELETE_FLAG
,	DIRECTION_HEADER.SEIZOTANTOCODE
,	DIRECTION_HEADER.SENJOTANTOCODE
,	DIRECTION_HEADER.MEKKINTANTOCODE
,	DIRECTION_HEADER.CHOGOTANKCONDI
,	DIRECTION_HEADER.YOBIYOKAICONDI
,	DIRECTION_HEADER.HOLDTANKCONDI
,	DIRECTION_HEADER.TOTAL_JOBTIME
,	DIRECTION_HEADER.ENPLOY_JOBTIME
,	DIRECTION_HEADER.COOPER_JOBTIME
,	DIRECTION_HEADER.APP_TANTO_CD
,	DIRECTION_HEADER.APP_DATE
,	DIRECTION_HEADER.LAST_APP_TANTO_CD
,	DIRECTION_HEADER.LAST_APP_DATE
,	DIRECTION_HEADER.INPUT_DATE
,	DIRECTION_HEADER.INPUTOR_CD
,	DIRECTION_HEADER.UPDATE_DATE
,	DIRECTION_HEADER.UPDATOR_CD

,	ITEM_NAMES.ITEM_NAME
,	ITEM_NAMES.UNIT_OF_OPERATION_MANAGEMENT
,	LINE.PRODUCTION_LINE_NAME
,	OPERATION.OPERATION_NAME
,	UNIT_NAMES.NAME01 as UNIT_NAME
,	LINE.PRODUCTION_LINE_NAME as LINE_NAME
,	RECIPE_RESOUCE.RESOUCE_NAME
,	LOT_INVENTORY.LOT_INVENTORY_QTY
FROM	DIRECTION_HEADER
,	(SELECT
	    ITEM2.ITEM_CD ,
	    ITEM2.ITEM_NAME,
	    ITEM2.OTHER_COMPANY_CD1,
	    ITEM2.UNIT_OF_OPERATION_MANAGEMENT
	FROM
	    VALID_ITEM_QUEUE MAX_ITEM
	,   VALID_ITEM_QUEUE  ITEM2
	WHERE
	    ITEM2.ITEM_CD = MAX_ITEM.ITEM_CD AND
	    ITEM2.VERSION = MAX_ITEM.VERSION
	) ITEM_NAMES
,	(SELECT	NAMES.NAME_CD
	,	NAMES.NAME01
	FROM	NAMES
	WHERE	NAMES.NAME_DIVISION = 'UNIT'　--運用管理単位のため'UNIT'固定
	)UNIT_NAMES
,	LINE
,	OPERATION
,	RECIPE_RESOUCE
,	(SELECT ITEM_CD,
			LOT_NO, 
			SUM(NVL(INVENTORY_QTY, 0) + NVL(INSPECTION_QTY, 0)) LOT_INVENTORY_QTY
		FROM LOT_INVENTORY
		WHERE LOCATION_CD IS NOT NULL
/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
		AND	LOT_INVENTORY.LOT_NO LIKE /*condition.srhDirectionNo*/
/*END*/
/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
		AND	LOT_INVENTORY.ITEM_CD LIKE /*condition.srhItemCd*/
/*END*/
		GROUP BY ITEM_CD, LOT_NO
     ) LOT_INVENTORY
WHERE	DIRECTION_HEADER.DIRECTION_DIVISION IN ('2','3')
AND		DIRECTION_HEADER.DIRECTION_STATUS IN('5','6')

AND		DIRECTION_HEADER.ITEM_CD = ITEM_NAMES.ITEM_CD(+)
AND		DIRECTION_HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND		DIRECTION_HEADER.CURRENT_STEP_NO = OPERATION.OPERATION_CD(+)
AND		ITEM_NAMES.UNIT_OF_OPERATION_MANAGEMENT = UNIT_NAMES.NAME_CD(+)
AND		DIRECTION_HEADER.PACKAGE_LINE = RECIPE_RESOUCE.RESOUCE_CD(+)
AND		DIRECTION_HEADER.ITEM_CD = LOT_INVENTORY.ITEM_CD(+)
AND		DIRECTION_HEADER.DIRECTION_NO = LOT_INVENTORY.LOT_NO(+)

/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
	AND	DIRECTION_HEADER.DIRECTION_NO LIKE /*condition.srhDirectionNo*/
/*END*/

/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	/*IF (condition.srhProductionLine != "0")*/
			AND	DIRECTION_HEADER.PRODUCTION_LINE = /*condition.srhProductionLine*/
	/*END*/		
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	DIRECTION_HEADER.ITEM_CD LIKE /*condition.srhItemCd*/
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/
/*END*/

/*IF (( condition.srhResultSdateFrom != null ) && ( condition.srhResultSdateFrom != "" ))*/
	AND	DIRECTION_HEADER.RESULT_SDATE >= /*condition.srhResultSdateFrom*/
/*END*/

/*IF (( condition.srhResultSdateTo != null ) && ( condition.srhResultSdateTo != "" ))*/
	AND	DIRECTION_HEADER.RESULT_SDATE <= /*condition.srhResultSdateTo*/
/*END*/

/*IF (( condition.srhResultEdateFrom != null ) && ( condition.srhResultEdateFrom != "" ))*/
	AND	DIRECTION_HEADER.RESULT_EDATE >= /*condition.srhResultEdateFrom*/
/*END*/

/*IF (( condition.srhResultEdateTo != null ) && ( condition.srhResultEdateTo != "" ))*/
	AND	DIRECTION_HEADER.RESULT_EDATE <= /*condition.srhResultEdateTo*/
/*END*/

/*IF (( condition.srhDirectionStatus != null ) && ( condition.srhDirectionStatus != "" ))*/
	/*IF (condition.srhDirectionStatus == "0")*/
			AND	DIRECTION_HEADER.DIRECTION_STATUS IN ('5','6')
	/*END*/
	/*IF (condition.srhDirectionStatus != "0")*/
			AND	DIRECTION_HEADER.DIRECTION_STATUS = /*condition.srhDirectionStatus*/
	/*END*/		
/*END*/

/*IF (( condition.srhPackageLine != null ) && ( condition.srhPackageLine != "" ))*/
	AND	DIRECTION_HEADER.PACKAGE_LINE LIKE /*condition.srhPackageLine*/
/*END*/

/*IF (( condition.srhCertificationDate != null ) && ( condition.srhCertificationDate != "" ))*/
	AND	TO_CHAR(DIRECTION_HEADER.CERTIFICATION_DATE,'YYYY/MM/DD') = /*condition.srhCertificationDate*/
/*END*/

/*IF (( condition.srhLotNo != null ) && ( condition.srhLotNo != "" ))*/
	AND	DIRECTION_HEADER.LOT_NO LIKE /*condition.srhLotNo*/
/*END*/

ORDER BY	DIRECTION_HEADER.RESULT_SDATE
,			DIRECTION_HEADER.DIRECTION_NO
