/**
 * @author t1344224
 *
 * entityName=BuyingListForReport
 * packageName=buyingforreport
 * methodName=getReportList
 *
 */
SELECT 
	PSUB.PURCHASE_NO
,	PSUB.BUY_SUBCONTRACT_ORDER_NO
,	PSUB.ORDER_DIVIDE_NO
,	PSUB.ORDER_NO
,	PSUB.ORDER_ROW_NO
,	PSUB.ASP_ORDER_NO
,	PSUB.MATERIAL_DIVISION
,	PSUB.SI_ORDER_NO
,	PSUB.ORDER_DATE
,	PSUB.CHARGE_ORGANIZATION_CD
,	CHARGE_ORGANIZATION.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME
,	PSUB.ORGANIZATION_CD
,	ORGANIZATION.ORGANIZATION_NAME
,	PSUB.TANTO_CD
,	TANTO.TANTO_NM AS TANTO_NAME
,	PSUB.ORDER_DIVISION
,	PSUB.VENDER_CD
,	VENDER_NAME.VENDER_NAME1
,	VENDER_NAME.VENDER_SHORTED_NAME
,	PSUB.ITEM_CD
,	DECODE(PSUB.ORDER_DIVISION, 4, PSUB.ITEM_NAME, ITEM_MAIN.ITEM_NAME) AS ITEM_NAME
,	ITEM_MAIN.STYLE_OF_PACKING
,	ITEM_MAIN.OTHER_COMPANY_CD1
,	NAME.NAME01
,	PSUB.ORDER_QUANTITY
,	PSUB.ORDER_CONVERT_QUANTITY
,	PSUB.ORDER_UNITPRICE
,	PSUB.UNITPRICE_DEFINEUNIT
,	PSUB.SUPPLIER_ORD_AMOUNT
,	PSUB.SUGGESTED_DELIVERLIMIT_DATE
,	PSUB.ORDER_SHEET_REMARK
,	PSUB.REMARK
,	PSUB.NOTES
,	PSUB.LOCATION_CD
,	LOCATION.LOCATION_NAME
,	PSUB.STATUS
,	PSUB.ORDER_SHEET_NO
,	PSUB.ORDER_SHEE_FLAG
,	PSUB.ORDER_SHEE_DATE
,	PSUB.ORDER_SHEEL_TANTO_CD
,	ORDER_SHEEL_TANTO.TANTO_NM AS ORDER_SHEEL_TANTO_NAME
,	PSUB.GOOD_HOUSING_SUM
,	PSUB.REPLY_CONTENTS_DIVISION
,	CASE PSUB.REPLY_CONTENTS_DIVISION
		WHEN 0 THEN '無'
		WHEN 1 THEN '有'
	END AS REPLY_CONTENTS_DIVISION_NAME
,	PSUB.DELIVERY_COMP
,	PSUB.NEXT_DELIVERLIMIT_DATE
,	PSUB.DATA_TYPE
,	PSUB.DATA_TOTAL_DIVISION
,	PSUB.CATEGORY_DIVISION
,	CATEGORY_DIVISION_NAMES.CATEGORY_NAME
,	PSUB.STOCKING_DATE
,	PSUB.ACCOUNT_YEARS
,	PSUB.SLIP_NO
,	PSUB.ROW_NO
,	PSUB.CANCEL_SLIP_NO
,	PSUB.CANCEL_ROW_NO
,	PSUB.SUPPLIER_LOTNO
,	PSUB.LOT_NO
,	PSUB.STOCK_LOCATION_CD
,	STOCK_LOCATION.LOCATION_NAME AS STOCK_LOCATION_NAME
,	PSUB.HOUSING_LOCATION_CD
,	HOUSING_LOCATION.LOCATION_NAME AS HOUSING_LOCATION_NAME
,	PSUB.ARRIVAL_QUANTITY
,	PSUB.STOCK_QUANTITY
,	PSUB.ACCEPT_QUANTITY
,	PSUB.ACCEPT_CONVERT_QUANTITY
,	PSUB.INCREASE_QUANTITY
,	PSUB.STOCKING_QUANTITY
,	PSUB.HOUSING_UNITPRICE
,	PSUB.FARE_AMOUNT
,	PSUB.STOCKING_AMOUNT
,	PSUB.ACCEPT_DATE
,	PSUB.ORDER_SHEET_REMARK2
,	PSUB.REMARK2
,	PSUB.NOTES2
,	PSUB.STATUS2
,	PSUB.TAX_DIVISION
,	PSUB.TAX_AMOUNT

,	PSUB.TAX_CD

,	PSUB.PAYEE_CD
,	PSUB.ACCOUNT_DEBIT_SECTION_CD
,	ACCOUNT_DEBIT_SECTION.SECTION_NAME AS ACCOUNT_DEBIT_SECTION_NAM
,	PSUB.ACCOUNT_CREDIT_SECTION_CD
,	ACCOUNT_CREDIT_SECTION.SECTION_NAME AS ACCOUNT_CREDIT_SECTION_NAME
,	PSUB.DEBIT_TITLE_CD
,	DEBIT_TITLE_CD.ACCOUNTS_NAME AS DEBIT_TITLE_NAME
,	PSUB.DEBIT_SUB_TITLE_CD
,	DEBIT_SUB_TITLE_CD.ACCOUNTS_NAME AS DEBIT_SUB_TITLE_NAME
,	PSUB.CREDIT_TITLE_CD
,	CREDIT_TITLE_CD.ACCOUNTS_NAME AS CREDIT_TITLE_NAME
,	PSUB.CREDIT_SUB_TITLE_CD
,	CREDIT_SUB_TITLE_CD.ACCOUNTS_NAME AS CREDIT_SUB_TITLE_NAME
,	PSUB.PAYABLE_TARGET_DIVISION
,	PSUB.PAYMENT_TARGET_DIVISION
,	PSUB.PAYABLE_UPDATE_DIVISION
,	PSUB.PAYABLE_NO
,	PSUB.PAYMENT_UPDATE_DIVISION
,	PSUB.PAYMENT_NO
,	PSUB.SUMMARY_CD
,	PSUB.SUMMARY
,	PSUB.PAYMENT_UPDATE_DATE
,	PSUB.PAYABLE_UPDATE_DATE
,	PSUB.TRANSMISSION_DATE
,	PSUB.LABEL_FLAG
,	PSUB.LABEL_DATE
,	PSUB.LABEL_TANTO_CD
,	LABEL_TANTO.TANTO_NM AS LABEL_TANTO_NAME
,	PSUB.TMP_UNITPRICE_FLG
,	PSUB.INSPECT_METHOD
,	PSUB.MORTGAGE_DETAIL_FLG
,	PSUB.INSPRECEIPT_WAIT_QUANTITY
,	PSUB.BAD_QUANTITY
,	PSUB.COST_ENTRY
,	PSUB.ADV_PUR_NOTICE_DECIDE_DIVISION
,	PSUB.ORDER_MORTGAGED_QUANTITY
,	PSUB.SUM_HOUSING_CONVERT_QUANT
,	PSUB.INSPECT_WAIT_CONVERT_QUANTITY
,	PSUB.EXTRACTIONS_QUANTITY
,	PSUB.DEFECTIVE_QUANTITY
,	PSUB.CHECK_TANTO_CD
,	CHECK_TANTO.TANTO_NM AS CHECK_TANTO_NAME
,	PSUB.LABORATORY_METHOD
,	PSUB.PROVISION_DIVISION
,	PSUB.CHECK_DATE
,	PSUB.TAX_RATIO
,	PSUB.CHECK_QUANTITY
,	PSUB.SLIP_ISSUE_DIVISION
,	PSUB.SLIP_ISSUE_DATE
,	PSUB.APPROVAL_STATUS
,	PSUB.APPROVEDBY
,	PSUB.APPROVALDATE
,	(CASE
		WHEN PSUB.ORDER_DIVISION IN (1, 2, 3, 6) THEN LOC.LOCATION_NAME
		WHEN PSUB.ORDER_DIVISION IN (4) THEN NVL(DEL.DELIVERY_NAME1, LOC.LOCATION_NAME)
		WHEN PSUB.ORDER_DIVISION IN (5) THEN DEL.DELIVERY_NAME1
		ELSE NULL
	END ) AS DELIVERY_NAME

,	PSUB.INPUT_DATE
,	PSUB.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	PSUB.UPDATE_DATE
,	PSUB.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
FROM
	PURCHASE_SUBCONTRACT PSUB
	LEFT JOIN (SELECT 
			VENDER_CD,VENDER_NAME1,VENDER_SHORTED_NAME
			FROM VENDER
			WHERE VENDER_DIVISION = 'SI'
		)VENDER_NAME	ON PSUB.VENDER_CD	= VENDER_NAME.VENDER_CD
	LEFT JOIN LOGIN		ON PSUB.TANTO_CD	= LOGIN.TANTO_CD
	LEFT JOIN ORGANIZATION	ON PSUB.ORGANIZATION_CD	= ORGANIZATION.ORGANIZATION_CD
	LEFT JOIN (	SELECT
				    ITEM2.ITEM_CD ,
				    ITEM2.ITEM_NAME,
				    ITEM2.UNIT_OF_OPERATION_MANAGEMENT,	
				    ITEM2.SPOT_DIVISION,
				    ITEM2.OTHER_COMPANY_CD1,
				    ITEM2.STYLE_OF_PACKING
				FROM
					VALID_ITEM_QUEUE ITEM2
				) ITEM_MAIN
		ON PSUB.ITEM_CD		= ITEM_MAIN.ITEM_CD
	LEFT JOIN (SELECT
			CATEGORY_DIVISION, CATEGORY_NAME
			FROM CLASSIFICATION
			WHERE DATA_TYPE = 3
		)CATEGORY_DIVISION_NAMES ON PSUB.CATEGORY_DIVISION = CATEGORY_DIVISION_NAMES.CATEGORY_DIVISION
	LEFT JOIN LOGIN INPUTOR ON PSUB.INPUTOR_CD = INPUTOR.TANTO_CD
	LEFT JOIN LOGIN UPDATOR ON PSUB.UPDATOR_CD = UPDATOR.TANTO_CD
	LEFT JOIN ORGANIZATION CHARGE_ORGANIZATION ON PSUB.CHARGE_ORGANIZATION_CD = CHARGE_ORGANIZATION.ORGANIZATION_CD
	LEFT JOIN LOGIN TANTO ON PSUB.TANTO_CD = TANTO.TANTO_CD
	LEFT JOIN LOCATION ON PSUB.LOCATION_CD = LOCATION.LOCATION_CD
	LEFT JOIN LOGIN ORDER_SHEEL_TANTO ON PSUB.ORDER_SHEEL_TANTO_CD = ORDER_SHEEL_TANTO.TANTO_CD
	LEFT JOIN LOCATION STOCK_LOCATION ON PSUB.STOCK_LOCATION_CD = STOCK_LOCATION.LOCATION_CD
	LEFT JOIN LOCATION HOUSING_LOCATION ON PSUB.HOUSING_LOCATION_CD = HOUSING_LOCATION.LOCATION_CD
	LEFT JOIN BUMON ACCOUNT_DEBIT_SECTION ON PSUB.ACCOUNT_DEBIT_SECTION_CD = ACCOUNT_DEBIT_SECTION.SECTION_CD
	LEFT JOIN BUMON ACCOUNT_CREDIT_SECTION ON PSUB.ACCOUNT_CREDIT_SECTION_CD = ACCOUNT_CREDIT_SECTION.SECTION_CD
	LEFT JOIN ACCOUNTS DEBIT_TITLE_CD ON PSUB.DEBIT_TITLE_CD = DEBIT_TITLE_CD.ACCOUNTS_CD
	LEFT JOIN ACCOUNTS DEBIT_SUB_TITLE_CD ON PSUB.DEBIT_SUB_TITLE_CD = DEBIT_SUB_TITLE_CD.ACCOUNTS_CD
	LEFT JOIN ACCOUNTS CREDIT_TITLE_CD ON PSUB.CREDIT_TITLE_CD = CREDIT_TITLE_CD.ACCOUNTS_CD
	LEFT JOIN ACCOUNTS CREDIT_SUB_TITLE_CD ON PSUB.CREDIT_SUB_TITLE_CD = CREDIT_SUB_TITLE_CD.ACCOUNTS_CD
	LEFT JOIN LOGIN LABEL_TANTO ON PSUB.LABEL_TANTO_CD = LABEL_TANTO.TANTO_CD
	LEFT JOIN LOGIN CHECK_TANTO ON PSUB.CHECK_TANTO_CD = CHECK_TANTO.TANTO_CD
	LEFT JOIN DELIVERY DEL ON PSUB.LOCATION_CD =  DEL.DELIVERY_CD
	LEFT JOIN LOCATION LOC ON PSUB.LOCATION_CD = LOC.LOCATION_CD
	LEFT JOIN (SELECT * FROM NAMES WHERE NAMES.NAME_DIVISION(+) = 'UNIT') NAME ON NAME.NAME_CD = ITEM_MAIN.UNIT_OF_OPERATION_MANAGEMENT


WHERE
	PSUB.STATUS = '6'			
	AND PSUB.STATUS2 IS NOT NULL	


/*IF (( condition.srhSlipNo != null ) && ( condition.srhSlipNo != "" ))*/
	AND	PSUB.SLIP_NO LIKE /*condition.srhSlipNo*/''
/*END*/

/*IF ( condition.srhCategoryDivision != null )*/
	/*IF ( condition.srhCategoryDivision == "0") */
		/*IF ( condition.srhCancelCheck == true) */
			AND	SUBSTR(PSUB.CATEGORY_DIVISION,1,1) = '-'
		/*END*/
	/*END*/
	/*IF ( condition.srhCategoryDivision != "0") */
		/*IF ( condition.srhCancelCheck == true) */
			AND	PSUB.CATEGORY_DIVISION = /*condition.srhCancelCategoryDivision*/''
		/*END*/
		/*IF ( condition.srhCancelCheck == false) */
			AND	(PSUB.CATEGORY_DIVISION = /*condition.srhCategoryDivision*/''
			OR	PSUB.CATEGORY_DIVISION = /*condition.srhCancelCategoryDivision*/'')
		/*END*/
	/*END*/
/*END*/

/*IF (( condition.srhStockingDateFrom != null ) && ( condition.srhStockingDateFrom != "" ))*/
	AND	PSUB.STOCKING_DATE >= /*condition.srhStockingDateFrom*/''
/*END*/
/*IF (( condition.srhStockingDateTo != null ) && ( condition.srhStockingDateTo != "" ))*/
	AND	PSUB.STOCKING_DATE <= /*condition.srhStockingDateTo*/''
/*END*/
/*IF (( condition.srhVenderCd != null ) && ( condition.srhVenderCd != "" ))*/
	AND	PSUB.VENDER_CD LIKE /*condition.srhVenderCd*/''
/*END*/
/*IF (( condition.srhChargeOrganizationCd != null ) && ( condition.srhChargeOrganizationCd != "" ))*/
	AND	PSUB.CHARGE_ORGANIZATION_CD LIKE /*condition.srhChargeOrganizationCd*/''
/*END*/
/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	PSUB.ITEM_CD LIKE /*condition.srhItemCd*/''
/*END*/
/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_MAIN.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/''
/*END*/
/*IF (( condition.srhOrganizationCd != null ) && ( condition.srhOrganizationCd != "" ))*/
	AND	PSUB.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/''
/*END*/
/*IF (( condition.srhTantoCd != null ) && ( condition.srhTantoCd != "" ))*/
	AND	PSUB.TANTO_CD LIKE /*condition.srhTantoCd*/''
/*END*/
/*IF (( condition.srhStockingStatus != null ) && ( condition.srhStockingStatus != "" ) && ( condition.srhStockingStatus != "0" ))*/
	AND	PSUB.STATUS2 = /*condition.srhStockingStatus*/''
/*END*/
/*IF ( condition.srhMonthlyCheck == true )*/
	AND	(PSUB.PAYMENT_UPDATE_DIVISION='1' 
	OR	 PSUB.PAYABLE_UPDATE_DIVISION='1'
		)
/*END*/

/*IF ( condition.srhSlipIssueDivision == true )*/
		AND	PSUB.SLIP_ISSUE_DIVISION = 0
/*END*/

ORDER BY
	PSUB.STOCKING_DATE ASC,
	VENDER_NAME.VENDER_NAME1 ASC,
	PSUB.SLIP_NO ASC,
	PSUB.ROW_NO ASC	
