/*
 * 売掛残高帳票用SQL
 *
 * entityName=ArBalanceListForReport
 * packageName=arbalanceforreport
 * methodName=getListForReport
 *
 */

/*IF (condition.srhNormalFlg)*/
SELECT DEP_HED.*
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.VENDER_NAME1
, VENDER.VENDER_SHORTED_NAME

, NVL(DEP_HED.CREDIT_SALES_BREAKDOWN, 0)
- NVL(DEP_HED.CLAIM_FORWARD, 0) CLAIM_BALANCE --請求残高

, NVL(DEP_HED.DEPOSIT_AMOUNT, 0)
+ NVL(DEP_HED.OTHER_DEPOSIT_AMOUNT, 0) OTHER_DEPOSIT --画面用.入金・その他計

, NVL(DEP_HED.RETURNED_AMOUNT, 0)
+ NVL(DEP_HED.DISCOUNT_AMOUNT, 0)
+ NVL(DEP_HED.OTHER_SALES_AMOUNT, 0)
+ NVL(DEP_HED.OFFSET_AMOUNT, 0) OTHER_SALES --画面用.その他計

, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM DEPOSIT_HEADER DEP_HED
, ORGANIZATION
, VENDER
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE DEP_HED.ORGANIZATION_CD IS NOT NULL
AND TO_CHAR(DEP_HED.CREDIT_DATE,'YYYY/MM') = /*condition.srhTargetMonth*/'2009/06'
	
/*IF (condition.srhCreditAmountDivi == "1")*/ --出力区分：売掛残高有のみ（売掛残高が0以外）
AND DEP_HED.CREDIT_SALES_BREAKDOWN IS NOT NULL
AND DEP_HED.CREDIT_SALES_BREAKDOWN != 0
/*END*/

/*IF (condition.srhSectionCd != null && condition.srhSectionCd != "")*/
AND (DEP_HED.ORGANIZATION_CD LIKE /*condition.srhSectionCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhSectionCd*/'%')
/*END*/

/*IF (condition.srhTantoCd != null && condition.srhTantoCd != "")*/
AND (DEP_HED.INPUTOR_CD LIKE /*condition.srhTantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.srhTantoCd*/'%')
/*END*/

/*IF (condition.srhVenderCd != null && condition.srhVenderCd != "")*/
AND (DEP_HED.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

AND DEP_HED.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND DEP_HED.VENDER_CD = VENDER.VENDER_CD(+)
AND DEP_HED.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND DEP_HED.UPDATOR_CD = UPDATOR.TANTO_CD(+)

/*IF (!condition.srhTempClosingFlg)*/
ORDER BY DEP_HED.VENDER_CD
/*END*/

/*END*/

/*IF (condition.srhNormalFlg && condition.srhTempClosingFlg)*/
UNION
/*END*/

/*IF (condition.srhTempClosingFlg)*/
SELECT TMP_DEP_HED.*
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.VENDER_NAME1
, VENDER.VENDER_SHORTED_NAME

, NVL(TMP_DEP_HED.CREDIT_SALES_BREAKDOWN, 0)
- NVL(TMP_DEP_HED.CLAIM_FORWARD, 0) CLAIM_BALANCE --請求残高

, NVL(TMP_DEP_HED.DEPOSIT_AMOUNT, 0)
+ NVL(TMP_DEP_HED.OTHER_DEPOSIT_AMOUNT, 0) OTHER_DEPOSIT --画面用.入金・その他計

, NVL(TMP_DEP_HED.RETURNED_AMOUNT, 0)
+ NVL(TMP_DEP_HED.DISCOUNT_AMOUNT, 0)
+ NVL(TMP_DEP_HED.OTHER_SALES_AMOUNT, 0)
+ NVL(TMP_DEP_HED.OFFSET_AMOUNT, 0) OTHER_SALES --画面用.その他計

, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM TEMPORARY_DEPOSIT_HEADER TMP_DEP_HED
, ORGANIZATION
, VENDER
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE TMP_DEP_HED.ORGANIZATION_CD IS NOT NULL
AND TO_CHAR(TMP_DEP_HED.CREDIT_DATE,'YYYY/MM') = /*condition.srhTargetMonth*/'2009/06'

/*IF (condition.srhCreditAmountDivi == "1")*/ --出力区分：売掛残高有のみ（売掛残高が0以外）
AND	TMP_DEP_HED.CREDIT_SALES_BREAKDOWN IS NOT NULL
AND TMP_DEP_HED.CREDIT_SALES_BREAKDOWN != 0
/*END*/

/*IF (condition.srhSectionCd != null && condition.srhSectionCd != "")*/
AND (TMP_DEP_HED.ORGANIZATION_CD LIKE /*condition.srhSectionCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhSectionCd*/'%')
/*END*/

/*IF (condition.srhTantoCd != null && condition.srhTantoCd != "")*/
AND (TMP_DEP_HED.INPUTOR_CD LIKE /*condition.srhTantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.srhTantoCd*/'%')
/*END*/

/*IF (condition.srhVenderCd != null && condition.srhVenderCd != "")*/
AND (TMP_DEP_HED.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

AND TMP_DEP_HED.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND TMP_DEP_HED.VENDER_CD = VENDER.VENDER_CD(+)
AND TMP_DEP_HED.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND TMP_DEP_HED.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY TMP_DEP_HED.VENDER_CD

/*END*/
