/*
 * 支払残高帳票用SQL
 *
 * entityName=PaymentBalanceListForReport
 * packageName=paymentbalancelistforreport
 * methodName=getListForReport
 *
 */
SELECT PYM_HED.*
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.VENDER_NAME1 AS VENDER_NAME1
, VENDER.VENDER_SHORTED_NAME AS VENDER_SHORTED_NAME
, CLS.CATEGORY_NAME

, NVL(PYM_HED.CREDIT_AMOUNT_FORWARD, 0)
+ NVL(PYM_HED.OTHER_CREDIT_AMOUNT_FORWARD, 0) CREDIT_AMOUNT --画面用.支払・その他計

--画面用.その他計
, (NVL(PYM_HED.OTHER_STOCKING_AMOUNT, 0) + NVL(PYM_HED.OFFSET_AMOUNT, 0))
- (NVL(PYM_HED.STOCKING_RETURNED_AMOUNT, 0) + NVL(PYM_HED.STOCKING_DISCOUNT_AMOUNT, 0)) OTHER_TOTAL

, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM PAYMENT_HEADER PYM_HED
, ORGANIZATION
, VENDER
, CLASSIFICATION CLS
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE PYM_HED.ORGANIZATION_CD IS NOT NULL
AND TO_CHAR(PYM_HED.PAYABLE_DATE,'YYYY/MM') = /*condition.srhTargetMonth*/'2009/07'

/*IF (condition.srhOutputDivision)*/ --出力区分：残高有のみ
AND PYM_HED.PAYABLE_AMOUNT IS NOT NULL
AND PYM_HED.PAYABLE_AMOUNT != 0
/*END*/

/*IF (condition.srhOrganizationCd != null && condition.srhOrganizationCd != "")*/
AND	(PYM_HED.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhOrganizationCd*/'%')
/*END*/

/*IF (condition.srhTantoCd != null && condition.srhTantoCd != "")*/
AND	(PYM_HED.INPUTOR_CD LIKE /*condition.srhTantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.srhTantoCd*/'%')
/*END*/

/*IF (condition.srhVenderCd != null && condition.srhVenderCd != "")*/
AND	(PYM_HED.SUPPLIER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

AND PYM_HED.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'SI'
AND PYM_HED.SUPPLIER_CD = VENDER.VENDER_CD(+)
AND CLS.DATA_TYPE(+) = 4
AND PYM_HED.CREDIT_DIVISION = CLS.CATEGORY_DIVISION(+)
AND PYM_HED.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND PYM_HED.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY PYM_HED.SUPPLIER_CD


