/*
 * 在庫照会一覧用SQL
 *
 * entityName=InventoryList
 * packageName=inventorylist
 * methodName=getList
 *
 */

SELECT LOCATION_INVENTORY.LOCATION_CD, MIN(LOCATION.LOCATION_NAME) LOCATION_NAME, SUBSTR(MIN(LOCATION.LOCATION_NAME), 0, 8) SHORT_LOCATION_NAME, LOCATION_INVENTORY.ITEM_CD, MIN(ITEM_NAME) ITEM_NAME, SUBSTR(MIN(ITEM_NAME), 0, 8) SHORT_ITEM_NAME, NULL LOT_NO, MIN(STYLE_OF_PACKING) STYLE_OF_PACKING,

SUM(DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1)),
DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1)),
CASE TYPE_DIVISION
    WHEN 1 THEN FLOOR(DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1)))
    WHEN 3 THEN FLOOR(DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1)))
    ELSE NVL(INVENTORY_QTY, 0)
END))) PACK_QTY,

MIN(UNIT_OF_OPERATION_MANAGEMENT) UNIT_OF_OPERATION_MANAGEMENT, MIN(OPERATION_NAMES.NAME01) PACK_UNIT,

SUM(DECODE(NVL(KG_CONVERSION_COEFFICIENT, 1), 0, 0, DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', 0, DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', 0,
CASE TYPE_DIVISION
    WHEN 1 THEN DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1)))
    WHEN 3 THEN DECODE(NVL(KG_OF_FRACTION_MANAGEMENT, 1), 0, 0, MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1)))
    ELSE 0
END)) / NVL(KG_CONVERSION_COEFFICIENT, 1))) FRACTION,

MIN(UNIT_OF_FRACTION_MANAGEMENT) UNIT_OF_FRACTION_MANAGEMENT, MIN(FRACTION_NAMES.NAME01) FRACTION_UNIT,

SUM(CASE TYPE_DIVISION
    WHEN 1 THEN NVL(INVENTORY_QTY, 0)
    WHEN 3 THEN NVL(INVENTORY_QTY, 0)
    ELSE NVL(INVENTORY_QTY, 0) * NVL(KG_OF_FRACTION_MANAGEMENT, 1)
END) INVENTORY_QTY

FROM LOCATION_INVENTORY, ITEM, LOCATION, NAMES OPERATION_NAMES, NAMES FRACTION_NAMES,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM
GROUP BY ITEM_CD) MAX_ITEM

WHERE LOCATION_INVENTORY.LOCATION_CD IN (SELECT LOCATION_CD FROM LOCATION WHERE UPPER_LOCATION_CD IS NULL)
AND INVENTORY_QTY <> 0
AND LOCATION_INVENTORY.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND MAX_ITEM.ITEM_CD = ITEM.ITEM_CD(+)
AND MAX_ITEM.VERSION = ITEM.VERSION(+)
AND LOCATION_INVENTORY.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND OPERATION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_OPERATION_MANAGEMENT = OPERATION_NAMES.NAME_CD(+)
AND FRACTION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_FRACTION_MANAGEMENT = FRACTION_NAMES.NAME_CD(+)

GROUP BY LOCATION_INVENTORY.LOCATION_CD, LOCATION_INVENTORY.ITEM_CD

ORDER BY LOCATION_CD, ITEM_CD
