/*
 * 部署マスタ詳細画面表示用SQL
 *
 * entityName=OrganizationDetail
 * packageName=organizationdetail
 * methodName=getEntity
 *
 */

SELECT ORGANIZATION.ORGANIZATION_CD, ORGANIZATION.ORGANIZATION_NAME, ORGANIZATION.PARENT_ORGANIZATION_CD, PARENT_ORGANIZATION.ORGANIZATION_NAME PARENT_ORGANIZATION_NAME, ORGANIZATION.BILL_DESCRIPTION_MATTER, ORGANIZATION.ZIPCODE_NO, ORGANIZATION.ADDRESS1, ORGANIZATION.ADDRESS2, ORGANIZATION.ADDRESS3, ORGANIZATION.TEL_NO, ORGANIZATION.FAX_NO, ORGANIZATION.TANTO_CD, TANTO_NM, ORGANIZATION.FROM_MAIL_ADDRESS1, ORGANIZATION.FROM_MAIL_ADDRESS2, ORGANIZATION.FROM_MAIL_ADDRESS3, ORGANIZATION.BCC_SEND_FLG, ORGANIZATION.UPDATE_DATE
FROM ORGANIZATION, ORGANIZATION PARENT_ORGANIZATION, LOGIN
WHERE ORGANIZATION.ORGANIZATION_CD = /*organizationCd*/'0100'
AND ORGANIZATION.PARENT_ORGANIZATION_CD = PARENT_ORGANIZATION.ORGANIZATION_CD(+)
AND ORGANIZATION.TANTO_CD = LOGIN.TANTO_CD(+)


