/*
* 製造品扱い属性検索用SQL
*
* entityName=ProductAttributeQueueDetail
* packageName=productattributequeuedetail
* methodName=getEntity
*
*/

SELECT ITEM_CD
	  ,VERSION
	  ,STATUS                PRODUCT_STATUS
	  ,ORDER_PATTERN
	  ,QUEUE.PRODUCTION_LINE
	  ,PRODUCTION_LINE_NAME
	  ,INSPECTION_DAYS
	  ,ORDER_POINT           PRODUCT_ORDER_POINT
	  ,QUEUE.SECTION_CD      PRODUCT_SECTION_CD
	  ,BUMON.SECTION_NAME    PRODUCT_SECTION_NAME
	  ,QUEUE.UPDATE_DATE     PRODUCT_UPDATE_DATE
FROM   PRODUCT_ATTRIBUTE_QUEUE QUEUE
	  ,LINE
	  ,BUMON
WHERE  ITEM_CD = /*itemCd*/'%'
AND    VERSION = /*version*/1
AND    QUEUE.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND    QUEUE.SECTION_CD = BUMON.SECTION_CD(+)


