/*
 * 取引先名称検索用SQL
 *
 * entityName=DeliveryDetail
 * packageName=deliverydetail
 * methodName=getEntity
 *
 */

SELECT 
    DELIVERY_CD,
    DELIVERY_NAME1,
    DELIVERY_NAME2, 
    SEARCH_KANA,
    ADDRESS1,
    ADDRESS2,
    ADDRESS3,
    TEL_NO,
    FAX_NO,
    CARRY_CD,
    FARE_CLAIM_EXISTENCE,
    LEAD_TIME,
    DELIVERY_TIME,
    TANTO_CD,
    VENDER_GROUP_CD
FROM DELIVERY
LEFT JOIN
(
    WITH TMP( VENDER_GROUP_CD , BALANCE_CD , UPPER_BALANCE_CD, SHOP_LEVEL , LOOP_COUNT ) AS (
    SELECT
        ORDER_VENDER_MASTER.VENDER_GROUP_CD
        , TO_NCHAR( ORDER_VENDER_MASTER.BALANCE_CD ) AS BALANCE_CD
        , NULL AS UPPER_BALANCE_CD
        , 1 AS SHOP_LEVEL
        , 1 AS LOOP_COUNT
    FROM
        ORDER_VENDER_MASTER
    UNION ALL
    SELECT
        TMP.VENDER_GROUP_CD
        , BALANCE.BALANCE_CD
        , BALANCE.UPPER_BALANCE_CD
        , BALANCE.SHOP_LEVEL
        , TMP.LOOP_COUNT + 1 AS LOOP_COUNT
    FROM
        BALANCE
    INNER JOIN
        TMP
    ON
        TMP.BALANCE_CD = BALANCE.UPPER_BALANCE_CD
        AND TMP.SHOP_LEVEL + 1 = BALANCE.SHOP_LEVEL
    WHERE
        TMP.LOOP_COUNT < 99
       ) , 
    ORDER_VENDER_EX AS (
    SELECT
        TMP.VENDER_GROUP_CD
        , TMP.BALANCE_CD
    FROM
        TMP
    GROUP BY
        TMP.VENDER_GROUP_CD
        , TMP.BALANCE_CD
    )
    SELECT
            SALES_TERMS.DELIVERY_CD AS SOM_DELIVERY_CD
            , MAX(ORDER_VENDER_MASTER.VENDER_GROUP_CD) AS VENDER_GROUP_CD
        FROM
            SALES_TERMS
        INNER JOIN
            ORDER_VENDER_EX ORDER_VENDER_MASTER
        ON
            ORDER_VENDER_MASTER.BALANCE_CD = SALES_TERMS.BALANCE_CD
        LEFT JOIN 
            DELIVERY
        ON 
            DELIVERY.DELIVERY_CD = SALES_TERMS.DELIVERY_CD
        AND DELIVERY.DELIVERY_CD = /*deliveryCd*/'%'
        GROUP BY 
            SALES_TERMS.DELIVERY_CD
            , DELIVERY.DELIVERY_CD) VENDER_GROUP
    ON VENDER_GROUP.SOM_DELIVERY_CD = DELIVERY.DELIVERY_CD
WHERE DELIVERY.DELIVERY_CD = /*deliveryCd*/'%'




