/*
 * 設備帳票用SQL
 *
 * entityName=RecipeResouceListForReport
 * packageName=reciperesoucelistforreport
 * methodName=getListForReport
 *
 */

SELECT RECIPE.*
, RESOUCE_GROUP.RESOUCE_GROUP_NAME
, LINE.PRODUCTION_LINE_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM RECIPE_RESOUCE RECIPE
, RECIPE_RESOUCE_GROUP RESOUCE_GROUP
, LINE
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE RESOUCE_CD IS NOT NULL

/*IF (condition.srhResouceCd != null) && (condition.srhResouceCd != "")*/
AND (RECIPE.RESOUCE_CD LIKE /*condition.srhResouceCd*/'%' OR RECIPE.RESOUCE_NAME LIKE /*condition.srhResouceCd*/'%')
/*END*/

AND RECIPE.RESOUCE_GROUP_CD = RESOUCE_GROUP.RESOUCE_GROUP_CD(+)
AND RECIPE.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND RECIPE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND RECIPE.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY RECIPE.RESOUCE_CD


