/*
 * 部署マスタ帳票用SQL
 *
 * entityName=OrganizationListForReport
 * packageName=organizationlistforreport
 * methodName=getListForReport
 *
 */

SELECT ORGANIZATION.*
, PARENT.ORGANIZATION_NAME PARENT_ORGANIZATION_NAME
, LOGIN.TANTO_NM
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM ORGANIZATION
, ORGANIZATION PARENT
, LOGIN
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE ORGANIZATION.ORGANIZATION_CD IS NOT NULL

/*IF (condition.srhOrganizationCd != null) && (condition.srhOrganizationCd != "")*/
AND	(ORGANIZATION.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhOrganizationCd*/'%')
/*END*/

AND ORGANIZATION.PARENT_ORGANIZATION_CD = PARENT.ORGANIZATION_CD(+)
AND ORGANIZATION.TANTO_CD = LOGIN.TANTO_CD(+)
AND ORGANIZATION.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND ORGANIZATION.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY ORGANIZATION.ORGANIZATION_CD


