/*
 * Created on 2009/01/13
 *
 * $copyright$
 *
*/

/**
 * 入荷入力用SQL
 *
 * @author tosco
 *
 * entityName=ArrivalList
 * packageName=arrival
 * methodName=getEntity
 *
 */
SELECT	PURCHASE_SUBCONTRACT.PURCHASE_NO
,	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DIVIDE_NO
,	PURCHASE_SUBCONTRACT.ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_ROW_NO
,	PURCHASE_SUBCONTRACT.ASP_ORDER_NO
,	PURCHASE_SUBCONTRACT.MATERIAL_DIVISION
,	PURCHASE_SUBCONTRACT.SI_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DATE
,	PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.TANTO_CD
,	PURCHASE_SUBCONTRACT.ORDER_DIVISION
,	PURCHASE_SUBCONTRACT.VENDER_CD
,	PURCHASE_SUBCONTRACT.ITEM_CD
,	PURCHASE_SUBCONTRACT.ITEM_NAME
,	PURCHASE_SUBCONTRACT.ORDER_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_UNITPRICE
,	PURCHASE_SUBCONTRACT.UNITPRICE_DEFINEUNIT
,	PURCHASE_SUBCONTRACT.SUPPLIER_ORD_AMOUNT
,	PURCHASE_SUBCONTRACT.SUGGESTED_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_REMARK
,	PURCHASE_SUBCONTRACT.REMARK
,	PURCHASE_SUBCONTRACT.NOTES
,	PURCHASE_SUBCONTRACT.LOCATION_CD
,	PURCHASE_SUBCONTRACT.STATUS
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO
,	PURCHASE_SUBCONTRACT.ORDER_SHEE_FLAG
,	PURCHASE_SUBCONTRACT.ORDER_SHEE_DATE
,	PURCHASE_SUBCONTRACT.ORDER_SHEEL_TANTO_CD
,	PURCHASE_SUBCONTRACT.GOOD_HOUSING_SUM
,	PURCHASE_SUBCONTRACT.REPLY_CONTENTS_DIVISION
,	PURCHASE_SUBCONTRACT.DELIVERY_COMP
,	PURCHASE_SUBCONTRACT.NEXT_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.DATA_TYPE
,	PURCHASE_SUBCONTRACT.DATA_TOTAL_DIVISION
,	PURCHASE_SUBCONTRACT.CATEGORY_DIVISION
,	PURCHASE_SUBCONTRACT.STOCKING_DATE
,	PURCHASE_SUBCONTRACT.ACCOUNT_YEARS
,	PURCHASE_SUBCONTRACT.SLIP_NO
,	PURCHASE_SUBCONTRACT.ROW_NO
,	PURCHASE_SUBCONTRACT.CANCEL_SLIP_NO
,	PURCHASE_SUBCONTRACT.CANCEL_ROW_NO
,	PURCHASE_SUBCONTRACT.SUPPLIER_LOTNO
,	PURCHASE_SUBCONTRACT.LOT_NO
,	PURCHASE_SUBCONTRACT.STOCK_LOCATION_CD
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ARRIVAL_QUANTITY
,	PURCHASE_SUBCONTRACT.STOCK_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.INCREASE_QUANTITY
,	PURCHASE_SUBCONTRACT.STOCKING_QUANTITY
,	PURCHASE_SUBCONTRACT.HOUSING_UNITPRICE
,	PURCHASE_SUBCONTRACT.FARE_AMOUNT
,	PURCHASE_SUBCONTRACT.STOCKING_AMOUNT
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_REMARK2
,	PURCHASE_SUBCONTRACT.REMARK2
,	PURCHASE_SUBCONTRACT.NOTES2
,	PURCHASE_SUBCONTRACT.STATUS2
,	PURCHASE_SUBCONTRACT.TAX_DIVISION
,	PURCHASE_SUBCONTRACT.TAX_AMOUNT
,	PURCHASE_SUBCONTRACT.PAYEE_CD
,	PURCHASE_SUBCONTRACT.ACCOUNT_DEBIT_SECTION_CD
,	PURCHASE_SUBCONTRACT.ACCOUNT_CREDIT_SECTION_CD
,	PURCHASE_SUBCONTRACT.DEBIT_TITLE_CD
,	PURCHASE_SUBCONTRACT.DEBIT_SUB_TITLE_CD
,	PURCHASE_SUBCONTRACT.CREDIT_TITLE_CD
,	PURCHASE_SUBCONTRACT.CREDIT_SUB_TITLE_CD
,	PURCHASE_SUBCONTRACT.PAYABLE_TARGET_DIVISION
,	PURCHASE_SUBCONTRACT.PAYMENT_TARGET_DIVISION
,	PURCHASE_SUBCONTRACT.PAYABLE_UPDATE_DIVISION
,	PURCHASE_SUBCONTRACT.PAYABLE_NO
,	PURCHASE_SUBCONTRACT.PAYMENT_UPDATE_DIVISION
,	PURCHASE_SUBCONTRACT.PAYMENT_NO
,	PURCHASE_SUBCONTRACT.SUMMARY_CD
,	PURCHASE_SUBCONTRACT.SUMMARY
,	PURCHASE_SUBCONTRACT.PAYMENT_UPDATE_DATE
,	PURCHASE_SUBCONTRACT.PAYABLE_UPDATE_DATE
,	PURCHASE_SUBCONTRACT.TRANSMISSION_DATE
,	PURCHASE_SUBCONTRACT.LABEL_FLAG
,	PURCHASE_SUBCONTRACT.LABEL_DATE
,	PURCHASE_SUBCONTRACT.LABEL_TANTO_CD
,	PURCHASE_SUBCONTRACT.TMP_UNITPRICE_FLG
,	PURCHASE_SUBCONTRACT.INSPECT_METHOD
,	PURCHASE_SUBCONTRACT.MORTGAGE_DETAIL_FLG
,	PURCHASE_SUBCONTRACT.INSPRECEIPT_WAIT_QUANTITY
,	PURCHASE_SUBCONTRACT.BAD_QUANTITY
,	PURCHASE_SUBCONTRACT.COST_ENTRY
,	PURCHASE_SUBCONTRACT.ADV_PUR_NOTICE_DECIDE_DIVISION
,	PURCHASE_SUBCONTRACT.ORDER_MORTGAGED_QUANTITY
,	PURCHASE_SUBCONTRACT.SUM_HOUSING_CONVERT_QUANT
,	PURCHASE_SUBCONTRACT.INSPECT_WAIT_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.EXTRACTIONS_QUANTITY
,	PURCHASE_SUBCONTRACT.DEFECTIVE_QUANTITY
,	PURCHASE_SUBCONTRACT.CHECK_TANTO_CD
,	PURCHASE_SUBCONTRACT.LABORATORY_METHOD
,	PURCHASE_SUBCONTRACT.PROVISION_DIVISION
,	PURCHASE_SUBCONTRACT.CHECK_DATE
,	PURCHASE_SUBCONTRACT.TAX_RATIO
,	PURCHASE_SUBCONTRACT.CHECK_QUANTITY
,	PURCHASE_SUBCONTRACT.SLIP_ISSUE_DIVISION
,	PURCHASE_SUBCONTRACT.SLIP_ISSUE_DATE
,	PURCHASE_SUBCONTRACT.APPROVAL_STATUS
,	PURCHASE_SUBCONTRACT.APPROVEDBY
,	PURCHASE_SUBCONTRACT.APPROVALDATE
,	PURCHASE_SUBCONTRACT.INPUT_DATE
,	PURCHASE_SUBCONTRACT.INPUTOR_CD
,	PURCHASE_SUBCONTRACT.UPDATE_DATE
,	PURCHASE_SUBCONTRACT.UPDATOR_CD
,	NVL(ITEM.TYPE_DIVISION, '') AS TYPE_DIVISION		-- 種別
,	ITEM.ITEM_NAME AS ITEM_QUEUE_NAME					-- 品目名称
,	ITEM.STYLE_OF_PACKING								-- 荷姿
,	ITEM.OTHER_COMPANY_CD1								-- 他社コード1
,	ITEM.KG_OF_FRACTION_MANAGEMENT						-- Kg換算係数(在庫)
,	ITEM.SHIPPER_DIVISION								-- 荷主
,	ARTICLE_ATTRIBUTE_QUEUE.PALETTE_PRODUCTS			-- パレット上製品数
,	VENDER.VENDER_NAME1 AS VENDER_NAME					-- 取引先名称1
,	VENDER.VENDER_SHORTED_NAME AS VENDER_SHORTED_NAME	-- 取引先略称
,	LOCATION.LOCATION_NAME								-- ロケーション名称
,	ORGANIZATION.ORGANIZATION_NAME						-- 部署名称
,	NAMES.NAME01 AS UNIT								-- 単位
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV		-- 運用管理単位(区分)

FROM	PURCHASE_SUBCONTRACT
,		ITEM
,		ARTICLE_ATTRIBUTE_QUEUE
,		(SELECT VENDER_CD
		 ,		VENDER_NAME1
		 ,		VENDER_SHORTED_NAME
		 FROM VENDER
		 WHERE VENDER_DIVISION = 'SI'
		) VENDER
,		LOCATION
,		ORGANIZATION
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'UNIT'
		) NAMES

WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
/*IF (( purchaseNo != null ) && ( purchaseNo != "" ))*/
	AND	PURCHASE_SUBCONTRACT.PURCHASE_NO = /*purchaseNo*/
/*END*/
/*IF (( slipNo != null ) && ( slipNo != "" ))*/
	AND	PURCHASE_SUBCONTRACT.SLIP_NO = /*slipNo*/
/*END*/
AND PURCHASE_SUBCONTRACT.ITEM_CD = ITEM.ITEM_CD(+) 
AND ITEM.ITEM_CD = ARTICLE_ATTRIBUTE_QUEUE.ITEM_CD(+)
AND ITEM.VERSION = ARTICLE_ATTRIBUTE_QUEUE.VERSION(+)
AND ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND PURCHASE_SUBCONTRACT.VENDER_CD = VENDER.VENDER_CD(+) 
AND PURCHASE_SUBCONTRACT.LOCATION_CD = LOCATION.LOCATION_CD(+) 
AND PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+) 
ORDER BY SLIP_NO
,		 ROW_NO
