/**
 * @author t1344224
 *
 * entityName=StockBookingFormulaListForReport
 * packageName=stockbookingforReport
 * methodName=getFormulaReportList
 *
 */
SELECT	

	FORMULA.DIRECTION_DIVISION
,	FORMULA.DIRECTION_NO
,	FORMULA.STEP_NO
,	FORMULA.LINE_NO
,	FORMULA.SEQ
,	FORMULA.LINE_TYPE
,	FORMULA.ITEM_CD
,	ITEM_FORMULA.ITEM_NAME
,	NAME_FORMULA.NAME01
,	FORMULA.TONYU
,	FORMULA.DATAREAD
,	FORMULA.TONYUSOKUDO
,	FORMULA.QTY
,	FORMULA.STOCKPD_QTY
,	FORMULA.RESULT_QTY
,	FORMULA.SAMPLE_QTY
,	FORMULA.LOSS_QTY
,	FORMULA.DEFECT_QTY
,	FORMULA.ADJUST_QTY
,	FORMULA.COST
,	FORMULA.STEP_CONDITION
,	FORMULA.NOTES
,	FORMULA.LOCATION_CD
,	FIRST_LOCATION.LOCATION_NAME AS FIRST_LOCATION_NAME
,	FORMULA.NEXT_LOCATION_CD
,	SECOND_LOCATION.LOCATION_NAME AS SECOND_LOCATION_NAME
,	FORMULA.NEXT_AFTER_LOCATION_CD
,	THIRD_LOCATION.LOCATION_NAME AS THIRD_LOCATION_NAME
,	FORMULA.LOT_NO
,	FORMULA.MANUFACTURER_LOT_NO
,	FORMULA.FILL_QTY
,	FORMULA.FILL_RESULT_QTY
,	FORMULA.REMARK
,	FORMULA.INPUT_DATE
,	FORMULA.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	FORMULA.UPDATE_DATE
,	FORMULA.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM	DIRECTION_HEADER HEAD
,	VALID_ITEM_QUEUE

,	DIRECTION_FORMULA FORMULA

,	LOGIN INPUTOR
,	LOGIN UPDATOR

,	ITEM ITEM_FORMULA
,	NAMES NAME_FORMULA
,	LOCATION FIRST_LOCATION
,	LOCATION SECOND_LOCATION
,	LOCATION THIRD_LOCATION


WHERE	HEAD.DIRECTION_DIVISION IN('2','3')
AND	HEAD.DIRECTION_STATUS = 4
AND	HEAD.ITEM_CD = VALID_ITEM_QUEUE.ITEM_CD(+)

AND	HEAD.DIRECTION_NO = FORMULA.DIRECTION_NO

AND	FORMULA.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	FORMULA.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND	FORMULA.ITEM_CD = ITEM_FORMULA.ITEM_CD(+)
AND	NAME_FORMULA.NAME_DIVISION(+) = 'UNIT'
AND	NAME_FORMULA.NAME_CD(+) = ITEM_FORMULA.UNIT_OF_OPERATION_MANAGEMENT
AND	FORMULA.LOCATION_CD = FIRST_LOCATION.LOCATION_CD(+)
AND	FORMULA.NEXT_LOCATION_CD = SECOND_LOCATION.LOCATION_CD(+)
AND	FORMULA.NEXT_AFTER_LOCATION_CD = THIRD_LOCATION.LOCATION_CD(+)

/*IF (( condition.srhResultSdateFrom != null ) && ( condition.srhResultSdateFrom != "" ))*/
	AND	HEAD.RESULT_SDATE >= /*condition.srhResultSdateFrom*/''
/*END*/
/*IF (( condition.srhResultSdateTo != null ) && ( condition.srhResultSdateTo != "" ))*/
	AND	HEAD.RESULT_SDATE <= /*condition.srhResultSdateTo*/''
/*END*/
/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	/*IF (condition.srhProductionLine != "0")*/
			AND	HEAD.PRODUCTION_LINE = /*condition.srhProductionLine*/''
	/*END*/		
/*END*/


ORDER BY	HEAD.RESULT_SDATE
,		HEAD.DIRECTION_NO
    ,FORMULA.STEP_NO
,FORMULA.LINE_NO


