/**
 * @author t1344224
 *
 * entityName=StockBookingInspectionListForReport
 * packageName=stockbookingforReport
 * methodName=getInspectionReportList
 *
 */
SELECT	

	INSPECTION.DIRECTION_DIVISION
,	INSPECTION.DIRECTION_NO
,	INSPECTION.STEP_NO
,	INSPECTION.LINE_NO
,	INSPECTION.SEQ
,	INSPECTION.INSPECTION_CD
,	NAMES.NAME01 AS INSPECTION_NAME
,	INSPECTION.DIVISION
,	INSPECTION.VALUE_TYPE
,	INSPECTION.VALUE1
,	INSPECTION.RESULT_VALUE1
,	INSPECTION.VALUE2
,	INSPECTION.RESULT_VALUE2
,	INSPECTION.CONDITION
,	INSPECTION.NOTES
,	INSPECTION.REMARK
,	INSPECTION.INPUT_DATE
,	INSPECTION.INPUTOR_CD
,	INSPECTION.UPDATE_DATE
,	INSPECTION.UPDATOR_CD
,	INSPECTION.INPUT_DATE
,	INSPECTION.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	INSPECTION.UPDATE_DATE
,	INSPECTION.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM	DIRECTION_HEADER HEAD
,	VALID_ITEM_QUEUE

,	DIRECTION_INSPECTION INSPECTION
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,	NAMES


WHERE	HEAD.DIRECTION_DIVISION IN('2','3')
AND	HEAD.DIRECTION_STATUS = 4
AND	HEAD.ITEM_CD = VALID_ITEM_QUEUE.ITEM_CD(+)

AND	HEAD.DIRECTION_NO = INSPECTION.DIRECTION_NO

AND	INSPECTION.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	INSPECTION.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND	INSPECTION.INSPECTION_CD = NAMES.NAME_CD(+)
AND	NAMES.NAME_DIVISION = 'STDV'

/*IF (( condition.srhResultSdateFrom != null ) && ( condition.srhResultSdateFrom != "" ))*/
	AND	HEAD.RESULT_SDATE >= /*condition.srhResultSdateFrom*/''
/*END*/
/*IF (( condition.srhResultSdateTo != null ) && ( condition.srhResultSdateTo != "" ))*/
	AND	HEAD.RESULT_SDATE <= /*condition.srhResultSdateTo*/''
/*END*/
/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	/*IF (condition.srhProductionLine != "0")*/
			AND	HEAD.PRODUCTION_LINE = /*condition.srhProductionLine*/''
	/*END*/		
/*END*/


ORDER BY	HEAD.RESULT_SDATE
,		HEAD.DIRECTION_NO
    ,INSPECTION.STEP_NO
,INSPECTION.LINE_NO


