/*
 * 帳合マスタ一覧用SQL
 *
 * entityName=BalanceListForReport
 * packageName=balancelistforreport
 * methodName=getListForReport
 *
 */

/*IF (condition.srhBalanceType == 0 || condition.srhBalanceType == 1)*/
SELECT BALANCE_CD
, NULL VENDER_CD1
, NULL VENDER_CD2
, NULL VENDER_CD3
, NULL VENDER_CD4
, NULL VENDER_CD5
, SHOP_LEVEL
, BALANCE_TYPE
, NULL BALANCE_TYPE_NAME
, NULL VENDER_NAME1
, NULL VENDER_NAME2
, NULL VENDER_NAME3
, NULL VENDER_NAME4
, NULL VENDER_NAME5
, SYSDATE INPUT_DATE
, NULL INPUTOR_CD
, NULL INPUTOR_NAME
, SYSDATE UPDATE_DATE
, NULL UPDATOR_CD
, NULL UPDATOR_NAME

FROM BALANCE, VENDER
WHERE BALANCE_CD IS NOT NULL
AND VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)

START WITH BALANCE.VENDER_CD IS NOT NULL

/*IF (condition.srhBalanceType == 1)*/
AND BALANCE_TYPE = 1
/*END*/

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (BALANCE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER_NAME1 LIKE /*condition.srhVenderCd*/'%')
/*END*/

CONNECT BY PRIOR BALANCE.UPPER_BALANCE_CD = BALANCE.BALANCE_CD

/*IF (condition.srhBalanceType == 1)*/
AND BALANCE_TYPE = 1
/*END*/

UNION

SELECT BALANCE_CD
, NULL VENDER_CD1
, NULL VENDER_CD2
, NULL VENDER_CD3
, NULL VENDER_CD4
, NULL VENDER_CD5
, SHOP_LEVEL
, BALANCE_TYPE
, NULL BALANCE_TYPE_NAME
, NULL VENDER_NAME1
, NULL VENDER_NAME2
, NULL VENDER_NAME3
, NULL VENDER_NAME4
, NULL VENDER_NAME5
, SYSDATE INPUT_DATE
, NULL INPUTOR_CD
, NULL INPUTOR_NAME
, SYSDATE UPDATE_DATE
, NULL UPDATOR_CD
, NULL UPDATOR_NAME

FROM BALANCE, VENDER
WHERE BALANCE_CD IS NOT NULL
AND VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)

START WITH BALANCE.VENDER_CD IS NOT NULL

/*IF (condition.srhBalanceType == 1)*/
AND BALANCE_TYPE = 1
/*END*/

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (BALANCE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER_NAME1 LIKE /*condition.srhVenderCd*/'%')
/*END*/

CONNECT BY PRIOR BALANCE.BALANCE_CD = BALANCE.UPPER_BALANCE_CD

/*IF (condition.srhBalanceType == 1)*/
AND BALANCE_TYPE = 1
/*END*/

/*END*/

/*IF (condition.srhBalanceType == 0)*/
UNION
/*END*/

/*IF (condition.srhBalanceType == 0 || condition.srhBalanceType == 2)*/
SELECT BALANCE_CD
, NULL VENDER_CD1
, NULL VENDER_CD2
, NULL VENDER_CD3
, NULL VENDER_CD4
, NULL VENDER_CD5
, SHOP_LEVEL
, BALANCE_TYPE
, NULL BALANCE_TYPE_NAME
, NULL VENDER_NAME1
, NULL VENDER_NAME2
, NULL VENDER_NAME3
, NULL VENDER_NAME4
, NULL VENDER_NAME5
, SYSDATE INPUT_DATE
, NULL INPUTOR_CD
, NULL INPUTOR_NAME
, SYSDATE UPDATE_DATE
, NULL UPDATOR_CD
, NULL UPDATOR_NAME

FROM BALANCE, VENDER
WHERE BALANCE_CD IS NOT NULL
AND VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)

START WITH BALANCE.VENDER_CD IS NOT NULL

/*IF (condition.srhBalanceType == 2)*/
AND BALANCE_TYPE = 2
/*END*/

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (BALANCE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER_NAME1 LIKE /*condition.srhVenderCd*/'%')
/*END*/

CONNECT BY PRIOR BALANCE.UPPER_BALANCE_CD = BALANCE.BALANCE_CD

/*IF (condition.srhBalanceType == 2)*/
AND BALANCE_TYPE = 2
/*END*/

UNION

SELECT BALANCE_CD
, NULL VENDER_CD1
, NULL VENDER_CD2
, NULL VENDER_CD3
, NULL VENDER_CD4
, NULL VENDER_CD5
, SHOP_LEVEL
, BALANCE_TYPE
, NULL BALANCE_TYPE_NAME
, NULL VENDER_NAME1
, NULL VENDER_NAME2
, NULL VENDER_NAME3
, NULL VENDER_NAME4
, NULL VENDER_NAME5
, SYSDATE INPUT_DATE
, NULL INPUTOR_CD
, NULL INPUTOR_NAME
, SYSDATE UPDATE_DATE
, NULL UPDATOR_CD
, NULL UPDATOR_NAME

FROM BALANCE, VENDER
WHERE BALANCE_CD IS NOT NULL
AND VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)

START WITH BALANCE.VENDER_CD IS NOT NULL

/*IF (condition.srhBalanceType == 2)*/
AND BALANCE_TYPE = 2
/*END*/

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (BALANCE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER_NAME1 LIKE /*condition.srhVenderCd*/'%')
/*END*/

CONNECT BY PRIOR BALANCE.BALANCE_CD = BALANCE.UPPER_BALANCE_CD

/*IF (condition.srhBalanceType == 2)*/
AND BALANCE_TYPE = 2
/*END*/

/*END*/

ORDER BY BALANCE_CD


