/*
 * Created on 2009/02/26
 *
 * $copyright$
 *
*/

/**
 * 仕入先入力時、検索SQL
 *
 * @author tosco
 *
 * entityName=BuyingDetail
 * packageName=buying
 * methodName=getVenderRelatedData
 *
 */
SELECT
	 MAIN_TB.UNITPRICE_DIVISION	AS UNITPRICE_DIVISION			-- 単価の単位区分
	,MAIN_TB.NAME01				AS HOUSING_UNITPRICE_UNIT  		-- 単価の単位名称
	,MAIN_TB.VENDER_CD			AS VENDER_CD					-- 仕入先コード
	,MAIN_TB.VENDER_NAME1		AS VENDER_NAME1					-- 仕入先名称
	,MAIN_TB.VENDER_SHORTED_NAME		AS VENDER_SHORTED_NAME	-- 仕入先略称
	,MAIN_TB.ORGANIZATION_CD	AS CHARGE_ORGANIZATION_CD		-- 担当部署コード
	,ORG.ORGANIZATION_NAME		AS TANTO_SECTION_NAME			-- 担当部署名称
	,MAIN_TB.SECTION_CD			AS ACCOUNT_CREDIT_SECTION_CD	-- 貸方部門コード
	,MAIN_TB.ACCOUNTS_CD		AS CREDIT_TITLE_CD				-- 貸方科目コード
	,BUM.SECTION_NAME			AS ACCOUNT_CREDIT_SECTION_NAME	-- 貸方部門名称
	,ACC.ACCOUNTS_NAME			AS CREDIT_TITLE_NAME			-- 貸方科目名称
	,MAIN_TB.PAYMENT_INVOICE_CD AS PAYMENT_INVOICE_CD
	,MAIN_TB.REDUCED_TAX_TARGET_FLG AS REDUCED_TAX_TARGET_FLG	-- 免税計算対象フラグ
FROM
	(
	SELECT
		 MAX(UNION_TB.UNITPRICE_DIVISION)	AS UNITPRICE_DIVISION
		,MAX(UNION_TB.NAME01)				AS NAME01
		,MAX(UNION_TB.VENDER_CD)			AS VENDER_CD
		,MAX(UNION_TB.VENDER_NAME1)			AS VENDER_NAME1
		,MAX(UNION_TB.VENDER_SHORTED_NAME)	AS VENDER_SHORTED_NAME
		,MAX(UNION_TB.ORGANIZATION_CD)		AS ORGANIZATION_CD
		,MAX(UNION_TB.SECTION_CD)			AS SECTION_CD
		,MAX(UNION_TB.ACCOUNTS_CD)			AS ACCOUNTS_CD
		,MAX(UNION_TB.PAYMENT_INVOICE_CD)   AS PAYMENT_INVOICE_CD
		,MAX(UNION_TB.REDUCED_TAX_TARGET_FLG)    AS REDUCED_TAX_TARGET_FLG
	FROM
		(
			-- 単価区分と単価名称を取得
			SELECT
				 UNIT.UNITPRICE_DIVISION
				,NAME.NAME01
				,null					AS VENDER_CD
				,null					AS VENDER_NAME1
				,null					AS VENDER_SHORTED_NAME
				,null					AS ORGANIZATION_CD
				,null					AS SECTION_CD
				,null					AS ACCOUNTS_CD
				,null                   AS PAYMENT_INVOICE_CD
				,null                   AS REDUCED_TAX_TARGET_FLG
			FROM
				(
				SELECT
					 VENDER_CD
					,ITEM_CD
					,MAX(VERSION) AS VERSION
				FROM	UNITPRICE
				WHERE	VENDER_DIVISION = 'SI'	--発注　'SI'固定
				AND		VENDER_CD = /*venderCd*/'03238003'
				AND		ITEM_CD =  /*itemCd*/'02003614'
				AND		CONSECUTIVE_NO = '1'
				GROUP BY	VENDER_CD, ITEM_CD
				) UNIT01
				,UNITPRICE UNIT
				,NAMES NAME
			WHERE
				UNIT.VENDER_DIVISION = 'SI'
			AND	UNIT.VENDER_CD = UNIT01.VENDER_CD
			AND	UNIT.ITEM_CD = UNIT01.ITEM_CD
			AND	UNIT.CONSECUTIVE_NO = '1'
			AND	UNIT.VERSION = UNIT01.VERSION
			AND	NAME.NAME_DIVISION(+) = 'COST'
			AND	NAME.NAME_CD(+) = UNIT.UNITPRICE_DIVISION
		UNION ALL
			-- 仕入先名称と部署コードと部署名称を取得
			-- 支払先の情報を優先、NULLならば仕入先の情報を設定
			SELECT
				 null					AS UNITPRICE_DIVISION
				,null					AS NAME01
				,VEN.VENDER_CD
				,VEN.VENDER_NAME1
				,VEN.VENDER_SHORTED_NAME
				,VEN.ORGANIZATION_CD	-- 部署コード
		 		,DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.SECTION_CD, PAYMENT.SECTION_CD) AS SECTION_CD			-- 会計部門コード
				,DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.ACCOUNTS_CD, PAYMENT.ACCOUNTS_CD) AS ACCOUNTS_CD		-- 科目コード
				,VEN.PAYMENT_INVOICE_CD AS PAYMENT_INVOICE_CD
                ,CASE
                   WHEN VEN.SI_INVOICE_PTN = '2'
                       THEN '1'
                   ELSE '0'
                   END REDUCED_TAX_TARGET_FLG      -- 0：免税の計算対象外 1：免税の計算対象
			FROM	VENDER	VEN, VENDER PAYMENT
			WHERE	VEN.VENDER_DIVISION = 'SI'
			AND	VEN.VENDER_CD = /*venderCd*/'03238003'
			AND	VEN.PAYMENT_INVOICE_CD = PAYMENT.VENDER_CD(+)
			AND	PAYMENT.VENDER_DIVISION(+) = 'SI'
		) UNION_TB
	) MAIN_TB
	,ORGANIZATION	ORG
	,BUMON			BUM
	,ACCOUNTS		ACC
WHERE
		ORG.ORGANIZATION_CD(+) = MAIN_TB.ORGANIZATION_CD
	AND	BUM.SECTION_CD(+) = MAIN_TB.SECTION_CD
	AND	ACC.ACCOUNTS_CD(+) = MAIN_TB.ACCOUNTS_CD