/*
 * Created on 2009/04/14
 *
 * $copyright$
 *
*/

/**
 * 仕入詳細用SQL
 *
 * @author tosco
 *
 * entityName=BuyingDetail
 * packageName=buying
 * methodName=getTaxRelatedData
 *
 */
SELECT
	(CASE		-- 購入品扱い属性.消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
		WHEN NVL(PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION,4) = 4 THEN
			(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税課税区分
				WHEN VENDER2.TAX_DIVISION = 4 THEN (SELECT TAX_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
				ELSE VENDER2.TAX_DIVISION	-- 取引先ﾏｽﾀ.消費税区分
			 END )
		ELSE PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION	-- 購入品扱い属性.消費税課税区分
	 END
	) AS TAX_DIVISION		-- 消費税課税区分
,	(CASE		-- 販売品扱い属性.売上消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
		WHEN PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION = 4 THEN
			(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税率
				WHEN VENDER2.TAX_DIVISION = 4 THEN (SELECT TAX_RATIO FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
				ELSE VENDER2.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
			 END )
		ELSE VENDER2.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
	 END
	) AS TAX_RATIO			-- 消費税率
,	VENDER2.CALC_DIVISION	-- 取引先マスタ.算出区分
,	(SELECT CALC_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001') AS COMP_CALC_DIVISION	-- 自社マスタ.消費税算出区分
FROM
	-- 支払先の情報を優先、NULLならば仕入先の情報を設定
	(SELECT VEN.VENDER_CD		AS VENDER_CD
	 ,		VEN.VENDER_NAME1	AS VENDER_NAME1
	 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.CALC_DIVISION, PAYMENT.CALC_DIVISION) AS CALC_DIVISION	-- 算出区分
	 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_DIVISION, PAYMENT.TAX_DIVISION) AS TAX_DIVISION	-- 消費税区分
	 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_RATIO, PAYMENT.TAX_RATIO) AS TAX_RATIO				-- 消費税率
	 FROM VENDER VEN
	,VENDER PAYMENT 
	WHERE	VEN.VENDER_DIVISION = 'SI'
	AND	VEN.PAYMENT_INVOICE_CD = PAYMENT.VENDER_CD(+)
	AND	PAYMENT.VENDER_DIVISION(+) = 'SI'
	) VENDER2
,	ITEM
,	PURCHASE_ATTRIBUTE_QUEUE	-- 消費税で使用
WHERE	VENDER2.VENDER_CD = /*venderCd*/'03238003'
AND	ITEM.ITEM_CD = /*itemCd*/'39000959'
AND ITEM.ITEM_CD = PURCHASE_ATTRIBUTE_QUEUE.ITEM_CD(+) -- 消費税で使用
AND ITEM.VERSION = PURCHASE_ATTRIBUTE_QUEUE.VERSION(+) -- 消費税で使用
