/*
 * ロールマスタ詳細用SQL
 *
 * entityName=RoleDetailList
 * packageName=roledetaillist
 * methodName=getList
 *
 */

SELECT
	 ROLE.KBN				-- メニュー区分(1:メニュー 2:タブ 3:操作)
	,ROLE.ROLE_ID			-- ロールID
	,ROLE.ROLE_NAME			-- ロール名称
	,ROLE.MENU_ID			-- メニューID
	,ROLE.TAB_ID			-- タブID
	,ROLE.CONTROL_ID		-- 操作ID
	,'m' || ROLE.MENU_ID || 't' || ROLE.TAB_ID || 'c' || ROLE.CONTROL_ID AS ID	-- ID
FROM (
	SELECT
		 ROLE.ROLE_ID AS ROLE_ID
		,ROLE.ROLE_NAME AS ROLE_NAME
		,NULL AS MENU_ID
		,NULL AS TAB_ID
		,NULL AS CONTROL_ID
		,'1' AS KBN
	FROM ROLE ROLE
	 UNION ALL
	SELECT
		 ROLE.ROLE_ID AS ROLE_ID
		,ROLE.ROLE_NAME AS ROLE_NAME
		,VAUTH.MENU_ID AS MENU_ID
		,VAUTH.TAB_ID AS TAB_ID
		,NULL AS CONTROL_ID
		,'2' AS KBN
	FROM ROLE ROLE
		 INNER JOIN
			VIEW_AUTHORITY VAUTH
			ON ROLE.ROLE_ID = VAUTH.ROLE_ID
	 UNION ALL
	SELECT
		 ROLE.ROLE_ID AS ROLE_ID
		,ROLE.ROLE_NAME AS ROLE_NAME
		,VAUTH.MENU_ID AS MENU_ID
		,VAUTH.TAB_ID AS TAB_ID
		,CAUTH.CONTROL_ID AS CONTROL_ID
		,'3' AS KBN
	FROM ROLE ROLE
		 INNER JOIN
			VIEW_AUTHORITY VAUTH
			ON ROLE.ROLE_ID = VAUTH.ROLE_ID
		 INNER JOIN
			CONTROL_AUTHORITY CAUTH
			ON ROLE.ROLE_ID = CAUTH.ROLE_ID
			AND VAUTH.MENU_ID = CAUTH.MENU_ID
			AND VAUTH.TAB_ID = CAUTH.TAB_ID
	) ROLE
WHERE
	ROLE.ROLE_ID = /*roleId*/1
ORDER BY
	 ROLE_ID
	,KBN
	,MENU_ID
	,KBN
	,TAB_ID
	,CONTROL_ID
