/*
 * 得意先管理月報
 *
 * entityName=RepMonthlyVender
 * packageName=monthlyvenderforreport
 * methodName=getListForReport
 *
 */

-- 2018/03/08 高速化のためSQL修正
SELECT
	VEN.VENDER_CD
,	VEN.VENDER_NAME1
,	VEN.VENDER_NAME2
,	VEN.ORGANIZATION_CD

,	CASE WHEN VEN.ADVANCE_DIVISION = 2
		THEN
			ZENZAN_MAEUKE		--前受金
		ELSE
			ZENZAN_URIKAKE		--売掛金
	END	AS ZENZAN

,	CREDIT_NYUKIN
,	CREDIT_NYUKIN_SONOTA
,	CREDIT_NYUKIN + CREDIT_NYUKIN_SONOTA	AS CREDIT_NYUKIN_ALL

,	SALES_URIAGE
,	SALES_URIAGE_HENPIN
,	SALES_URIAGE_TAX
,	SALES_URIAGE - SALES_URIAGE_HENPIN + SALES_URIAGE_TAX			AS SALES_URIAGE_ALL

,	SALES_URIAGE_MI
,	SALES_URIAGE_HENPIN_MI
,	SALES_URIAGE_TAX_MI
,	SALES_URIAGE_MI - SALES_URIAGE_HENPIN_MI + SALES_URIAGE_TAX_MI		AS SALES_URIAGE_ALL_MI

,	SALES_URIAGE - SALES_URIAGE_HENPIN + SALES_URIAGE_TAX
	+ SALES_URIAGE_MI - SALES_URIAGE_HENPIN_MI + SALES_URIAGE_TAX_MI	AS SALES_ALL

,	CASE WHEN VEN.ADVANCE_DIVISION = 2
		THEN
			NULL
		ELSE
			ZENZAN_URIKAKE - (CREDIT_NYUKIN + CREDIT_NYUKIN_SONOTA)
			+ SALES_URIAGE - SALES_URIAGE_HENPIN + SALES_URIAGE_TAX
			+ SALES_URIAGE_MI - SALES_URIAGE_HENPIN_MI + SALES_URIAGE_TAX_MI

	END	AS TOUZAN

,	CASE WHEN VEN.ADVANCE_DIVISION = 2
		THEN
			ZENZAN_MAEUKE - (CREDIT_NYUKIN + CREDIT_NYUKIN_SONOTA)
			+ SALES_URIAGE - SALES_URIAGE_HENPIN + SALES_URIAGE_TAX
			+ SALES_URIAGE_MI - SALES_URIAGE_HENPIN_MI + SALES_URIAGE_TAX_MI
		ELSE
			NULL
	END	AS MAEUKEZAN


FROM
(
	SELECT
		VEN.VENDER_CD

		--前月末残高（売掛金・・・売掛ヘッダー）
	,	NVL(ZENZAN_URIKAKE.CREDIT_AMOUNT,0) AS ZENZAN_URIKAKE

		--前月末残高（前受金）
		--前月までの売上計-前月までの入金計 2014/04/11 Upd
	,	NVL(ZENZAN_MAEUKE_SALES.SUM_ZENZAN_MAEUKE_SALES,0) - NVL(ZENZAN_MAEUKE_CREDIT.SUM_ZENZAN_MAEUKE_CREDIT,0) AS ZENZAN_MAEUKE

		--入金額
	,	NVL(NYUKIN.SUM_CREDIT_AMOUNT_NYUKIN,0) AS CREDIT_NYUKIN

		--入金その他
	,	NVL(NYUKIN.SUM_CREDIT_AMOUNT_SONOTA,0) AS CREDIT_NYUKIN_SONOTA

		--入金計
	,	NVL(NYUKIN.SUM_CREDIT_AMOUNT_ALL,0) AS CREDIT_NYUKIN_ALL

		--売上高（請求分）
	,	NVL(URIAGE_SEIKYU.SUM_SALES_AMOUNT_URIAGE,0) AS SALES_URIAGE

		--返品値引高（請求分）
	,	NVL(URIAGE_SEIKYU.SUM_SALES_AMOUNT_HENPIN,0) AS SALES_URIAGE_HENPIN

		--消費税等（請求分）
	,	NVL(URIAGE_SEIKYU.SUM_TAX_AMOUNT,0) AS SALES_URIAGE_TAX

		--売上高（未請求分）
	,	NVL(URIAGE_SEIKYU_MI.SUM_SALES_AMOUNT_URIAGE,0) AS SALES_URIAGE_MI

		--返品値引高（未請求分）
	,	NVL(URIAGE_SEIKYU_MI.SUM_SALES_AMOUNT_HENPIN,0) AS SALES_URIAGE_HENPIN_MI

		--消費税等（未請求分）
	,	NVL(URIAGE_SEIKYU_MI.SUM_TAX_AMOUNT,0) AS SALES_URIAGE_TAX_MI

	FROM
		VENDER		VEN

		--前月末残高（売掛金・・・売掛ヘッダー）
	,	(
			SELECT
				VENDER_CD
			,	NVL(SUM(CREDIT_AMOUNT),0) AS CREDIT_AMOUNT
			FROM
				DEPOSIT_HEADER 
			WHERE
				TO_CHAR(CREDIT_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),-1),'YYYYMM')
			GROUP BY
				VENDER_CD
		) ZENZAN_URIKAKE

		--前月末残高（前受金）
		--前月までの売上計
	,	(
			SELECT 
				VENDER_CD
			,	NVL(SUM(SUM_SALES_AMOUNT_ALL),0) AS SUM_ZENZAN_MAEUKE_SALES
			FROM
				REP_VENDER_REPORT_SALES C
			WHERE
				SALES_MONTH <= TO_CHAR(ADD_MONTHS(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),-1),'YYYYMM')
			GROUP BY
				VENDER_CD
		) ZENZAN_MAEUKE_SALES
		
		--前月までの入金計
	,	(
			SELECT 
				VENDER_CD
			,	NVL(SUM(SUM_CREDIT_AMOUNT_ALL),0) AS SUM_ZENZAN_MAEUKE_CREDIT
			FROM
				REP_VENDER_REPORT_CREDIT D
			WHERE
				CREDIT_MONTH <= TO_CHAR(ADD_MONTHS(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),-1),'YYYYMM')
			GROUP BY
				VENDER_CD
		) ZENZAN_MAEUKE_CREDIT
		
		--入金
	,	(
			SELECT 
				VENDER_CD
			,	NVL(SUM(SUM_CREDIT_AMOUNT_NYUKIN),0) AS SUM_CREDIT_AMOUNT_NYUKIN
			,	NVL(SUM(SUM_CREDIT_AMOUNT_SONOTA),0) AS SUM_CREDIT_AMOUNT_SONOTA
			,	NVL(SUM(SUM_CREDIT_AMOUNT_ALL),0)    AS SUM_CREDIT_AMOUNT_ALL
			FROM
				REP_VENDER_REPORT_CREDIT A
			WHERE 
				CREDIT_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			AND	CREDIT_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
			GROUP BY
				VENDER_CD
		) NYUKIN
		
		--売上高（請求分）
	,	(
			SELECT 
				VENDER_CD
			,	NVL(SUM(SUM_SALES_AMOUNT_URIAGE),0) AS SUM_SALES_AMOUNT_URIAGE
			,	NVL(SUM(SUM_SALES_AMOUNT_HENPIN),0) AS SUM_SALES_AMOUNT_HENPIN
			,	NVL(SUM(SUM_TAX_AMOUNT),0)          AS SUM_TAX_AMOUNT
			FROM
				REP_VENDER_REPORT_SALES A
			WHERE 
				SALES_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			AND	SALES_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
			AND	ACCOUNT_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM') 
			AND	ACCOUNT_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
			GROUP BY
				VENDER_CD
		) URIAGE_SEIKYU
		
		--売上高（未請求分）
	,	(
			SELECT 
				VENDER_CD
			,	NVL(SUM(SUM_SALES_AMOUNT_URIAGE),0) AS SUM_SALES_AMOUNT_URIAGE
			,	NVL(SUM(SUM_SALES_AMOUNT_HENPIN),0) AS SUM_SALES_AMOUNT_HENPIN
			,	NVL(SUM(SUM_TAX_AMOUNT),0)   AS SUM_TAX_AMOUNT
			FROM
				REP_VENDER_REPORT_SALES A
			WHERE 
				SALES_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			AND	SALES_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
			AND	(ACCOUNT_MONTH < TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			 OR	 ACCOUNT_MONTH > TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM'))
			GROUP BY
				VENDER_CD
		) URIAGE_SEIKYU_MI
		
	WHERE
		VEN.VENDER_DIVISION = 'TS'
	AND	VEN.VENDER_CD = ZENZAN_URIKAKE.VENDER_CD(+)
	AND	VEN.VENDER_CD = ZENZAN_MAEUKE_SALES.VENDER_CD(+)
	AND	VEN.VENDER_CD = ZENZAN_MAEUKE_CREDIT.VENDER_CD(+)
	AND	VEN.VENDER_CD = NYUKIN.VENDER_CD(+)
	AND	VEN.VENDER_CD = URIAGE_SEIKYU.VENDER_CD(+)
	AND	VEN.VENDER_CD = URIAGE_SEIKYU_MI.VENDER_CD(+)
)	B

,	VENDER		VEN

,	(	
		--明細に表示する条件
		SELECT DISTINCT VENDER_CD
		FROM
		(
		SELECT A.VENDER_CD
			FROM DEPOSIT_HEADER A, VENDER V
			WHERE A.VENDER_CD = V.VENDER_CD
			AND   TO_CHAR(CREDIT_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),-1),'YYYYMM')	
			AND   A.CREDIT_AMOUNT != 0
			AND   V.ADVANCE_DIVISION = 1
		UNION ALL
		SELECT A.VENDER_CD
			FROM CLAIM_HEADER A, VENDER V
			WHERE A.VENDER_CD = V.VENDER_CD
			AND   TO_CHAR(CREDIT_DATE,'YYYYMM') = TO_CHAR(ADD_MONTHS(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),-1),'YYYYMM')	
			AND   A.CLAIM_AMOUNT != 0
			AND   V.ADVANCE_DIVISION = 2
		UNION ALL
		SELECT VENDER_CD 
			FROM REP_VENDER_REPORT_SALES
			WHERE SALES_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			AND SALES_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
		UNION ALL
		SELECT VENDER_CD 
			FROM REP_VENDER_REPORT_CREDIT
			WHERE CREDIT_MONTH >= TO_CHAR(TO_DATE(/*dateFrom*/'2018/02','YYYY/MM'),'YYYYMM')
			AND CREDIT_MONTH <= TO_CHAR(TO_DATE(/*dateTo*/'2018/02','YYYY/MM'),'YYYYMM')
		)
	) VEN2

WHERE
	B.VENDER_CD = VEN.VENDER_CD
	AND	VEN.VENDER_CD = VEN2.VENDER_CD
	AND	VEN.VENDER_DIVISION = 'TS'

/*IF (( organizationCd != null ) && ( organizationCd != "" ))*/
	AND	VEN.ORGANIZATION_CD LIKE /*organizationCd*/
/*END*/

ORDER BY
	VEN.ORGANIZATION_CD
,	VEN.VENDER_CD