/**
 *
 * @author T1344224
 *
 * entityName=CarryShippingListForReport
 * packageName=carryshippingforreport
 * methodName=getSearchList
 *
 */
SELECT	SHIPPING_TEMP.SHIPPING_INSTRUCT_DATE
,	SHIPPING_TEMP.VENDER_CD
,	SHIPPING_TEMP.DELIVERY_CD
,	SHIPPING_TEMP.DELIVERY_NAME
,	SHIPPING_TEMP.CARRY_CD
,	CARRY.CARRY_NAME1 || ' ' || CARRY.CARRY_NAME2 AS CARRY_NAME
,	SHIPPING_TEMP.SENDING_OFF_NUMBER
,	SHIPPING_TEMP.SHIPPING_ORDER_SEND_COMP_FLAG
,	CASE SHIPPING_TEMP.SHIPPING_ORDER_SEND_COMP_FLAG
		WHEN 0 THEN '未'
		WHEN 1 THEN '済'
	END AS SHIPPING_ORDER_SEND_COMP

,	SHIPPING_TEMP.ITEM_CD
,	SHIPPING_TEMP.ITEM_NAME
,	SHIPPING_TEMP.ITEM_UNIT
,	SHIPPING_TEMP.SHIPPING_RESULT_DATE
,	SHIPPING_TEMP.INPUT_DATE
,	SHIPPING_TEMP.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	SHIPPING_TEMP.UPDATE_DATE
,	SHIPPING_TEMP.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME


FROM	SHIPPING_TEMP
,	CARRY
,	LOGIN INPUTOR
,	LOGIN UPDATOR

WHERE	SHIPPING_TEMP.CARRY_CD = CARRY.CARRY_CD(+)
AND	SHIPPING_TEMP.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND	SHIPPING_TEMP.UPDATOR_CD = UPDATOR.TANTO_CD(+)

/*IF (( condition.srhShippingInstructDate != null ) && ( condition.srhShippingInstructDate != "" ))*/
	AND	TO_CHAR(SHIPPING_TEMP.SHIPPING_INSTRUCT_DATE,'YYYY/MM/DD') = /*condition.srhShippingInstructDate*/'%'
/*END*/

ORDER BY SENDING_OFF_NUMBER

