/*
 *　販売条件マスタ品目存在確認用SQL
 *
 * entityName=OrderVenderLinkListForReport
 * packageName=ordervenderlinklistforreport
 * methodName=getItemListInSalesTerms
 *
 */
WITH TMP( VENDER_GROUP_CD , BALANCE_CD , UPPER_BALANCE_CD, SHOP_LEVEL , LOOP_COUNT ) AS (
SELECT
    ORDER_VENDER_MASTER.VENDER_GROUP_CD
    , TO_NCHAR( ORDER_VENDER_MASTER.BALANCE_CD ) AS BALANCE_CD
    , NULL AS UPPER_BALANCE_CD
    , 1 AS SHOP_LEVEL
    , 1 AS LOOP_COUNT
FROM
    ORDER_VENDER_MASTER
WHERE
    ORDER_VENDER_MASTER.VENDER_GROUP_CD = /*venderGroupCd*/'001'
UNION ALL
SELECT
    TMP.VENDER_GROUP_CD
    , BALANCE.BALANCE_CD
    , BALANCE.UPPER_BALANCE_CD
    , BALANCE.SHOP_LEVEL
    , TMP.LOOP_COUNT + 1 AS LOOP_COUNT
FROM
    BALANCE
INNER JOIN
    TMP
ON
    TMP.BALANCE_CD = BALANCE.UPPER_BALANCE_CD
    AND TMP.SHOP_LEVEL + 1 = BALANCE.SHOP_LEVEL
WHERE
    TMP.LOOP_COUNT < 99
    ) , 
ORDER_VENDER_EX AS (
SELECT
    TMP.VENDER_GROUP_CD
    , TMP.BALANCE_CD
FROM
    TMP
GROUP BY
    TMP.VENDER_GROUP_CD
    , TMP.BALANCE_CD
)
SELECT
    SALES_TERMS.ITEM_CD AS SOM_ITEM_CD
    , ITEM.ITEM_NAME
FROM
    SALES_TERMS
INNER JOIN
    ORDER_VENDER_EX ORDER_VENDER_MASTER
ON
    ORDER_VENDER_MASTER.BALANCE_CD = SALES_TERMS.BALANCE_CD
LEFT JOIN 
    ITEM 
ON 
    ITEM.ITEM_CD = SALES_TERMS.ITEM_CD
GROUP BY 
    SALES_TERMS.ITEM_CD
,   ITEM.ITEM_NAME
,   ITEM.STYLE_OF_PACKING
,   ITEM.OTHER_COMPANY_CD1
,   ITEM.UNIT_OF_STOCK_CONTROL
,   ITEM.ALL_UP_WEIGHT
,   ITEM.NUMBER_OF_INSERTIONS