/*
 *　得意先グループ連携情報一覧(品目)帳票用SQL
 *
 * entityName=OrderVenderLinkListForReport
 * packageName=ordervenderlinklistforreport
 * methodName=getItemListForReport
 *
 */
WITH TMP( VENDER_GROUP_CD , BALANCE_CD , UPPER_BALANCE_CD, SHOP_LEVEL , LOOP_COUNT ) AS (
SELECT
    ORDER_VENDER_MASTER.VENDER_GROUP_CD
    , TO_NCHAR( ORDER_VENDER_MASTER.BALANCE_CD ) AS BALANCE_CD
    , NULL AS UPPER_BALANCE_CD
    , 1 AS SHOP_LEVEL
    , 1 AS LOOP_COUNT
FROM
    ORDER_VENDER_MASTER
WHERE
    ORDER_VENDER_MASTER.VENDER_GROUP_CD = /*venderGroupCd*/'001'
UNION ALL
SELECT
    TMP.VENDER_GROUP_CD
    , BALANCE.BALANCE_CD
    , BALANCE.UPPER_BALANCE_CD
    , BALANCE.SHOP_LEVEL
    , TMP.LOOP_COUNT + 1 AS LOOP_COUNT
FROM
    BALANCE
INNER JOIN
    TMP
ON
    TMP.BALANCE_CD = BALANCE.UPPER_BALANCE_CD
    AND TMP.SHOP_LEVEL + 1 = BALANCE.SHOP_LEVEL
WHERE
    TMP.LOOP_COUNT < 99
) , 
ORDER_VENDER_EX AS (
SELECT
    TMP.VENDER_GROUP_CD
    , TMP.BALANCE_CD
FROM
    TMP
GROUP BY
    TMP.VENDER_GROUP_CD
    , TMP.BALANCE_CD
)
SELECT
        TMP.SOM_ITEM_CD
    ,   MAX( TMP.ITEM_NAME ) AS ITEM_NAME
    ,   MAX( TMP.STYLE_OF_PACKING ) AS STYLE_OF_PACKING
    ,   MAX( TMP.OTHER_COMPANY_CD1 ) AS OTHER_COMPANY_CD1
    ,   MAX( TMP.UNIT_OF_STOCK_CONTROL ) AS UNIT_OF_STOCK_CONTROL
    ,   MAX( TMP.ALL_UP_WEIGHT ) AS ALL_UP_WEIGHT
    ,   MAX( TMP.NUMBER_OF_INSERTIONS ) AS NUMBER_OF_INSERTIONS
    ,   MAX( TMP.ITEM_CD1 ) AS ITEM_CD1
    ,   MAX( TMP.ITEM_CD2 ) AS ITEM_CD2
    ,   MAX( TMP.ITEM_CD3 ) AS ITEM_CD3
FROM
(
    SELECT
        ORDER_VENDER_ITEM.SOM_ITEM_CD
    ,   ITEM.ITEM_NAME
    ,   ITEM.STYLE_OF_PACKING
    ,   ITEM.OTHER_COMPANY_CD1
    ,   NAMES.NAME01 AS UNIT_OF_STOCK_CONTROL
    ,   ITEM.ALL_UP_WEIGHT
    ,   ITEM.NUMBER_OF_INSERTIONS
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_01 ITEM_CD1
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_02 ITEM_CD2
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_03 ITEM_CD3
    FROM
        ORDER_VENDER_EX ORDER_VENDER_MASTER
    INNER JOIN
        ORDER_VENDER_ITEM
    ON
        ORDER_VENDER_MASTER.VENDER_GROUP_CD = ORDER_VENDER_ITEM.VENDER_GROUP_CD
    LEFT JOIN 
        ITEM 
    ON 
        ITEM.ITEM_CD = ORDER_VENDER_ITEM.SOM_ITEM_CD
    LEFT JOIN
    	NAMES
    ON
    	NAMES.NAME_DIVISION = 'UNIT'
    	AND NAMES.NAME_CD = ITEM.UNIT_OF_STOCK_CONTROL
    GROUP BY
        ORDER_VENDER_ITEM.SOM_ITEM_CD
    ,   ITEM.ITEM_NAME
    ,   ITEM.STYLE_OF_PACKING
    ,   ITEM.OTHER_COMPANY_CD1
    ,   NAMES.NAME01 
    ,   ITEM.ALL_UP_WEIGHT
    ,   ITEM.NUMBER_OF_INSERTIONS
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_01
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_02
    ,   ORDER_VENDER_ITEM.CTM_ITEM_CD_03
    UNION ALL
    SELECT
        SALES_TERMS.ITEM_CD AS SOM_ITEM_CD
    ,   ITEM.ITEM_NAME
    ,   ITEM.STYLE_OF_PACKING
    ,   ITEM.OTHER_COMPANY_CD1
    ,   NAMES.NAME01 AS UNIT_OF_STOCK_CONTROL
    ,   ITEM.ALL_UP_WEIGHT
    ,   ITEM.NUMBER_OF_INSERTIONS
    ,   NULL AS ITEM_CD1
    ,   NULL AS ITEM_CD2
    ,   NULL AS ITEM_CD3
    FROM
        SALES_TERMS
    INNER JOIN
        ORDER_VENDER_EX ORDER_VENDER_MASTER
    ON
        ORDER_VENDER_MASTER.BALANCE_CD = SALES_TERMS.BALANCE_CD
    INNER JOIN 
        ITEM 
    ON 
        ITEM.ITEM_CD = SALES_TERMS.ITEM_CD
    LEFT JOIN
    	NAMES
    ON
    	NAMES.NAME_DIVISION = 'UNIT'
    	AND NAMES.NAME_CD = ITEM.UNIT_OF_STOCK_CONTROL
    GROUP BY 
        SALES_TERMS.ITEM_CD
    ,   ITEM.ITEM_NAME
    ,   ITEM.STYLE_OF_PACKING
    ,   ITEM.OTHER_COMPANY_CD1
    ,   NAMES.NAME01 
    ,   ITEM.ALL_UP_WEIGHT
    ,   ITEM.NUMBER_OF_INSERTIONS
) TMP
GROUP BY
    TMP.SOM_ITEM_CD
ORDER BY
    TMP.SOM_ITEM_CD
