/*
 * Created on 2009/03/09
 *
 * $copyright$
 *
 */

/**
 * 納期回答まとめ入力画面納入先取得用SQL
 *
 * @author tosco
 *
 * entityName=PurchaseDeliverySumDetail
 * packageName=purchasedelivery
 * methodName=getLocation
 *
 */
SELECT
		(CASE	-- 購買.納入ﾛｹｰｼｮﾝｺｰﾄﾞの場合はｵｰﾀﾞｰ区分によりﾛｹｰｼｮﾝまたは納入先の名称、発注まとめ場所の場合はﾛｹｰｼｮﾝの名称
			WHEN PURCHASE_SUBCONTRACT.TBL = 'PURCHASE_SUBCONTRACT' THEN 
					(CASE
						WHEN PURCHASE_SUBCONTRACT.ORDER_DIVISION IN (1, 2, 3, 6) THEN LOCATION.LOCATION_NAME
						WHEN PURCHASE_SUBCONTRACT.ORDER_DIVISION IN (4, 5) THEN DELIVERY.DELIVERY_NAME1
						ELSE NULL
					 END )
			WHEN PURCHASE_SUBCONTRACT.TBL = 'ITEM_QUEUE' THEN LOCATION.LOCATION_NAME
			ELSE NULL
		 END
		) AS LOCATION_NAME
FROM	(
		SELECT	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO
		,		PURCHASE_SUBCONTRACT.ORDER_DIVISION
		,		DECODE(VALID_ITEM_QUEUE.ORDER_LOCATION, NULL, 'PURCHASE_SUBCONTRACT'
													  , 'ITEM_QUEUE'
					  ) AS TBL
		,		DECODE(VALID_ITEM_QUEUE.ORDER_LOCATION, NULL, PURCHASE_SUBCONTRACT.LOCATION_CD
													  , VALID_ITEM_QUEUE.ORDER_LOCATION
					  ) AS LOCATION
		FROM	(SELECT	ORDER_SHEET_NO
				 ,		ORDER_DIVISION
				 ,		ITEM_CD
				 ,		LOCATION_CD
				 FROM PURCHASE_SUBCONTRACT
				 WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
				 /*IF (( orderSheetNo != null ) && ( orderSheetNo != "" ))*/
					AND	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO = /*orderSheetNo*/'1'
				 /*END*/
				 AND	PURCHASE_SUBCONTRACT.STATUS IN (2, 3, 4)
				 AND	(PURCHASE_SUBCONTRACT.ORDER_DIVIDE_NO IS NULL AND PURCHASE_SUBCONTRACT.ROW_NO IN (0, 1))
				 AND	ROWNUM <= 1
				) PURCHASE_SUBCONTRACT
		,		VALID_ITEM_QUEUE
		,		VALID_ITEM_QUEUE MAX_ITEM
		WHERE	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO IS NOT NULL
		AND		PURCHASE_SUBCONTRACT.ITEM_CD = VALID_ITEM_QUEUE.ITEM_CD(+) 
		AND 	VALID_ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD(+)
		AND 	VALID_ITEM_QUEUE.VERSION = MAX_ITEM.VERSION(+)
		) PURCHASE_SUBCONTRACT
,		LOCATION
,		DELIVERY
WHERE	PURCHASE_SUBCONTRACT.LOCATION = LOCATION.LOCATION_CD(+)
AND		PURCHASE_SUBCONTRACT.LOCATION = DELIVERY.DELIVERY_CD(+)

