/*
 * Created on 2009/03/12
 *
 * $copyright$
 *
*/

/**
 * 納期回答入力用SQL
 *
 * @author tosco
 *
 * entityName=PurchaseDeliveryDetailList
 * packageName=purchasedelivery
 * methodName=getEntity
 *
 */
SELECT	PURCHASE_SUBCONTRACT.PURCHASE_NO
,	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO
,   PURCHASE_SUBCONTRACT.ORDER_DIVIDE_NO
,	PURCHASE_SUBCONTRACT.SI_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DATE
,	PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.TANTO_CD
,	PURCHASE_SUBCONTRACT.ORDER_DIVISION
,	PURCHASE_SUBCONTRACT.VENDER_CD
,	PURCHASE_SUBCONTRACT.ITEM_CD
,	PURCHASE_SUBCONTRACT.ITEM_NAME
,	PURCHASE_SUBCONTRACT.ORDER_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.SUGGESTED_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_REMARK
,	PURCHASE_SUBCONTRACT.REMARK
,	PURCHASE_SUBCONTRACT.NOTES
,	PURCHASE_SUBCONTRACT.LOCATION_CD
,	PURCHASE_SUBCONTRACT.STATUS
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO
,	PURCHASE_SUBCONTRACT.REPLY_CONTENTS_DIVISION
,	PURCHASE_SUBCONTRACT.INPUT_DATE
,	PURCHASE_SUBCONTRACT.INPUTOR_CD
,	PURCHASE_SUBCONTRACT.UPDATE_DATE
,	PURCHASE_SUBCONTRACT.UPDATOR_CD
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, PURCHASE_SUBCONTRACT.ITEM_NAME
												 , ITEM.ITEM_NAME
		  ) AS ITEM_QUEUE_NAME							-- 品目名称
,	ITEM.STYLE_OF_PACKING								-- 荷姿
,	ITEM.OTHER_COMPANY_CD1								-- 他社コード1
,	VENDER.VENDER_SHORTED_NAME AS VENDER_NAME						-- 取引先略称
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, DELIVERY.DELIVERY_NAME1
											  ,	5, DELIVERY.DELIVERY_NAME1
												 , LOCATION.LOCATION_NAME
		  ) AS LOCATION_NAME								-- ロケーション名称
,	ORG.ORGANIZATION_NAME									-- 部署名称
,	TANTO_ORG.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME	-- 担当部署名称
,	LOGIN.TANTO_NM											-- 担当者名称
,	NAMES.NAME01 AS UNIT									-- 単位
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV		-- 運用管理単位(区分)
FROM	PURCHASE_SUBCONTRACT
,		ITEM
,		(SELECT VENDER_CD
		 ,		VENDER_NAME1
		 ,		VENDER_SHORTED_NAME
		 FROM VENDER
		 WHERE VENDER_DIVISION = 'SI'
		) VENDER
,		LOCATION
,		DELIVERY
,		ORGANIZATION ORG
,		ORGANIZATION TANTO_ORG
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'UNIT'
		) NAMES
,		LOGIN
WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
/*IF (( purchaseNo != null ) && ( purchaseNo != "" ))*/
	AND	PURCHASE_SUBCONTRACT.PURCHASE_NO = /*purchaseNo*/'00002744'
/*END*/
AND PURCHASE_SUBCONTRACT.ITEM_CD = ITEM.ITEM_CD(+) 
AND ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND PURCHASE_SUBCONTRACT.VENDER_CD = VENDER.VENDER_CD(+) 
AND PURCHASE_SUBCONTRACT.LOCATION_CD = LOCATION.LOCATION_CD(+) 
AND PURCHASE_SUBCONTRACT.LOCATION_CD = DELIVERY.DELIVERY_CD(+) 
AND PURCHASE_SUBCONTRACT.ORGANIZATION_CD = ORG.ORGANIZATION_CD(+) 
AND PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD = TANTO_ORG.ORGANIZATION_CD(+) 
AND PURCHASE_SUBCONTRACT.TANTO_CD = LOGIN.TANTO_CD(+) 
