/*
 * 相殺入力：買掛残リスト表示用SQL(検索ボタン押下時：新規)
 *
 * entityName=OffsetPayable
 * packageName=payment.offset
 * methodName=getPayableNew
 *
 */
SELECT PYB_HDR.PAYABLE_NO
,      PYB_HDR.ORGANIZATION_CD
,      PYB_HDR.SUPPLIER_CD
,      VND.VENDER_NAME1 AS SUPPLIER_NAME
,      PYB_HDR.PAYABLE_DATE
,      PYB_HDR.OFFSET_AMOUNT
,      PYB_HDR.PAYABLE_AMOUNT
,      SUM(PAYABLE_AMOUNT)
         OVER(ORDER BY PYB_HDR.SUPPLIER_CD)
           AS TOTAL_PAYABLE_AMOUNT

FROM (	SELECT PYH.PAYABLE_NO
		,      PYH.ORGANIZATION_CD
		,      PYH.SUPPLIER_CD
		,      PYH.PAYABLE_DATE
		,      PYH.OFFSET_AMOUNT
/*IF payableFlg == 1 */
		,      PYH.ACCOUNT_PAYABLE_BREAKDOWN AS PAYABLE_AMOUNT
/*END*/
/*IF payableFlg == 2 */
		,      PYH.ARREARAGE_BREAKDOWN AS PAYABLE_AMOUNT
/*END*/
		FROM PAYABLE_HEADER PYH,
		     (	SELECT ORGANIZATION_CD
				,      SUPPLIER_CD
				,      MAX(PAYABLE_DATE) AS PAYABLE_DATE
				FROM   PAYABLE_HEADER
				GROUP BY ORGANIZATION_CD
				,        SUPPLIER_CD 
		     ) PYH_MAX
		WHERE PYH.ORGANIZATION_CD = PYH_MAX.ORGANIZATION_CD
		AND   PYH.SUPPLIER_CD = PYH_MAX.SUPPLIER_CD
		AND   PYH.PAYABLE_DATE = PYH_MAX.PAYABLE_DATE
/*IF payableFlg == 1 */
		AND   ( PYH.ACCOUNT_PAYABLE_BREAKDOWN > 0 )
/*END*/
/*IF payableFlg == 2 */
		AND   ( PYH.ARREARAGE_BREAKDOWN > 0  )
/*END*/
	 ) PYB_HDR
	 LEFT JOIN VENDER VND
     ON   VND.VENDER_DIVISION = 'SI'
	 AND  PYB_HDR.SUPPLIER_CD = VND.VENDER_CD
       
WHERE PYB_HDR.PAYABLE_NO IS NOT NULL
  AND PYB_HDR.SUPPLIER_CD IN  (	SELECT VENDER_CD
								FROM OFFSET_GROUP
								WHERE OFFSET_GROUP_CD = /*offsetGroupCd*/'%'
							  )
ORDER BY PYB_HDR.SUPPLIER_CD
