/*
 * 請求残高帳票用SQL
 *
 * entityName=ClaimBalanceListForReport
 * packageName=balancelistforreport
 * methodName=getListForReport
 *
 */
SELECT *
FROM
(
/*IF (condition.srhNormalFlg)*/
SELECT CLM_HED.*
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.VENDER_NAME1
, VENDER.VENDER_SHORTED_NAME

, CREDIT_AMOUNT_FORWARD
+ OTHER_CREDIT_AMOUNT_FORWARD OTHER_CREDIT --画面用.入金・その他計

, OTHER_SALES_AMOUNT
- SALES_RETURNED_AMOUNT
- SALES_DISCOUNT_AMOUNT
- OFFSET_AMOUNT OTHER_SALES --画面用.その他計

, VENDER.CREDIT_LIMIT_PRICE
, ISSUER.TANTO_NM ISSUER_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME
, FUN_GET_CLAIM_TAX_AMOUNT(CLM_HED.CLAIM_NO) AS FUN_TAX_AMOUNT

FROM CLAIM_HEADER CLM_HED
, ORGANIZATION
, VENDER
, LOGIN ISSUER
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE CLM_HED.ORGANIZATION_CD IS NOT NULL
AND TO_CHAR(CLM_HED.CREDIT_DATE,'YYYY/MM') = /*condition.srhTargetMonth*/'2009/05'

/*IF (condition.srhOutputDivision)*/ --出力区分：残高有のみ（請求残高が0以外）
AND	CLM_HED.CLAIM_AMOUNT IS NOT NULL
AND CLM_HED.CLAIM_AMOUNT != 0
/*END*/

/*IF (condition.srhSectionCd != null && condition.srhSectionCd != "")*/
AND	(CLM_HED.ORGANIZATION_CD LIKE /*condition.srhSectionCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhSectionCd*/'%')
/*END*/

/*IF (condition.srhTantoCd != null && condition.srhTantoCd != "")*/
AND	(CLM_HED.INPUTOR_CD LIKE /*condition.srhTantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.srhTantoCd*/'%')
/*END*/

/*IF (condition.srhVenderCd != null && condition.srhVenderCd != "")*/
AND	(CLM_HED.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

AND CLM_HED.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND CLM_HED.VENDER_CD = VENDER.VENDER_CD(+)
AND CLM_HED.ISSUER_CD = ISSUER.TANTO_CD(+)
AND CLM_HED.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND CLM_HED.UPDATOR_CD = UPDATOR.TANTO_CD(+)

/*END*/

/*IF (condition.srhNormalFlg && condition.srhTempClosingFlg)*/
UNION
/*END*/

/*IF (condition.srhTempClosingFlg)*/
SELECT TMP_CLM_HED.*
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.VENDER_NAME1
, VENDER.VENDER_SHORTED_NAME

, CREDIT_AMOUNT_FORWARD
+ OTHER_CREDIT_AMOUNT_FORWARD OTHER_CREDIT --画面用.入金・その他計

, OTHER_SALES_AMOUNT
- SALES_RETURNED_AMOUNT
- SALES_DISCOUNT_AMOUNT
- OFFSET_AMOUNT OTHER_SALES --画面用.その他計

, VENDER.CREDIT_LIMIT_PRICE
, ISSUER.TANTO_NM ISSUER_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME
, FUN_GET_TEMP_CLAIM_TAX_AMOUNT(TMP_CLM_HED.CLAIM_NO) AS FUN_TAX_AMOUNT

FROM TEMPORARY_CLAIM_HEADER TMP_CLM_HED
, ORGANIZATION
, VENDER
, LOGIN ISSUER
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE TMP_CLM_HED.ORGANIZATION_CD IS NOT NULL
AND TO_CHAR(TMP_CLM_HED.CREDIT_DATE,'YYYY/MM') = /*condition.srhTargetMonth*/'2009/05'

/*IF (condition.srhOutputDivision)*/
AND	TMP_CLM_HED.CLAIM_AMOUNT IS NOT NULL
AND TMP_CLM_HED.CLAIM_AMOUNT != 0
/*END*/

/*IF (condition.srhSectionCd != null && condition.srhSectionCd != "")*/
AND	(TMP_CLM_HED.ORGANIZATION_CD LIKE /*condition.srhSectionCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhSectionCd*/'%')
/*END*/

/*IF (condition.srhTantoCd != null && condition.srhTantoCd != "")*/
AND	(TMP_CLM_HED.INPUTOR_CD LIKE /*condition.srhTantoCd*/'%' OR INPUTOR.TANTO_NM LIKE /*condition.srhTantoCd*/'%')
/*END*/

/*IF (condition.srhVenderCd != null && condition.srhVenderCd != "")*/
AND	(TMP_CLM_HED.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

AND TMP_CLM_HED.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND TMP_CLM_HED.VENDER_CD = VENDER.VENDER_CD(+)
AND TMP_CLM_HED.ISSUER_CD = ISSUER.TANTO_CD(+)
AND TMP_CLM_HED.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND TMP_CLM_HED.UPDATOR_CD = UPDATOR.TANTO_CD(+)

/*END*/
)

ORDER BY VENDER_CD


