/*
 * 取引先帳票用SQL
 *
 * entityName=VenderListForReport
 * packageName=venderlistforreport
 * methodName=getListForReport
 *
 */

SELECT VENDER.*
, INVOICE.VENDER_SHORTED_NAME PAYMENT_INVOICE_NAME
, LOGIN.TANTO_NM
, AREA.AREA_NAME
, BANK.BANK_MASTER_NAME
, BUMON.SECTION_NAME
, ACCOUNTS.ACCOUNTS_NAME
, CAL.CAL_NAME
, OTHER_BANK.BANK_MASTER_NAME OTHER_BANK_MASTER_NAME
, ORGANIZATION.ORGANIZATION_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME
, MAIL_ORGANIZATION.ORGANIZATION_NAME MAIL_ORGANIZATION_NAME

FROM VENDER
, VENDER INVOICE
, LOGIN
, AREA
, BANK
, BUMON
, ACCOUNTS
, BANK OTHER_BANK
, ORGANIZATION
, LOGIN INPUTOR
, LOGIN UPDATOR
, ORGANIZATION MAIL_ORGANIZATION

, (SELECT CAL.CAL_CD, CAL.CAL_NAME
FROM CAL,

(SELECT CAL_CD, MAX(CAL_YEAR) CAL_YEAR
FROM CAL
GROUP BY CAL_CD) MAX_CAL

WHERE CAL.CAL_CD = MAX_CAL.CAL_CD
AND CAL.CAL_YEAR = MAX_CAL.CAL_YEAR
GROUP BY CAL.CAL_CD, CAL.CAL_NAME) CAL

WHERE VENDER.VENDER_DIVISION = /*condition.srhVenderDivision*/'%'

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND	(VENDER.VENDER_CD LIKE /*condition.srhVenderCd*/'%'
OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%')
OR VENDER.VENDER_NAME2 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

/*IF (condition.srhOrganizationCd != null) && (condition.srhOrganizationCd != "")*/
AND	(VENDER.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/'%' OR ORGANIZATION.ORGANIZATION_NAME LIKE /*condition.srhOrganizationCd*/'%')
/*END*/

AND VENDER.VENDER_DIVISION = INVOICE.VENDER_DIVISION(+)
AND VENDER.PAYMENT_INVOICE_CD = INVOICE.VENDER_CD(+)
AND VENDER.TANTO_CD = LOGIN.TANTO_CD(+)
AND VENDER.AREA_CD = AREA.AREA_CD(+)
AND VENDER.BANK_CD = BANK.BANK_MASTER_CD(+)
AND VENDER.SECTION_CD = BUMON.SECTION_CD(+)
AND VENDER.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
AND VENDER.CALENDAR_CD = CAL.CAL_CD(+)
AND VENDER.OTHER_BANK_CD = OTHER_BANK.BANK_MASTER_CD(+)
AND VENDER.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND VENDER.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND VENDER.MAIL_ORGANIZATION_CD = MAIL_ORGANIZATION.ORGANIZATION_CD(+)

ORDER BY VENDER.VENDER_CD
