/*
 * 仕入先別単価マスタ検索帳票用SQL
 * entityName=UnitpriceListForReport
 * packageName=unitpriceiistforreport
 * methodName=getListForReport
 *
 */
SELECT UNITPRICE.*
, VENDER.VENDER_SHORTED_NAME AS VENDER_NAME1
, ITEM_QUEUE.ITEM_NAME
, ITEM_QUEUE.STYLE_OF_PACKING
, PURCHASE_ATTRIBUTE_QUEUE.MATERIAL_MAKER_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM UNITPRICE
, VENDER
, VALID_ITEM_QUEUE ITEM_QUEUE
, PURCHASE_ATTRIBUTE_QUEUE
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE UNITPRICE.VENDER_DIVISION = /*condition.srhVenderDivision*/'SI'

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (UNITPRICE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (UNITPRICE.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

AND	VENDER.VENDER_DIVISION(+) = UNITPRICE.VENDER_DIVISION
AND UNITPRICE.VENDER_CD = VENDER.VENDER_CD(+)
AND UNITPRICE.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE_ATTRIBUTE_QUEUE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE_ATTRIBUTE_QUEUE.VERSION(+)
AND UNITPRICE.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND UNITPRICE.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY UNITPRICE.VENDER_CD, UNITPRICE.ITEM_CD, UNITPRICE.CONSECUTIVE_NO, UNITPRICE.VALID_DATE
