/*
 * Created on 2009/03/05
 *
 * $copyright$
 *
 */

/**
 * 受入入力 受注関連データ取得SQL
 * (売上データ登録用)
 *
 * @author tosco
 *
 * entityName=AcceptDetailSales
 * packageName=accept
 * methodName=getSalesData
 *
 */
SELECT	ORDER_HEAD.ORDER_NO						-- 受注番号
,		ORDER_DETAIL.ROW_NO AS ORDER_ROW_NO		-- 行番号(受注)
,		ORDER_DETAIL.ITEM_CD					-- 品目コード
,		ORDER_HEAD.VENDER_CD					-- 得意先コード
,		ORDER_HEAD.BALANCE_CD					-- 帳合コード
,		DELIVERY.TANTO_CD AS SALES_TANTO_CD					-- 営業担当者コード
,		ORDER_DETAIL.ORDER_UNITPRICE AS SALES_UNITPRICE		-- 受注単価
,		ORDER_DETAIL.STANDARD_UNITPRICE			-- 標準単価
,		ORDER_DETAIL.STANDARD_DISCOUNT			-- 標準値引
,		ORDER_DETAIL.SPECIAL_DISCOUNT			-- 特別値引
,		ORDER_DETAIL.TMP_UNITPRICE_FLG AS TMP_UNITPRICE_FLG	-- 仮単価FLG
,		ORDER_HEAD.ORDER_SUMMERY AS REMARK		-- 受注時備考
,		ORDER_HEAD.DELIVERY_CD					-- 納入先コード
,		(CASE		-- 販売品扱い属性.売上消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
			WHEN NVL(ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION,4) = 4 THEN
				(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税課税区分
					WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
					ELSE VENDER.TAX_DIVISION	-- 取引先ﾏｽﾀ.消費税区分
				 END )
			ELSE ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION	-- 販売品扱い属性.売上消費税課税区分
		 END
		) AS TAX_DIVISION		-- 消費税課税区分
,		VENDER.CALC_DIVISION					-- 取引先マスタ.算出区分
,		(SELECT CALC_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001') AS COMP_CALC_DIVISION	-- 自社マスタ.消費税算出区分
,		NVL(VENDER.PAYMENT_INVOICE_CD, VENDER.VENDER_CD) AS INVOICE_CD	-- 請求先コード
,		(CASE		-- 販売品扱い属性.売上消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
			WHEN NVL(ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION,4) = 4 THEN
				(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税率
					WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_RATIO FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
					ELSE VENDER.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
				 END )
			ELSE VENDER.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
		 END
		) AS TAX_RATIO		-- 消費税率
,		TO_CHAR(
				  TO_DATE(TO_CHAR(ORDER_HEAD.SCHEDULED_SHIPPING_DATE, 'YYYY/MM/DD'), 'YYYY/MM/DD') + NVL(DELIVERY.LEAD_TIME, 0)
				, 'YYYYMM'
			   ) AS ACCOUNT_YEARS				-- 勘定年月
,		(SELECT DATA_TOTAL_DIVISION
		 FROM CLASSIFICATION
		 WHERE DATA_TYPE = 1
		 AND   CATEGORY_DIVISION = '1'
		 AND   ROWNUM <= 1
		) AS DATA_TOTAL_DIVISION				-- ﾃﾞｰﾀ集計区分
,		VENDER.SECTION_CD AS ACCOUNT_DEBIT_SECTION_CD					-- 会計部門借方コード
,		ARTICLE_ATTRIBUTE_QUEUE.SECTION_CD AS ACCOUNT_CREDIT_SECTION_CD	-- 会計部門貸方コード
,		VENDER.ACCOUNTS_CD AS DEBIT_TITLE_CD					-- 借方科目コード
,		ARTICLE_ATTRIBUTE_QUEUE.ACCOUNTS_CD AS CREDIT_TITLE_CD	-- 貸方科目コード
,		VENDER.ORGANIZATION_CD AS CHARGE_ORGANIZATION_CD		-- 担当部署(得意先)
,		ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV			-- 運用管理単位(区分)
FROM	ORDER_HEAD					-- 受注ヘッダ
,		ORDER_DETAIL				-- 受注明細 
,		DELIVERY					-- 納入先マスタ
,		ITEM						-- 品目マスタ
,		ARTICLE_ATTRIBUTE_QUEUE		-- 販売品扱い属性キュー
,		(SELECT VEN.VENDER_CD
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_DIVISION, INVOICE.TAX_DIVISION) AS TAX_DIVISION	-- 消費税区分(得意先or請求先)
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.CALC_DIVISION, INVOICE.CALC_DIVISION) AS CALC_DIVISION	-- 算出区分(得意先or請求先)
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_RATIO, INVOICE.TAX_RATIO) AS TAX_RATIO				-- 消費税率(得意先or請求先)
		 ,		VEN.PAYMENT_INVOICE_CD	-- 支払･請求先コード
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.SECTION_CD, INVOICE.SECTION_CD) AS SECTION_CD			-- 会計部門コード(得意先or請求先)
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.ACCOUNTS_CD, INVOICE.ACCOUNTS_CD) AS ACCOUNTS_CD		-- 勘定科目コード(得意先or請求先)
		 ,		VEN.ORGANIZATION_CD		-- 部署コード
		 FROM VENDER VEN, VENDER INVOICE
		 WHERE VEN.VENDER_DIVISION = 'TS'
		 AND   VEN.PAYMENT_INVOICE_CD = INVOICE.VENDER_CD(+)
		 AND   INVOICE.VENDER_DIVISION(+) = 'TS'
		) VENDER
WHERE	ORDER_HEAD.ORDER_NO IS NOT NULL
AND	ORDER_HEAD.ORDER_NO = /*orderNo*/'JT000000192'
AND	ORDER_DETAIL.ORDER_NO = /*orderNo*/'JT000000192'
AND	ORDER_DETAIL.ROW_NO = /*rowNo*/1
AND ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
AND ORDER_HEAD.DELIVERY_CD = DELIVERY.DELIVERY_CD(+) 
AND ORDER_DETAIL.ITEM_CD = ITEM.ITEM_CD(+) 
AND ITEM.ITEM_CD = ARTICLE_ATTRIBUTE_QUEUE.ITEM_CD(+) 
AND ITEM.VERSION = ARTICLE_ATTRIBUTE_QUEUE.VERSION(+) 
AND ORDER_HEAD.VENDER_CD = VENDER.VENDER_CD(+)