/**
 *
 *
 * entityName=AcceptDetailSalesCarry
 * packageName=accept
 * methodName=getSalesData
 *
 */
SELECT	ORDER_HEAD.ORDER_NO
,		ORDER_DETAIL.ROW_NO AS ORDER_ROW_NO
,		ITEM.ITEM_CD
,		ORDER_HEAD.VENDER_CD
,		ORDER_HEAD.BALANCE_CD
,		DELIVERY.TANTO_CD AS SALES_TANTO_CD
,		ORDER_HEAD.ORDER_SUMMERY AS REMARK
,		ORDER_HEAD.DELIVERY_CD
,		(CASE
			WHEN ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION = 4 THEN
				(CASE
					WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
					ELSE VENDER.TAX_DIVISION
				 END )
			ELSE ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION
		 END
		) AS TAX_DIVISION
,		VENDER.CALC_DIVISION
,		(SELECT CALC_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001') AS COMP_CALC_DIVISION
,		NVL(VENDER.PAYMENT_INVOICE_CD, VENDER.VENDER_CD) AS INVOICE_CD
,		(CASE
			WHEN ARTICLE_ATTRIBUTE_QUEUE.TAX_DIVISION = 4 THEN
				(CASE
					WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_RATIO FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
					ELSE VENDER.TAX_RATIO
				 END )
			ELSE VENDER.TAX_RATIO
		 END
		) AS TAX_RATIO
,		TO_CHAR(
				  TO_DATE(TO_CHAR(ORDER_HEAD.SCHEDULED_SHIPPING_DATE, 'YYYY/MM/DD'), 'YYYY/MM/DD') + NVL(DELIVERY.LEAD_TIME, 0)
				, 'YYYYMM'
			   ) AS ACCOUNT_YEARS
,		(SELECT DATA_TOTAL_DIVISION
		 FROM CLASSIFICATION
		 WHERE DATA_TYPE = 1
		 AND   CATEGORY_DIVISION = '1'
		 AND   ROWNUM <= 1
		) AS DATA_TOTAL_DIVISION
,		VENDER.SECTION_CD AS ACCOUNT_DEBIT_SECTION_CD
,		ARTICLE_ATTRIBUTE_QUEUE.SECTION_CD AS ACCOUNT_CREDIT_SECTION_CD
,		VENDER.ACCOUNTS_CD AS DEBIT_TITLE_CD
,		ARTICLE_ATTRIBUTE_QUEUE.ACCOUNTS_CD AS CREDIT_TITLE_CD
,		VENDER.ORGANIZATION_CD AS CHARGE_ORGANIZATION_CD
,		ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV
FROM	ORDER_HEAD
,		ORDER_DETAIL
,		DELIVERY
,		ITEM
,		ARTICLE_ATTRIBUTE_QUEUE
,		(SELECT VEN.VENDER_CD
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_DIVISION, INVOICE.TAX_DIVISION) AS TAX_DIVISION
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.CALC_DIVISION, INVOICE.CALC_DIVISION) AS CALC_DIVISION
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_RATIO, INVOICE.TAX_RATIO) AS TAX_RATIO
		 ,		VEN.PAYMENT_INVOICE_CD
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.SECTION_CD, INVOICE.SECTION_CD) AS SECTION_CD
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.ACCOUNTS_CD, INVOICE.ACCOUNTS_CD) AS ACCOUNTS_CD
		 ,		VEN.ORGANIZATION_CD
		 FROM VENDER VEN, VENDER INVOICE
		 WHERE VEN.VENDER_DIVISION = 'TS'
		 AND   VEN.PAYMENT_INVOICE_CD = INVOICE.VENDER_CD(+)
		 AND   INVOICE.VENDER_DIVISION(+) = 'TS'
		) VENDER
WHERE	ORDER_HEAD.ORDER_NO IS NOT NULL
AND	ORDER_HEAD.ORDER_NO = /*orderNo*/'JT200901017'
AND	ORDER_DETAIL.ORDER_NO = /*orderNo*/'JT200901017'
AND	ORDER_DETAIL.ROW_NO = /*rowNo*/1
AND ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
AND ORDER_HEAD.DELIVERY_CD = DELIVERY.DELIVERY_CD(+) 
AND ITEM.ITEM_CD = /*itemCd*/''
AND ITEM.ITEM_CD = ARTICLE_ATTRIBUTE_QUEUE.ITEM_CD(+) 
AND ITEM.VERSION = ARTICLE_ATTRIBUTE_QUEUE.VERSION(+) 
AND ORDER_HEAD.VENDER_CD = VENDER.VENDER_CD(+)

