/**
 * 受入 入力用SQL
 *
 * @author tosco
 *
 * entityName=AcceptDetailList
 * packageName=accept
 * methodName=getEntity
 *
 */
SELECT	PURCHASE_SUBCONTRACT.PURCHASE_NO
,	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DIVIDE_NO
,	PURCHASE_SUBCONTRACT.MATERIAL_DIVISION
,	PURCHASE_SUBCONTRACT.SI_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DATE
,	PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.TANTO_CD
,	PURCHASE_SUBCONTRACT.ORDER_DIVISION
,	PURCHASE_SUBCONTRACT.VENDER_CD
,	PURCHASE_SUBCONTRACT.ITEM_CD
,	PURCHASE_SUBCONTRACT.ITEM_NAME
,	PURCHASE_SUBCONTRACT.ORDER_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.SUGGESTED_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.LOCATION_CD
,	PURCHASE_SUBCONTRACT.STATUS
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO
,	PURCHASE_SUBCONTRACT.REPLY_CONTENTS_DIVISION
,	PURCHASE_SUBCONTRACT.DELIVERY_COMP
,	PURCHASE_SUBCONTRACT.NEXT_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.CATEGORY_DIVISION
,	PURCHASE_SUBCONTRACT.SLIP_NO
,	PURCHASE_SUBCONTRACT.ROW_NO
,	PURCHASE_SUBCONTRACT.SUPPLIER_LOTNO
,	PURCHASE_SUBCONTRACT.LOT_NO
,	PURCHASE_SUBCONTRACT.INCREASE_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_REMARK2
,	PURCHASE_SUBCONTRACT.REMARK2
,	PURCHASE_SUBCONTRACT.NOTES2
,	PURCHASE_SUBCONTRACT.STATUS2
,	PURCHASE_SUBCONTRACT.INPUT_DATE
,	PURCHASE_SUBCONTRACT.INPUTOR_CD
,	PURCHASE_SUBCONTRACT.UPDATE_DATE
,	PURCHASE_SUBCONTRACT.UPDATOR_CD
,	PURCHASE_SUBCONTRACT.ARRIVAL_QUANTITY
,	NVL(ITEM.TYPE_DIVISION, '') AS TYPE_DIVISION		-- 種別
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, PURCHASE_SUBCONTRACT.ITEM_NAME
												 , ITEM.ITEM_NAME
		  ) AS ITEM_QUEUE_NAME								-- 品目名称
,	ITEM.STYLE_OF_PACKING								-- 荷姿
,	ITEM.OTHER_COMPANY_CD1							-- 他社コード1
,	ITEM.KG_OF_FRACTION_MANAGEMENT					-- Kg換算係数(在庫)
,	VENDER.VENDER_NAME1 AS VENDER_NAME						-- 取引先名称1
,	VENDER.VENDER_SHORTED_NAME AS VENDER_SHORTED_NAME		-- 取引先略称
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, DELIVERY.SEARCH_KANA
											  ,	5, DELIVERY.SEARCH_KANA
												 , LOCATION.LOCATION_NAME
		  ) AS LOCATION_NAME								-- ロケーション名称
,	ORG.ORGANIZATION_NAME									-- 部署名称
,	TANTO_ORG.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME	-- 担当部署名称
,	NAMES.NAME01 AS UNIT									-- 単位
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV		-- 運用管理単位(区分)
	/*IF (kbn == "A" )*/	-- 原材料(自社)ローリー以外
,	JISSEKI_GENZAIRYO.LOCATION AS HOUSING_LOCATION_CD			-- 入庫ロケーション
,	NVL(JISSEKI_GENZAIRYO.SUM_SUURYOU,0) AS ACCEPT_QUANTITY	-- 受入数量
,   JISSEKI_GENZAIRYO.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "B" )*/	-- 原材料(自社)ローリー
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "C" )*/	-- 原材料(外注)
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "D" )*/	-- 外注製品(直送)
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "E" )*/	-- 外注製品(非直送)
,	JISSEKI_SEIHIN.LOCATION AS HOUSING_LOCATION_CD
,	NVL(JISSEKI_SEIHIN.SUM_SUURYOU, 0) AS ACCEPT_QUANTITY
,   JISSEKI_SEIHIN.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "F" )*/	-- 仕入直送品
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "G" )*/	-- スポット品
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
	/*END*/
	/*IF (kbn == "H" )*/	-- 仕入在庫品
,	JISSEKI_SEIHIN.LOCATION AS HOUSING_LOCATION_CD
,	NVL(JISSEKI_SEIHIN.SUM_SUURYOU, 0) AS ACCEPT_QUANTITY
,   JISSEKI_SEIHIN.ACCEPT_DATE
	/*END*/
,   CASE
      WHEN VENDER.SI_INVOICE_PTN = '2'
          THEN '1'
      ELSE '0'
      END REDUCED_TAX_TARGET_FLG	-- 0：免税の計算対象外 1：免税の計算対象

FROM	PURCHASE_SUBCONTRACT
,		ITEM
,		(SELECT VENDER_CD
		 ,		VENDER_NAME1
		 ,		VENDER_SHORTED_NAME
		 ,      SI_INVOICE_PTN
		 FROM VENDER
		 WHERE VENDER_DIVISION = 'SI'
		) VENDER
,		LOCATION
,		DELIVERY
,		ORGANIZATION ORG
,		ORGANIZATION TANTO_ORG
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'UNIT'
		) NAMES
,		(SELECT TRIM(TRAILING FROM NYUKALOT) NYUKALOT
		 ,		TRIM(TRAILING FROM MAX(LOCATION)) LOCATION		--	ロケーション
		 ,		SUM(NISUGATASU) SUM_SUURYOU	--	未開封数合計
         ,      TRUNC(MIN(JIKOKU)) AS ACCEPT_DATE
		 FROM JISSEKI_GENZAIRYO
		 GROUP BY NYUKALOT
		) JISSEKI_GENZAIRYO
,		(SELECT TRIM(TRAILING FROM NYUKABC) NYUKABC
		 ,		TRIM(TRAILING FROM LOCATION) LOCATION		--	ロケーション
		 ,		SUM(SUURYOU) SUM_SUURYOU	--	入出庫数合計
         ,      TRUNC(MIN(JIKOKU)) AS ACCEPT_DATE
		 FROM JISSEKI_SEIHIN
		 GROUP BY NYUKABC,location
		) JISSEKI_SEIHIN

WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
/*IF (( purchaseNo != null ) && ( purchaseNo != "" ))*/
	AND	PURCHASE_SUBCONTRACT.PURCHASE_NO = /*purchaseNo*/'1259'
/*END*/
AND PURCHASE_SUBCONTRACT.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND PURCHASE_SUBCONTRACT.VENDER_CD = VENDER.VENDER_CD(+)
AND PURCHASE_SUBCONTRACT.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND PURCHASE_SUBCONTRACT.LOCATION_CD = DELIVERY.DELIVERY_CD(+)
AND PURCHASE_SUBCONTRACT.ORGANIZATION_CD = ORG.ORGANIZATION_CD(+)
AND PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD = TANTO_ORG.ORGANIZATION_CD(+)
AND PURCHASE_SUBCONTRACT.LOT_NO = JISSEKI_GENZAIRYO.NYUKALOT(+)
AND PURCHASE_SUBCONTRACT.LOT_NO = JISSEKI_SEIHIN.NYUKABC(+)
ORDER BY SLIP_NO
,		 ROW_NO
