/*
 * Created on 2009/02/27
 *
 * $copyright$
 *
*/

/**
 * 受入・仕入　仕入入力用SQL
 *
 * @author tosco
 *
 * entityName=AcceptBuyingDetailList
 * packageName=accept
 * methodName=getEntity
 *
 */
SELECT	PURCHASE_SUBCONTRACT.PURCHASE_NO
,	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DIVIDE_NO
,	PURCHASE_SUBCONTRACT.MATERIAL_DIVISION
,	PURCHASE_SUBCONTRACT.SI_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_DATE
,	PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.ORGANIZATION_CD
,	PURCHASE_SUBCONTRACT.TANTO_CD
,	PURCHASE_SUBCONTRACT.VENDER_CD
,	PURCHASE_SUBCONTRACT.ITEM_CD
,	PURCHASE_SUBCONTRACT.ITEM_NAME
,	PURCHASE_SUBCONTRACT.ORDER_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.SUGGESTED_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.LOCATION_CD
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO
,	PURCHASE_SUBCONTRACT.REPLY_CONTENTS_DIVISION
,	PURCHASE_SUBCONTRACT.DELIVERY_COMP
,	PURCHASE_SUBCONTRACT.NEXT_DELIVERLIMIT_DATE
,	PURCHASE_SUBCONTRACT.CATEGORY_DIVISION
,	PURCHASE_SUBCONTRACT.STOCKING_DATE
,	PURCHASE_SUBCONTRACT.SLIP_NO
,	PURCHASE_SUBCONTRACT.ROW_NO
,	PURCHASE_SUBCONTRACT.SUPPLIER_LOTNO
,	PURCHASE_SUBCONTRACT.LOT_NO
,	PURCHASE_SUBCONTRACT.HOUSING_LOCATION_CD
,	PURCHASE_SUBCONTRACT.ACCEPT_QUANTITY
,	PURCHASE_SUBCONTRACT.ACCEPT_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.INCREASE_QUANTITY
,	PURCHASE_SUBCONTRACT.STOCKING_QUANTITY
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, UNITPRICE.UNITPRICE
									 	,	5, UNITPRICE.UNITPRICE
											 , PURCHASE_SUBCONTRACT.HOUSING_UNITPRICE
		  ) AS HOUSING_UNITPRICE			-- 単価(取引先単価マスタ)／仕入単価
,	PURCHASE_SUBCONTRACT.FARE_AMOUNT
,	PURCHASE_SUBCONTRACT.STOCKING_AMOUNT
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_REMARK2
,	PURCHASE_SUBCONTRACT.REMARK2
,	PURCHASE_SUBCONTRACT.STATUS2
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, PURCHASE_ATTRIBUTE_QUEUE.SECTION_CD
										,	5, PURCHASE_ATTRIBUTE_QUEUE.SECTION_CD
											 , PURCHASE_SUBCONTRACT.ACCOUNT_DEBIT_SECTION_CD
		  ) AS ACCOUNT_DEBIT_SECTION_CD		-- 仕入会計部門コード／会計部門借方コード
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, VENDER.SECTION_CD
										,	5, VENDER.SECTION_CD
											 , PURCHASE_SUBCONTRACT.ACCOUNT_CREDIT_SECTION_CD
		  ) AS ACCOUNT_CREDIT_SECTION_CD	-- 買掛会計部門コード／会計部門貸方コード
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, PURCHASE_ATTRIBUTE_QUEUE.ACCOUNTS_CD
										,	5, PURCHASE_ATTRIBUTE_QUEUE.ACCOUNTS_CD
											 , PURCHASE_SUBCONTRACT.DEBIT_TITLE_CD
		  ) AS DEBIT_TITLE_CD				-- 仕入勘定科目コード／借方科目コード
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, VENDER.ACCOUNTS_CD
										,	5, VENDER.ACCOUNTS_CD
											 , PURCHASE_SUBCONTRACT.CREDIT_TITLE_CD
		  ) AS CREDIT_TITLE_CD				-- 買掛勘定科目コード／貸方科目コード
,	PURCHASE_SUBCONTRACT.CREDIT_TITLE_CD
,	PURCHASE_SUBCONTRACT.INPUT_DATE
,	PURCHASE_SUBCONTRACT.INPUTOR_CD
,	PURCHASE_SUBCONTRACT.UPDATE_DATE
,	PURCHASE_SUBCONTRACT.UPDATOR_CD
,	PURCHASE_SUBCONTRACT.TAX_AMOUNT
,	PURCHASE_SUBCONTRACT.TAX_CD
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, PURCHASE_SUBCONTRACT.ITEM_NAME,
												   ITEM.ITEM_NAME) AS ITEM_QUEUE_NAME	-- 品目名称
,	ITEM.STYLE_OF_PACKING							-- 荷姿
,	ITEM.OTHER_COMPANY_CD1							-- 他社コード1
,	ITEM.KG_OF_FRACTION_MANAGEMENT					-- Kg換算係数(在庫)
,	VENDER.VENDER_NAME1 AS VENDER_NAME				-- 取引先名称1
,	VENDER.VENDER_SHORTED_NAME AS VENDER_SHORTED_NAME	-- 取引先略称
,	DECODE(PURCHASE_SUBCONTRACT.ORDER_DIVISION, 4, DELIVERY.SEARCH_KANA,
												5, DELIVERY.SEARCH_KANA,
												LOCATION.LOCATION_NAME) AS LOCATION_NAME	-- ロケーション名称
,	ORG.ORGANIZATION_NAME									-- 部署名称
,	TANTO_ORG.ORGANIZATION_NAME AS CHARGE_ORGANIZATION_NAME	-- 担当部署名称
,	NAMES.NAME01 AS UNIT									-- 単位
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV			-- 運用管理単位(区分)
,	UNITPRICE.UNITPRICE_DIVISION							-- 単価区分(1:個あたり 2:KGあたり)
,	NAMES_COST.NAME01 AS UNITPRICE_UNIT						-- 単価単位

,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, DEBIT_BUMON_ITEM.SECTION_NAME
										,	5, DEBIT_BUMON_ITEM.SECTION_NAME
											 , DEBIT_BUMON.SECTION_NAME
		  ) AS ACCOUNT_DEBIT_SECTION_NAME		-- 仕入会計部門名称／会計部門借方名称
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, CREDIT_BUMON_VENDER.SECTION_NAME
										,	5, CREDIT_BUMON_VENDER.SECTION_NAME
											 , CREDIT_BUMON.SECTION_NAME
		  ) AS ACCOUNT_CREDIT_SECTION_NAME		-- 買掛会計部門名称／会計部門貸方名称
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, DEBIT_ACCOUNTS_ITEM.ACCOUNTS_NAME
										,	5, DEBIT_ACCOUNTS_ITEM.ACCOUNTS_NAME
											 , DEBIT_ACCOUNTS.ACCOUNTS_NAME
		  ) AS DEBIT_TITLE_NAME					-- 仕入勘定科目名称／借方勘定科目名称
,	DECODE(PURCHASE_SUBCONTRACT.STATUS2, NULL, CREDIT_ACCOUNTS_VENDER.ACCOUNTS_NAME
										,	5, CREDIT_ACCOUNTS_VENDER.ACCOUNTS_NAME
											 , CREDIT_ACCOUNTS.ACCOUNTS_NAME
		  ) AS CREDIT_TITLE_NAME				-- 買掛勘定科目名称／貸方勘定科目名称

,	(CASE		-- 購入品扱い属性.消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
		WHEN NVL(PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION,4) = 4 THEN
			(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税課税区分
				WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
				ELSE VENDER.TAX_DIVISION	-- 取引先ﾏｽﾀ.消費税区分
			 END )
		ELSE PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION	-- 購入品扱い属性.消費税課税区分
	 END
	) AS TAX_DIVISION		-- 消費税課税区分
,	(CASE		-- 販売品扱い属性.売上消費税課税区分＝4:取引先ﾏｽﾀの場合は次へ
		WHEN NVL(PURCHASE_ATTRIBUTE_QUEUE.TAX_DIVISION,4) = 4 THEN
			(CASE	-- 取引先ﾏｽﾀ.消費税区分＝4:自社ﾏｽﾀの場合は自社ﾏｽﾀ.消費税率
				WHEN VENDER.TAX_DIVISION = 4 THEN (SELECT TAX_RATIO FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001')
				ELSE VENDER.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
			 END )
		ELSE VENDER.TAX_RATIO	-- 取引先ﾏｽﾀ.消費税率
	 END
	) AS TAX_RATIO				-- 消費税率
,	VENDER.CALC_DIVISION		-- 取引先マスタ.算出区分
,	(SELECT CALC_DIVISION FROM COMPANY WHERE COMPANY_CD = /*companyCd*/'000001') AS COMP_CALC_DIVISION	-- 自社マスタ.消費税算出区分
,   VENDER.PAYMENT_INVOICE_CD
, CASE
    WHEN VENDER.SI_INVOICE_PTN = '2'
        THEN '1'
    ELSE '0'
    END REDUCED_TAX_TARGET_FLG	-- 0：免税の計算対象外 1：免税の計算対象
FROM	PURCHASE_SUBCONTRACT
,		ITEM
,		PURCHASE_ATTRIBUTE_QUEUE
		-- 支払先の情報を優先、NULLならば仕入先の情報を設定
,		(SELECT VEN.VENDER_CD
		 ,		VEN.VENDER_NAME1
		 ,		VEN.VENDER_SHORTED_NAME
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.SECTION_CD, PAYMENT.SECTION_CD) AS SECTION_CD			-- 会計部門コード
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.ACCOUNTS_CD, PAYMENT.ACCOUNTS_CD) AS ACCOUNTS_CD		-- 科目コード
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.CALC_DIVISION, PAYMENT.CALC_DIVISION) AS CALC_DIVISION	-- 算出区分
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_DIVISION, PAYMENT.TAX_DIVISION) AS TAX_DIVISION	-- 消費税区分
		 ,		DECODE(VEN.PAYMENT_INVOICE_CD, NULL, VEN.TAX_RATIO, PAYMENT.TAX_RATIO) AS TAX_RATIO				-- 消費税率
		 ,      VEN.PAYMENT_INVOICE_CD  AS PAYMENT_INVOICE_CD
		 ,      VEN.SI_INVOICE_PTN
		 FROM VENDER VEN, VENDER PAYMENT
		 WHERE	VEN.VENDER_DIVISION = 'SI'
		 AND	VEN.PAYMENT_INVOICE_CD = PAYMENT.VENDER_CD(+)
		 AND	PAYMENT.VENDER_DIVISION(+) = 'SI'
		) VENDER
,		LOCATION
,		DELIVERY
,		ORGANIZATION ORG
,		ORGANIZATION TANTO_ORG
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'UNIT'
		) NAMES
,		(SELECT	UNITPRICE.VENDER_CD
		,		UNITPRICE.ITEM_CD
		,		UNITPRICE.UNITPRICE
		,		UNITPRICE.UNITPRICE_DIVISION
		FROM
			(SELECT	VENDER_CD
			,		ITEM_CD
			,		MAX(VERSION) as VERSION
			,		CONSECUTIVE_NO
			FROM	UNITPRICE
			WHERE	VENDER_DIVISION = 'SI'	--仕入先 'SI'固定
			AND		CONSECUTIVE_NO = '1'  	--連番 '1'固定
			GROUP BY	VENDER_CD
			,			ITEM_CD
			,			CONSECUTIVE_NO
			)MAX_UNITPRICE
		,	UNITPRICE
		WHERE	UNITPRICE.VENDER_CD = MAX_UNITPRICE.VENDER_CD
		AND		UNITPRICE.ITEM_CD = MAX_UNITPRICE.ITEM_CD
		AND		UNITPRICE.VERSION = MAX_UNITPRICE.VERSION
		AND		UNITPRICE.CONSECUTIVE_NO = MAX_UNITPRICE.CONSECUTIVE_NO
		) UNITPRICE
,		(SELECT NAME_CD
		 ,		NAME01
		 FROM NAMES
		 WHERE	NAME_DIVISION = 'COST'
		) NAMES_COST
,		BUMON DEBIT_BUMON			-- 借方会計部門
,		BUMON CREDIT_BUMON			-- 貸方会計部門
,		(SELECT	ACCOUNTS_CD
		 ,		ACCOUNTS_NAME
		 FROM	ACCOUNTS
		 GROUP BY	ACCOUNTS_CD
		 ,			ACCOUNTS_NAME
		) DEBIT_ACCOUNTS			-- 借方勘定科目
,		(SELECT	ACCOUNTS_CD
		 ,		ACCOUNTS_NAME
		 FROM	ACCOUNTS
		 GROUP BY	ACCOUNTS_CD
		 ,			ACCOUNTS_NAME
		) CREDIT_ACCOUNTS			-- 貸方勘定科目
,		BUMON DEBIT_BUMON_ITEM		-- 仕入会計部門(品目)
,		BUMON CREDIT_BUMON_VENDER	-- 買掛会計部門
,		(SELECT	ACCOUNTS_CD
		 ,		ACCOUNTS_NAME
		 FROM	ACCOUNTS
		 GROUP BY	ACCOUNTS_CD
		 ,			ACCOUNTS_NAME
		) DEBIT_ACCOUNTS_ITEM		-- 仕入勘定科目(品目)
,		(SELECT	ACCOUNTS_CD
		 ,		ACCOUNTS_NAME
		 FROM	ACCOUNTS
		 GROUP BY	ACCOUNTS_CD
		 ,			ACCOUNTS_NAME
		) CREDIT_ACCOUNTS_VENDER	-- 買掛勘定科目
WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
/*IF (( slipNo != null ) && ( slipNo != "" ))*/
	AND	PURCHASE_SUBCONTRACT.SLIP_NO = /*slipNo*/'SI000000029'
/*END*/
AND PURCHASE_SUBCONTRACT.ITEM_CD = ITEM.ITEM_CD(+)
AND ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND ITEM.ITEM_CD = PURCHASE_ATTRIBUTE_QUEUE.ITEM_CD(+)
AND ITEM.VERSION = PURCHASE_ATTRIBUTE_QUEUE.VERSION(+)
AND PURCHASE_SUBCONTRACT.VENDER_CD = VENDER.VENDER_CD(+)
AND PURCHASE_SUBCONTRACT.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND PURCHASE_SUBCONTRACT.LOCATION_CD = DELIVERY.DELIVERY_CD(+)
AND PURCHASE_SUBCONTRACT.ORGANIZATION_CD = ORG.ORGANIZATION_CD(+)
AND PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD = TANTO_ORG.ORGANIZATION_CD(+)
AND PURCHASE_SUBCONTRACT.VENDER_CD = UNITPRICE.VENDER_CD(+)
AND PURCHASE_SUBCONTRACT.ITEM_CD = UNITPRICE.ITEM_CD(+)
AND UNITPRICE.UNITPRICE_DIVISION = NAMES_COST.NAME_CD(+)
AND PURCHASE_SUBCONTRACT.ACCOUNT_DEBIT_SECTION_CD = DEBIT_BUMON.SECTION_CD(+)
AND PURCHASE_SUBCONTRACT.ACCOUNT_CREDIT_SECTION_CD = CREDIT_BUMON.SECTION_CD(+)
AND PURCHASE_SUBCONTRACT.DEBIT_TITLE_CD = DEBIT_ACCOUNTS.ACCOUNTS_CD(+)
AND PURCHASE_SUBCONTRACT.CREDIT_TITLE_CD = CREDIT_ACCOUNTS.ACCOUNTS_CD(+)
AND PURCHASE_ATTRIBUTE_QUEUE.SECTION_CD = DEBIT_BUMON_ITEM.SECTION_CD(+)
AND VENDER.SECTION_CD = CREDIT_BUMON_VENDER.SECTION_CD(+)
AND PURCHASE_ATTRIBUTE_QUEUE.ACCOUNTS_CD = DEBIT_ACCOUNTS_ITEM.ACCOUNTS_CD(+)
AND VENDER.ACCOUNTS_CD = CREDIT_ACCOUNTS_VENDER.ACCOUNTS_CD(+)
ORDER BY SLIP_NO
,		 ROW_NO