/*
 * 購入品扱い属性検索用SQL
 *
 * entityName=PurchaseAttributeQueueDetail
 * packageName=purchaseattributequeuedetail
 * methodName=getEntity
 *
 */

SELECT ITEM_CD, VERSION, STATUS PURCHASE_STATUS, MATERIAL_MAKER_NAME, QUEUE.VENDER_CD, VENDER_NAME1, QUEUE.DELIVERY_CD, DELIVERY_NAME1, PURCHASE_LEAD_TIME, PURCHASE_PRICE, QUEUE.TAX_DIVISION PURCHASE_TAX_DIVISION, PURCHASE_TRIGGER, MULTI_SUPPLIER_DIVISION, ORDER_POINT PURCHASE_ORDER_POINT, ORDER_QTY, INSPECTION_TYPE, PRICE_CALC_DIVISION PURCHASE_PRICE_CALC_DIVISION, SUPPLIED_GOODS_DIVISION, LEASE_DRUM_FLAG, LORRY_DIVISION, QUEUE.SECTION_CD PURCHASE_SECTION_CD, SECTION_NAME PURCHASE_SECTION_NAME, QUEUE.ACCOUNTS_CD PURCHASE_ACCOUNTS_CD, ACCOUNTS_NAME PURCHASE_ACCOUNTS_NAME, QUEUE.UPDATE_DATE PURCHASE_UPDATE_DATE
FROM PURCHASE_ATTRIBUTE_QUEUE QUEUE, VENDER, DELIVERY, BUMON, ACCOUNTS
WHERE ITEM_CD = /*itemCd*/'%'
AND VERSION = /*version*/1
AND VENDER_DIVISION(+) = 'SI'
AND QUEUE.VENDER_CD = VENDER.VENDER_CD(+)
AND QUEUE.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
AND QUEUE.SECTION_CD = BUMON.SECTION_CD(+)
AND QUEUE.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)


