/*
 * 在庫出庫入力一覧用SQL
 *
 * entityName=InventoryShippingoutList
 * packageName=inventoryshippingoutlist
 * methodName=getList
 *
 */

SELECT LOT_INVENTORY.LOCATION_CD, NVL(LOCATION_NAME, 'ロケーション名称未登録') LOCATION_NAME, LOT_NO, ALIAS_LOT_NO,

DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1),
DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1),
CASE TYPE_DIVISION
    WHEN 1 THEN FLOOR(NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    WHEN 3 THEN FLOOR(NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    ELSE NVL(INVENTORY_QTY, 0)
END)) PACK_QTY,

UNIT_OF_OPERATION_MANAGEMENT, OPERATION_NAMES.NAME01 PACK_UNIT,

DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', 0, DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', 0,
CASE TYPE_DIVISION
    WHEN 1 THEN MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    WHEN 3 THEN MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    ELSE 0
END)) FRACTION,

UNIT_OF_FRACTION_MANAGEMENT, FRACTION_NAMES.NAME01 FRACTION_UNIT, LOT_INVENTORY.ITEM_CD,

CASE TYPE_DIVISION
    WHEN 1 THEN NVL(INVENTORY_QTY, 0)
    WHEN 3 THEN NVL(INVENTORY_QTY, 0)
    ELSE NVL(INVENTORY_QTY, 0) * NVL(KG_OF_FRACTION_MANAGEMENT, 1)
END INVENTORY_QTY

FROM LOT_INVENTORY, VALID_ITEM_QUEUE ITEM_QUEUE, LOCATION, NAMES OPERATION_NAMES, NAMES FRACTION_NAMES
WHERE LOT_INVENTORY.LOCATION_CD IS NOT NULL

/*IF(condition.srhLocationCd != null) && (condition.srhLocationCd != "")*/
AND (LOT_INVENTORY.LOCATION_CD LIKE /*condition.srhLocationCd*/'%' OR LOCATION_NAME LIKE /*condition.srhLocationCd*/'%')
/*END*/

AND (LOT_INVENTORY.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_NAME LIKE /*condition.srhItemCd*/'%')

/*IF(condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND	ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

AND LOT_INVENTORY.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND LOT_INVENTORY.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND OPERATION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_OPERATION_MANAGEMENT = OPERATION_NAMES.NAME_CD(+)
AND FRACTION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_FRACTION_MANAGEMENT = FRACTION_NAMES.NAME_CD(+)
