/*
 * 製造指図作成　オーダコードに紐付く作業を　取得用SQL
 *
 * entityName=AspImportAspOperation
 * packageName=aspimport
 * methodName=getEntityByMunufuctOrderCd
 *
 */

SELECT
	ASP_OPERATION.*
FROM
	ASP_OPERATION
,	(SELECT ASP_OPERATION.OPERATION_CD, DIRECTION_HEADER.DIRECTION_NO
	FROM	ASP_OPERATION, DIRECTION_HEADER
	WHERE	ASP_OPERATION.OPERATION_CD = DIRECTION_HEADER.ASP_ORDER_NO(+)
	)DIRECTION_HEADER

WHERE
	ASP_OPERATION.ORDER_CD = /*orderCd*/
AND	DIRECTION_HEADER.OPERATION_CD = ASP_OPERATION.OPERATION_CD
AND	DIRECTION_HEADER.DIRECTION_NO IS NULL
AND	(ASP_OPERATION.STATUS = 'D' OR ASP_OPERATION.STATUS = 'B')


ORDER BY
	ASP_OPERATION.OPERATION_CD