/*
 * Created on 2009/02/26
 *
 * $copyright$
 *
*/

/**
 * 製造指図一覧－指図書発行-計装インターフェイス用SQL
 *
 * @author tosco
 *
 * entityName=DirectionProcedureFormulaList
 * packageName=direction
 * methodName=getList
 *
 */
SELECT
	 PRO.DIRECTION_DIVISION AS DIRECTION_DIVISION
	,PRO.DIRECTION_NO AS DIRECTION_NO
	,PRO.STEP_NO AS STEP_NO
	,PRO.SEQ AS PROCEDURE_SEQ
	,PRO.OPERATION_CD AS OPERATION_CD
	,PRO.CONDITION AS CONDITION
	,PRO.REMARK AS PROCEDURE_REMARK
	,PRO.NOTES AS PROCEDURE_NOTES
	,PRO.LEADTIME AS LEADTIME
	,PRO.START_DATE AS START_DATE
	,PRO.END_DATE AS END_DATE
	,PRO.RESULT_SDATE AS RESULT_SDATE
	,PRO.RESULT_EDATE AS RESULT_EDATE
	,PRO.CONDITION_TEMP AS CONDITION_TEMP
	,PRO.CONDITION_TIME AS CONDITION_TIME
	,PRO.STIR_SPEED1 AS STIR_SPEED1
	,PRO.STIR_SPEED2 AS STIR_SPEED2
	,PRO.WATER_WEIGHT AS WATER_WEIGHT
	,PRO.MAIN_STREAM AS MAIN_STREAM
	,PRO.PH AS PH
	,PRO.FILLING_QTY AS FILLING_QTY
	,PRO.FILLING_UNIT AS FILLING_UNIT
	,PRO.NET AS NET
	,PRO.WEIGHT_MIN AS WEIGHT_MIN
	,PRO.WEIGHT_MAX AS WEIGHT_MAX
	,PRO.FILTER AS FILTER
	,PRO.AUTO_CHECKER_MIN AS AUTO_CHECKER_MIN
	,PRO.AUTO_CHECKER_MAX AS AUTO_CHECKER_MAX
	,PRO.GROSS_CHECKER_MIN AS GROSS_CHECKER_MIN
	,PRO.GROSS_CHECKER_MAX AS GROSS_CHECKER_MAX
	,PRO.OPENING_TORQUE_MIN AS OPENING_TORQUE_MIN
	,PRO.OPENING_TORQUE_MAX AS OPENING_TORQUE_MAX
	,PRO.HOT_AIR_PRESET_TEMP AS HOT_AIR_PRESET_TEMP
	,PRO.HOT_AIR_PRESSURE AS HOT_AIR_PRESSURE
	,PRO.MESH AS MESH
	,PRO.AUTO_CHECKER_AVE AS AUTO_CHECKER_AVE
	,PRO.GROSS_CHECKER_AVE AS GROSS_CHECKER_AVE
	,PRO.CLOSING_TORQUE_MIN AS CLOSING_TORQUE_MIN
	,PRO.CLOSING_TORQUE_MAX AS CLOSING_TORQUE_MAX
	,PRO.TORQUE_PRESSURE AS TORQUE_PRESSURE
	,PRO.AIR_PRESSURE AS AIR_PRESSURE
	,PRO.VCLOSE_TIME AS VCLOSE_TIME
	,PRO.FIRST_HEAT_SEAL AS FIRST_HEAT_SEAL
	,PRO.SECOND_HEAT_SEAL AS SECOND_HEAT_SEAL
	,PRO.INPUT_DATE AS PROCEDURE_INPUT_DATE
	,PRO.INPUTOR_CD AS PROCEDURE_INPUTOR_CD
	,PRO.UPDATE_DATE AS PROCEDURE_UPDATE_DATE
	,PRO.UPDATOR_CD AS PROCEDURE_UPDATOR_CD
	,FML.LINE_NO AS LINE_NO
	,FML.SEQ AS FORMULA_SEQ
	,FML.LINE_TYPE AS LINE_TYPE
	,FML.ITEM_CD AS ITEM_CD
	,FML.TONYU AS TONYU
	,FML.DATAREAD AS DATAREAD
	,FML.TONYUSOKUDO AS TONYUSOKUDO
	,FML.QTY AS QTY
	,FML.STOCKPD_QTY AS STOCKPD_QTY
	,FML.RESULT_QTY AS RESULT_QTY
	,FML.SAMPLE_QTY AS SAMPLE_QTY
	,FML.LOSS_QTY AS LOSS_QTY
	,FML.DEFECT_QTY AS DEFECT_QTY
	,FML.ADJUST_QTY AS ADJUST_QTY
	,FML.COST AS COST
	,FML.STEP_CONDITION AS STEP_CONDITION
	,FML.NOTES AS FORMULA_NOTES
	,FML.LOCATION_CD AS LOCATION_CD
	,FML.NEXT_LOCATION_CD AS NEXT_LOCATION_CD
	,FML.NEXT_AFTER_LOCATION_CD AS NEXT_AFTER_LOCATION_CD
	,FML.LOT_NO AS LOT_NO
	,FML.MANUFACTURER_LOT_NO AS MANUFACTURER_LOT_NO
	,FML.FILL_QTY AS FILL_QTY
	,FML.FILL_RESULT_QTY AS FILL_RESULT_QTY
	,FML.REMARK AS FORMULA_REMARK
	,FML.INPUT_DATE AS FORMULA_INPUT_DATE
	,FML.INPUTOR_CD AS FORMULA_INPUTOR_CD
	,FML.UPDATE_DATE AS FORMULA_UPDATE_DATE
	,FML.UPDATOR_CD AS FORMULA_UPDATOR_CD
    ,ITM.ITEM_NAME AS ITEM_NAME
    ,ITM.UNIT_OF_STOCK_CONTROL AS UNIT_OF_STOCK_CONTROL
    ,OPE.OPERATION_NAME AS OPERATION_NAME
FROM
    OPERATION OPE,
    ITEM ITM,
    (
        SELECT
            ITEM_CD AS ITEM_CD,
            MAX(VERSION) AS VERSION
        FROM
            ITEM
        GROUP BY
            ITEM_CD
    ) MITM,
    DIRECTION_FORMULA FML,
    DIRECTION_PROCEDURE PRO
WHERE
        PRO.DIRECTION_DIVISION = /*directionDivision*/'1'
    AND PRO.DIRECTION_NO = /*directionNo*/'00001'
    AND FML.DIRECTION_DIVISION(+) = PRO.DIRECTION_DIVISION
    AND FML.DIRECTION_NO(+) = PRO.DIRECTION_NO
    AND FML.STEP_NO(+) = PRO.STEP_NO
    AND FML.LINE_TYPE(+) = -1
    AND MITM.ITEM_CD(+) = FML.ITEM_CD
    AND ITM.ITEM_CD(+) = MITM.ITEM_CD
    AND ITM.VERSION(+) = MITM.VERSION
    AND OPE.OPERATION_CD(+) = PRO.OPERATION_CD
ORDER BY
    PRO.STEP_NO,
    FML.LINE_NO
