/*
 * Created on 2009/02/20
 *
 * $copyright$
 *
*/

/**
 * 製造指図ヘッダー共通ヘッダ用SQL
 *
 * @author tosco
 *
 * entityName=DirectionHeaderDetail
 * packageName=direction
 * methodName=findByDirectionNo
 *
 */
SELECT
     HEAD.DIRECTION_DIVISION
    ,HEAD.DIRECTION_NO
    ,HEAD.DIRECTION_DATE
    ,HEAD.ASP_ORDER_NO
    ,HEAD.DIRECTION_STATUS
    ,HEAD.RECIPE_ID
    ,HEAD.RECIPE_CD
    ,HEAD.RECIPE_VERSION
    ,HEAD.PRODUCTION_LINE
    ,HEAD.COMPOUND_TANK_NO
    ,HEAD.HOLD_TANK_NO
    ,HEAD.DISSOLUTION_TANK_NO
    ,HEAD.FILLTANK_NO
    ,HEAD.PACKAGE_LINE
    ,HEAD.CURRENT_STEP_NO
    ,HEAD.ITEM_CD
    ,HEAD.PLANED_QTY
    ,HEAD.RESULT_QTY
    ,HEAD.DIVIDE_FLAG
    ,HEAD.NEXT_PLANED_QTY
    ,HEAD.PDW_RESULT
    ,HEAD.PEOCESS_LOSS
    ,HEAD.LOT_NO
    ,HEAD.PLANED_SDATE
    ,HEAD.PLANED_EDATE
    ,HEAD.RESULT_SDATE
    ,HEAD.RESULT_EDATE
    ,HEAD.STERIT_SDATE
    ,HEAD.STERIT_EDATE
    ,HEAD.MEKKIN_TANK_TEMP_MIN
    ,HEAD.MEKKIN_TANK_TEMP_MAX
    ,HEAD.HAISUI_CHECK
    ,HEAD.STAMP_FLAG
    ,HEAD.STAMP_DATE
    ,HEAD.STAMP_TANTO_CD
    ,HEAD.PRODUCT_LABEL_FLAG
    ,HEAD.PRODUCT_LABEL_DATE
    ,HEAD.PRODUCT_LABEL_TANTO_CD
    ,HEAD.PRODUCT_RECORD_FLAG
    ,HEAD.PRODUCT_RECORD_DATE
    ,HEAD.PRODUCT_RECORD_TANTO_CD
    ,HEAD.STOCKDISS_LABEL_FLAG
    ,HEAD.STOCKDISS_LABEL_DATE
    ,HEAD.STOCKDISS_LABEL_TANTO_CD
    ,HEAD.CERTIFICATION_FLAG
    ,HEAD.CERTIFICATION_DATE
    ,HEAD.REMARK
    ,HEAD.NOTES
    ,HEAD.DELETE_FLAG
    ,HEAD.SEIZOTANTOCODE
    ,HEAD.SENJOTANTOCODE
    ,HEAD.MEKKINTANTOCODE
    ,HEAD.CHOGOTANKCONDI
    ,HEAD.YOBIYOKAICONDI
    ,HEAD.HOLDTANKCONDI
    ,HEAD.TOTAL_JOBTIME
    ,HEAD.ENPLOY_JOBTIME
    ,HEAD.COOPER_JOBTIME
    ,HEAD.APP_TANTO_CD
    ,HEAD.APP_DATE
    ,HEAD.LAST_APP_TANTO_CD
    ,HEAD.LAST_APP_DATE
    ,HEAD.INPUT_DATE
    ,HEAD.INPUTOR_CD
    ,HEAD.UPDATE_DATE
    ,HEAD.UPDATOR_CD
    ,ITEM.ITEM_NAME AS             ITEM_NAME
    ,ITEM.OTHER_COMPANY_CD1 AS     OTHER_COMPANY_CD1
    ,ITEM.SHIPPER_DIVISION AS      SHIPPER_DIVISION
    ,ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_OF_OPERATION_MANAGEMENT
    ,LINE.PRODUCTION_LINE_NAME AS  PRODUCTION_LINE_NAME
    ,NAME.NAME01 AS                UNIT_NAME
    ,PROC.WATER_WEIGHT AS          WATER_WEIGHT
FROM
    (
        SELECT
             DIRECTION_PROCEDURE.DIRECTION_NO AS DIRECTION_NO
            ,SUM(WATER_WEIGHT) AS WATER_WEIGHT
        FROM
           DIRECTION_PROCEDURE
        WHERE
               DIRECTION_PROCEDURE.DIRECTION_DIVISION = '1'
           AND DIRECTION_PROCEDURE.DIRECTION_NO = /*directionNo*/'%'
        GROUP BY
            DIRECTION_PROCEDURE.DIRECTION_NO
    ) PROC,
    VALID_ITEM_QUEUE ITEM,
    LINE LINE,
    NAMES NAME,
	DIRECTION_HEADER HEAD
WHERE
        HEAD.DIRECTION_DIVISION = '1'
	AND HEAD.DIRECTION_NO = /*directionNo*/'%'
    AND ITEM.ITEM_CD(+) = HEAD.ITEM_CD
    AND LINE.PRODUCTION_LINE(+) = HEAD.PRODUCTION_LINE
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
    AND PROC.DIRECTION_NO(+) = HEAD.DIRECTION_NO
