/*
 * Created on 2009/01/22
 *
 * $copyright$
 *
*/

/**
 * 処方検査用SQL
 *
 * @author tosco
 *
 * entityName=DirectionRecipeInspectionList
 * packageName=direction
 * methodName=getRecipeId
 *
 */
SELECT
	RECIPE_INSPECTION.RECIPE_ID
,	RECIPE_INSPECTION.STEP_NO
,	RECIPE_INSPECTION.LINE_NO
,	RECIPE_INSPECTION.SEQ
,	RECIPE_INSPECTION.INSPECTION_CD
,	RECIPE_INSPECTION.DIVISION
,	RECIPE_INSPECTION.VALUE_TYPE
,	RECIPE_INSPECTION.VALUE1
,	RECIPE_INSPECTION.VALUE2
,	RECIPE_INSPECTION.CONDITION
,	RECIPE_INSPECTION.REMARK
,	RECIPE_INSPECTION.NOTES
,	RECIPE_INSPECTION.INPUTOR_CD
,	RECIPE_INSPECTION.INPUT_DATE
,	RECIPE_INSPECTION.UPDATOR_CD
,	RECIPE_INSPECTION.UPDATE_DATE
FROM
	RECIPE_INSPECTION

WHERE
	RECIPE_INSPECTION.RECIPE_ID = /*recipeId*/
ORDER BY
	 RECIPE_INSPECTION.RECIPE_ID
	,RECIPE_INSPECTION.STEP_NO
	,RECIPE_INSPECTION.LINE_NO
