/*
 * 取引先一覧用SQL
 *
 * entityName=VenderDetail
 * packageName=venderdetail
 * methodName=getEntity
 *
 */
SELECT VENDER.VENDER_DIVISION,

CASE VENDER.VENDER_DIVISION
	WHEN N'TS' THEN '得意先'
	WHEN N'SI' THEN '仕入先'
	ELSE NULL
END VENDER_DIVISION_NAME

, VENDER.VENDER_CD
, VENDER.VENDER_NAME1
, VENDER.VENDER_NAME2
, VENDER.VENDER_SHORTED_NAME
, VENDER.ZIPCODE_NO
, VENDER.ADDRESS1
, VENDER.ADDRESS2
, VENDER.ADDRESS3
, VENDER.TEL_NO
, VENDER.FAX_NO
, VENDER.ORDER_FAX_NO
, VENDER.ORDER_FAX_OUTPUT
, VENDER.ORDER_MAIL_ADDRESS1
, VENDER.ORDER_MAIL_ADDRESS2
, VENDER.ORDER_MAIL_ADDRESS3
, VENDER.ORDER_MAIL_OUTPUT
, VENDER.SALES_FAX_NO
, VENDER.SALES_FAX_OUTPUT
, VENDER.SALES_MAIL_ADDRESS1
, VENDER.SALES_MAIL_ADDRESS2
, VENDER.SALES_MAIL_ADDRESS3
, VENDER.SALES_MAIL_OUTPUT
, VENDER.REPRESENT_ROLE
, VENDER.REPRESENT_PERSON
, VENDER.CLOSING_DATE
, VENDER.BOUND_AMOUNT3
, VENDER.BOUND_AMOUNT4
, VENDER.NOTE_SIGHT3
, VENDER.NOTE_SIGHT4
, VENDER.NOTE_SIGHT5
, VENDER.PAYMENT_INVOICE_CD
, PAYMENT.VENDER_NAME1 PAYMENT_INVOICE_NAME
, PAYMENT.VENDER_SHORTED_NAME PAYMENT_INVOICE_SHORT_NAME
, VENDER.CREDIT_LIMIT_PRICE
, VENDER.TANTO_CD
, TANTO_NM
, VENDER.AREA_CD
, AREA_NAME
, VENDER.TAX_DIVISION
, VENDER.CALC_DIVISION
, VENDER.TAX_RATIO
, VENDER.ROUNDUP
, VENDER.ROUNDUP_UNIT
, VENDER.SALES_PURCHASE_ROUNDUP
, VENDER.SALES_PURCHASE_ROUNDUP_UNIT
, VENDER.UNITPRICE_ROUNDUP
, VENDER.UNITPRICE_ROUNDUP_UNIT
, VENDER.BANK_CD
, BANK.BANK_NAME
, BANK.BRANCH_NAME
, VENDER.ACCOUNT_DIVISION
,
CASE VENDER.ACCOUNT_DIVISION
	WHEN 1 THEN '普通'
	WHEN 2 THEN '当座'
	WHEN 3 THEN 'その他'
	ELSE NULL
END ACCOUNT_DIVISION_NAME

, VENDER.ACCOUNT_NO
, VENDER.ACCOUNT_STOCKHOLD
, VENDER.CUSTOMER_TANTO_NAME1
, VENDER.CUSTOMER_TANTO_NAME2
, VENDER.CUSTOMER_IMPRESSION1
, VENDER.CUSTOMER_IMPRESSION2
, VENDER.BILL_PUBLISH
, VENDER.SLIP_PUBLISH
, VENDER.SECTION_CD
, SECTION_NAME
, VENDER.ACCOUNTS_CD
, ACCOUNTS_NAME
, VENDER.CITY_CD
, VENDER.SUBCONTRACT_LAW
, VENDER.CALENDAR_CD
, CAL_NAME
, VENDER.ACCOUNT_CD
, VENDER.OTHER_BANK_CD
, OTHER_BANK.BANK_NAME OTHER_BANK_NAME
, OTHER_BANK.BRANCH_NAME OTHER_BRANCH_NAME
, VENDER.OTHER_ACCOUNT_DIVISION
, VENDER.OTHER_ACCOUNT_NO
, VENDER.OTHER_ACCOUNT_STOCKHOLD
, VENDER.TAX_ROUNDUP
, VENDER.TAX_ROUNDUP_UNIT
, VENDER.TRANSFER_COMMISSION_LOAD
, VENDER.REMARKS
, VENDER.ADVANCE_DIVISION
, VENDER.CREDIT_MONTH_DIVISION1
, VENDER.CREDIT_MONTH_DIVISION2
, VENDER.CREDIT_MONTH_DIVISION3
, VENDER.CREDIT_SCHEDULED_DATE1
, VENDER.CREDIT_SCHEDULED_DATE2
, VENDER.CREDIT_SCHEDULED_DATE3
, VENDER.CREDIT_DIVISION3
, VENDER.CREDIT_DIVISION4
, VENDER.CREDIT_DIVISION5
, VENDER.PURCHASE_DISCOUNT_DAYS1
, VENDER.PURCHASE_DISCOUNT_DAYS2
, VENDER.PURCHASE_DISCOUNT_DAYS3
, VENDER.ORGANIZATION_CD
, ORGANIZATION.ORGANIZATION_NAME
, VENDER.HOLIDAY_FLG
, VENDER.UPDATE_DATE
, VENDER.FAX_OUTPUT
, VENDER.SLIP_FAX_NO
, VENDER.MAIL_ORGANIZATION_CD
, MAIL_ORGANIZATION.ORGANIZATION_NAME MAIL_ORGANIZATION_NAME
, VENDER.TS_INVOICE_PTN
, VENDER.SI_INVOICE_PTN
, VENDER.INVOICE_NO

FROM VENDER, ORGANIZATION, VENDER PAYMENT, LOGIN, AREA, BUMON, ACCOUNTS, BANK, BANK OTHER_BANK, ORGANIZATION MAIL_ORGANIZATION,

(SELECT CAL_CD, MAX(CAL_NAME) CAL_NAME
FROM CAL
GROUP BY CAL_CD) CAL

WHERE VENDER.VENDER_DIVISION = /*venderDivison*/'%'
AND VENDER.VENDER_CD = /*venderCd*/'%'
AND VENDER.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
AND VENDER.VENDER_DIVISION = PAYMENT.VENDER_DIVISION(+)
AND VENDER.PAYMENT_INVOICE_CD = PAYMENT.VENDER_CD(+)
AND VENDER.TANTO_CD = LOGIN.TANTO_CD(+)
AND VENDER.AREA_CD = AREA.AREA_CD(+)
AND VENDER.SECTION_CD = BUMON.SECTION_CD(+)
AND VENDER.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
AND VENDER.CALENDAR_CD = CAL.CAL_CD(+)
AND VENDER.BANK_CD = BANK.BANK_MASTER_CD(+)
AND VENDER.OTHER_BANK_CD = OTHER_BANK.BANK_MASTER_CD(+)
AND VENDER.MAIL_ORGANIZATION_CD = MAIL_ORGANIZATION.ORGANIZATION_CD(+)


