/*
 * 最新有効品目検索用SQL
 *
 * entityName=ItemQueueLastActive
 * packageName=itemqueuelastactive
 * methodName=getEntity
 *
 */

SELECT ITEM_QUEUE.*
FROM ITEM_QUEUE,

(SELECT ITEM_QUEUE.ITEM_CD, MAX(ITEM_QUEUE.VERSION) VERSION
FROM ITEM_QUEUE
, ARTICLE_ATTRIBUTE_QUEUE ARTICLE
, PRODUCT_ATTRIBUTE_QUEUE PRODUCT
, PURCHASE_ATTRIBUTE_QUEUE PURCHASE
WHERE ITEM_QUEUE.ACTIVE_DATE <= TO_CHAR(SYSDATE, 'YYYY/MM/DD')
AND ITEM_QUEUE.STATUS = 3
AND LEAST(DECODE(NVL(ITEM_QUEUE.PRODUCT_DIVISION, 0), 0, 4, PRODUCT.STATUS), DECODE(NVL(ITEM_QUEUE.ARTICLE_DIVISION, 0), 0, 4, ARTICLE.STATUS), DECODE(NVL(ITEM_QUEUE.PURCHASE_DIVISION, 0), 0, 4, PURCHASE.STATUS)) = 3
AND ITEM_QUEUE.ITEM_CD = ARTICLE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = ARTICLE.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PRODUCT.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PRODUCT.VERSION(+)
AND ITEM_QUEUE.ITEM_CD = PURCHASE.ITEM_CD(+)
AND ITEM_QUEUE.VERSION = PURCHASE.VERSION(+)
GROUP BY ITEM_QUEUE.ITEM_CD) MAX_ITEM

WHERE ITEM_QUEUE.ITEM_CD = /*itemCd*/'%'
AND ITEM_QUEUE.ITEM_CD = MAX_ITEM.ITEM_CD
AND ITEM_QUEUE.VERSION = MAX_ITEM.VERSION
