/*
 * Created on 2009/01/22
 *
 * $copyright$
 *
*/

/**
 * 包装実績-検査詳細用SQL
 *
 * @author tosco
 *
 * entityName=PkgRdirectionDirectionInspectionList
 * packageName=pkgrdirection
 * methodName=getEntity
 *
 */
SELECT
	INSP.DIRECTION_DIVISION
,	INSP.DIRECTION_NO
,	INSP.STEP_NO
,	INSP.LINE_NO
,	INSP.SEQ
,	INSP.INSPECTION_CD
,	INSP.DIVISION
,	INSP.VALUE_TYPE
,	INSP.VALUE1
,	INSP.VALUE2
,	INSP.RESULT_VALUE1
,	INSP.RESULT_VALUE2
,	INSP.CONDITION
,	INSP.REMARK
,	INSP.NOTES
,	INSP.INPUTOR_CD
,	INSP.INPUT_DATE
,	INSP.UPDATOR_CD
,	INSP.UPDATE_DATE
,   PROC.OPERATION_CD AS          OPERATION_CD         -- 工程コード
,	OPE.OPERATION_NAME AS         OPERATION_NAME       -- 工程名称
,	NAMES.NAME01 AS INSPECTION_NAME
FROM
    DIRECTION_PROCEDURE PROC
,	DIRECTION_INSPECTION INSP
,   OPERATION OPE
,	NAMES
WHERE
	INSP.DIRECTION_NO IS NOT NULL
AND INSP.DIRECTION_DIVISION =/*directionDivision*/
AND	INSP.DIRECTION_NO = /*directionNo*/
AND	INSP.STEP_NO = /*stepNo*/
AND	INSP.LINE_NO = /*lineNo*/
AND PROC.DIRECTION_DIVISION(+) = INSP.DIRECTION_DIVISION
AND PROC.DIRECTION_NO(+) = INSP.DIRECTION_NO
AND PROC.STEP_NO(+) = INSP.STEP_NO
AND OPE.OPERATION_CD(+) = PROC.OPERATION_CD
AND NAMES.NAME_DIVISION(+) = 'STDV'
AND INSP.INSPECTION_CD = NAMES.NAME_CD(+)

ORDER BY
	 INSP.DIRECTION_NO
	,INSP.STEP_NO
	,INSP.LINE_NO
