/*
 * 権限検索要SQL
 *
 * entityName=ControlAuthorityList
 * packageName=controlauthoritylist
 * methodName=getList
 */

SELECT	ROLE.ROLE_ID
,	CONTROL_AUTHORITY.MENU_ID
,	CONTROL_AUTHORITY.TAB_ID
,	CONTROL_AUTHORITY.CONTROL_ID

FROM	CONTROL_AUTHORITY
,
(
	SELECT	TANTO_ROLE.ROLE_ID
	FROM TANTO_ROLE
	WHERE TANTO_ROLE.TANTO_CD = /*tantoCd*/'%'

	UNION

	SELECT	BELONG_ROLE.ROLE_ID
	FROM	BELONG , BELONG_ROLE
	WHERE	BELONG.TANTO_CD = /*tantoCd*/'%'
	AND	BELONG.ORGANIZATION_CD = /*organizationCd*/'%'
	AND	BELONG.POST_ID = /*postId*/1
	AND	BELONG.ORGANIZATION_CD = BELONG_ROLE.ORGANIZATION_CD
	AND	BELONG.POST_ID = BELONG_ROLE.POST_ID
)	ROLE

WHERE	CONTROL_AUTHORITY.ROLE_ID = ROLE.ROLE_ID
AND CONTROL_AUTHORITY.MENU_ID = /*menuId*/60
AND CONTROL_AUTHORITY.TAB_ID = /*tabId*/1
AND CONTROL_AUTHORITY.CONTROL_ID = /*controlId*/1
