/*
 *?pSQL
 *
 * entityName=InoutRecordListForReport
 * packageName=inoutrecordlistforreport
 * methodName=getListForReport
 *
 */
SELECT 
	INOUT_RECORD.INOUT_NO
,	INOUT_RECORD.INOUT_DIVISION
,	CASE
    WHEN INOUT_DIVISION = 1 THEN '製造受入'
    WHEN INOUT_DIVISION = 2 THEN '製造払出'
    WHEN INOUT_DIVISION = 3 THEN '入荷受入'
    WHEN INOUT_DIVISION = 4 THEN '出荷払出'
    WHEN INOUT_DIVISION = 10 THEN '在庫入出庫'
    WHEN INOUT_DIVISION = 11 THEN '棚差調整'
    WHEN INOUT_DIVISION = 12 THEN '売上返品'
    WHEN INOUT_DIVISION = 13 THEN '売上(預り品)'
    ELSE NULL
	END	INOUT_DIVISION_NAME
,	INOUT_RECORD.ODER_NO
,	INOUT_RECORD.ODER_LINE_NO
,	INOUT_RECORD.ITEM_CD
,	ITEM.ITEM_NAME
,	ITEM.STYLE_OF_PACKING
,	ITEM.OTHER_COMPANY_CD1
,	INOUT_RECORD.LOCATION_CD
,	LOCATION.LOCATION_NAME
,	INOUT_RECORD.LOT_NO
,	INOUT_RECORD.INOUT_QTY
,	INOUT_RECORD.INOUT_PRICE
,	INOUT_RECORD.INOUT_COST
,	INOUT_RECORD.INOUT_DATE
,	INOUT_RECORD.REMARK
,	INOUT_RECORD.INOUT_SOURCE_NO
,	INOUT_RECORD.SECTION_CD
,	BUMON.SECTION_NAME
,	INOUT_RECORD.ACCOUNTS_CD
,	OWN_ACCOUNTS.ACCOUNTS_NAME
,	INOUT_RECORD.ACCOUNTS_SUB_CD
,	OWN_ACCOUNTS_SUB.ACCOUNTS_NAME AS ACCOUNTS_SUB_NAME
,	INOUT_RECORD.ITEM_CATEGORY
,	INOUT_RECORD.PARENT_ITEM_CD
,	ITEM_PARENT.ITEM_NAME AS PARENT_ITEM_NAME
,	INOUT_RECORD.PARENT_ACCOUNTS_CD
,	PARENT_ACCOUNTS.ACCOUNTS_NAME AS PARENT_ACCOUNTS_NAME
,	INOUT_RECORD.PARENT_ACCOUNT_SUB_CD
,	PARENT_ACCOUNTS_SUB.ACCOUNTS_NAME AS PARENT_ACCOUNTS_SUB_NAME
,	INOUT_RECORD.PARENT_ITEM_CATEGORY
,	INOUT_RECORD.RY_CD
,	REASON.RY_DESCRIPTION
,	INOUT_RECORD.REASON
,	INOUT_RECORD.INOUT_UPDATE_DATE
,	INOUT_RECORD.INVENTORY_UPDATE_DATE
,	INOUT_RECORD.FUNC_DIVISION
,	INOUT_RECORD.INPUT_DATE
,	INOUT_RECORD.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	INOUT_RECORD.UPDATE_DATE
,	INOUT_RECORD.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM 
	INOUT_RECORD
,	DIRECTION_HEADER
,	ITEM
,	ITEM ITEM_PARENT
,	LOCATION
,	NAMES
,	(SELECT ITEM_CD, MAX(VERSION) VERSION FROM ITEM GROUP BY ITEM_CD) MAX_ITEM
,	BUMON
,	ACCOUNTS OWN_ACCOUNTS
,	ACCOUNTS OWN_ACCOUNTS_SUB
,	ACCOUNTS PARENT_ACCOUNTS
,	ACCOUNTS PARENT_ACCOUNTS_SUB
,	REASON
,	LOGIN INPUTOR
,	LOGIN UPDATOR

WHERE INOUT_RECORD.INOUT_NO IS NOT NULL

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (INOUT_RECORD.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM.ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhLocationCd != null) && (condition.srhLocationCd != "")*/
AND (INOUT_RECORD.LOCATION_CD LIKE /*condition.srhLocationCd*/'%' OR LOCATION.LOCATION_NAME LIKE /*condition.srhLocationCd*/'%')
/*END*/

/*IF (condition.srhInoutDivision != 0)*/
AND INOUT_RECORD.INOUT_DIVISION = /*condition.srhInoutDivision*/1
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (condition.srhInoutDateFrom != null) && (condition.srhInoutDateFrom != "")*/
AND INOUT_RECORD.INOUT_DATE >= /*condition.srhInoutDateFrom*/'2008/04/20'
/*END*/

/*IF (condition.srhInoutDateTo != null) && (condition.srhInoutDateTo != "")*/
 AND INOUT_RECORD.INOUT_DATE <= /*condition.srhInoutDateTo*/'2008/04/20'
/*END*/
AND INOUT_RECORD.SECTION_CD = BUMON.SECTION_CD(+)
AND INOUT_RECORD.ACCOUNTS_CD = OWN_ACCOUNTS.ACCOUNTS_CD(+)
AND INOUT_RECORD.ACCOUNTS_SUB_CD = OWN_ACCOUNTS_SUB.ACCOUNTS_CD(+)
AND INOUT_RECORD.PARENT_ITEM_CD = ITEM_PARENT.ITEM_CD(+)
AND INOUT_RECORD.PARENT_ACCOUNTS_CD = PARENT_ACCOUNTS.ACCOUNTS_CD(+)
AND INOUT_RECORD.PARENT_ACCOUNT_SUB_CD = PARENT_ACCOUNTS_SUB.ACCOUNTS_CD(+)
AND INOUT_RECORD.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND INOUT_RECORD.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND INOUT_RECORD.RY_CD = REASON.RY_CD(+)
AND INOUT_RECORD.ODER_NO = DIRECTION_HEADER.DIRECTION_NO(+)
AND INOUT_RECORD.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND MAX_ITEM.ITEM_CD = ITEM.ITEM_CD(+)
AND MAX_ITEM.VERSION = ITEM.VERSION(+)
AND NAME_DIVISION(+) = 'UNIT'
AND ITEM.UNIT_OF_OPERATION_MANAGEMENT = NAMES.NAME_CD(+)
AND INOUT_RECORD.LOCATION_CD = LOCATION.LOCATION_CD(+)
ORDER BY INOUT_RECORD.INOUT_DATE, INOUT_RECORD.INOUT_NO






