/*
 * 消込入力詳細画面(下段)用SQL
 *
 * entityName=EraserSales
 * packageName=claim.eraser
 * methodName=getSalesData
 *
 */
/*IF (( eraserNo != null ) && ( eraserNo != "" ))*/
	SELECT  CHECK_KBN					--チェック区分
	,		DATA_TYPE					--データ種別
	,		CUSTOMER_CD					--得意先コード
	,		CUSTOMER_NAME				--得意先名称
	,		SALES_DATE					--売上日付
	,		SLIP_NO						--伝票番号
	,		ROW_NO						--行番号
	,		CATEGORY_NAME				--分類名称
	,		ITEM_CD						--品目コード
	,		ITEM_NAME					--品目名称
	,		SALES_QUANTITY				--売上数量
	,		OPERATE_MANAGEMENT_UNIT		--運用管理単位
	,		DEFINE_UNITPRICE			--決定単価
	,		SALES_AMOUNT				--売上金額
	,		TAX_AMOUNT					--消費税額
	,		TOTAL_SALES_AMOUNT			--請求金額
	,		ERASER_NO					--消込番号
	FROM
		(
		--①選択した消込番号で消込済請求データ
		SELECT  '1' AS CHECK_KBN						--チェック区分
		,		SALES.DATA_TYPE							--データ種別
		,		SALES.CUSTOMER_CD						--得意先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		SALES.SALES_DATE						--売上日付
		,		SALES.SLIP_NO							--伝票番号
		,		SALES.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		SALES.ITEM_CD							--品目コード
		,		SALES.ITEM_NAME							--品目名称
		,		SALES.SALES_QUANTITY					--売上数量
		,		SALES.OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		SALES.DEFINE_UNITPRICE					--決定単価
		,		DECODE(SALES.TAX_TAXATION_DIVISION, '1', SALES.SALES_AMOUNT + SALES.TAX_AMOUNT		--売上金額(内税)
													   , SALES.SALES_AMOUNT) AS SALES_AMOUNT		--売上金額(内税以外)
		,		DECODE(SALES.TAX_TAXATION_DIVISION, '0', SALES.TAX_AMOUNT							--消費税額(外税)
													   , 0) AS TAX_AMOUNT							--消費税額(外税以外)
		,		(SALES.SALES_AMOUNT + SALES.TAX_AMOUNT) AS TOTAL_SALES_AMOUNT						--請求金額
		,		ERASER_HEADER.ERASER_NO					--消込番号
		FROM 	ERASER_HEADER ERASER_HEADER
				INNER JOIN
					(SELECT ERASER_NO
					 ,		ROW_NO
					 ,		MAX(SLIP_NO) AS SLIP_NO
					 ,		MAX(SLIP_ROW_NO) AS SLIP_ROW_NO
					 FROM ERASER
					 GROUP BY ERASER_NO
					 ,		  ROW_NO
					) ERASER
					ON  ERASER_HEADER.ERASER_NO = ERASER.ERASER_NO
				INNER JOIN
					SALES SALES
					ON  ERASER.SLIP_NO = SALES.SLIP_NO
					AND ERASER.SLIP_ROW_NO = SALES.ROW_NO
					AND SALES.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND SALES.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND SALES.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  SALES.CUSTOMER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  SALES.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND SALES.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		WHERE	ERASER_HEADER.ERASER_NO IS NOT NULL
		AND		ERASER_HEADER.ERASER_NO = /*eraserNo*/'KES0000001'
		UNION ALL
		--①選択した消込番号で消込済グループ間相殺データ
		SELECT  '1' AS CHECK_KBN						--チェック区分
		,		OFFSET.DATA_TYPE						--データ種別
		,		OFFSET.VENDER_CD AS CUSTOMER_CD			--請求先/支払先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		OFFSET.OFFSET_DATE AS SALES_DATE		--相殺日付
		,		OFFSET.OFFSET_NO AS SLIP_NO				--相殺番号
		,		NULL AS ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		OFFSET_HEADER.SUMMARY_CD AS ITEM_CD		--摘要コード
		,		OFFSET_HEADER.SUMMARY AS ITEM_NAME		--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT,0)*-1 AS SALES_AMOUNT			--売掛相殺金額(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--売掛相殺金額(ﾏｲﾅｽ)
		,		ERASER_HEADER.ERASER_NO					--消込番号
		FROM 	ERASER_HEADER ERASER_HEADER
				INNER JOIN
					(SELECT ERASER_NO
					 ,		ROW_NO
					 ,		MAX(SLIP_NO) AS SLIP_NO
					 ,		MAX(VENDER_CD) AS VENDER_CD
					 FROM ERASER
					 GROUP BY ERASER_NO
					 ,		  ROW_NO
					) ERASER
					ON  ERASER_HEADER.ERASER_NO = ERASER.ERASER_NO
				INNER JOIN
					OFFSET_GROUP_HEADER OFFSET_HEADER
					ON  ERASER.SLIP_NO = OFFSET_HEADER.OFFSET_NO				--相殺番号
				INNER JOIN
					OFFSET_GROUP_DATA OFFSET
					ON  ERASER.SLIP_NO = OFFSET.OFFSET_NO						--相殺番号
					AND ERASER.VENDER_CD = OFFSET.VENDER_CD						--請求先/支払先コード
					AND OFFSET.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND OFFSET.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND OFFSET.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  OFFSET.VENDER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  OFFSET.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND OFFSET.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		WHERE	ERASER_HEADER.ERASER_NO IS NOT NULL
		AND		ERASER_HEADER.ERASER_NO = /*eraserNo*/'KES0000002'
		UNION ALL
		--①選択した消込番号で消込済支払(相殺)データ
		SELECT  '1' AS CHECK_KBN						--チェック区分
		,		PAYMENT.DATA_TYPE						--データ種別
		,		PAYMENT.SUPPLIER_CD AS CUSTOMER_CD		--仕入先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		PAYMENT.PAYMENT_DATE AS SALES_DATE		--支払日付
		,		PAYMENT.SLIP_NO							--伝票番号
		,		PAYMENT.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		PAYMENT.SUMMARY_CD AS ITEM_CD			--摘要コード
		,		PAYMENT.SUMMARY AS ITEM_NAME			--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(PAYMENT.PAYMENT_AMOUNT,0)*-1 AS SALES_AMOUNT		--支払金額(相殺)(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(PAYMENT.PAYMENT_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--支払金額(相殺)(ﾏｲﾅｽ)
		,		ERASER_HEADER.ERASER_NO					--消込番号
		FROM 	ERASER_HEADER ERASER_HEADER
				INNER JOIN
					(SELECT ERASER_NO
					 ,		ROW_NO
					 ,		MAX(SLIP_NO) AS SLIP_NO
					 ,		MAX(SLIP_ROW_NO) AS SLIP_ROW_NO
					 FROM ERASER
					 GROUP BY ERASER_NO
					 ,		  ROW_NO
					) ERASER
					ON  ERASER_HEADER.ERASER_NO = ERASER.ERASER_NO
				INNER JOIN
					PAYMENT PAYMENT
					ON  ERASER.SLIP_NO = PAYMENT.SLIP_NO
					AND ERASER.SLIP_ROW_NO = PAYMENT.ROW_NO
					AND PAYMENT.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND PAYMENT.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND PAYMENT.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  PAYMENT.SUPPLIER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  PAYMENT.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND PAYMENT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		WHERE	ERASER_HEADER.ERASER_NO IS NOT NULL
		AND		ERASER_HEADER.ERASER_NO = /*eraserNo*/'KES0000002'
		UNION ALL
		--①選択した消込番号で消込済入金(相殺)データ
		SELECT  '1' AS CHECK_KBN						--チェック区分
		,		CREDIT.DATA_TYPE						--データ種別
		,		CREDIT.CUSTOMER_CD AS CUSTOMER_CD		--請求先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		CREDIT.CREDIT_DATE AS SALES_DATE		--入金日付
		,		CREDIT.CREDIT_NO						--入金番号
		,		CREDIT.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		CREDIT.SUMMARY_CD AS ITEM_CD			--摘要コード
		,		CREDIT.SUMMARY AS ITEM_NAME				--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(CREDIT.CREDIT_AMOUNT,0)*-1 AS SALES_AMOUNT			--入金金額(相殺)(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(CREDIT.CREDIT_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--入金金額(相殺)(ﾏｲﾅｽ)
		,		ERASER_HEADER.ERASER_NO					--消込番号
		FROM 	ERASER_HEADER ERASER_HEADER
				INNER JOIN
					(SELECT ERASER_NO
					 ,		ROW_NO
					 ,		MAX(SLIP_NO) AS SLIP_NO
					 ,		MAX(SLIP_ROW_NO) AS SLIP_ROW_NO
					 FROM ERASER
					 GROUP BY ERASER_NO
					 ,		  ROW_NO
					) ERASER
					ON  ERASER_HEADER.ERASER_NO = ERASER.ERASER_NO
				INNER JOIN
					CREDIT CREDIT
					ON  ERASER.SLIP_NO = CREDIT.CREDIT_NO
					AND ERASER.SLIP_ROW_NO = CREDIT.ROW_NO
					AND CREDIT.DATA_TOTAL_DIVISION = '2'						--データ集計区分(2:相殺)
					AND CREDIT.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND CREDIT.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND CREDIT.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  CREDIT.CUSTOMER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  CREDIT.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND CREDIT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		WHERE	ERASER_HEADER.ERASER_NO IS NOT NULL
		AND		ERASER_HEADER.ERASER_NO = /*eraserNo*/'KES0000002'
		)
	ORDER BY CUSTOMER_CD
	,		 SALES_DATE
	,		 SLIP_NO
	,		 ROW_NO
/*END*/
/*IF (( eraserNo == null ) || ( eraserNo == "" ))*/
	SELECT  CHECK_KBN					--チェック区分
	,		DATA_TYPE					--データ種別
	,		CUSTOMER_CD					--得意先コード
	,		CUSTOMER_NAME				--得意先名称
	,		SALES_DATE					--売上日付
	,		SLIP_NO						--伝票番号
	,		ROW_NO						--行番号
	,		CATEGORY_NAME				--分類名称
	,		ITEM_CD						--品目コード
	,		ITEM_NAME					--品目名称
	,		SALES_QUANTITY				--売上数量
	,		OPERATE_MANAGEMENT_UNIT		--運用管理単位
	,		DEFINE_UNITPRICE			--決定単価
	,		SALES_AMOUNT				--売上金額
	,		TAX_AMOUNT					--消費税額
	,		TOTAL_SALES_AMOUNT			--請求金額
	,		ERASER_NO					--消込番号
	FROM
		(
		--③未消込請求データ
		SELECT  '0' AS CHECK_KBN						--チェック区分
		,		SALES.DATA_TYPE							--データ種別
		,		SALES.CUSTOMER_CD						--得意先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		SALES.SALES_DATE						--売上日付
		,		SALES.SLIP_NO							--伝票番号
		,		SALES.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		SALES.ITEM_CD							--品目コード
		,		SALES.ITEM_NAME							--品目名称
		,		SALES.SALES_QUANTITY					--売上数量
		,		SALES.OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		SALES.DEFINE_UNITPRICE					--決定単価
		,		DECODE(SALES.TAX_TAXATION_DIVISION, '1', SALES.SALES_AMOUNT + SALES.TAX_AMOUNT		--売上金額(内税)
													   , SALES.SALES_AMOUNT) AS SALES_AMOUNT		--売上金額(内税以外)
		,		DECODE(SALES.TAX_TAXATION_DIVISION, '0', SALES.TAX_AMOUNT							--消費税額(外税)
													   , 0) AS TAX_AMOUNT							--消費税額(外税以外)
		,		(SALES.SALES_AMOUNT + SALES.TAX_AMOUNT) AS TOTAL_SALES_AMOUNT						--請求金額
		,		NULL AS ERASER_NO						--消込番号
		FROM 	(SELECT CLAIM_HEADER.CLAIM_NO
				 FROM CLAIM_HEADER
					  LEFT JOIN
						  LOGIN
						  ON CLAIM_HEADER.INPUTOR_CD = LOGIN.TANTO_CD
				 WHERE	CLAIM_HEADER.SECTION_CD IS NOT NULL
				 AND	CLAIM_HEADER.SECTION_CD = /*sectionCd*/'SC00001'
				 AND	CLAIM_HEADER.CUSTOMER_CD = /*venderCd*/'TS0001'
				 /*IF (( tantoCd != null ) && ( tantoCd != "" ))*/
				 AND   CLAIM_HEADER.INPUTOR_CD LIKE /*tantoCd*/
				 /*END*/
				 /*IF (( tantoNm != null ) && ( tantoNm != "" ))*/
				 AND	LOGIN.TANTO_NM LIKE /*tantoNm*/
				 /*END*/
				) CLAIM_HEADER
				INNER JOIN
					SALES SALES
					ON  CLAIM_HEADER.CLAIM_NO = SALES.CLAIM_NO
					AND SALES.ERASER_COMPLETE_DIVISION = '0'					--消込完了フラグ
					AND SALES.ERASER_COMPLETE_DATE IS NULL						--消込完了日
					AND SALES.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND SALES.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND SALES.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  SALES.CUSTOMER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  SALES.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND SALES.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		UNION ALL
		--③未消込グループ間相殺データ
		SELECT  '0' AS CHECK_KBN						--チェック区分
		,		OFFSET.DATA_TYPE						--データ種別
		,		OFFSET.VENDER_CD AS CUSTOMER_CD			--請求先/支払先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		OFFSET.OFFSET_DATE AS SALES_DATE		--相殺日付
		,		OFFSET.OFFSET_NO AS SLIP_NO				--相殺番号
		,		NULL AS ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		OFFSET_HEADER.SUMMARY_CD AS ITEM_CD		--摘要コード
		,		OFFSET_HEADER.SUMMARY AS ITEM_NAME		--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT,0)*-1 AS SALES_AMOUNT			--売掛相殺金額(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--売掛相殺金額(ﾏｲﾅｽ)
		,		NULL AS ERASER_NO						--消込番号
		FROM 	(SELECT CLAIM_HEADER.CLAIM_NO
				 FROM CLAIM_HEADER
					  LEFT JOIN
						  LOGIN
						  ON CLAIM_HEADER.INPUTOR_CD = LOGIN.TANTO_CD
				 WHERE	CLAIM_HEADER.SECTION_CD IS NOT NULL
				 AND	CLAIM_HEADER.SECTION_CD = /*sectionCd*/'SC00001'
				 AND	CLAIM_HEADER.CUSTOMER_CD = /*venderCd*/'TS0001'
				 /*IF (( tantoCd != null ) && ( tantoCd != "" ))*/
				 AND   CLAIM_HEADER.INPUTOR_CD LIKE /*tantoCd*/
				 /*END*/
				 /*IF (( tantoNm != null ) && ( tantoNm != "" ))*/
				 AND	LOGIN.TANTO_NM LIKE /*tantoNm*/
				 /*END*/
				) CLAIM_HEADER
				INNER JOIN
					OFFSET_GROUP_DATA OFFSET
					ON  CLAIM_HEADER.CLAIM_NO = OFFSET.CLAIM_NO
					AND OFFSET.ERASER_COMPLETE_DIVISION = '0'					--消込完了フラグ
					AND OFFSET.ERASER_COMPLETE_DATE IS NULL						--消込完了日
					AND OFFSET.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND OFFSET.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND OFFSET.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				INNER JOIN
					OFFSET_GROUP_HEADER OFFSET_HEADER
					ON  OFFSET.OFFSET_NO = OFFSET_HEADER.OFFSET_NO				--相殺番号
				LEFT JOIN
					VENDER
					ON  OFFSET.VENDER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  OFFSET.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND OFFSET.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		UNION ALL
		--③未消込支払(相殺)データ
		SELECT  '0' AS CHECK_KBN						--チェック区分
		,		PAYMENT.DATA_TYPE						--データ種別
		,		PAYMENT.SUPPLIER_CD AS CUSTOMER_CD			--請求先/支払先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		PAYMENT.PAYMENT_DATE AS SALES_DATE		--相殺日付
		,		PAYMENT.SLIP_NO AS SLIP_NO				--相殺番号
		,		PAYMENT.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		PAYMENT.SUMMARY_CD AS ITEM_CD			--摘要コード
		,		PAYMENT.SUMMARY AS ITEM_NAME			--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(PAYMENT.PAYMENT_AMOUNT,0)*-1 AS SALES_AMOUNT		--支払金額(相殺)(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(PAYMENT.PAYMENT_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--支払金額(相殺)(ﾏｲﾅｽ)
		,		NULL AS ERASER_NO						--消込番号
		FROM 	(SELECT CLAIM_HEADER.CLAIM_NO
				 FROM CLAIM_HEADER
					  LEFT JOIN
						  LOGIN
						  ON CLAIM_HEADER.INPUTOR_CD = LOGIN.TANTO_CD
				 WHERE	CLAIM_HEADER.SECTION_CD IS NOT NULL
				 AND	CLAIM_HEADER.SECTION_CD = /*sectionCd*/'SC00001'
				 AND	CLAIM_HEADER.CUSTOMER_CD = /*venderCd*/'TS0001'
				 /*IF (( tantoCd != null ) && ( tantoCd != "" ))*/
				 AND   CLAIM_HEADER.INPUTOR_CD LIKE /*tantoCd*/
				 /*END*/
				 /*IF (( tantoNm != null ) && ( tantoNm != "" ))*/
				 AND	LOGIN.TANTO_NM LIKE /*tantoNm*/
				 /*END*/
				) CLAIM_HEADER
				INNER JOIN
					PAYMENT PAYMENT
					ON  CLAIM_HEADER.CLAIM_NO = PAYMENT.CLAIM_NO
					AND PAYMENT.ERASER_COMPLETE_DIVISION = '0'					--消込完了フラグ
					AND PAYMENT.ERASER_COMPLETE_DATE IS NULL					--消込完了日
					AND PAYMENT.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND PAYMENT.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND PAYMENT.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  PAYMENT.SUPPLIER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  PAYMENT.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND PAYMENT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		UNION ALL
		--③未消込入金(相殺)データ
		SELECT  '0' AS CHECK_KBN						--チェック区分
		,		CREDIT.DATA_TYPE						--データ種別
		,		CREDIT.CUSTOMER_CD AS CUSTOMER_CD			--請求先/支払先コード
		,		VENDER.VENDER_NAME AS CUSTOMER_NAME		--得意先名称
		,		CREDIT.CREDIT_DATE AS SALES_DATE		--入金日付
		,		CREDIT.CREDIT_NO AS SLIP_NO				--入金番号
		,		CREDIT.ROW_NO							--行番号
		,		CLASSIFICATION.CATEGORY_NAME			--分類名称
		,		CREDIT.SUMMARY_CD AS ITEM_CD			--摘要コード
		,		CREDIT.SUMMARY AS ITEM_NAME				--摘要名
		,		NULL AS SALES_QUANTITY					--売上数量
		,		NULL AS OPERATE_MANAGEMENT_UNIT			--運用管理単位
		,		NULL AS DEFINE_UNITPRICE				--決定単価
		,		NVL(CREDIT.CREDIT_AMOUNT,0)*-1 AS SALES_AMOUNT			--入金金額(相殺)(ﾏｲﾅｽ)
		,		0 AS TAX_AMOUNT							--消費税額
		,		NVL(CREDIT.CREDIT_AMOUNT,0)*-1 AS TOTAL_SALES_AMOUNT	--入金金額(相殺)(ﾏｲﾅｽ)
		,		NULL AS ERASER_NO						--消込番号
		FROM 	(SELECT CLAIM_HEADER.CLAIM_NO
				 FROM CLAIM_HEADER
					  LEFT JOIN
						  LOGIN
						  ON CLAIM_HEADER.INPUTOR_CD = LOGIN.TANTO_CD
				 WHERE	CLAIM_HEADER.SECTION_CD IS NOT NULL
				 AND	CLAIM_HEADER.SECTION_CD = /*sectionCd*/'SC00001'
				 AND	CLAIM_HEADER.CUSTOMER_CD = /*venderCd*/'TS0001'
				 /*IF (( tantoCd != null ) && ( tantoCd != "" ))*/
				 AND   CLAIM_HEADER.INPUTOR_CD LIKE /*tantoCd*/
				 /*END*/
				 /*IF (( tantoNm != null ) && ( tantoNm != "" ))*/
				 AND	LOGIN.TANTO_NM LIKE /*tantoNm*/
				 /*END*/
				) CLAIM_HEADER
				INNER JOIN
					CREDIT CREDIT
					ON  CLAIM_HEADER.CLAIM_NO = CREDIT.CLAIM_NO
					AND CREDIT.DATA_TOTAL_DIVISION = '2'						--データ集計区分(2:相殺)
					AND CREDIT.ERASER_COMPLETE_DIVISION = '0'					--消込完了フラグ
					AND CREDIT.ERASER_COMPLETE_DATE IS NULL						--消込完了日
					AND CREDIT.CLAIM_TARGET_DIVISION = '1'						--請求対象
					AND CREDIT.CLAIM_UPDATE_DIVISION = '1'						--請求更新フラグ
					AND CREDIT.INVOICE_UPDATE_DATE IS NOT NULL					--請求締め日
				LEFT JOIN
					VENDER
					ON  CREDIT.CUSTOMER_CD = VENDER.VENDER_CD
					AND VENDER.VENDER_DIVISION = 'TS'							--得意先
				LEFT JOIN
					CLASSIFICATION
					ON  CREDIT.DATA_TYPE = CLASSIFICATION.DATA_TYPE
					AND CREDIT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION
		)
	ORDER BY CUSTOMER_CD
	,		 SALES_DATE
	,		 SLIP_NO
	,		 ROW_NO
/*END*/
