/*
* 消込入力詳細画面用SQL(カスタマイズ)
*
* entityName=EraserCsmDetail
* packageName=claim.eraser
* methodName=getDetailData
*
*/
SELECT ERASER_CSM.ORGANIZATION_CD --部署コード
	  ,ERASER_CSM.ORGANIZATION_NAME --部署名称
	  ,ERASER_CSM.INVOICE_CD AS VENDER_CD --請求先コード
	  ,ERASER_CSM.VENDER_NAME1 --請求先名称
	  ,ERASER_CSM.VENDER_SHORTED_NAME --請求先略称
	  ,ERASER_CSM.ERASER_OBJECT_AMOUNT AS ERASER_CAPA_AMOUNT --消込対象額
	  ,ERASER_CSM.ERASER_AMOUNT --消込額
	  ,ERASER_CSM.ERASER_BALANCE_AMOUNT --消込残合計
	  ,ERASER_CSM.ERASER_DATE --消込日付
	  ,NVL(CREDIT_SUM.SUM_CREDIT_AMOUNT, 0) AS SUM_CREDIT_AMOUNT --入金金額合計
	  ,NVL(CREDIT_SUM.SUM_ERASER_AMOUNT, 0) AS SUM_ERASER_AMOUNT --消込額合計
	  ,NVL(CREDIT_SUM.SUM_CREDIT_ERASER_AMOUNT, 0) AS SUM_CREDIT_ERASER_AMOUNT --入金消込残合計
	  ,CREDIT.CREDIT_DATE --入金日付
	  ,CREDIT.CREDIT_NO --入金番号
	  ,CREDIT.DATA_TYPE --データ種別
	  ,CREDIT.ROW_NO --行番号
	  ,CREDIT.NYUKIN_CATE_NAME --分類名称(入金分類)
	  ,CREDIT.CREDIT_AMOUNT --入金金額
	  ,CREDIT.CR_ERASER_AMOUNT --消込額
	  ,CREDIT.CREDIT_ERASER_AMOUNT --入金消込残
FROM   (
		--消込(Csm)データ
		SELECT ERASER_CSM.INVOICE_CD
			   ,MAX(ERASER_CSM.ORGANIZATION_CD) AS ORGANIZATION_CD
			   ,MAX(ORGANIZATION.ORGANIZATION_NAME) AS ORGANIZATION_NAME
			   ,MAX(VENDER.VENDER_NAME1) AS VENDER_NAME1
			   ,MAX(VENDER.VENDER_SHORTED_NAME) AS VENDER_SHORTED_NAME
			   ,SUM(ERASER_CSM.ERASER_OBJECT_AMOUNT) AS ERASER_OBJECT_AMOUNT --消込対象額
			   ,SUM(ERASER_CSM.ERASER_AMOUNT) AS ERASER_AMOUNT --消込金額
			   ,SUM(ERASER_CSM.ERASER_BALANCE_AMOUNT) AS ERASER_BALANCE_AMOUNT --消込残
			   ,MAX(ERASER_CSM.ERASER_DATE) AS ERASER_DATE --消込日付
		FROM   ERASER_CSM
		LEFT   JOIN ORGANIZATION
		ON     ERASER_CSM.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD
		LEFT   JOIN LOGIN
		ON     ERASER_CSM.INPUTOR_CD = LOGIN.TANTO_CD
		LEFT   JOIN VENDER
		ON     ERASER_CSM.INVOICE_CD = VENDER.VENDER_CD
		AND    VENDER.VENDER_DIVISION = 'TS' --得意先
		WHERE  ERASER_CSM.ORGANIZATION_CD IS NOT NULL
		AND    ERASER_CSM.ORGANIZATION_CD = /*organizationCd*/'%'
		AND    ERASER_CSM.CLAIM_NO = /*claimNo*/'%'
			  
			  /*IF (( tantoCd != null ) && ( tantoCd != "" ))*/
		AND    ERASER_CSM.INPUTOR_CD LIKE /*tantoCd*/'%'
			  /*END*/
			  
			  /*IF (( venderCd != null ) && ( venderCd != "" ))*/
		AND    ERASER_CSM.INVOICE_CD = /*venderCd*/'%'
			  /*END*/
			  
			  /*IF (( eraserCompleteDateFrom != null ) && ( eraserCompleteDateFrom != "" ))*/
		AND    ERASER_CSM.ERASER_COMPLETE_DATE >= /*eraserCompleteDateFrom*/'2010/01/01'
			  /*END*/
			  
			  /*IF (( eraserCompleteDateTo != null ) && ( eraserCompleteDateTo != "" ))*/
		AND    ERASER_CSM.ERASER_COMPLETE_DATE <= /*eraserCompleteDateTo*/'2010/12/31'
			  /*END*/
			  
			  /*IF ( kbn != null && kbn == "2" )*/
		AND    ERASER_CSM.ERASER_COMPLETE_DIVISION = 1 --処理中のみ
			  /*END*/
			  
		AND    ERASER_CSM.APPROVAL_STATUS = /*approvalStatus*/1
		GROUP  BY ERASER_CSM.INVOICE_CD) ERASER_CSM
LEFT   JOIN (
			 --入金合計
			 SELECT ORGANIZATION_CD --部門コード
					,VENDER_CD --請求先コード
					,SUM(SUM_CREDIT_AMOUNT) AS SUM_CREDIT_AMOUNT --入金金額
					,SUM(SUM_ERASER_AMOUNT) AS SUM_ERASER_AMOUNT --消込額
					,SUM(SUM_CREDIT_ERASER_AMOUNT) AS SUM_CREDIT_ERASER_AMOUNT --入金消込残
			 FROM   (
					  --部門・請求先に紐づく入金消込残<>０のデータ
					  SELECT CREDIT.ORGANIZATION_CD --部門コード
							 ,CREDIT.VENDER_CD AS VENDER_CD --請求先コード
							 ,SUM(NVL(CREDIT.CREDIT_AMOUNT, 0)) AS SUM_CREDIT_AMOUNT --入金金額
							 ,SUM(NVL(CREDIT.ERASER_AMOUNT, 0)) AS SUM_ERASER_AMOUNT --消込額
							 ,SUM(NVL(CREDIT.CREDIT_ERASER_AMOUNT, 0)) AS SUM_CREDIT_ERASER_AMOUNT --入金消込残
					  FROM   CREDIT CREDIT
					  WHERE  CREDIT.ORGANIZATION_CD IS NOT NULL
					  AND    CREDIT.ORGANIZATION_CD = /*organizationCd*/'%'
					  AND    CREDIT.VENDER_CD = /*venderCd*/'%'
					  AND    CREDIT.APPROVAL_STATUS = 3 --承認
					  AND    (CREDIT.DATA_TOTAL_DIVISION = '1' OR CREDIT.DATA_TOTAL_DIVISION = '9') --データ集計区分(1:入金、9:その他)
					  AND    CREDIT.CLAIM_TARGET_DIVISION <> '9' --請求対象
					  AND    CREDIT.CREDIT_ERASER_AMOUNT <> 0 --入金消込残<>０
					  GROUP  BY CREDIT.ORGANIZATION_CD
								,CREDIT.VENDER_CD
					  UNION
					  
					  SELECT OFFSET.ORGANIZATION_CD
							,OFFSET.VENDER_CD
							,SUM(NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT, 0)) SUM_CREDIT_AMOUNT
							,SUM(NVL(OFFSET.ERASER_AMOUNT, 0)) SUM_ERASER_AMOUNT
							,SUM(NVL(OFFSET.CREDIT_ERASER_AMOUNT, 0)) SUM_CREDIT_ERASER_AMOUNT
					  FROM   OFFSET_GROUP_DATA OFFSET
					  WHERE  OFFSET.ORGANIZATION_CD IS NOT NULL
					  AND    OFFSET.ORGANIZATION_CD = /*organizationCd*/'%'
					  AND    OFFSET.VENDER_DIVISION = 'TS' --得意先
					  AND    OFFSET.VENDER_CD = /*venderCd*/'%'
					  AND    OFFSET.APPROVAL_STATUS = 3 --承認済
					  AND    (OFFSET.DATA_TOTAL_DIVISION = 1 OR OFFSET.DATA_TOTAL_DIVISION = 9) --相殺 OR その他
					  AND    OFFSET.CLAIM_TARGET_DIVISION <> 9 --対象外
					  AND    OFFSET.CREDIT_ERASER_AMOUNT <> 0
					  GROUP  BY OFFSET.ORGANIZATION_CD
							   ,OFFSET.VENDER_DIVISION
							   ,OFFSET.VENDER_CD)
			 GROUP  BY ORGANIZATION_CD
					   ,VENDER_CD) CREDIT_SUM
ON     ERASER_CSM.ORGANIZATION_CD = CREDIT_SUM.ORGANIZATION_CD
AND    ERASER_CSM.INVOICE_CD = CREDIT_SUM.VENDER_CD
LEFT   JOIN (
			 --入金内訳
			 SELECT DISTINCT ORGANIZATION_CD --部門コード
							 ,VENDER_CD --請求先コード
							 ,CREDIT_DATE --入金日付
							 ,CREDIT_NO --入金番号
							 ,DATA_TYPE --データ種別
							 ,ROW_NO --行番号
							 ,NYUKIN_CATE_NAME --分類名称(入金分類)
							 ,CREDIT_AMOUNT --入金金額
							 ,CR_ERASER_AMOUNT --消込額
							 ,CREDIT_ERASER_AMOUNT --入金消込残
			 FROM   (
					  --部門・請求先に紐づく入金消込残<>０の入金データ
					  SELECT CREDIT.ORGANIZATION_CD --部門コード
							 ,CREDIT.VENDER_CD AS VENDER_CD --請求先コード
							 ,CREDIT.CREDIT_DATE --入金日付
							 ,CREDIT.CREDIT_NO --入金番号
							 ,CREDIT.DATA_TYPE --データ種別
							 ,CREDIT.ROW_NO --行番号
							 ,CL2.CATEGORY_NAME AS NYUKIN_CATE_NAME --分類名称(入金分類)
							 ,NVL(CREDIT.CREDIT_AMOUNT, 0) AS CREDIT_AMOUNT --入金金額
							 ,NVL(CREDIT.ERASER_AMOUNT, 0) AS CR_ERASER_AMOUNT --消込額
							 ,NVL(CREDIT.CREDIT_ERASER_AMOUNT, 0) AS CREDIT_ERASER_AMOUNT --入金消込残
					  FROM   CREDIT CREDIT
					  LEFT   JOIN CLASSIFICATION CL2
					  ON     CREDIT.DATA_TYPE = CL2.DATA_TYPE
					  AND    CREDIT.CATEGORY_DIVISION = CL2.CATEGORY_DIVISION
					  WHERE  CREDIT.ORGANIZATION_CD IS NOT NULL
					  AND    CREDIT.ORGANIZATION_CD = /*organizationCd*/'%'
					  AND    CREDIT.VENDER_CD = /*venderCd*/'%'
					  AND    CREDIT.APPROVAL_STATUS = 3 --承認
					  AND    (CREDIT.DATA_TOTAL_DIVISION = '1' OR CREDIT.DATA_TOTAL_DIVISION = '9') --データ集計区分(1:入金、9:その他)
					  AND    CREDIT.CLAIM_TARGET_DIVISION <> '9' --請求対象
					  AND    CREDIT.CREDIT_ERASER_AMOUNT <> 0 --入金消込残<>０
					  )
			 
			 UNION
			 
			  (SELECT OFFSET.ORGANIZATION_CD
					 ,OFFSET.VENDER_CD
					 ,OFFSET.OFFSET_DATE CREDIT_DATE
					 ,OFFSET.OFFSET_NO CREDIT_NO
					 ,OFFSET.DATA_TYPE
					 ,NULL ROW_NO
					 ,CLS.CATEGORY_NAME NYUKIN_CATE_NAME
					 ,NVL(OFFSET.DEPOSIT_OFFSET_AMOUNT, 0) ERASER_AMOUNT
					 ,NVL(OFFSET.ERASER_AMOUNT, 0) ERASER_AMOUNT
					 ,NVL(OFFSET.CREDIT_ERASER_AMOUNT, 0) CREDIT_ERASER_AMOUNT
			   FROM   OFFSET_GROUP_DATA OFFSET
					 ,CLASSIFICATION    CLS
			   WHERE  OFFSET.ORGANIZATION_CD IS NOT NULL
			   AND    OFFSET.ORGANIZATION_CD = /*organizationCd*/'%'
			   AND    OFFSET.VENDER_DIVISION = 'TS' --得意先
			   AND    OFFSET.VENDER_CD = /*venderCd*/'%'
			   AND    OFFSET.APPROVAL_STATUS = 3 --承認済
			   AND    (OFFSET.DATA_TOTAL_DIVISION = 1 OR OFFSET.DATA_TOTAL_DIVISION = 9) --相殺 OR その他
			   AND    OFFSET.CLAIM_TARGET_DIVISION <> 9 --対象外
			   AND    OFFSET.CREDIT_ERASER_AMOUNT <> 0
			   AND    OFFSET.DATA_TYPE = CLS.DATA_TYPE(+)
			   AND    OFFSET.CATEGORY_DIVISION = CLS.CATEGORY_DIVISION(+))) CREDIT
ON     ERASER_CSM.ORGANIZATION_CD = CREDIT.ORGANIZATION_CD
AND    ERASER_CSM.INVOICE_CD = CREDIT.VENDER_CD
ORDER  BY CREDIT_DATE
		 ,DATA_TYPE DESC
		 ,ROW_NO
