/*
 * ��Ɠ��w�b��ꗗ�pSQL
 *
 * entityName=DailyReportDetailListForReport
 * packageName=dailyeportforreport
 * methodName=getDetailListForReprot
 *
 */
SELECT
	DAILY_REPORT.PRODUCTION_LINE
,	LINE.PRODUCTION_LINE_NAME
,	DIRECTION_ITEM.ITEM_CD
,	DIRECTION_ITEM.ITEM_NAME
,	DAILY_REPORT.PRODUCTION_DATE
,	DAILY_REPORT.TANTO_DIVISION
,	DAILY_REPORT.TANTO_CD
,	TANTO.TANTO_NM
,	DAILY_REPORT.DIRECTION_NO
,	DAILY_REPORT.JOB_TIME
,	DAILY_REPORT.JOB_TIME_HHMM

,	DAILY_REPORT.INPUT_DATE
,	DAILY_REPORT.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	DAILY_REPORT.UPDATE_DATE
,	DAILY_REPORT.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM DAILY_REPORT
	INNER JOIN (
/*IF (condition.srhTantoDiv != null) && (condition.srhTantoDiv == "1")*/
			SELECT	-- �S����
				 TANTO_CD
				,TANTO_NM
			 FROM LOGIN
/*END*/
/*IF (condition.srhTantoDiv != null) && (condition.srhTantoDiv == "2")*/
			SELECT	-- 協力会社
				 ORGANIZATION_CD AS TANTO_CD
				,ORGANIZATION_NAME AS TANTO_NM
			FROM ORGANIZATION
/*END*/
			) TANTO ON DAILY_REPORT.TANTO_CD = TANTO.TANTO_CD
	INNER JOIN (LOGIN) INPUTOR ON DAILY_REPORT.INPUTOR_CD = INPUTOR.TANTO_CD
	INNER JOIN (LOGIN) UPDATOR ON DAILY_REPORT.UPDATOR_CD = UPDATOR.TANTO_CD
	INNER JOIN (LINE) LINE ON DAILY_REPORT.PRODUCTION_LINE = LINE.PRODUCTION_LINE
	INNER JOIN (SELECT DIRECTION_NO,ITEM.ITEM_CD,ITEM.ITEM_NAME FROM DIRECTION_HEADER,ITEM WHERE ITEM.ITEM_CD = DIRECTION_HEADER.ITEM_CD) DIRECTION_ITEM ON DIRECTION_ITEM.DIRECTION_NO = DAILY_REPORT.DIRECTION_NO


WHERE DAILY_REPORT.TANTO_CD IS NOT NULL
AND	TO_CHAR(DAILY_REPORT.PRODUCTION_DATE,'YYYY/MM/DD') = /*condition.srhDate*/'2009/04/14'
AND	DAILY_REPORT.PRODUCTION_LINE = /*condition.srhLine*/'KL'
AND	DAILY_REPORT.TANTO_DIVISION = /*condition.srhTantoDiv*/'1'
ORDER BY DAILY_REPORT.TANTO_DIVISION,  DAILY_REPORT.TANTO_CD,DAILY_REPORT.DIRECTION_NO


