CREATE OR REPLACE PACKAGE AP21.PAK_ALLZAITABLE IS

--本番用
	LNG_OPNO NUMBER := 0;				--0:出荷指示更新,1:出荷処理更新,2:手持在庫更新,3:親品目発注残更新,4:子品目引当残更新,5:受入(検査なし)更新,6:受入(検査あり)更新,7:検収入力更新,8:子品目出庫更新,9:出荷売上系(受注番号なし),10:在庫評価単価特殊更新（仕入単価決定入力時）,11:ロケーション別棚卸情報更新,12:在庫評価単価特殊更新（月次総平均）,13:棚卸調整(),14:棚卸調整,15:売上(返品),20:受注
	LNG_INOUTKBN NUMBER := 0;			--処理区分(0:入庫, 1:出庫)
	STR_ITEMCODE VARCHAR2(255) := '';		--品目コード
	LNG_QTY NUMBER := 0;				--数量
	LNG_FAULTQTY NUMBER := 0;			--不良数量
	DTE_INOUTDATE DATE := '';			--入出庫日
	STR_LOCATIONCODE VARCHAR2(255) := '';		--ロケーションコード
	LNG_COST NUMBER := 100;				--単価(在庫評価単価計算時に使用)
	DTE_UKEDATE DATE;				--受入日(在庫評価単価計算時に使用)
	LNG_COSTFLG NUMBER := 0;			--仮単価フラグ(在庫評価単価計算時に使用)(0:通常 1:仮単価)
	LNG_CHKFLG NUMBER := 1;				--チェック無フラグ (0:在庫管理区分チェックをしない 1:在庫管理区分チェックをする)
	LNG_CALCCOSTFLG NUMBER := 0;			--在庫評価単価更新フラグ (0:在庫評価単価を再計算する 1:在庫評価単価を再計算しない)
	LNG_INVENTORYQTY NUMBER := 0;			--棚卸時点在庫数
	LNG_INVENTORYCOST NUMBER := 0;			--棚卸時点単価
	STR_LOTCODE VARCHAR2(255) := '';		--ロット
	DTE_YUKOKAISHIDATE DATE := '';			--有効開始日付	2007/12/12追加
	DTE_LOTMAKEDATE DATE := '';			--ロット発生日時	2007/12/12追加
	DTE_START_DATE DATE := '';			--有効開始日付	2007/12/12追加
	DTE_ISSUE_DATE DATE := '';			--ロット発生日時	2007/12/12追加
	DTE_END_DATE DATE := '';			--有効終了日付	2007/12/21追加
	LNG_INOUTDIVISION NUMBER := 0;			--受払区分(1:製造受入,2:製造払出,3:入荷受入,4:出荷払出,5:支給払出)
	STR_ODERNO VARCHAR2(255);			--オーダー番号
	LNG_ODERLINENO NUMBER := 0;			--オーダー行番号
	LNG_INOUTPRICE NUMBER := 0;			--受払時点単価
	LNG_INOUTCOST NUMBER := 0;			--受払金額
	STR_REMARK NVARCHAR2(255) := '';			--摘要
	LNG_INOUTSOURCEDELFLG NUMBER := 0;		--受払ソース削除フラグ(0以外:削除)	2007/12/12追加
	STR_INOUTSOURCENO VARCHAR2(255) := '';		--受払ソース番号
	STR_SECTIONCD VARCHAR2(255) := '';		--入力者部門コード
	STR_ACCOUNTCD VARCHAR2(255) := '';		--科目コード
	STR_SUBACCOUNTCD VARCHAR2(255) := '';		--補助科目コード
	STR_ITEMCATEGORY VARCHAR2(255) := '';		--品目分類コード
	STR_PARENTITEMCD VARCHAR2(255) := '';		--親品目コード
	STR_PARENTACCOUNTCD VARCHAR2(255) := '';	--親科目コード
	STR_PARENTSUBACCOUNTCD VARCHAR2(255) := '';	--親補助科目コード
	STR_PARENTITEMCATEGORY VARCHAR2(255) := '';	--親品目分類コード
	STR_REASON VARCHAR2(255) := '';			--理由
	STR_INOUTUPDATEDATE VARCHAR2(255) := '';	--受払更新日付
	STR_INVENTORYUPDATEDATE VARCHAR2(255) := '';	--在庫更新日付
	LNG_LOTTRACEDELFLG NUMBER := 0;			--ロットトレース削除フラグ(0以外:削除)	2007/12/12追加
	LNG_FUNCDIVISION NUMBER := 0;			--処理区分
	STR_SLIPNO VARCHAR2(255) := '';			--伝票番号
	LNG_SLIPLINENO NUMBER := 0;			--伝票行番号
	LNG_ORDERDIVISION NUMBER := 0;			--主オーダー区分
	STR_ORDERNO VARCHAR2(255) := '';		--主オーダー番号
	LNG_LASTINDIVISION NUMBER := 0;			--出庫元在庫入庫区分
	STR_LASTINNO VARCHAR2(255) := '';		--出庫元在庫入庫番号
	STR_INPUTNO VARCHAR2(255) := '';		--入力者				2007/12/12追加
	STR_ALIAS_LOT VARCHAR2(255) := '';

	STR_HANPA_ITEMCODE VARCHAR2(255) := '';		--代表品目コード(半端用）		2008/10/30追加
	LNG_HANPAQTY NUMBER := 0;			--半端数量				2008/10/30追加
-- ここまで 

	LNG_AZUDIV NUMBER := 0;			--預品区分(0:手持ち在庫, 1:検査待ち在庫)

	STR_DATE VARCHAR2(255);			--入力日付

	STR_RYCD NVARCHAR2(8) := '';

	LNG_SYORIF		NUMBER := 0;					--処理進行状況（0=正常 / 0以外=異常）
	STR_ERRORCODE		VARCHAR2(255) := '';				--エラーコード
	STR_ERRORNAME		VARCHAR2(255) := '';				--エラー名称
	CSTR_DATEFORMAT		VARCHAR2(255) := 'RRRR-MM-DD';			--日付フォーマット用
	CSTR_FULLDATEFORMAT	VARCHAR2(255) := 'RRRR-MM-DD HH24:MI:SS';	--日付フォーマット用


-- 2008.02.09 Add Start Kitada
-- 更新前ロットデータ保存用
	LNG_INVENTORY_QTY		NUMBER := 0;
	LNG_BACKORDER_QTY		NUMBER := 0;
	LNG_ASSIGN_QTY			NUMBER := 0;
	LNG_SALES_ASSIGN_QTY		NUMBER := 0;
	LNG_INSPECTION_QTY		NUMBER := 0;
	LNG_INVALID_QTY			NUMBER := 0;
	LNG_FAULT_QTY			NUMBER := 0;

	--会社情報
	STR_COMPANY_CD COMPANY.COMPANY_CD%TYPE := 'COMPA00001';
	CURSOR	CUR_COMPANY(PARA IN VARCHAR2) IS SELECT * FROM COMPANY WHERE COMPANY_CD = PARA;
	F_COMPANY  CUR_COMPANY%ROWTYPE;
-- 2008.02.09 Add End Kitada

	--在庫UPDATE
	PROCEDURE UPDATE_ZAI(OUT_ERROR OUT VARCHAR2);
	--在庫関連更新
	PROCEDURE UPDATE_ALLZAITABLE;
	--在庫
	PROCEDURE UPDATE_ZAICTL;
	--受払履歴
	PROCEDURE UPDATE_INOUT_RECORD_CTL;
	--受払ソース
	PROCEDURE UPDATE_INOUT_SOURCE_CTL;
	--受払ソース
	PROCEDURE UPDATE_INOUT_SOURCE_CTL11;
	--受払ソース
	PROCEDURE UPDATE_INOUT_SOURCE_CTL99;
	--ロットトレース
	PROCEDURE UPDATE_LOTTRACE;
	--在庫テーブルチェック（無ければ作成）
	PROCEDURE INVENTORYTABLE_CHK;
	--科目等セット
	PROCEDURE ACCOUNT_ETC_SET;
-- 2008.02.09 Add Start Kitada
	--親ロケ作成
	PROCEDURE PRO_LOCATION_ZAIKO_MAKE(PARA_STR_LOCATION IN VARCHAR2
					,PARA_STR_ITEM IN VARCHAR2
					,PARA_STR_LOT IN VARCHAR2
					,PARA_LNG_QTY IN NUMBER);
-- 2008.02.09 Add Start Kitada
	--
	FUNCTION UPDATE_PRE_CHK RETURN NUMBER;
	FUNCTION FUN_GET_LOTMAKEDATE(ITEMCD VARCHAR2,LOTNO VARCHAR2,SETDATE date) RETURN DATE;
--- 2010.11.19 Add ETO BACKORDER_QTY負値調査
	FUNCTION CHK_BACKORDER_QTY(ITEMCD VARCHAR2) RETURN NUMBER ;
	PROCEDURE CHK_BACKORDER_QTY_NEGATIVE(BEFORE_QTY IN NUMBER, AFTER_QTY IN NUMBER);


END;
/
