CREATE OR REPLACE PACKAGE AP21.ZAIKOUKEHARAI IS
	--■
	--■　受注関連プロシージャ
	--■
	--受注入力
	PROCEDURE ENTRY_ORDER(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_ROW_NO IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--■
	--■　発注関連プロシージャ
	--■
	--発注入力
	PROCEDURE ENTRY_PURCHASE(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--受入入力
	PROCEDURE RECEIVE_PURCHASE(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--発注完了
	PROCEDURE COMPLETE_PURCHASE(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 ) ;
	--■
	--■　出荷関連プロシージャ
	--■
	--出荷指図入力（一詳細）
	PROCEDURE ENTRY_SHIPPING(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_ROW_NO IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--■
	--■　製造関連プロシージャ
	--■
	--包装・製造指図入力
	PROCEDURE ENTRY_DIRECTION(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
    	-- レシピに従い製造指図を作成する
    	PROCEDURE CREATE_DIRECTION(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
    	-- 在庫チェック
	PROCEDURE CHK_INVENTORY(STR_ITEM IN NVARCHAR2,QTY IN NUMBER,B_FLG IN boolean,STR_MESSAGE OUT NVARCHAR2 );
	--配合指図入力
	PROCEDURE ENTRY_FORMULA(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,LNG_STEP IN NUMBER,LNG_LINE IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--配合実績入力
	PROCEDURE RESULT_FORMULA(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,LNG_STEP IN NUMBER,LNG_LINE IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--外注投入実績入力
	PROCEDURE RESULT_INJECTION(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,LNG_STEP IN NUMBER,LNG_LINE IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--包装・製造指図実績入力 
	PROCEDURE RESULT_DIRECTION(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	PROCEDURE RESULT_GRADE(LNG_FLG IN NUMBER,STR_CODE IN NVARCHAR2,LNG_DIV IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	--■
	--■　在庫入出庫関連プロシージャ
	--■
	-- 返品入庫
	PROCEDURE RETURN_DELIVERY(LNG_FLG IN NUMBER,SLIP_NO IN NVARCHAR2,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	-- 在庫入出庫入力 棚卸　預品売上計上
	PROCEDURE ENTRY_INOUT(LNG_FLG IN NUMBER,ITEM_CODE IN NVARCHAR2,QTY IN NUMBER,INOUTDATE IN DATE,LOCATION IN NVARCHAR2,LOT IN NVARCHAR2,REMARK IN NVARCHAR2,REASON IN NVARCHAR2,REASONCD IN NVARCHAR2,LNG_FUNC IN NUMBER,LNG_INOUT IN NUMBER,STR_ALOT IN NVARCHAR2,LNG_COST IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
	PROCEDURE ENTRY_SALES(LNG_FLG IN NUMBER,ITEM_CODE IN NVARCHAR2,QTY IN NUMBER,INOUTDATE IN DATE,LOCATION IN NVARCHAR2,LOT IN NVARCHAR2,REMARK IN NVARCHAR2,REASON IN NVARCHAR2,REASONCD IN NVARCHAR2,LNG_FUNC IN NUMBER,LNG_INOUT IN NUMBER,STR_ALOT IN NVARCHAR2,LNG_COST IN NUMBER,STR_LOGIN_USER IN NVARCHAR2,OUT_PARA OUT NVARCHAR2 );
END;
/
