/*
*entityName=InoutMaterial
*packageName=inoutmaterial
*methodName=getList
*/
-- ①原材料別入出庫一覧表用ビューを品目と区分（理由など）毎に数量と金額を集計している。
WITH REP_INOUT_MATERIAL_DATA AS(
	SELECT 
	ITEM_CD
	,	DIVISION
	,	SUM(QTY) AS QTY 
	,	SUM(AMOUNT) AS AMOUNT
	FROM 
		REP_INOUT_MATERIAL 
	WHERE 
		YEAR_MONTH >= /*condition.srhDateFrom*/
		AND YEAR_MONTH <= /*condition.srhDateTo*/
	GROUP BY ITEM_CD
		,DIVISION
)

-- ②では①で作成した仮テーブルを参照して、品目毎に理由毎の数量・金額の合計を出力している。
SELECT
	ITEM.ITEM_CD
,	(CASE WHEN ITEM.SHIPPER_DIVISION IN(0,1,2) THEN '化成品' ELSE '油脂' END) STOCK_DIVISION
,	(CASE WHEN ITEM.TYPE_DIVISION =1 THEN '原料' ELSE '包材' END) TYPE_DIVISION
,	ITEM.ITEM_NAME
,	ITEM.STYLE_OF_PACKING
,	NVL(ZENZAN_QTY.QTY,0) AS ZENZAN_QTY
,	NVL(ZENZAN_AMOUNT.AMOUNT,0) AS ZENZAN_AMOUNT
,	NVL(TOUGETU_UKEIRE_QTY.QTY,0) AS TOUGETU_UKEIRE_QTY
,	NVL(TOUGETU_UKEIRE_AMOUNT.AMOUNT,0) AS TOUGETU_UKEIRE_AMOUNT
,	NVL(HENPIN_QTY.QTY,0) AS HENPIN_QTY
,	NVL(HENPIN_AMOUNT.AMOUNT,0) AS HENPIN_AMOUNT
,	NVL(RY_401_ZISYA.QTY,0) AS RY_401_ZISYA_QTY
,	NVL(RY_401_KAO.QTY,0) AS RY_401_KAO_QTY
,	NVL(RY_402.QTY,0) AS RY_402_QTY
,	NVL(RY_403.QTY,0) AS RY_403_QTY
,	NVL(RY_404.QTY,0) AS RY_404_QTY
,	NVL(RY_405.QTY,0) AS RY_405_QTY
,	NVL(RY_406.QTY,0) AS RY_406_QTY
,	NVL(RY_407.QTY,0) AS RY_407_QTY
,	NVL(RY_408.QTY,0) AS RY_408_QTY
,	NVL(RY_409.QTY,0) AS RY_409_QTY
,	NVL(RY_410.QTY,0) AS RY_410_QTY
,	NVL(RY_999.QTY,0) AS RY_999_QTY
,	NVL(RY_302.QTY,0) AS RY_302_QTY
,	NVL(RY_302.AMOUNT,0) AS RY_302_AMOUNT

FROM	
	ITEM
,	(SELECT ITEM_CD,QTY FROM REP_INOUT_MATERIAL WHERE REP_INOUT_MATERIAL.DIVISION = 'ZENZAN_QTY' AND YEAR_MONTH = /*condition.srhDateFrom*/) ZENZAN_QTY
,	(SELECT ITEM_CD,AMOUNT FROM REP_INOUT_MATERIAL WHERE REP_INOUT_MATERIAL.DIVISION = 'ZENZAN_AMOUNT' AND YEAR_MONTH = /*condition.srhDatePrev*/) ZENZAN_AMOUNT
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'TOUGETU_UKEIRE_QTY'  GROUP BY ITEM_CD) TOUGETU_UKEIRE_QTY
,	(SELECT ITEM_CD,SUM(AMOUNT) AS AMOUNT FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'TOUGETU_UKEIRE_AMOUNT'  GROUP BY ITEM_CD) TOUGETU_UKEIRE_AMOUNT
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'HENPIN_QTY'  GROUP BY ITEM_CD) HENPIN_QTY
,	(SELECT ITEM_CD,SUM(AMOUNT) AS AMOUNT FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'HENPIN_AMOUNT'  GROUP BY ITEM_CD) HENPIN_AMOUNT
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_401_ZISYA'  GROUP BY ITEM_CD) RY_401_ZISYA
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_401_KAO'  GROUP BY ITEM_CD) RY_401_KAO
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_402'  GROUP BY ITEM_CD) RY_402
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_403'  GROUP BY ITEM_CD) RY_403
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_404'  GROUP BY ITEM_CD) RY_404
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_405'  GROUP BY ITEM_CD) RY_405
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_406'  GROUP BY ITEM_CD) RY_406
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_407'  GROUP BY ITEM_CD) RY_407
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_408'  GROUP BY ITEM_CD) RY_408
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_409'  GROUP BY ITEM_CD) RY_409
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_410'  GROUP BY ITEM_CD) RY_410
,	(SELECT ITEM_CD,SUM(QTY) AS QTY FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_999'  GROUP BY ITEM_CD) RY_999
,	(SELECT ITEM_CD,SUM(QTY) AS QTY,SUM(AMOUNT) AS AMOUNT FROM REP_INOUT_MATERIAL_DATA WHERE REP_INOUT_MATERIAL_DATA.DIVISION = 'RY_302'  GROUP BY ITEM_CD) RY_302
WHERE
	ITEM.ITEM_CD = ZENZAN_QTY.ITEM_CD(+)
AND	ITEM.ITEM_CD = ZENZAN_AMOUNT.ITEM_CD(+)
AND	ITEM.ITEM_CD = HENPIN_QTY.ITEM_CD(+)
AND	ITEM.ITEM_CD = HENPIN_AMOUNT.ITEM_CD(+)
AND	ITEM.ITEM_CD = TOUGETU_UKEIRE_QTY.ITEM_CD(+)
AND	ITEM.ITEM_CD = TOUGETU_UKEIRE_AMOUNT.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_401_ZISYA.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_401_KAO.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_402.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_403.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_404.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_405.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_406.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_407.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_408.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_409.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_410.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_999.ITEM_CD(+)
AND	ITEM.ITEM_CD = RY_302.ITEM_CD(+)
/*IF (condition.srhBalanceType == 2)*/
AND	ITEM.SHIPPER_DIVISION IN (0,1,2)
/*END*/

/*IF (condition.srhBalanceType == 1)*/
AND	ITEM.SHIPPER_DIVISION = 3
/*END*/

/*IF ((condition.srhDirectionDivision != null) && (condition.srhDirectionDivision != ""))*/

	/*IF (condition.srhShipperDivision != "0")*/
		AND	ITEM.TYPE_DIVISION = /*condition.srhDirectionDivision*/
	/*END*/		
/*END*/

/*IF (( condition.srhShipperDivision != null ) && ( condition.srhShipperDivision != "" ))*/

	/*IF (condition.srhShipperDivision == "0")*/

	/*END*/

	/*IF (condition.srhShipperDivision != "0")*/
			AND	ITEM.SHIPPER_DIVISION + 1 = /*condition.srhShipperDivision*/1
	/*END*/		
/*END*/

/*IF (( condition.srhStyleOfPacking != null ) && ( condition.srhStyleOfPacking != "" ))*/
AND	ITEM.STYLE_OF_PACKING LIKE /*condition.srhStyleOfPacking*/
/*END*/


AND	(ZENZAN_QTY.QTY > 0
	OR TOUGETU_UKEIRE_QTY.QTY IS NOT NULL OR TOUGETU_UKEIRE_AMOUNT.AMOUNT IS NOT NULL 
	OR	HENPIN_QTY.QTY IS NOT NULL OR HENPIN_AMOUNT.AMOUNT IS NOT NULL
	OR	RY_401_ZISYA.QTY IS NOT NULL 
	OR	RY_401_KAO.QTY IS NOT NULL 
	OR	RY_402.QTY IS NOT NULL 
	OR	RY_403.QTY IS NOT NULL 
	OR	RY_404.QTY IS NOT NULL 
	OR	RY_405.QTY IS NOT NULL 
	OR	RY_406.QTY IS NOT NULL 
	OR	RY_407.QTY IS NOT NULL 
	OR	RY_408.QTY IS NOT NULL 
	OR	RY_409.QTY IS NOT NULL 
	OR	RY_410.QTY IS NOT NULL 
	OR	RY_999.QTY IS NOT NULL 
	OR	RY_302.QTY IS NOT NULL OR RY_302.AMOUNT IS NOT NULL
)
ORDER BY STOCK_DIVISION,TYPE_DIVISION,ITEM.ITEM_CD