CREATE OR REPLACE FUNCTION      FUN_GET_ITEM_PARENT_ITEM_CD(PARA VARCHAR2) RETURN VARCHAR2 IS
--■■■■■■■■■■■■■■■■■■■
--■　親品目コード取得
--■　TABLE:ITEM
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STRCODE	VARCHAR2(255) := '';
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM ITEM
	WHERE
		ITEM_CD = PARA
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN NULL;
	ELSE
		--
		SELECT PARENT_ITEM_CD INTO STRCODE FROM ITEM
		WHERE
			ITEM_CD = PARA
		;
		RETURN STRCODE;
	END IF;
END;
/
