CREATE OR REPLACE FUNCTION      FUN_GET_ITEM_ZAITANKAKBN(PARA VARCHAR2) RETURN NUMBER IS
--■■■■■■■■■■■■■■■■■■■
--■　在庫評価単価区分取得
--■　TABLE:ITEM
--■■■■■■■■■■■■■■■■■■■
	LNGRC		NUMBER:=0;
	LNG_ZAIKBN	NUMBER:=0;
BEGIN
	--
	SELECT COUNT(*) INTO LNGRC FROM ITEM
	WHERE
		ITEM_CD = PARA
	;
	--
	IF LNGRC = 0 THEN
		RETURN 0;
	ELSE
		--
		SELECT COST_DIVISION INTO LNG_ZAIKBN FROM ITEM
		WHERE
			ITEM_CD = PARA
		;
		RETURN LNG_ZAIKBN;
	END IF;
END;
/
