CREATE OR REPLACE FUNCTION AP21.FUN_GET_ACCOUNT_CD(PARA VARCHAR2) RETURN VARCHAR2 IS
--■■■■■■■■■■■■■■■■■■■
--■　科目コード取得
--■　TABLE:ITEM_CATEGORY
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STRCODE	VARCHAR2(255) := '';
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM ITEM
	WHERE
		ITEM_CD = PARA
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN 9;
	END IF;
 	SELECT COUNT(*) INTO LNGRC FROM ARTICLE_ATTRIBUTE_QUEUE
	WHERE
		ITEM_CD = PARA
	;
	IF LNGRC IS not NULL AND LNGRC > 0 THEN
		--科目コード取得
		SELECT ACCOUNTS_CD INTO STRCODE FROM ARTICLE_ATTRIBUTE_QUEUE
		WHERE
			ITEM_CD = PARA AND VERSION = (SELECT VERSION FROM ITEM WHERE ITEM_CD = PARA )
		;
		RETURN STRCODE;
	END IF;

 	SELECT COUNT(*) INTO LNGRC FROM PURCHASE_ATTRIBUTE_QUEUE
	WHERE
		ITEM_CD = PARA
	;
	IF LNGRC IS not NULL AND LNGRC > 0 THEN
		--科目コード取得
		SELECT ACCOUNTS_CD INTO STRCODE FROM PURCHASE_ATTRIBUTE_QUEUE
		WHERE
			ITEM_CD = PARA AND VERSION = (SELECT VERSION FROM ITEM WHERE ITEM_CD = PARA )
		;
		RETURN STRCODE;
	END IF;
 	SELECT COUNT(*) INTO LNGRC FROM PRODUCT_ATTRIBUTE_QUEUE
	WHERE
		ITEM_CD = PARA AND VERSION = (SELECT VERSION FROM ITEM WHERE ITEM_CD = PARA )
	;
	IF LNGRC IS not NULL AND LNGRC > 0 THEN
 		SELECT COUNT(*) INTO LNGRC FROM ACCOUNTS
		WHERE
			ACCOUNTS_NAME = '製品'
		;
		IF LNGRC IS  NULL OR LNGRC = 0 THEN
			RETURN 9;
		END IF;
		SELECT ACCOUNTS_CD INTO STRCODE FROM ACCOUNTS
		WHERE
			ACCOUNTS_NAME = '製品'
		;
		RETURN STRCODE;
	END IF;
	RETURN 9;
END;
/
