CREATE OR REPLACE FUNCTION      FUN_GET_INOUT_QTY(PARA1 VARCHAR2,PARA2 NUMBER) RETURN VARCHAR IS
--■■■■■■■■■■■■■■■■■■■
--■　受払ソース数量取得
--■　TABLE:INOUT_SOURCE
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	LNGQTY	NUMBER := 0;
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM INOUT_SOURCE
	WHERE
		ODER_NO          = PARA1
		AND ODER_LINE_NO = PARA2
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN 0;
	ELSE
		--
		SELECT INOUT_QTY*ASSIGN_FLAG INTO LNGQTY FROM INOUT_SOURCE
		WHERE
			ODER_NO          = PARA1
			AND ODER_LINE_NO = PARA2
		;
		RETURN LNGQTY;
	END IF;
END;
/
