CREATE OR REPLACE FUNCTION AP21.FUN_GET_INOUT_ITEM(PARA1 VARCHAR2,PARA2 NUMBER) RETURN VARCHAR2 IS
--■■■■■■■■■■■■■■■■■■■
--■　受払ソース品目コード取得
--■　TABLE:INOUT_SOURCE
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STR_ITEM	VARCHAR2(255) := '';
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM INOUT_SOURCE
	WHERE
		ODER_NO          = PARA1
		AND ODER_LINE_NO = PARA2
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN NULL;
	ELSE
		--
		SELECT ITEM_CD INTO STR_ITEM FROM INOUT_SOURCE
		WHERE
			ODER_NO          = PARA1
			AND ODER_LINE_NO = PARA2
		;
		RETURN STR_ITEM;
	END IF;
END;
/
