CREATE OR REPLACE FUNCTION      FUN_GET_INOUT_LOCATION(PARA1 VARCHAR2,PARA2 NUMBER) RETURN VARCHAR IS
--■■■■■■■■■■■■■■■■■■■
--■　受払ソースロケーション取得
--■　TABLE:ITEM
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STRCODE	VARCHAR2(255) := '';
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM INOUT_SOURCE
	WHERE
		ODER_NO          = PARA1
		AND ODER_LINE_NO = PARA2
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN '';
	ELSE
		--
		SELECT LOCATION_CD INTO STRCODE FROM INOUT_SOURCE
		WHERE
			ODER_NO          = PARA1
			AND ODER_LINE_NO = PARA2
		;
		RETURN STRCODE;
	END IF;
END;
/
