CREATE OR REPLACE FUNCTION      FUN_GET_SERVERDATE(PARA NUMBER:=0) RETURN VARCHAR2 IS
--■■■■■■■■■■■■■■■■■■■
--■　サーバ日付取得
--■　TABLE:
--■　PARA = 0:'YYYY-MM-DD HH24:MI:SS'
--■　PARA = 1:'YYYY-MM-DD HH24:MI:SS:XXX'ミリ秒まで取得
--■　PARA = 2:'YYYY-MM-DD'
--■　PARA = 3:'YYYYMMDD'
--■　PARA = 4:'YYMM'
--■■■■■■■■■■■■■■■■■■■

	STR_DATE VARCHAR2(255):='';
	STR_YYYY VARCHAR2(255):='';
	LNGPOS NUMBER;
BEGIN

	--
	CASE PARA
	WHEN 0 THEN
		SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') INTO STR_DATE FROM DUAL;
	WHEN 1 THEN
		SELECT TO_CHAR(SYSDATE,'YYYY') INTO STR_YYYY FROM DUAL;
		SELECT TO_CHAR(SYSTIMESTAMP(3)) INTO STR_DATE FROM DUAL;
		LNGPOS := INSTR(STR_DATE,' ', 1, 2);
		STR_DATE := SUBSTR(STR_DATE, 1, LNGPOS);
		STR_DATE := SUBSTR(STR_DATE, 3, LENGTH(STR_DATE));
		STR_DATE := STR_YYYY || REPLACE(STR_DATE,'.',':');
	WHEN 2 THEN
		SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD') INTO STR_DATE FROM DUAL;
	WHEN 3 THEN
		SELECT TO_CHAR(SYSDATE,'YYYYMMDD') INTO STR_DATE FROM DUAL;
	WHEN 4 THEN
		SELECT TO_CHAR(SYSDATE,'YYMM') INTO STR_DATE FROM DUAL;
	ELSE
		NULL;
	END CASE;
	--
	RETURN TRIM(STR_DATE);
EXCEPTION
	WHEN OTHERS THEN
	RETURN ' ';
END;
/
