CREATE OR REPLACE FUNCTION      FUN_GET_ITEM_DEFAULT_LOCATION(PARA VARCHAR2) RETURN VARCHAR IS
--■■■■■■■■■■■■■■■■■■■
--■　基準保管場所
--■　TABLE:ITEM
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STRCODE	VARCHAR2(255) := '';
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM ITEM
	WHERE
		ITEM_CD = PARA
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN 9;
	ELSE
		--親品目コード取得
		SELECT DEFAULT_LOCATION INTO STRCODE FROM ITEM
		WHERE
			ITEM_CD = PARA
		;
		RETURN STRCODE;
	END IF;
END;
/
