CREATE OR REPLACE FUNCTION      FUN_GET_IDOUHEIKIN
--■■■■■■■■■■■■■■■■■■■
--■　移動平均計算
--■　TABLE:
--■■■■■■■■■■■■■■■■■■■
				(
				PSTR_ITEMCODE VARCHAR2
				,PLNG_MODE NUMBER
				,PLNG_UKESUU NUMBER
				,PLNG_UKETANK NUMBER
				,PLNG_OPNO NUMBER
				)
RETURN NUMBER IS
	LNGRC			NUMBER:=0;
	LNG_MST_ZAIKOSUU	NUMBER:=0;	--在庫数
	LNG_MST_ZAIKOHTANK	NUMBER:=0;	--在庫単価
	LNG_ZAIKOKIN		NUMBER:=0;	--在庫金額
	LNG_TOTALSUU		NUMBER:=0;	--合計数量
	LNG_TOTALKIN		NUMBER:=0;	--合計金額
BEGIN
	--カウント取得
	SELECT COUNT(*) INTO LNGRC FROM ITEM_INVENTORY
	WHERE
		ITEM_CD = PSTR_ITEMCODE
	;
	--
	IF LNGRC = 0 THEN
		RETURN 0;
	ELSE
		--現在在庫数・単価取得
		SELECT INVENTORY_QTY,INVENTORY_COST INTO LNG_MST_ZAIKOSUU,LNG_MST_ZAIKOHTANK FROM ITEM_INVENTORY
		WHERE
			ITEM_CD = PSTR_ITEMCODE
		;
		--10:在庫評価単価特殊更新（仕入単価決定入力時）
		IF PLNG_OPNO <> 10 THEN
			--在庫金額計算
			LNG_MST_ZAIKOSUU := LNG_MST_ZAIKOSUU;
			LNG_ZAIKOKIN := LNG_MST_ZAIKOSUU * LNG_MST_ZAIKOHTANK;
			--入出庫区分(0:正更新処理, 1:逆更新処理)
			IF PLNG_MODE = 0 THEN
				LNG_TOTALSUU := LNG_MST_ZAIKOSUU + PLNG_UKESUU;
				LNG_TOTALKIN := LNG_ZAIKOKIN + (PLNG_UKESUU * PLNG_UKETANK);
			ELSE
				LNG_TOTALSUU := LNG_MST_ZAIKOSUU - PLNG_UKESUU;
				LNG_TOTALKIN := LNG_ZAIKOKIN - (PLNG_UKESUU * PLNG_UKETANK);
			END IF;
		ELSE
			--合計数量 = 手持在庫数
			LNG_TOTALSUU := LNG_MST_ZAIKOSUU;
			--合計金額 = ((手持在庫数 - 数量) * 在庫評価単価) + (単価 * 数量)
			LNG_TOTALKIN := ((LNG_MST_ZAIKOSUU - PLNG_UKESUU) * LNG_MST_ZAIKOHTANK) + (PLNG_UKETANK * PLNG_UKESUU);
		END IF;
		--
		IF LNG_TOTALSUU = 0 OR LNG_TOTALKIN = 0 THEN
			IF PLNG_UKETANK = 0 THEN
				IF LNG_TOTALKIN = 0 THEN
					NULL;
				ELSE
					--計算結果の金額を採用
					RETURN LNG_TOTALKIN;
				END IF;
			ELSE
				--引数の単価を採用
				RETURN PLNG_UKETANK;
			END IF;
		ELSE
			--平均単価 = 合計金額 / 合計数量
			RETURN LNG_TOTALKIN / LNG_TOTALSUU;
		END IF;
	END IF;
END;
/
