CREATE OR REPLACE FUNCTION      FUN_GET_LOT_LAST_IN_DATE(PLOCATION_CD VARCHAR2,PITEM_CD VARCHAR2,PLOT_NO VARCHAR2) RETURN VARCHAR2 IS
--■■■■■■■■■■■■■■■■■■■
--■　ロット最終入庫日取得
--■　TABLE:LOT_INVENTORY
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER:=0;
	LNGC	NUMBER:=0;
	DTEWORK	DATE;
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM LOT_INVENTORY
	WHERE
		LOCATION_CD = TRIM(PLOCATION_CD)
		AND ITEM_CD = TRIM(PITEM_CD)
		AND LOT_NO = TRIM(PLOT_NO)
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		RETURN 9;
	ELSE
		SELECT LAST_IN_DATE INTO DTEWORK FROM LOT_INVENTORY
		WHERE
			LOCATION_CD = TRIM(PLOCATION_CD)
			AND ITEM_CD = TRIM(PITEM_CD)
			AND LOT_NO = TRIM(PLOT_NO)
		;
		RETURN DTEWORK;
	END IF;
END;
/
