CREATE OR REPLACE FUNCTION AP21.FUNC_GET_SECTION_FROM_ITEM(STR_CODE IN NVARCHAR2,NUM_KBN IN NUMBER,STR_LOT IN NVARCHAR2)
RETURN NVARCHAR2
IS
kbn NUMBER;
tkbn NUMBER;
ct  NUMBER;
rt nvarchar2(10);
sc nvarchar2(10);
VNO  number;
BEGIN
	sc := '';
	IF STR_CODE is NULL or STR_CODE = '' THEN 
		GOTO P_END;
	END IF;
 	SELECT COUNT(*) INTO ct FROM ITEM WHERE ITEM_CD = STR_CODE;
	IF ct IS NULL OR ct = 0 THEN
		RETURN SC;
	END IF;
	select VERSION INTO VNO FROM ITEM WHERE ITEM_CD = STR_CODE;
	if num_kbn is null or num_kbn < 0 then
		select TYPE_DIVISION INTO tkbn FROM ITEM WHERE ITEM_CD = STR_CODE;
	else
		tkbn := num_kbn;
	end if;
	CASE tkbn
		WHEN 0 THEN kbn := 0;
		WHEN 1 THEN kbn := 1;
		WHEN 2 THEN kbn := 1;
		WHEN 3 THEN kbn := 3;
		WHEN 4 THEN kbn := 1;
		WHEN 5 THEN kbn := 1;
		WHEN 6 THEN kbn := 0;
		WHEN 7 THEN kbn := 0;
		ELSE 
			kbn := 9;
	END CASE;
	IF kbn = 0 or kbn = 9 THEN
 		SELECT COUNT(*) INTO CT FROM ARTICLE_ATTRIBUTE_QUEUE
		WHERE ITEM_CD = STR_CODE AND VERSION = VNO;
		IF CT IS not NULL AND CT > 0 THEN
			--コード取得
			SELECT SECTION_CD INTO SC FROM ARTICLE_ATTRIBUTE_QUEUE
			WHERE	ITEM_CD = STR_CODE AND VERSION = VNO;
			RETURN SC;
		END IF;
		IF kbn = 0 THEN 
			RETURN SC;
		END IF;
	END IF;
	IF kbn = 1 or kbn = 9 THEN
 		SELECT COUNT(*) INTO CT FROM PURCHASE_ATTRIBUTE_QUEUE
		WHERE ITEM_CD = STR_CODE AND VERSION = VNO;
		IF CT IS not NULL AND CT > 0 THEN
			--コード取得
			SELECT SECTION_CD INTO SC FROM PURCHASE_ATTRIBUTE_QUEUE
			WHERE	ITEM_CD = STR_CODE AND VERSION = VNO;
			RETURN SC;
		END IF;
		IF kbn = 1 THEN 
			kbn := 3;
		END IF;
	END IF;
	IF (kbn = 3 or kbn = 9 )  THEN
		IF  STR_LOT is not NULL  THEN
 			SELECT COUNT(RECIPE_HEADER.SECTION_CD) INTO CT FROM DIRECTION_HEADER , RECIPE_HEADER
			WHERE DIRECTION_HEADER.ITEM_CD = STR_CODE AND DIRECTION_HEADER.DIRECTION_NO= STR_LOT
			AND DIRECTION_HEADER.RECIPE_ID = RECIPE_HEADER.RECIPE_ID;
			IF CT IS not NULL AND CT > 0 THEN
				--コード取得
 				SELECT RECIPE_HEADER.SECTION_CD INTO SC FROM DIRECTION_HEADER , RECIPE_HEADER
				WHERE DIRECTION_HEADER.ITEM_CD = STR_CODE AND DIRECTION_HEADER.DIRECTION_NO= STR_LOT
				AND DIRECTION_HEADER.RECIPE_ID = RECIPE_HEADER.RECIPE_ID;
				RETURN SC;
			END IF;
		END IF;
	END IF;

<<P_END>>
		return sc;
-- 異常処理
EXCEPTION

	WHEN OTHERS THEN
		return '';
END;
/
