CREATE OR REPLACE FUNCTION AP21.FUNC_SET_SUMI(sSUMI IN CHAR,sSEIHINCODE IN CHAR, sLOC_CD2 IN CHAR,sJIKOKU IN DATE, 
			sNYUUSYUKKO IN CHAR,sHOSOSASHIZUNO IN CHAR,sNYUKABC IN CHAR )
RETURN BOOLEAN IS
	INOUTDATE_BEFORE		DATE;				-- 一秒前
	INOUTDATE_AFTER			DATE;				-- 一秒後
	CT NUMBER;
	TEMP_ERR_CODE 			VARCHAR2(100);
	TEMP_ERR_MSG 			VARCHAR2(2048);
BEGIN
	INOUTDATE_BEFORE := sJIKOKU - 1 / 86400;	-- 一秒前
	INOUTDATE_AFTER	 := sJIKOKU + 1 / 86400;	-- 一秒後
	UPDATE 
		JISSEKI_SEIHIN_PRO SET SUMI = sSUMI 
		WHERE 
			SEIHINCODE = sSEIHINCODE
			AND LOCATION = sLOC_CD2 
			AND INOUTDATE_BEFORE <= JIKOKU 
			AND JIKOKU <= INOUTDATE_AFTER
			AND NYUUSYUKKO = sNYUUSYUKKO
			AND HOSOSASHIZUNO = sHOSOSASHIZUNO
			AND NYUKABC = sNYUKABC
			AND not SUMI = sSUMI;

	-- フラグがたったかどうか確認
	SELECT 
		COUNT(*) INTO CT 
		FROM 
			JISSEKI_SEIHIN_PRO 
		WHERE 
			SUMI = sSUMI
			AND SEIHINCODE = sSEIHINCODE
			AND LOCATION = sLOC_CD2 
			AND INOUTDATE_BEFORE <= JIKOKU 
			AND JIKOKU <= INOUTDATE_AFTER
			AND NYUUSYUKKO = sNYUUSYUKKO
			AND HOSOSASHIZUNO = sHOSOSASHIZUNO
			AND NYUKABC = sNYUKABC;
	IF CT = 1 THEN 
		COMMIT;
		RETURN TRUE;
	END IF;
	ROLLBACK;
	RETURN FALSE;

-- 異常処理
EXCEPTION
	WHEN OTHERS THEN
		-- SQLエラーコード、エラーメッセージを取得
	    	TEMP_ERR_CODE := SQLCODE;
		TEMP_ERR_MSG  := SUBSTR(SQLERRM,1,1024);
		ROLLBACK;
		OUTPUT_ERROR_LOG('FUNC_SET_SUMI','AUTO',TEMP_ERR_CODE,TEMP_ERR_MSG);
		DBMS_OUTPUT.PUT_LINE(SQLCODE || ':' || SQLERRM);
		COMMIT;
		RETURN FALSE;
END;
/
