CREATE OR REPLACE FUNCTION AP21.FUNC_GET_SECTION_FOR_SHIPPING(STR_CODE IN NVARCHAR2,STR_KBN IN NVARCHAR2) 
RETURN NVARCHAR2
IS
CT NUMBER;
sc nvarchar2(15);
BEGIN
	SC := '';
	IF STR_CODE is  null OR STR_CODE = '' THEN
		RETURN SC;
	END IF;
	IF STR_KBN is null OR STR_KBN = '' THEN
		RETURN SC;
	END IF;
	IF STR_KBN = 'TS' OR STR_KBN = 'SI' THEN
		null;
	ELSE
		RETURN SC;
	END IF;
	SELECT COUNT(*) INTO CT FROM VENDER a WHERE a.VENDER_CD = (SELECT b.PAYMENT_INVOICE_CD FROM VENDER b WHERE b.VENDER_CD = STR_CODE AND b.VENDER_DIVISION = STR_KBN) ;
	IF CT is null OR CT < 1 THEN
		RETURN SC;
	END IF;
	SELECT a.SECTION_CD INTO SC FROM VENDER a WHERE a.VENDER_CD = (SELECT b.PAYMENT_INVOICE_CD FROM VENDER b WHERE b.VENDER_CD = STR_CODE AND b.VENDER_DIVISION = STR_KBN) ;
	RETURN SC;

-- 異常処理
EXCEPTION

	WHEN OTHERS THEN
		return '';
	
END;
/
