CREATE OR REPLACE PROCEDURE AP21.PRO_GET_INOUT_DATA(PARA1 IN VARCHAR2,PARA2 IN NUMBER,STRHINCD OUT VARCHAR2,STRLOT OUT VARCHAR2,STRLOCATION OUT VARCHAR2,NUMQTY OUT NUMBER)  IS
--■■■■■■■■■■■■■■■■■■■
--■　受払ソース取得
--■　TABLE:INOUT_SOURCE
--■■■■■■■■■■■■■■■■■■■
	LNGRC	NUMBER := 0;
	STR_HIN	VARCHAR2(255) := '';
	STR_LOT	VARCHAR2(255) := '';
	STR_LOC	VARCHAR2(255) := '';
	N_QTY	NUMBER := 0;
BEGIN
 	SELECT COUNT(*) INTO LNGRC FROM INOUT_SOURCE
	WHERE
		ODER_NO          = PARA1
		AND ODER_LINE_NO = PARA2
	;
	IF LNGRC IS NULL OR LNGRC = 0 THEN
		STRHINCD := '';
		STRLOT := '';
		STRLOCATION := '';
		NUMQTY := 0;
	ELSE
		--
		SELECT ITEM_CD,LOT_NO,LOCATION_CD,INOUT_QTY*ASSIGN_FLAG INTO STR_HIN,STR_LOT,STR_LOC,N_QTY FROM INOUT_SOURCE
		WHERE
			ODER_NO          = PARA1
			AND ODER_LINE_NO = PARA2
		;
		STRHINCD := STR_HIN;
		STRLOT := STR_LOT;
		STRLOCATION := STR_LOC;
		NUMQTY := N_QTY;
	END IF;
END;
/
