/*
 * 自社マスタ用SQL
 *
 * entityName=CompanyDetail
 * packageName=companydetail
 * methodName=getEntity
 *
 */
SELECT HOME_NAME1
, ZIPCODE_NO
, ADDRESS1
, ADDRESS2
, ADDRESS3
, TEL_NO
, FAX_NO
, REPRESENT_ROLE
, REPRESENT_PERSON
, INVOICE_NO
, SETTLEMENT
, CLOSING_DAY
, TAX_DIVISION
, CALC_DIVISION
, TAX_ROUNDUP
, TAX_ROUNDUP_UNIT
, TAX_RATIO
, STOCK_DISCOUNT_RATE
, PURCHASE_DISCOUNT_RATE
, ROUNDUP
, ROUNDUP_UNIT
, SALES_ROUNDUP
, SALES_ROUNDUP_UNIT
, PURCHASE_ROUNDUP
, PURCHASE_ROUNDUP_UNIT
, UNITPRICE_ROUNDUP
, UNITPRICE_ROUNDUP_UNIT
, BLEND_QTY_ROUNDUP
, BLEND_QTY_ROUNDUP_UNIT
, MIX_RATE_ROUNDUP
, MIX_RATE_ROUNDUP_UNIT
, ADJ_ROUNDUP
, ADJ_ROUNDUP_UNIT
, PAYMENT_UPDATE
, COMPANY_CD
, BANK_MASTER_CD1
, BANK1.BANK_MASTER_NAME BANK_MASTER_NAME1
, ACCOUNT_ABBREVIATION1
, ACCOUNT_DIVISION1
, ACCOUNT_NO1
, ACCOUNT_STOCKHOLD1
, BANK_MASTER_CD2
, BANK2.BANK_MASTER_NAME BANK_MASTER_NAME2
, ACCOUNT_ABBREVIATION2
, ACCOUNT_DIVISION2
, ACCOUNT_NO2
, ACCOUNT_STOCKHOLD2
, BANK_MASTER_CD3
, BANK3.BANK_MASTER_NAME BANK_MASTER_NAME3
, ACCOUNT_ABBREVIATION3
, ACCOUNT_DIVISION3
, ACCOUNT_NO3
, ACCOUNT_STOCKHOLD3
, BANK_MASTER_CD4
, BANK4.BANK_MASTER_NAME BANK_MASTER_NAME4
, ACCOUNT_ABBREVIATION4
, ACCOUNT_DIVISION4
, ACCOUNT_NO4
, ACCOUNT_STOCKHOLD4
, COMPANY.BANK_MASTER_CD
, BANK.BANK_MASTER_NAME
, ACCOUNT_DIVISION
, ACCOUNT_NO
, TRANSFER_CLIENT_CD
, TRANSFER_CLIENT_NAME
, PASSWORD_VALID_TERM
, PASSWORD_KETA_LOWER_LIMIT
, PASSWORD_KETA_UPPER_LIMIT
, PRIME
, COMPANY.UPDATE_DATE
, NEW_TAX_RATIO
, NEW_TAX_APLLY_DATE
FROM COMPANY, BANK BANK1, BANK BANK2, BANK BANK3, BANK BANK4, BANK
WHERE COMPANY_CD IS NOT NULL

/*IF((companyCd != null) && (companyCd != ""))*/
AND COMPANY_CD = /*companyCd*/'%'
/*END*/

AND COMPANY.BANK_MASTER_CD1 = BANK1.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD2 = BANK2.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD3 = BANK3.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD4 = BANK4.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD = BANK.BANK_MASTER_CD(+)


