/*
 * 販売条件一覧用SQL
 *
 * entityName=SalesTermsList
 * packageName=salestermslist
 * methodName=getList
 *
 */

SELECT SALES_TERMS.DELIVERY_CD, DELIVERY.SEARCH_KANA as DELIVERY_NAME1, SALES_TERMS.BALANCE_CD, SALES_TERMS.ITEM_CD, ITEM_QUEUE.ITEM_NAME, SUBSTRB(ITEM_QUEUE.ITEM_NAME, 0, 36) SHORT_ITEM_NAME, ITEM_QUEUE.STYLE_OF_PACKING, BALANCE.VENDER_CD, VENDER.VENDER_SHORTED_NAME as VENDER_NAME1,NVL(DELIVERY.LEAD_TIME,0) AS LEAD_TIME
,DELIVERY.ADDRESS1 || DELIVERY.ADDRESS2 || DELIVERY.ADDRESS3 AS DELIVERY_ADDRESS
,DELIVERY.TEL_NO AS DELIVERY_TEL_NO
FROM SALES_TERMS, BALANCE, VENDER, VALID_ITEM_QUEUE ITEM_QUEUE, DELIVERY,

(SELECT DELIVERY_CD, BALANCE_CD
FROM SALES_TERMS
WHERE SEQ = 1
GROUP BY DELIVERY_CD, BALANCE_CD) GROUP_SALES_TERMS

WHERE SALES_TERMS.DELIVERY_CD IS NOT NULL

/*IF (condition.srhVenderCd != null) && (condition.srhVenderCd != "")*/
AND (BALANCE.VENDER_CD LIKE /*condition.srhVenderCd*/'%' OR VENDER.VENDER_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhVenderCd*/'%'))
/*END*/

/*IF (condition.srhDeliveryCd != null) && (condition.srhDeliveryCd != "")*/
AND (SALES_TERMS.DELIVERY_CD LIKE /*condition.srhDeliveryCd*/'%' OR DELIVERY_NAME1 LIKE FUN_RET_MASTER_STRING_USE_AC(/*condition.srhDeliveryCd*/'%'))
/*END*/

/*IF (condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (SALES_TERMS.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF (condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND ITEM_QUEUE.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

AND SALES_TERMS.BALANCE_CD = BALANCE.BALANCE_CD(+)
AND VENDER.VENDER_DIVISION(+) = 'TS'
AND BALANCE.VENDER_CD = VENDER.VENDER_CD(+)
AND SALES_TERMS.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND SALES_TERMS.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
AND SALES_TERMS.DELIVERY_CD = GROUP_SALES_TERMS.DELIVERY_CD(+)
AND SALES_TERMS.BALANCE_CD = GROUP_SALES_TERMS.BALANCE_CD(+)

ORDER BY SALES_TERMS.DELIVERY_CD, SALES_TERMS.ITEM_CD, BALANCE.VENDER_CD
