/*
 * 販売条件の保存テーブルのデータを取得
 *
 * entityName=SalesTermsSavedListForReport
 * packageName=SalesTermsSavedListForReport
 * methodName=getListForReport
 *
 */

SELECT
	SALES_TERMS_SAVED.PK_NO
,	SALES_TERMS_SAVED.PROC_TYPE
,	SALES_TERMS_SAVED.DELIVERY_CD
,	CONCAT(DELIVERY.DELIVERY_NAME1,DELIVERY.DELIVERY_NAME2) AS DELIVERY_NAME
,	SALES_TERMS_SAVED.BALANCE_CD
,	SALES_TERMS_SAVED.ITEM_CD
,	ITEM.ITEM_NAME
,	SALES_TERMS_SAVED.SEQ
,	SALES_TERMS_SAVED.TANTO_CD
,	TANTO.TANTO_NM AS TANTO_NAME
,	SALES_TERMS_SAVED.INPUT_DATE
,	SALES_TERMS_SAVED.INPUTOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
,	SALES_TERMS_SAVED.UPDATE_DATE
,	SALES_TERMS_SAVED.UPDATOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME

FROM
	SALES_TERMS_SAVED
LEFT JOIN DELIVERY ON DELIVERY.DELIVERY_CD = SALES_TERMS_SAVED.DELIVERY_CD
LEFT JOIN ITEM ON ITEM.ITEM_CD = SALES_TERMS_SAVED.ITEM_CD
LEFT JOIN LOGIN TANTO ON TANTO.TANTO_CD = SALES_TERMS_SAVED.TANTO_CD
LEFT JOIN LOGIN UPDATOR ON UPDATOR.TANTO_CD = SALES_TERMS_SAVED.UPDATOR_CD
LEFT JOIN LOGIN INPUTOR ON INPUTOR.TANTO_CD = SALES_TERMS_SAVED.INPUTOR_CD

WHERE
	SALES_TERMS_SAVED.PK_NO = /*pkNo*/''