/*
 * 自社銀行一覧コンボボックス用SQL
 *
 * entityName=CompanyBankListForComboboxes
 * packageName=companybank
 * methodName=getListForComboboxes
 *
 */

SELECT BANK.BANK_MASTER_CD, BANK_MASTER_NAME, ACCOUNT_DIVISION1 ACCOUNT_DIVISION, ACCOUNT_NO1 ACCOUNT_NO
FROM COMPANY, BANK
WHERE COMPANY.BANK_MASTER_CD1 = BANK.BANK_MASTER_CD(+)

UNION

SELECT BANK.BANK_MASTER_CD, BANK_MASTER_NAME, ACCOUNT_DIVISION2 ACCOUNT_DIVISION, ACCOUNT_NO2 ACCOUNT_NO
FROM COMPANY, BANK
WHERE COMPANY.BANK_MASTER_CD2 = BANK.BANK_MASTER_CD(+)

UNION

SELECT BANK.BANK_MASTER_CD, BANK_MASTER_NAME, ACCOUNT_DIVISION3 ACCOUNT_DIVISION, ACCOUNT_NO3 ACCOUNT_NO
FROM COMPANY, BANK
WHERE COMPANY.BANK_MASTER_CD3 = BANK.BANK_MASTER_CD(+)

UNION

SELECT BANK.BANK_MASTER_CD, BANK_MASTER_NAME, ACCOUNT_DIVISION4 ACCOUNT_DIVISION, ACCOUNT_NO4 ACCOUNT_NO
FROM COMPANY, BANK
WHERE COMPANY.BANK_MASTER_CD4 = BANK.BANK_MASTER_CD(+)

ORDER BY BANK_MASTER_CD


