/*
 * Created on 2009/02/02
 *
 * $copyright$
 *
*/

/**
 * 仕入承認画面用SQL
 *
 * @author tosco
 *
 * entityName=BuyingApprovalList
 * packageName=buyingapproval
 * methodName=getSearchList
 *
 */
SELECT
	PURCHASE_SUBCONTRACT.SLIP_NO					AS SLIP_NO
,	PURCHASE_SUBCONTRACT.PURCHASE_NO				AS PURCHASE_NO
,	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO	AS BUY_SUBCONTRACT_ORDER_NO
,	PURCHASE_SUBCONTRACT.ORDER_NO					AS ORDER_NO
,	PURCHASE_SUBCONTRACT.VENDER_CD					AS VENDER_CD
,	PURCHASE_SUBCONTRACT.ORDER_QUANTITY				AS ORDER_QUANTITY
,	PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY		AS ORDER_CONVERT_QUANTITY
,	PURCHASE_SUBCONTRACT.SUPPLIER_ORD_AMOUNT		AS SUPPLIER_ORD_AMOUNT
,	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO				AS ORDER_SHEET_NO
,	PURCHASE_SUBCONTRACT.STOCKING_DATE				AS STOCKING_DATE
,	PURCHASE_SUBCONTRACT.ROW_NO						AS ROW_NO
,	PURCHASE_SUBCONTRACT.STOCKING_QUANTITY			AS STOCKING_QUANTITY
,	PURCHASE_SUBCONTRACT.HOUSING_UNITPRICE			AS HOUSING_UNITPRICE
,	PURCHASE_SUBCONTRACT.STOCKING_AMOUNT			AS STOCKING_AMOUNT
,	PURCHASE_SUBCONTRACT.ACCEPT_DATE				AS ACCEPT_DATE
,	PURCHASE_SUBCONTRACT.STATUS2					AS STATUS2
,	PURCHASE_SUBCONTRACT.APPROVAL_STATUS			AS APPROVAL_STATUS
,	PURCHASE_SUBCONTRACT.APPROVEDBY					AS APPROVEDBY
,	PURCHASE_SUBCONTRACT.APPROVALDATE				AS APPROVALDATE
,	PURCHASE_SUBCONTRACT.INPUT_DATE					AS INPUT_DATE
,	PURCHASE_SUBCONTRACT.INPUTOR_CD					AS INPUTOR_CD
,	PURCHASE_SUBCONTRACT.UPDATE_DATE				AS UPDATE_DATE
,	PURCHASE_SUBCONTRACT.UPDATOR_CD					AS UPDATOR_CD
,	DECODE(ITEM_NAMES.SPOT_DIVISION, 2, PURCHASE_SUBCONTRACT.ITEM_NAME, ITEM_NAMES.ITEM_NAME)	AS ITEM_QUEUE_NAME
,	ITEM_NAMES.STYLE_OF_PACKING						AS STYLE_OF_PACKING
,	ITEM_NAMES.UNIT_OF_OPERATION_MANAGEMENT			AS UNIT_OF_OPERATION_MANAGEMENT
,	PURCHASE_SUBCONTRACT.VENDER_NAME1				AS VENDER_NAME1
,	PURCHASE_SUBCONTRACT.PAYMENT_INVOICE_CD			AS PAYMENT_INVOICE_CD
,	PURCHASE_SUBCONTRACT.VENDER_PAYMENT_NAME		AS VENDER_PAYMENT_NAME
,	PURCHASE_SUBCONTRACT.CATEGORY_NAME				AS CATEGORY_NAME
,   PURCHASE_SUBCONTRACT.ITEM_CD                    AS ITEM_CD
FROM (
	SELECT
		PURCHASE_SUBCONTRACT.SLIP_NO						AS SLIP_NO
	,	MIN(PURCHASE_SUBCONTRACT.PURCHASE_NO)				AS PURCHASE_NO
	,	MIN(PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO)	AS BUY_SUBCONTRACT_ORDER_NO
	,	MIN(PURCHASE_SUBCONTRACT.ORDER_NO)					AS ORDER_NO
	,	MIN(PURCHASE_SUBCONTRACT.VENDER_CD)					AS VENDER_CD
	,	MIN(PURCHASE_SUBCONTRACT.ITEM_CD)					AS ITEM_CD
	,	MIN(PURCHASE_SUBCONTRACT.ITEM_NAME)					AS ITEM_NAME
	,	MIN(PURCHASE_SUBCONTRACT.ORDER_QUANTITY)			AS ORDER_QUANTITY
	,	MIN(PURCHASE_SUBCONTRACT.ORDER_CONVERT_QUANTITY)	AS ORDER_CONVERT_QUANTITY
	,	MIN(PURCHASE_SUBCONTRACT.SUPPLIER_ORD_AMOUNT)		AS SUPPLIER_ORD_AMOUNT
	,	MIN(PURCHASE_SUBCONTRACT.ORDER_SHEET_NO)			AS ORDER_SHEET_NO
	,	MIN(PURCHASE_SUBCONTRACT.STOCKING_DATE)				AS STOCKING_DATE
	,	MIN(PURCHASE_SUBCONTRACT.ROW_NO)					AS ROW_NO
	,	SUM(PURCHASE_SUBCONTRACT.STOCKING_QUANTITY)			AS STOCKING_QUANTITY
	,	SUM(PURCHASE_SUBCONTRACT.HOUSING_UNITPRICE)			AS HOUSING_UNITPRICE
	,	SUM(PURCHASE_SUBCONTRACT.STOCKING_AMOUNT)			AS STOCKING_AMOUNT
	,	MIN(PURCHASE_SUBCONTRACT.ACCEPT_DATE)				AS ACCEPT_DATE
	,	MIN(PURCHASE_SUBCONTRACT.STATUS2)					AS STATUS2
	,	MIN(PURCHASE_SUBCONTRACT.APPROVAL_STATUS)			AS APPROVAL_STATUS
	,	MIN(PURCHASE_SUBCONTRACT.APPROVEDBY)				AS APPROVEDBY
	,	MIN(PURCHASE_SUBCONTRACT.APPROVALDATE)				AS APPROVALDATE
	,	MIN(PURCHASE_SUBCONTRACT.INPUT_DATE)				AS INPUT_DATE
	,	MIN(PURCHASE_SUBCONTRACT.INPUTOR_CD)				AS INPUTOR_CD
	,	MIN(PURCHASE_SUBCONTRACT.UPDATE_DATE)				AS UPDATE_DATE
	,	MIN(PURCHASE_SUBCONTRACT.UPDATOR_CD)				AS UPDATOR_CD
	,	MIN(VENDER_NAMES.VENDER_SHORTED_NAME)				AS VENDER_NAME1
	,	MIN(VENDER_PAYMENT.PAYMENT_INVOICE_CD)				AS PAYMENT_INVOICE_CD
	,	MIN(VENDER_PAYMENT.VENDER_PAYMENT_NAME)				AS VENDER_PAYMENT_NAME
	,	MIN(CLASSIFICATION.CATEGORY_NAME)					AS CATEGORY_NAME
	FROM	PURCHASE_SUBCONTRACT
	,	VENDER VENDER_NAMES
	,	(SELECT	VENDER_PAYMENT.VENDER_CD
		,	VENDER_PAYMENT.PAYMENT_INVOICE_CD
		,	VENDER.VENDER_SHORTED_NAME AS VENDER_PAYMENT_NAME
		
		FROM
			(SELECT
				VENDER.VENDER_DIVISION
			,	VENDER.VENDER_CD
			,	VENDER.VENDER_SHORTED_NAME
			,	NVL(VENDER.PAYMENT_INVOICE_CD,VENDER.VENDER_CD) PAYMENT_INVOICE_CD
			FROM
				VENDER
			WHERE
				VENDER_DIVISION = 'SI'
			)VENDER_PAYMENT
		,	VENDER
		WHERE
			VENDER_PAYMENT.PAYMENT_INVOICE_CD = VENDER.VENDER_CD(+)
		AND	VENDER.VENDER_DIVISION = 'SI'
		)VENDER_PAYMENT
	,	(SELECT
				CATEGORY_DIVISION,CATEGORY_NAME
				FROM CLASSIFICATION
				WHERE DATA_TYPE = 3
		)CLASSIFICATION
	
	WHERE	PURCHASE_SUBCONTRACT.PURCHASE_NO IS NOT NULL
	AND	PURCHASE_SUBCONTRACT.STATUS = '6'
	AND PURCHASE_SUBCONTRACT.STATUS2 = '2'
	AND	PURCHASE_SUBCONTRACT.VENDER_CD = VENDER_NAMES.VENDER_CD(+)
	AND	VENDER_NAMES.VENDER_DIVISION(+) = 'SI'
	AND	PURCHASE_SUBCONTRACT.VENDER_CD = VENDER_PAYMENT.VENDER_CD(+)
	AND PURCHASE_SUBCONTRACT.CATEGORY_DIVISION = CLASSIFICATION.CATEGORY_DIVISION(+)
	
	/*IF (( condition.srhBuySubcontractOrderNo != null ) && ( condition.srhBuySubcontractOrderNo != "" ))*/
		AND	PURCHASE_SUBCONTRACT.BUY_SUBCONTRACT_ORDER_NO LIKE /*condition.srhBuySubcontractOrderNo*/'%'
	/*END*/
	/*IF (( condition.srhSlipNo != null ) && ( condition.srhSlipNo != "" ))*/
		AND	PURCHASE_SUBCONTRACT.SLIP_NO LIKE /*condition.srhSlipNo*/'%'
	/*END*/
	/*IF (( condition.srhAcceptDateFrom != null ) && ( condition.srhAcceptDateFrom != "" ))*/
		AND	PURCHASE_SUBCONTRACT.ACCEPT_DATE >= /*condition.srhAcceptDateFrom*/'2000/01/01'
	/*END*/
	/*IF (( condition.srhAcceptDateTo != null ) && ( condition.srhAcceptDateTo != "" ))*/
		AND	PURCHASE_SUBCONTRACT.ACCEPT_DATE <= /*condition.srhAcceptDateTo*/'2010/01/01'
	/*END*/
	/*IF (( condition.srhStockingDateFrom != null ) && ( condition.srhStockingDateFrom != "" ))*/
		AND	PURCHASE_SUBCONTRACT.STOCKING_DATE >= /*condition.srhStockingDateFrom*/'2000/01/01'
	/*END*/
	/*IF (( condition.srhStockingDateTo != null ) && ( condition.srhStockingDateTo != "" ))*/
		AND	PURCHASE_SUBCONTRACT.STOCKING_DATE <= /*condition.srhStockingDateTo*/'2010/01/01'
	/*END*/
	/*IF (( condition.srhVenderCd != null ) && ( condition.srhVenderCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.VENDER_CD LIKE /*condition.srhVenderCd*/'%'
	/*END*/
	/*IF (( condition.srhChargeOrganizationCd != null ) && ( condition.srhChargeOrganizationCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.CHARGE_ORGANIZATION_CD LIKE /*condition.srhChargeOrganizationCd*/'%'
	/*END*/
	/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.ITEM_CD LIKE /*condition.srhItemCd*/'%'
	/*END*/
	/*IF (( condition.srhOrderDivision != null ) && ( condition.srhOrderDivision != "0" ))*/
		AND	PURCHASE_SUBCONTRACT.ORDER_DIVISION = /*condition.srhOrderDivision*/'1'
	/*END*/
	/*IF (( condition.srhOrderSheetNo != null ) && ( condition.srhOrderSheetNo != "" ))*/
		AND	PURCHASE_SUBCONTRACT.ORDER_SHEET_NO LIKE /*condition.srhOrderSheetNo*/'%'
	/*END*/
	/*IF (( condition.srhOrganizationCd != null ) && ( condition.srhOrganizationCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/'%'
	/*END*/
	/*IF (( condition.srhTantoCd != null ) && ( condition.srhTantoCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.TANTO_CD LIKE /*condition.srhTantoCd*/'%'
	/*END*/
	
	/*IF ( condition.srhCategoryDivision != null )*/
		/* 仕入区分をすべてを選択した場合 */
		/*IF ( condition.srhCategoryDivision == "0") */
			/* 取消チェックボックスにチェックが入っていない場合 */
			/*IF ( condition.srhCancelCheck == true) */
				/* 先頭1文字目が'-'のものを検索 */
				AND SUBSTR(PURCHASE_SUBCONTRACT.CATEGORY_DIVISION,1,1) = '-'
			/*END*/
		/*END*/
		/* 仕入区分をすべて以外を選択した場合 */
		/*IF ( condition.srhCategoryDivision != "0") */
			/* 取消チェックボックスにチェックが入っていない場合 */
			/*IF ( condition.srhCancelCheck == false) */
				AND	(PURCHASE_SUBCONTRACT.CATEGORY_DIVISION = /*condition.srhCategoryDivision*/'1'
				OR	PURCHASE_SUBCONTRACT.CATEGORY_DIVISION = /*condition.srhCancelCategoryDivision*/'1')
			/*END*/
			/* 取消チェックボックスにチェックが入っていいる場合 */
			/*IF ( condition.srhCancelCheck == true) */
				AND	PURCHASE_SUBCONTRACT.CATEGORY_DIVISION = /*condition.srhCancelCategoryDivision*/'1'
			/*END*/
		/*END*/
	/*END*/
	
	/*IF (( condition.srhLocationCd != null ) && ( condition.srhLocationCd != "" ))*/
		AND	PURCHASE_SUBCONTRACT.LOCATION_CD LIKE /*condition.srhLocationCd*/'%'
	/*END*/
	
	GROUP BY
		SLIP_NO
	) PURCHASE_SUBCONTRACT
,	(SELECT
	    ITEM2.ITEM_CD ,
	    ITEM2.ITEM_NAME,
	    ITEM2.OTHER_COMPANY_CD1,
	    ITEM2.STYLE_OF_PACKING,
	    ITEM2.SPOT_DIVISION,
	    ITEM2.UNIT_OF_OPERATION_MANAGEMENT
	FROM
		VALID_ITEM_QUEUE ITEM2
	) ITEM_NAMES

WHERE	PURCHASE_SUBCONTRACT.ITEM_CD = ITEM_NAMES.ITEM_CD(+)
/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/
ORDER BY
	STOCKING_DATE	ASC
,	ACCEPT_DATE	ASC
,	ORDER_SHEET_NO	ASC
,	VENDER_CD	ASC

	