/*
 * 表示権限検索要SQL
 *
 * entityName=ViewAuthorityList
 * packageName=viewauthoritylist
 * methodName=getList
 */

SELECT	ROLE.ROLE_ID
,	VIEW_AUTHORITY.MENU_ID
,	VIEW_AUTHORITY.TAB_ID

FROM	VIEW_AUTHORITY
,
(
	SELECT	TANTO_ROLE.ROLE_ID
	FROM TANTO_ROLE
	WHERE TANTO_ROLE.TANTO_CD = /*tantoCd*/'%'

	UNION

	SELECT	BELONG_ROLE.ROLE_ID
	FROM	BELONG , BELONG_ROLE
	WHERE	BELONG.TANTO_CD = /*tantoCd*/'%'
	AND	BELONG.ORGANIZATION_CD = BELONG_ROLE.ORGANIZATION_CD
	AND	BELONG.POST_ID = BELONG_ROLE.POST_ID
)	ROLE

WHERE	VIEW_AUTHORITY.ROLE_ID = ROLE.ROLE_ID
AND VIEW_AUTHORITY.MENU_ID = /*menuId*/1

/*IF (tabId != null) && (tabId != "")*/
AND VIEW_AUTHORITY.TAB_ID = /*tabId*/1
/*END*/
