-- 製造指図フォーミュラ一時取込
DROP TABLE DIRECTION_FORMULA_TEMP CASCADE CONSTRAINTS
/

CREATE TABLE DIRECTION_FORMULA_TEMP (
  TEMP_NO NVARCHAR2(20) NOT NULL
  , ROW_NUMBER NUMBER NOT NULL
  , DIRECTION_DIVISION NUMBER NOT NULL
  , DIRECTION_NO NVARCHAR2(20) NOT NULL
  , STEP_NO NUMBER NOT NULL
  , LINE_NO NUMBER NOT NULL
  , SEQ NUMBER
  , LINE_TYPE NUMBER NOT NULL
  , ITEM_CD NVARCHAR2(20)
  , TONYU NUMBER
  , DATAREAD NUMBER
  , TONYUSOKUDO NUMBER
  , QTY NUMBER
  , STOCKPD_QTY NUMBER
  , RESULT_QTY NUMBER
  , SAMPLE_QTY NUMBER
  , LOSS_QTY NUMBER
  , DEFECT_QTY NUMBER
  , ADJUST_QTY NUMBER
  , COST NUMBER DEFAULT 0
  , STEP_CONDITION NVARCHAR2(100)
  , NOTES NVARCHAR2(256)
  , LOCATION_CD NVARCHAR2(20)
  , NEXT_LOCATION_CD NVARCHAR2(20)
  , NEXT_AFTER_LOCATION_CD NVARCHAR2(20)
  , LOT_NO NVARCHAR2(20)
  , MANUFACTURER_LOT_NO NVARCHAR2(20)
  , FILL_QTY NUMBER
  , FILL_RESULT_QTY NUMBER
  , REMARK NVARCHAR2(200)
  , UPDATE_DATE DATE
  , UPDATOR_CD NVARCHAR2(10)
  , CONSTRAINT DIRECTION_FORMULA_TEMP_PKC PRIMARY KEY (TEMP_NO, ROW_NUMBER) USING INDEX
)
/
COMMENT ON TABLE DIRECTION_FORMULA_TEMP IS '製造指図フォーミュラ一時取込'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.TEMP_NO IS '一時取込番号'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.ROW_NUMBER IS '行番号'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.DIRECTION_DIVISION IS '指図区分|1:バッチ指図,2:充填・包装指図,3:詰替・貼替指図'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.DIRECTION_NO IS '指図番号'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.STEP_NO IS 'ステップNO.'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.LINE_NO IS '行NO.'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.SEQ IS '投入順'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.LINE_TYPE IS '品目タイプ|-1:原材料,1:製品,2:中間品,3:回収品,4:副生品,5:廃棄物'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.ITEM_CD IS '品目コード'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.TONYU IS '投入方法|0:自動,1:手動'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.DATAREAD IS 'データ読み取り|0:自動,1:手動'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.TONYUSOKUDO IS '投入速度'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.QTY IS '数量'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.STOCKPD_QTY IS '在庫引落量'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.RESULT_QTY IS '実績数量'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.SAMPLE_QTY IS 'サンプル'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.LOSS_QTY IS 'ロス数量'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.DEFECT_QTY IS '不良'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.ADJUST_QTY IS '調整数量'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.COST IS '原価'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.STEP_CONDITION IS '条件'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.NOTES IS '注釈'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.LOCATION_CD IS 'ロケーションコード（第1タンクNo　兼　実績タンクNo）'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.NEXT_LOCATION_CD IS '第2タンクNo'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.NEXT_AFTER_LOCATION_CD IS '第3タンクNo'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.LOT_NO IS '入荷ロット番号'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.MANUFACTURER_LOT_NO IS 'メーカーロット番号'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.FILL_QTY IS '充填予定数'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.FILL_RESULT_QTY IS '充填実績数'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.REMARK IS '備考'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.UPDATE_DATE IS '更新日時'
/
COMMENT ON COLUMN DIRECTION_FORMULA_TEMP.UPDATOR_CD IS '更新者ID'
/
