-- 製造指図ヘッダー一時取込
DROP TABLE DIRECTION_HEADER_TEMP CASCADE CONSTRAINTS
/

CREATE TABLE DIRECTION_HEADER_TEMP (
  TEMP_NO NVARCHAR2(20) NOT NULL
  , ROW_NUMBER NUMBER NOT NULL
  , DIRECTION_DIVISION NUMBER NOT NULL
  , DIRECTION_NO NVARCHAR2(20) NOT NULL
  , LOT_NO NVARCHAR2(20)
  , RESULT_SDATE DATE
  , RESULT_EDATE DATE
  , STERIT_SDATE DATE
  , STERIT_EDATE DATE
  , REMARK NVARCHAR2(256)
  , NOTES NVARCHAR2(256)
  , SEIZOTANTOCODE NVARCHAR2(3)
  , SENJOTANTOCODE NVARCHAR2(3)
  , MEKKINTANTOCODE NVARCHAR2(3)
  , UPDATE_DATE DATE
  , UPDATOR_CD NVARCHAR2(10)
  , CONSTRAINT DIRECTION_HEADER_TEMP_PKC PRIMARY KEY (TEMP_NO, ROW_NUMBER)
)
/
COMMENT ON TABLE DIRECTION_HEADER_TEMP IS '製造指図ヘッダー一時取込'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.TEMP_NO IS '一時取込番号'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.ROW_NUMBER IS '行番号'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.DIRECTION_DIVISION IS '指図区分|1:バッチ指図,2:充填・包装指図,3:詰替・貼替指図'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.DIRECTION_NO IS '指図番号'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.LOT_NO IS 'ロット番号'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.RESULT_SDATE IS '開始実績日時'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.RESULT_EDATE IS '終了実績日時'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.STERIT_SDATE IS '滅菌作業開始日時'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.STERIT_EDATE IS '滅菌作業終了日時'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.REMARK IS '摘要'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.NOTES IS '注釈'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.SEIZOTANTOCODE IS '製造担当者'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.SENJOTANTOCODE IS '調合タンク洗浄担当者'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.MEKKINTANTOCODE IS '調合タンク滅菌作業担当者'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.UPDATE_DATE IS '更新日時'
/
COMMENT ON COLUMN DIRECTION_HEADER_TEMP.UPDATOR_CD IS '更新者ID'
/
