/*
 *  受注画面からチェックをした、受注取込のリストから、受注ファイルデータ一時取込テーブルの1行単位のデータの主キー情報を取得する。
 *
 * entityName=OrderImportTempList
 * packageName=orderImportTempList
 * methodName=getAecDataList
 *
 */
WITH ORDER_IMPORT_FILE_OUT_WK AS 
(
    SELECT 
    	FRST_ORDER_DETAIL.FRST_ORDER_NO AS PK_NO
    ,	FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO AS PK_ROW
    ,	TO_CHAR(FRST_ORDER_HEAD.DELIVERY_EXPECTED_DATE,'YYYY/MM/DD') AS DELIVERY_EXPECTED_DATE 
    ,	VENDER.VENDER_CD 
    ,	VENDER.VENDER_SHORTED_NAME
    ,	FRST_ORDER_DETAIL.ORDER_QTY
    ,	NVL(FRST_ORDER_HEAD.CARRY_FARE,0) AS CARRY_FARE
    ,	FRST_ORDER_DETAIL.FRST_ORDER_NO AS CARRY_GROUP
    ,	(CASE WHEN FRST_ORDER_DETAIL.ERROR_FLG = 0 THEN 'OK' ELSE 'NG' END ) AS ERROR_STATUS
    ,	(CASE WHEN FRST_ORDER_DETAIL.ORDER_NO IS NOT NULL THEN '受注登録' ELSE '先付受注' END) AS IMPORT_STATUS
    ,	(CASE WHEN ORDER_IMP_BASE.CTM_DELIVERLIMIT <> FRST_ORDER_HEAD.DELIVERY_EXPECTED_DATE THEN 'デフォルト納期の納入予定日が異なります' ELSE '' END) AS CHECK01 
    ,	(CASE WHEN ORDER_IMP_BASE.CTM_ORDER_QTY <> FRST_ORDER_DETAIL.ORDER_QTY THEN '発注数量と受注数量が異なります。' ELSE '' END) AS CHECK02 
    ,	(CASE WHEN FRST_ORDER_DETAIL.ITEM_CD IS NULL THEN '品目の紐づけがされていません' ELSE '' END) AS CHECK03 
    ,	(CASE WHEN FRST_ORDER_HEAD.DELIVERY_CD IS NULL THEN '納入先の紐づけがされていません' ELSE '' END) AS CHECK04 
    ,	NULL AS CHECK05 -- 下部SQLで取得
    ,	NULL AS CHECK06
    ,	NULL AS CHECK07
    ,	NULL AS CHECK08
    ,	NULL AS CHECK09
    ,	NULL AS CHECK10
    ,	'' AS CHECK_ALL
    ,   FRST_ORDER_DETAIL.ORDER_NO
    FROM
    	ORDER_IMPORT_FILE_OUT
    LEFT JOIN FRST_ORDER_DETAIL ON FRST_ORDER_DETAIL.FRST_ORDER_NO = ORDER_IMPORT_FILE_OUT.PK_NO AND FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO = ORDER_IMPORT_FILE_OUT.PK_ROW
    LEFT JOIN FRST_ORDER_HEAD ON FRST_ORDER_HEAD.FRST_ORDER_NO = FRST_ORDER_DETAIL.FRST_ORDER_NO 
    LEFT JOIN VENDER ON VENDER.VENDER_DIVISION='TS' AND VENDER.VENDER_CD = FRST_ORDER_HEAD.VENDER_CD
    LEFT JOIN ORDER_IMP_BASE ON FRST_ORDER_DETAIL.ORDER_IMP_NO = ORDER_IMP_BASE.ORDER_IMP_NO
    WHERE
    	ORDER_IMPORT_FILE_OUT.SEQ = /*seq*/16
) , 
HAND_INPUT_CHECK05 AS (
SELECT
    FRST_ORDER_DETAIL.ORDER_NO
    , '返信ファイル外の品目と受注が纏められています。(' ||  
            LISTAGG( NVL( ITEM.OTHER_COMPANY_CD1 , ITEM.ITEM_NAME ) || '/' || FRST_ORDER_DETAIL.ORDER_QTY || NAMES.NAME01 , '、' ) WITHIN GROUP ( ORDER BY FRST_ORDER_DETAIL.ITEM_CD ) 
      || ')'
    AS CHECK05_MESSAGE
FROM
    FRST_ORDER_DETAIL
LEFT JOIN 
    ITEM 
ON 
    ITEM.ITEM_CD = FRST_ORDER_DETAIL.ITEM_CD
LEFT JOIN
	NAMES
ON
	NAMES.NAME_DIVISION = 'UNIT'
	AND NAMES.NAME_CD = ITEM.UNIT_OF_STOCK_CONTROL
WHERE
    NOT EXISTS( SELECT 
                    'X' 
            FROM 
                    ORDER_IMPORT_FILE_OUT_WK
            WHERE
                ( FRST_ORDER_DETAIL.FRST_ORDER_NO = ORDER_IMPORT_FILE_OUT_WK.PK_NO 
                    AND FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO = ORDER_IMPORT_FILE_OUT_WK.PK_ROW )
    )
    AND EXISTS( SELECT 
                    'X' 
            FROM 
                    ORDER_IMPORT_FILE_OUT_WK
            WHERE
                FRST_ORDER_DETAIL.ORDER_NO = ORDER_IMPORT_FILE_OUT_WK.ORDER_NO
    )
GROUP BY
    FRST_ORDER_DETAIL.ORDER_NO
)
SELECT
	ORDER_IMPORT_FILE_OUT_WK.PK_NO
,	ORDER_IMPORT_FILE_OUT_WK.PK_ROW
,	ORDER_IMPORT_FILE_OUT_WK.DELIVERY_EXPECTED_DATE 
,	ORDER_IMPORT_FILE_OUT_WK.VENDER_CD 
,	ORDER_IMPORT_FILE_OUT_WK.VENDER_SHORTED_NAME
,	ORDER_IMPORT_FILE_OUT_WK.ORDER_QTY
,	ORDER_IMPORT_FILE_OUT_WK.CARRY_FARE
,	ORDER_IMPORT_FILE_OUT_WK.CARRY_GROUP
,	ORDER_IMPORT_FILE_OUT_WK.ERROR_STATUS
,	ORDER_IMPORT_FILE_OUT_WK.IMPORT_STATUS
,	ORDER_IMPORT_FILE_OUT_WK.CHECK01 
,	ORDER_IMPORT_FILE_OUT_WK.CHECK02 
,	ORDER_IMPORT_FILE_OUT_WK.CHECK03 
,	ORDER_IMPORT_FILE_OUT_WK.CHECK04 
,	HAND_INPUT_CHECK05.CHECK05_MESSAGE AS CHECK05
,	NULL AS CHECK06
,	NULL AS CHECK07
,	NULL AS CHECK08
,	NULL AS CHECK09
,	NULL AS CHECK10
,	'' AS CHECK_ALL
FROM
    ORDER_IMPORT_FILE_OUT_WK
LEFT JOIN
    HAND_INPUT_CHECK05
ON
    HAND_INPUT_CHECK05.ORDER_NO = ORDER_IMPORT_FILE_OUT_WK.ORDER_NO
ORDER BY ORDER_IMPORT_FILE_OUT_WK.PK_NO,ORDER_IMPORT_FILE_OUT_WK.PK_ROW ASC