/*
 *  受注画面からチェックをした、受注取込のリストから、受注ファイルデータ一時取込テーブルの1行単位のデータの主キー情報を取得する。
 *
 * entityName=OrderImportTempList
 * packageName=orderImportTempList
 * methodName=getCheckList
 *
 */
SELECT
	ORDER_DATA.SEQ
,	ORDER_DATA.PK_NO
,	ORDER_DATA.PK_ROW
,	ORDER_DATA.SCREEN_ROW
,	ORDER_DATA.DELIVERY_NAME
,	ORDER_DATA.ITEM_NAME
,	ORDER_DATA.IMPORT_STATUS
,	ORDER_DATA.VENDER_CD
,	VENDER.ORDER_MAIL_OUTPUT
,	VENDER.ORDER_MAIL_ADDRESS1
,	VENDER.ORDER_MAIL_ADDRESS2
,	VENDER.ORDER_MAIL_ADDRESS3
,	ORDER_DATA.IMPORT_DATA_NUM
FROM
	(
		SELECT
			ORDER_IMPORT_FILE_OUT.SEQ
		,	ORDER_IMPORT_FILE_OUT.PK_NO
		,	ORDER_IMPORT_FILE_OUT.PK_ROW
		,	ORDER_IMPORT_FILE_OUT.SCREEN_ROW
		,	ORDER_IMPORT_FILE_OUT.DELIVERY_NAME
		,	ORDER_IMPORT_FILE_OUT.ITEM_NAME
		,	CASE WHEN FRST_ORDER_DETAIL.DEL_FLG = 1    THEN 90
               WHEN FRST_ORDER_DETAIL.CANCEL_FLG = 1 THEN 90
               WHEN FRST_ORDER_DETAIL.ORDER_NO IS NOT NULL THEN 30
               WHEN FRST_ORDER_DETAIL.INPUT_APPROVAL_DATE IS NOT NULL THEN 20
               WHEN FRST_ORDER_DETAIL.INPUT_APPROVAL_DATE IS NULL THEN 10
          END IMPORT_STATUS
		,	FNC_GET_UPPER_VENDER(FRST_ORDER_HEAD.BALANCE_CD,1) AS VENDER_CD
		,	(SELECT COUNT(*) FROM ORDER_IMPORT_TEMP 
			WHERE ORDER_IMPORT_TEMP.TEMP_NO = ORDER_IMP_BASE.TEMP_NO 
			AND ORDER_IMPORT_TEMP.CELL_ROW_NUMBER = ORDER_IMP_BASE.CELL_ROW_NUMBER 
			AND ORDER_IMPORT_TEMP.ORDER_FILE_COLUMN_NAME <> ORDER_IMPORT_TEMP.CELL_DATA) AS IMPORT_DATA_NUM
		FROM
    		ORDER_IMPORT_FILE_OUT
        LEFT JOIN FRST_ORDER_DETAIL ON FRST_ORDER_DETAIL.FRST_ORDER_NO = ORDER_IMPORT_FILE_OUT.PK_NO AND FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO = ORDER_IMPORT_FILE_OUT.PK_ROW
        LEFT JOIN FRST_ORDER_HEAD ON FRST_ORDER_HEAD.FRST_ORDER_NO = FRST_ORDER_DETAIL.FRST_ORDER_NO 
        LEFT JOIN ORDER_IMP_BASE ON ORDER_IMP_BASE.ORDER_IMP_NO = FRST_ORDER_DETAIL.ORDER_IMP_NO
   		WHERE
			ORDER_IMPORT_FILE_OUT.SEQ = /*seq*/
	)ORDER_DATA
LEFT JOIN VENDER ON VENDER.VENDER_DIVISION = 'TS' AND VENDER.VENDER_CD = ORDER_DATA.VENDER_CD
ORDER BY ORDER_DATA.SCREEN_ROW ASC