/*
 *  受注画面からチェックをした、受注取込のリストから、受注ファイルデータ一時取込テーブルの1行単位のデータの主キー情報を取得する。
 *
 * entityName=OrderImportTempList
 * packageName=orderImportTempList
 * methodName=getDetailList
 *
 */
SELECT
	ORDER_IMPORT_TEMP.TEMP_NO
,	ORDER_IMPORT_TEMP.VENDER_GROUP_CD
,	ORDER_IMPORT_TEMP.ORDER_FILE_NAME
,	ORDER_IMPORT_TEMP.IMPORT_DATE
,	ORDER_IMPORT_TEMP.IMPORT_TANTO_CD
,	ORDER_IMPORT_TEMP.CELL_ROW_NUMBER
,	ORDER_IMPORT_TEMP.CELL_COLUMN_NUMBER
,	ORDER_IMPORT_TEMP.ORDER_FILE_COLUMN_NAME
,	NVL(ORDER_IMPORT_TEMP.CELL_DATA,'') AS CELL_DATA
,	FNC_GET_UPPER_VENDER( FRST_ORDER_HEAD.BALANCE_CD,1) AS VENDER_CD
,	ORDER_IMPORT_TEMP.UPDATE_DATE
,	ORDER_IMPORT_TEMP.UPDATOR_CD
,	ORDER_IMPORT_FILE_OUT.PK_NO
,	ORDER_IMPORT_FILE_OUT.PK_ROW
FROM 
	ORDER_IMPORT_FILE_OUT
INNER JOIN FRST_ORDER_DETAIL ON FRST_ORDER_DETAIL.FRST_ORDER_NO = ORDER_IMPORT_FILE_OUT.PK_NO AND FRST_ORDER_DETAIL.FRST_ORDER_ROW_NO = ORDER_IMPORT_FILE_OUT.PK_ROW
INNER JOIN FRST_ORDER_HEAD ON FRST_ORDER_HEAD.FRST_ORDER_NO = FRST_ORDER_DETAIL.FRST_ORDER_NO 
INNER JOIN ORDER_IMP_BASE ON ORDER_IMP_BASE.ORDER_IMP_NO = FRST_ORDER_DETAIL.ORDER_IMP_NO
INNER JOIN ORDER_IMPORT_TEMP ON ORDER_IMPORT_TEMP.TEMP_NO = ORDER_IMP_BASE.TEMP_NO AND ORDER_IMPORT_TEMP.CELL_ROW_NUMBER = ORDER_IMP_BASE.CELL_ROW_NUMBER AND ORDER_IMPORT_TEMP.ORDER_FILE_COLUMN_NAME <> ORDER_IMPORT_TEMP.CELL_DATA
WHERE 
	ORDER_IMPORT_FILE_OUT.SEQ = /*seq*/
ORDER BY 
	FNC_GET_UPPER_VENDER( FRST_ORDER_HEAD.BALANCE_CD,1)
,	ORDER_IMPORT_TEMP.TEMP_NO
,	ORDER_IMPORT_TEMP.CELL_ROW_NUMBER
,	ORDER_IMPORT_TEMP.CELL_COLUMN_NUMBER ASC