/*
 * 棚卸準備処理用SQL
 *
 * entityName=InquiryPreparationList
 * packageName=inquirypreparationlist
 * methodName=getList
 *
 */

SELECT /*countDate*/'2008/02/27' COUNT_DATE, LOCATION.COUNT_DIVISION, LOCATION.LOCATION_CD, LOT_INVENTORY.ITEM_CD, LOT_INVENTORY.LOT_NO, ALIAS_LOT_NO, INVENTORY_QTY, INVENTORY_COST
FROM LOCATION, LOT_INVENTORY
WHERE LOT_INVENTORY.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND LOCATION.COUNT_DIVISION = /*countDivision*/'%'
ORDER BY LOCATION.LOCATION_CD, LOT_INVENTORY.LOT_NO


