/*
 * 取引先名称検索用SQL
 *
 * entityName=DeliveryDetail
 * packageName=deliverydetail
 * methodName=getEntity
 *
 */

SELECT DELIVERY_CD, DELIVERY_NAME1, DELIVERY_NAME2, SEARCH_KANA, DELIVERY.ZIPCODE_NO, DELIVERY.ADDRESS1,
DELIVERY.ADDRESS2, DELIVERY.ADDRESS3, DELIVERY.TEL_NO, DELIVERY.FAX_NO, CITY_CD, CARRY_FARE_CD, DELIVERY.CARRY_CD,
CARRY_NAME1, LEAD_TIME, DELIVERY_TIME, FARE_CLAIM_EXISTENCE, DIVISION, DELIVERY.TANTO_CD, TANTO_NM,
DELIVERY_CONDITION, DELIVERY.REMARKS, DELIVERY.UPDATE_DATE
FROM DELIVERY, CARRY, LOGIN
WHERE DELIVERY.DELIVERY_CD = /*deliveryCd*/'%'
AND DELIVERY.CARRY_CD = CARRY.CARRY_CD(+)
AND DELIVERY.TANTO_CD = LOGIN.TANTO_CD(+)


