/*
 * Created on 2009/03/03
 *
 * $copyright$
 *
*/

/**
 * 売上詳細(預り品)画面用品目情報取得SQL
 *
 * @author tosco
 *
 * entityName=SalesDetailKeepEntity
 * packageName=sales
 * methodName=getSalesByItem
 *
 */
SELECT
    ITEM.ITEM_NAME
,	ITEM.ARTICLE_DIVISION
,   ITEM.OTHER_COMPANY_CD1
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   ITEM.STYLE_OF_PACKING
,   ATTRIBUTE.SECTION_CD           AS ACCOUNT_CREDIT_SECTION_CD
,   ATTRIBUTE.ACCOUNTS_CD          AS CREDIT_TITLE_CD
,   BUMON.SECTION_NAME             AS ACCOUNTS_CREDIT_SECTION_NAME
,   ACCOUNTS.ACCOUNTS_NAME         AS CREDIT_TITLE_NAME
,   ATTRIBUTE.KEEP_DIVISION
FROM
    ITEM
,   ARTICLE_ATTRIBUTE_QUEUE ATTRIBUTE
,   BUMON    
,   (SELECT ACCOUNTS_CD, ACCOUNTS_NAME
     FROM ACCOUNTS
     GROUP BY ACCOUNTS_CD, ACCOUNTS_NAME
    ) ACCOUNTS
WHERE
    ITEM.ITEM_CD = /*itemCd*/
AND ATTRIBUTE.ITEM_CD = ITEM.ITEM_CD(+)
AND ATTRIBUTE.VERSION = ITEM.VERSION(+)
AND ATTRIBUTE.SECTION_CD = BUMON.SECTION_CD(+)
AND ATTRIBUTE.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
