/*
 * Created on 2009/03/03
 *
 * $copyright$
 *
*/

/**
 * 売上詳細(標準)画面用品目会計情報取得SQL
 *
 * @author tosco
 *
 * entityName=SalesDetailStandardEntity
 * packageName=sales
 * methodName=getSalesByItem
 *
 */
SELECT
    ATTRIBUTE.SECTION_CD           AS ACCOUNT_CREDIT_SECTION_CD
,   ATTRIBUTE.ACCOUNTS_CD          AS CREDIT_TITLE_CD
,   BUMON.SECTION_NAME             AS ACCOUNTS_CREDIT_SECTION_NAME
,   ACCOUNTS.ACCOUNTS_NAME         AS CREDIT_TITLE_NAME
FROM
    ITEM
,   ARTICLE_ATTRIBUTE_QUEUE ATTRIBUTE
,   BUMON    
,   (SELECT ACCOUNTS_CD, ACCOUNTS_NAME
     FROM ACCOUNTS
     GROUP BY ACCOUNTS_CD, ACCOUNTS_NAME
    ) ACCOUNTS
WHERE
    ITEM.ITEM_CD = /*itemCd*/
AND ATTRIBUTE.ITEM_CD = ITEM.ITEM_CD(+)
AND ATTRIBUTE.VERSION = ITEM.VERSION(+)
AND ATTRIBUTE.SECTION_CD = BUMON.SECTION_CD(+)
AND ATTRIBUTE.ACCOUNTS_CD = ACCOUNTS.ACCOUNTS_CD(+)
