/*
 * Created on 2009/03/11
 *
 * $copyright$
 *
 */

/*
 * 出庫ロケーション一覧取得用SQL
 *
 * entityName=SalesLotSearchList
 * packageName=sales
 * methodName=getSearchList
 *
 */
SELECT
       INOUT_RECORD.LOCATION_CD
,      INOUT_RECORD.LOT_NO
,      ABS(INOUT_RECORD.INOUT_QTY) AS INOUT_QTY
,      LOCATION.LOCATION_NAME
,      LOT_INVENTORY.INVENTORY_QTY
,      LOT_INVENTORY.INSPECTION_QTY
FROM
     (SELECT MAX(INOUT_NO) INOUT_NO
      FROM  INOUT_RECORD
      WHERE
            INOUT_RECORD.INOUT_DIVISION = /*inoutDivision*/
        AND ODER_NO = /*salesNo*/
        AND ODER_LINE_NO = 1
     ) INOUT_RECORD_MAX
,    INOUT_RECORD
,    LOCATION
,    LOT_INVENTORY
WHERE
     INOUT_RECORD.INOUT_NO >= INOUT_RECORD_MAX.INOUT_NO
AND  INOUT_RECORD.INOUT_DIVISION = /*inoutDivision*/
AND  INOUT_RECORD.ODER_NO = /*salesNo*/
AND  INOUT_RECORD.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND  INOUT_RECORD.LOCATION_CD = LOT_INVENTORY.LOCATION_CD(+)
AND  INOUT_RECORD.ITEM_CD = LOT_INVENTORY.ITEM_CD(+)
AND  INOUT_RECORD.LOT_NO = LOT_INVENTORY.LOT_NO(+)
ORDER BY INOUT_RECORD.ODER_LINE_NO
