/*
 * 受注取込詳細用SQL
 *
 * entityName=ODerImportDetailEntity
 * packageName=ODerImportDetailEntity
 * methodName=getEntity
 *
 */
SELECT
    FRST_ORDER_HEAD.FRST_ORDER_NO
,   FRST_ORDER_HEAD.ORDER_NO
,   FRST_ORDER_HEAD.ORDER_DIVISION
,   FRST_ORDER_HEAD.VENDER_GROUP_CD
,   OVM.VENDER_GROUP_NAME
,   FRST_ORDER_HEAD.ORDER_DATE
,   FRST_ORDER_HEAD.DELIVERY_CD
,   DEL.SEARCH_KANA AS DELIVERY_NAME
,   DEL.ADDRESS1 || DEL.ADDRESS2 || DEL.ADDRESS3 ADDRESS
,   FRST_ORDER_HEAD.DELIVERY_ADDRESS
,   FRST_ORDER_HEAD.DELIVERY_TEL_NO
,   FRST_ORDER_HEAD.SCHEDULED_SHIPPING_DATE
,   FRST_ORDER_HEAD.LEAD_TIME
,   FRST_ORDER_HEAD.CARRY_CD
,   FRST_ORDER_HEAD.DELIVERY_EXPECTED_DATE
,   FRST_ORDER_HEAD.DELIVERY_EXPECTED_TIME
,   FRST_ORDER_HEAD.SUGGESTED_DELIVERLIMIT
,   FRST_ORDER_HEAD.ORDER_AMOUNT
,   FRST_ORDER_HEAD.BALANCE_CD
,   FRST_ORDER_HEAD.ORGANIZATION_CD
,   ORG.ORGANIZATION_NAME
,   FRST_ORDER_HEAD.VENDER_CD
,   VEN.VENDER_SHORTED_NAME VENDER_NAME
,   FRST_ORDER_HEAD.CARRY_FARE
,   FRST_ORDER_HEAD.CARRY_INVOICE_FLAG
,   FRST_ORDER_HEAD.PRINT_SUMMERY
,   FRST_ORDER_HEAD.DELIVERY_SLIP_SUMMERY
,   FRST_ORDER_HEAD.ORDER_PICTURE
,   FRST_ORDER_HEAD.ORDER_SUMMERY
,   FRST_ORDER_HEAD.DELIVERYDATE_CONTACT_SUMMERY  /* 20210906 Asclab Saita 納期連絡表専用備考追加対応  */
,   FRST_ORDER_HEAD.ORDER_SUMMERY
,   FRST_ORDER_HEAD.SALES_TANTO_CD
,   FRST_ORDER_HEAD.DEL_FLG
,   FRST_ORDER_HEAD.CANCEL_FLG
,   CASE WHEN FRST_ORDER_HEAD.DEL_FLG= 1 THEN 90
		 WHEN FRST_ORDER_HEAD.INVISIBLE_FLG= 1 THEN 90
		 WHEN FRST_ORDER_HEAD.ORDER_NO IS NULL THEN 10
	     WHEN FRST_ORDER_HEAD.ORDER_NO IS NOT NULL THEN 30
	END AS IMPORT_STATUS
,   FRST_ORDER_HEAD.CUSTOMER_ORDER_NO
FROM FRST_ORDER_HEAD
LEFT JOIN
        (SELECT DISTINCT
            ORDER_VENDER_MASTER.VENDER_GROUP_CD
        ,   ORDER_VENDER_MASTER.VENDER_GROUP_NAME
        FROM ORDER_VENDER_MASTER)OVM
        ON FRST_ORDER_HEAD.VENDER_GROUP_CD = OVM.VENDER_GROUP_CD
LEFT JOIN ORDER_HEAD OH ON FRST_ORDER_HEAD.ORDER_NO = OH.ORDER_NO
LEFT JOIN DELIVERY DEL ON FRST_ORDER_HEAD.DELIVERY_CD = DEL.DELIVERY_CD
LEFT JOIN VENDER VEN ON FRST_ORDER_HEAD.VENDER_CD = VEN.VENDER_CD
LEFT JOIN ORGANIZATION ORG ON FRST_ORDER_HEAD.ORGANIZATION_CD = ORG.ORGANIZATION_CD
WHERE
    FRST_ORDER_HEAD.FRST_ORDER_NO IS NOT NULL
AND FRST_ORDER_HEAD.FRST_ORDER_NO = /*frstOrderNo*/'FO000001433'