/*
 * 受注取込基データヘッダ用SQL 
 *
 * entityName=OderImportDetailEntity
 * packageName=OderImportDetailEntity
 * methodName=getImportHeaderEntity.sql
 * 取り込んだ先付け受注番号1:取込データNになるため、列ごとにLIST_AGGの結果をDISTINCTした。
 */
WITH TARGET_DATA AS (
    SELECT
        FRST_ORDER_HEAD.FRST_ORDER_NO 
    ,   TO_CHAR( ORDER_IMP_BASE.CTM_ORDER_DATE , 'yyyy/MM/dd' ) AS CTM_ORDER_DATE
    ,   TO_CHAR( ORDER_IMP_BASE.IMPORT_DATE , 'yyyy/MM/dd' ) AS IMPORT_DATE
    ,   ORDER_IMP_BASE.CTM_DELIVERY_CD_01 || ORDER_IMP_BASE.CTM_DELIVERY_CD_02 || ORDER_IMP_BASE.CTM_DELIVERY_CD_03 AS CTM_DELIVERY_CD
    ,   ORDER_IMP_BASE.CTM_DELIVERY_NAME_01 || ORDER_IMP_BASE.CTM_VENDER_NAME_02 || ORDER_IMP_BASE.CTM_DELIVERY_NAME_03  AS CTM_DELIVERY_NAME
    ,   ORDER_IMP_BASE.CTM_DELIVERY_ADDRESS_01 || ORDER_IMP_BASE.CTM_DELIVERY_ADDRESS_02 || ORDER_IMP_BASE.CTM_DELIVERY_ADDRESS_03  AS CTM_ADDRESS
    ,   ORDER_IMP_BASE.CTM_DELIVERY_ADDRESS
    ,   ORDER_IMP_BASE.CTM_DELIVERY_TEL_NO
    ,   ORDER_IMP_BASE.CTM_REMARK_01 
        || CASE WHEN NVL(LENGTH(TRIM( ORDER_IMP_BASE.CTM_REMARK_02 ) ) , 0 ) <> 0 THEN '/' || ORDER_IMP_BASE.CTM_REMARK_02 END
        || CASE WHEN NVL(LENGTH(TRIM( ORDER_IMP_BASE.CTM_REMARK_03 ) ) , 0 ) <> 0 THEN '/' || ORDER_IMP_BASE.CTM_REMARK_03 END
        AS CTM_REMARK
    ,   ORDER_IMP_BASE.CTM_VENDER_NAME_01 || ORDER_IMP_BASE.CTM_VENDER_NAME_02 || ORDER_IMP_BASE.CTM_VENDER_NAME_03 AS CTM_VENDER_NAME
    ,   CASE WHEN ORDER_VENDER_DELIVERY.SOM_DELIVERY_CD IS NULL THEN '変換マスタに客先納入先コードを登録してください。'  END AS ERROR_MSG1
    ,   CASE WHEN DELIVERY.DELIVERY_CD IS NULL THEN '変換マスタに登録されている納入先を納入先マスタに登録してください。' END AS ERROR_MSG2
    ,   CASE WHEN FRST_ORDER_HEAD.BALANCE_CD IS NULL THEN '最上位の得意先を取得できませんでした。帳合マスタを設定してください。' END AS ERROR_MSG3
    FROM 
        FRST_ORDER_HEAD
    INNER JOIN
        FRST_ORDER_DETAIL
    ON
        FRST_ORDER_DETAIL.FRST_ORDER_NO = FRST_ORDER_HEAD.FRST_ORDER_NO
    LEFT JOIN
        ORDER_IMP_BASE
    ON
        ORDER_IMP_BASE.ORDER_IMP_NO = FRST_ORDER_DETAIL.ORDER_IMP_NO
    LEFT JOIN
        ORDER_VENDER_DELIVERY
    ON
        ORDER_VENDER_DELIVERY.VENDER_GROUP_CD = ORDER_IMP_BASE.VENDER_GROUP_CD
        AND ( ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_01 IS NULL AND ORDER_IMP_BASE.CTM_DELIVERY_CD_01  IS NULL ) OR ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_01 = ORDER_IMP_BASE.CTM_DELIVERY_CD_01 ) )
        AND ( ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_02 IS NULL AND ORDER_IMP_BASE.CTM_DELIVERY_CD_02  IS NULL ) OR ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_02 = ORDER_IMP_BASE.CTM_DELIVERY_CD_02 ) )
        AND ( ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_03 IS NULL AND ORDER_IMP_BASE.CTM_DELIVERY_CD_03  IS NULL ) OR ( ORDER_VENDER_DELIVERY.CTM_DELIVERY_CD_03 = ORDER_IMP_BASE.CTM_DELIVERY_CD_03 ) )
    LEFT JOIN
        DELIVERY
    ON
        DELIVERY.DELIVERY_CD = ORDER_VENDER_DELIVERY.SOM_DELIVERY_CD
    WHERE
        FRST_ORDER_HEAD.FRST_ORDER_NO IS NOT NULL
    AND FRST_ORDER_HEAD.FRST_ORDER_NO = /*frstOrderNo*/'1273'
) , BASE_TABLE AS (
    SELECT
        /*frstOrderNo*/'1273' AS FRST_ORDER_NO
    FROM
        DUAL
)
SELECT
        BASE_TABLE.FRST_ORDER_NO 
    ,   TMP1.CTM_ORDER_DATE
    ,   TMP2.IMPORT_DATE
    ,   TMP3.CTM_DELIVERY_CD
    ,   TMP4.CTM_DELIVERY_NAME
    ,   TMP5.CTM_ADDRESS
    ,   TMP6.CTM_DELIVERY_ADDRESS
    ,   TMP7.CTM_DELIVERY_TEL_NO
    ,   TMP8.CTM_REMARK
    ,   TMP9.CTM_VENDER_NAME
    ,   TMP10.ERROR_MSG1
    ,   TMP11.ERROR_MSG2
    ,   TMP12.ERROR_MSG3
FROM
    BASE_TABLE
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_ORDER_DATE , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_ORDER_DATE ) AS CTM_ORDER_DATE
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_ORDER_DATE FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_ORDER_DATE ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP1
ON
    BASE_TABLE.FRST_ORDER_NO = TMP1.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.IMPORT_DATE , ',' ) WITHIN GROUP( ORDER BY TMP.IMPORT_DATE ) AS IMPORT_DATE
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.IMPORT_DATE FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.IMPORT_DATE ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP2
ON
    BASE_TABLE.FRST_ORDER_NO = TMP2.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_DELIVERY_CD , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_DELIVERY_CD ) AS CTM_DELIVERY_CD
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_CD FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_CD ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP3
ON
    BASE_TABLE.FRST_ORDER_NO = TMP3.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_DELIVERY_NAME , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_DELIVERY_NAME ) AS CTM_DELIVERY_NAME
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_NAME FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_NAME ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP4
ON
    BASE_TABLE.FRST_ORDER_NO = TMP4.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_ADDRESS , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_ADDRESS ) AS CTM_ADDRESS
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_ADDRESS FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_ADDRESS ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP5
ON
    BASE_TABLE.FRST_ORDER_NO = TMP5.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_DELIVERY_ADDRESS , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_DELIVERY_ADDRESS ) AS CTM_DELIVERY_ADDRESS
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_ADDRESS FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_ADDRESS ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP6
ON
    BASE_TABLE.FRST_ORDER_NO = TMP6.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_DELIVERY_TEL_NO , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_DELIVERY_TEL_NO ) AS CTM_DELIVERY_TEL_NO
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_TEL_NO FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_DELIVERY_TEL_NO ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP7
ON
    BASE_TABLE.FRST_ORDER_NO = TMP7.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_REMARK , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_REMARK ) AS CTM_REMARK
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_REMARK FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_REMARK ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP8
ON
    BASE_TABLE.FRST_ORDER_NO = TMP8.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.CTM_VENDER_NAME , ',' ) WITHIN GROUP( ORDER BY TMP.CTM_VENDER_NAME ) AS CTM_VENDER_NAME
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_VENDER_NAME FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.CTM_VENDER_NAME ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP9
ON
    BASE_TABLE.FRST_ORDER_NO = TMP9.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.ERROR_MSG1 , ',' ) WITHIN GROUP( ORDER BY TMP.ERROR_MSG1 ) AS ERROR_MSG1
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG1 FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG1 ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP10
ON
    BASE_TABLE.FRST_ORDER_NO = TMP10.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.ERROR_MSG2 , ',' ) WITHIN GROUP( ORDER BY TMP.ERROR_MSG2 ) AS ERROR_MSG2
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG2 FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG2 ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP11
ON
    BASE_TABLE.FRST_ORDER_NO = TMP11.FRST_ORDER_NO
LEFT JOIN
    ( SELECT TMP.FRST_ORDER_NO , LISTAGG( TMP.ERROR_MSG3 , ',' ) WITHIN GROUP( ORDER BY TMP.ERROR_MSG3 ) AS ERROR_MSG3
        FROM ( SELECT TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG3 FROM TARGET_DATA GROUP BY TARGET_DATA.FRST_ORDER_NO , TARGET_DATA.ERROR_MSG3 ) TMP 
        GROUP BY TMP.FRST_ORDER_NO ) TMP12
ON
    BASE_TABLE.FRST_ORDER_NO = TMP12.FRST_ORDER_NO