/*
 * 見積/単価更新用SQL
 *
 * entityName=EstimateUpdate
 * packageName=estimateupdate
 * methodName=update
 */

MERGE INTO ESTIMATE A
	USING (SELECT /*bean.estimateNo*/'%' ESTIMATE_NO
	, /*bean.estimateInputDate*/'2009/09/01' ESTIMATE_INPUT_DATE
	, /*bean.balanceCd*/'%' BALANCE_CD
	, /*bean.venderCd*/'%' VENDER_CD
	, /*bean.itemCd*/'%' ITEM_CD
	, /*bean.consecutiveNo*/1 CONSECUTIVE_NO
	, /*bean.standardUnitPrice*/1 STANDARD_UNIT_PRICE
	, /*bean.standardDiscount*/1 STANDARD_DISCOUNT
	, /*bean.specialDiscount*/1 SPECIAL_DISCOUNT
	, /*bean.unitprice*/1 UNITPRICE
	, /*bean.standardAmount*/1 STANDARD_AMOUNT
	, /*bean.matss*/1 MATSS
	, /*bean.estimateValidDateFrom*/'2009/09/01' ESTIMATE_VALID_DATE_FROM
	, /*bean.estimateValidDateTo*/'2009/09/01' ESTIMATE_VALID_DATE_TO
	, /*bean.remark*/'%' REMARK
	, /*bean.inputDate*/'2009/09/01' INPUT_DATE
	, /*bean.inputorCd*/'%' INPUTOR_CD
	, /*bean.updateDate*/'2009/09/01' UPDATE_DATE
	, /*bean.updatorCd*/'%' UPDATOR_CD
	, /*bean.estimateStatus*/1 ESTIMATE_STATUS
	FROM DUAL) B
	ON (A.ESTIMATE_NO = B.ESTIMATE_NO AND A.CONSECUTIVE_NO = B.CONSECUTIVE_NO)
WHEN MATCHED THEN
	UPDATE SET A.ESTIMATE_INPUT_DATE = B.ESTIMATE_INPUT_DATE
	, A.BALANCE_CD = B.BALANCE_CD
	, A.VENDER_CD = B.VENDER_CD
	, A.ITEM_CD = B.ITEM_CD
	, A.STANDARD_UNIT_PRICE = B.STANDARD_UNIT_PRICE
	, A.STANDARD_DISCOUNT = B.STANDARD_DISCOUNT
	, A.SPECIAL_DISCOUNT = B.SPECIAL_DISCOUNT
	, A.UNITPRICE = B.UNITPRICE
	, A.STANDARD_AMOUNT = B.STANDARD_AMOUNT
	, A.MATSS = B.MATSS
	, A.ESTIMATE_VALID_DATE_FROM = B.ESTIMATE_VALID_DATE_FROM
	, A.ESTIMATE_VALID_DATE_TO = B.ESTIMATE_VALID_DATE_TO
	, A.REMARK = B.REMARK
	, A.UPDATE_DATE = B.UPDATE_DATE
	, A.UPDATOR_CD = B.UPDATOR_CD
WHEN NOT MATCHED THEN
	INSERT VALUES(B.ESTIMATE_NO
	, B.ESTIMATE_INPUT_DATE
	, B.BALANCE_CD
	, B.VENDER_CD
	, B.ITEM_CD
	, B.CONSECUTIVE_NO
	, B.STANDARD_UNIT_PRICE
	, B.STANDARD_DISCOUNT
	, B.SPECIAL_DISCOUNT
	, B.UNITPRICE
	, B.STANDARD_AMOUNT
	, B.MATSS
	, B.ESTIMATE_VALID_DATE_FROM
	, B.ESTIMATE_VALID_DATE_TO
	, B.REMARK
	, B.INPUT_DATE
	, B.INPUTOR_CD
	, B.UPDATE_DATE
	, B.UPDATOR_CD
	, B.ESTIMATE_STATUS);
