/*
 * 自社マスタ帳票用SQL
 *
 * entityName=CompanyListForReport
 * packageName=companylistforreport
 * methodName=getListForReport
 *
 */

SELECT COMPANY.*
, CREDIT_BANK1.BANK_MASTER_NAME CREDIT_BANK_NAME1
, CREDIT_BANK2.BANK_MASTER_NAME CREDIT_BANK_NAME2
, CREDIT_BANK3.BANK_MASTER_NAME CREDIT_BANK_NAME3
, CREDIT_BANK4.BANK_MASTER_NAME CREDIT_BANK_NAME4
, PAYMENT_BANK.BANK_MASTER_NAME PAYMENT_BANK_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM COMPANY
, BANK CREDIT_BANK1
, BANK CREDIT_BANK2
, BANK CREDIT_BANK3
, BANK CREDIT_BANK4
, BANK PAYMENT_BANK
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE COMPANY.COMPANY_CD IS NOT NULL

/*IF((condition.srhHomeName1 != null) && (condition.srhHomeName1 != ""))*/
AND	COMPANY.HOME_NAME1 LIKE /*condition.srhHomeName1*/'%'
/*END*/

AND COMPANY.BANK_MASTER_CD1 = CREDIT_BANK1.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD2 = CREDIT_BANK2.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD3 = CREDIT_BANK3.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD4 = CREDIT_BANK4.BANK_MASTER_CD(+)
AND COMPANY.BANK_MASTER_CD = PAYMENT_BANK.BANK_MASTER_CD(+)
AND COMPANY.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND COMPANY.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY COMPANY.COMPANY_CD


