CREATE OR REPLACE VIEW REP_SLIP_ORDER_DETAIL
    (ORDER_NO,ROW_NO,SHIPPING_NO,ITEM_CD,ITEM_NAME,STYLE_OF_PACKING,OTHER_COMPANY_CD1,
    ORDER_QTY,ORDER_UNITPRICE,STANDARD_UNITPRICE,STANDARD_DISCOUNT,SPECIAL_DISCOUNT,
    ORDER_AMOUNT,TMP_UNITPRICE_FLG,TMP_UNITPRICE_STRING,MATSS,ESTIMATE_STANDARD_AMOUNT,
    ESTIMATE_MATSS,INPUT_DATE,INPUTOR_CD,STATUS_NAME,ORDER_DIVISION,INPUT_TANTO_CD,
    INPUT_TANTO_NAME,SALES_TANTO_CD,SALES_TANTO_NAME,DELIVERY_CD,DELIVERY_NAME,
    DELIVERY_ADDRESS_ALL,DELIVERY_TEL_NO,VENDER_CD,VENDER_NAME,ORGANIZATION_CD,
    ORGANIZATION_NAME,SHIPPING_STATUS_CD,PURCHASE_STATUS_CD,SCHEDULED_SHIPPING_DATE,
    ORDER_DATE,INPUTOR_NAME,UPDATE_DATE,UPDATOR_CD,UPDATOR_NAME,CARRY_CD)
AS
SELECT 
	ORDER_DETAIL.ORDER_NO
,	ORDER_DETAIL.ROW_NO
,	ORDER_DETAIL.SHIPPING_NO
,	ORDER_DETAIL.ITEM_CD
,	ORDER_LIST.ITEM_NAME
,	ORDER_LIST.STYLE_OF_PACKING
,	ORDER_LIST.OTHER_COMPANY_CD1
,	ORDER_DETAIL.ORDER_QTY
,	ORDER_DETAIL.ORDER_UNITPRICE
,	ORDER_DETAIL.STANDARD_UNITPRICE
,	ORDER_DETAIL.STANDARD_DISCOUNT
,	ORDER_DETAIL.SPECIAL_DISCOUNT
,	(NVL(ORDER_DETAIL.ORDER_QTY,0) * NVL(ORDER_DETAIL.ORDER_UNITPRICE,0)) AS ORDER_AMOUNT
,	ORDER_DETAIL.TMP_UNITPRICE_FLG
,	(CASE ORDER_DETAIL.TMP_UNITPRICE_FLG WHEN 1 THEN '仮単価' ELSE '正単価' END) AS TMP_UNITPRICE_STRING
,	ORDER_DETAIL.MATSS
,	ORDER_DETAIL.ESTIMATE_STANDARD_AMOUNT
,	ORDER_DETAIL.ESTIMATE_MATSS
,	ORDER_DETAIL.INPUT_DATE
,	ORDER_DETAIL.INPUTOR_CD
,	NVL(CASE ORDER_LIST.ORDER_DIVISION WHEN 3 THEN ORDER_LIST.PURCHASE_STATUS_NAME ELSE ORDER_LIST.SHIPPING_STATUS_NAME END,'受注登録') AS STATUS_NAME
,	ORDER_LIST.ORDER_DIVISION
,	ORDER_LIST.INPUT_TANTO_CD
,	ORDER_LIST.INPUT_TANTO_NAME
,	ORDER_LIST.SALES_TANTO_CD
,	ORDER_LIST.SALES_TANTO_NAME
,	ORDER_LIST.DELIVERY_CD
,	ORDER_LIST.DELIVERY_NAME
,	ORDER_LIST.DELIVERY_ADDRESS_ALL
,	ORDER_LIST.DELIVERY_TEL_NO
,	ORDER_LIST.VENDER_CD
,	ORDER_LIST.VENDER_NAME
,	ORDER_LIST.ORGANIZATION_CD
,	ORDER_LIST.ORGANIZATION_NAME
,	ORDER_LIST.SHIPPING_STATUS_CD
,	ORDER_LIST.PURCHASE_STATUS_CD
,	ORDER_LIST.SCHEDULED_SHIPPING_DATE
,	ORDER_LIST.ORDER_DATE
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	ORDER_DETAIL.UPDATE_DATE
,	ORDER_DETAIL.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
,	ORDER_LIST.CARRY_CD
FROM
	(SELECT 
		ORDER_HEAD.ORDER_NO
	,	ORDER_DETAIL.ROW_NO
	,	ORDER_HEAD.ORDER_DIVISION
	,	ORDER_DIVISION.DIVISION_NAME
	,	DELIVERY.DELIVERY_CD
	,	DELIVERY.DELIVERY_NAME1 || DELIVERY_NAME2 AS DELIVERY_NAME
	,	DELIVERY.ADDRESS1 || DELIVERY.ADDRESS2 || DELIVERY.ADDRESS3 AS DELIVERY_ADDRESS_ALL
	,	DELIVERY.TEL_NO AS DELIVERY_TEL_NO
	,	VENDER.VENDER_CD
	,	VENDER.VENDER_NAME1 || VENDER.VENDER_NAME2 AS VENDER_NAME
	,	VENDER.ORGANIZATION_CD
	,	ORGANIZATION.ORGANIZATION_NAME
	,	ORDER_HEAD.SALES_TANTO_CD
	,	SALES_TANTO.SALES_TANTO_NAME
	,	ORDER_HEAD.INPUT_TANTO_CD
	,	INPUT_TANTO.INPUT_TANTO_NAME
	,	ITEM_QUEUE.ITEM_CD
	,	ITEM_QUEUE.ITEM_NAME
	,	ITEM_QUEUE.STYLE_OF_PACKING
	,	ITEM_QUEUE.OTHER_COMPANY_CD1
	,	ORDER_HEAD.ORDER_DATE
	,	ORDER_HEAD.SCHEDULED_SHIPPING_DATE
	,	NVL(SHIPPING_STATUS.STATUS_CD,'99') AS SHIPPING_STATUS_CD
	,	NVL(SHIPPING_STATUS.SHIPPING_STATUS_NAME,'受注登録') AS SHIPPING_STATUS_NAME
	,	NVL(PURCHASE_STATUS.STATUS_CD,'99') AS PURCHASE_STATUS_CD
	,	NVL(PURCHASE_STATUS.PURCHASE_STATUS_NAME,'受注登録') AS PURCHASE_STATUS_NAME
	-- 運送会社を検索条件に追加
	,	ORDER_HEAD.CARRY_CD 
	FROM 
		ORDER_HEAD
	,	ORDER_DETAIL
	,	DELIVERY
	,	VENDER
	-- > 2009/12/16 修正 ETO
	--,   (SELECT ITEM_CD AS ITEM_CD,MAX(VERSION) AS VERSION FROM ITEM_QUEUE GROUP BY ITEM_CD) ITEM_QUEUE_MAX
	,       VALID_ITEM_QUEUE  ITEM_QUEUE_MAX
	-- < 2009/12/16
	,	VALID_ITEM_QUEUE ITEM_QUEUE
	,	SHIPPING
	,	(SELECT ORDER_NO,ORDER_ROW_NO,STATUS FROM PURCHASE_SUBCONTRACT WHERE ORDER_NO IS NOT NULL GROUP BY ORDER_NO,ORDER_ROW_NO,STATUS) PURCHASE_SUBCONTRACT
	,	ORGANIZATION
	,	(SELECT ORDER_HEAD.ORDER_NO AS ORDER_NO,LOGIN.TANTO_CD AS TANTO_CD,LOGIN.TANTO_NM AS SALES_TANTO_NAME FROM ORDER_HEAD,LOGIN WHERE ORDER_HEAD.SALES_TANTO_CD = LOGIN.TANTO_CD) SALES_TANTO
	,	(SELECT ORDER_HEAD.ORDER_NO AS ORDER_NO,LOGIN.TANTO_CD AS TANTO_CD,LOGIN.TANTO_NM AS INPUT_TANTO_NAME FROM ORDER_HEAD,LOGIN WHERE ORDER_HEAD.INPUT_TANTO_CD = LOGIN.TANTO_CD) INPUT_TANTO
	,	(SELECT NAMES.NAME_CD AS DIVISION_CD ,NAMES.NAME01 AS DIVISION_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'ORDR') ORDER_DIVISION
	,	(SELECT NAMES.NAME_CD AS STATUS_CD ,NAMES.NAME01 AS SHIPPING_STATUS_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'ORST') SHIPPING_STATUS
	,	(SELECT NAMES.NAME_CD AS STATUS_CD ,NAMES.NAME01 AS PURCHASE_STATUS_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'PUST') PURCHASE_STATUS
	WHERE 
		ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
	AND	ORDER_HEAD.ORDER_DIVISION = ORDER_DIVISION.DIVISION_CD
	AND	ORDER_HEAD.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
	AND	ORDER_HEAD.VENDER_CD = VENDER.VENDER_CD(+) AND VENDER.VENDER_DIVISION(+) = 'TS'
	
	AND 	ITEM_QUEUE_MAX.ITEM_CD(+) = ITEM_QUEUE.ITEM_CD
	AND 	ITEM_QUEUE_MAX.VERSION(+) = ITEM_QUEUE.VERSION
	
	AND	ORDER_DETAIL.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
	AND	ORDER_HEAD.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
	AND	ORDER_HEAD.ORDER_NO = SALES_TANTO.ORDER_NO(+)
	AND	ORDER_HEAD.ORDER_NO = INPUT_TANTO.ORDER_NO(+)
	AND	ORDER_DETAIL.SHIPPING_NO = SHIPPING.SHIPPING_NO(+)
	AND	SHIPPING.SHIPPING_STATUS = SHIPPING_STATUS.STATUS_CD(+)
	AND	ORDER_DETAIL.ORDER_NO = PURCHASE_SUBCONTRACT.ORDER_NO(+) 
	AND	ORDER_DETAIL.ROW_NO = PURCHASE_SUBCONTRACT.ORDER_ROW_NO(+) 
	AND	PURCHASE_SUBCONTRACT.STATUS = PURCHASE_STATUS.STATUS_CD(+)
	) ORDER_LIST
,	ORDER_DETAIL
,	LOGIN INPUTOR
,	LOGIN UPDATOR
WHERE ORDER_LIST.ORDER_NO IS NOT NULL
AND	ORDER_LIST.ORDER_NO = ORDER_DETAIL.ORDER_NO
AND	ORDER_LIST.ROW_NO = ORDER_DETAIL.ROW_NO
AND	ORDER_DETAIL.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND	ORDER_DETAIL.UPDATOR_CD = UPDATOR.TANTO_CD(+)
/
COMMENT ON TABLE REP_SLIP_ORDER_DETAIL IS '受注一覧表詳細'
/
CREATE OR REPLACE VIEW REP_SLIP_ORDER_DETAIL
    (ORDER_NO,ROW_NO,SHIPPING_NO,ITEM_CD,ITEM_NAME,STYLE_OF_PACKING,OTHER_COMPANY_CD1,
    ORDER_QTY,ORDER_UNITPRICE,STANDARD_UNITPRICE,STANDARD_DISCOUNT,SPECIAL_DISCOUNT,
    ORDER_AMOUNT,TMP_UNITPRICE_FLG,TMP_UNITPRICE_STRING,MATSS,ESTIMATE_STANDARD_AMOUNT,
    ESTIMATE_MATSS,INPUT_DATE,INPUTOR_CD,STATUS_NAME,ORDER_DIVISION,INPUT_TANTO_CD,
    INPUT_TANTO_NAME,SALES_TANTO_CD,SALES_TANTO_NAME,DELIVERY_CD,DELIVERY_NAME,
    DELIVERY_ADDRESS_ALL,DELIVERY_TEL_NO,VENDER_CD,VENDER_NAME,ORGANIZATION_CD,
    ORGANIZATION_NAME,SHIPPING_STATUS_CD,PURCHASE_STATUS_CD,SCHEDULED_SHIPPING_DATE,
    ORDER_DATE,INPUTOR_NAME,UPDATE_DATE,UPDATOR_CD,UPDATOR_NAME,CARRY_CD)
AS
SELECT 
	ORDER_DETAIL.ORDER_NO
,	ORDER_DETAIL.ROW_NO
,	ORDER_DETAIL.SHIPPING_NO
,	ORDER_DETAIL.ITEM_CD
,	ORDER_LIST.ITEM_NAME
,	ORDER_LIST.STYLE_OF_PACKING
,	ORDER_LIST.OTHER_COMPANY_CD1
,	ORDER_DETAIL.ORDER_QTY
,	ORDER_DETAIL.ORDER_UNITPRICE
,	ORDER_DETAIL.STANDARD_UNITPRICE
,	ORDER_DETAIL.STANDARD_DISCOUNT
,	ORDER_DETAIL.SPECIAL_DISCOUNT
,	(NVL(ORDER_DETAIL.ORDER_QTY,0) * NVL(ORDER_DETAIL.ORDER_UNITPRICE,0)) AS ORDER_AMOUNT
,	ORDER_DETAIL.TMP_UNITPRICE_FLG
,	(CASE ORDER_DETAIL.TMP_UNITPRICE_FLG WHEN 1 THEN '仮単価' ELSE '正単価' END) AS TMP_UNITPRICE_STRING
,	ORDER_DETAIL.MATSS
,	ORDER_DETAIL.ESTIMATE_STANDARD_AMOUNT
,	ORDER_DETAIL.ESTIMATE_MATSS
,	ORDER_DETAIL.INPUT_DATE
,	ORDER_DETAIL.INPUTOR_CD
,	NVL(CASE ORDER_LIST.ORDER_DIVISION WHEN 3 THEN ORDER_LIST.PURCHASE_STATUS_NAME ELSE ORDER_LIST.SHIPPING_STATUS_NAME END,'受注登録') AS STATUS_NAME
,	ORDER_LIST.ORDER_DIVISION
,	ORDER_LIST.INPUT_TANTO_CD
,	ORDER_LIST.INPUT_TANTO_NAME
,	ORDER_LIST.SALES_TANTO_CD
,	ORDER_LIST.SALES_TANTO_NAME
,	ORDER_LIST.DELIVERY_CD
,	ORDER_LIST.DELIVERY_NAME
,	ORDER_LIST.DELIVERY_ADDRESS_ALL
,	ORDER_LIST.DELIVERY_TEL_NO
,	ORDER_LIST.VENDER_CD
,	ORDER_LIST.VENDER_NAME
,	ORDER_LIST.ORGANIZATION_CD
,	ORDER_LIST.ORGANIZATION_NAME
,	ORDER_LIST.SHIPPING_STATUS_CD
,	ORDER_LIST.PURCHASE_STATUS_CD
,	ORDER_LIST.SCHEDULED_SHIPPING_DATE
,	ORDER_LIST.ORDER_DATE
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	ORDER_DETAIL.UPDATE_DATE
,	ORDER_DETAIL.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
,	ORDER_LIST.CARRY_CD
FROM
	(SELECT 
		ORDER_HEAD.ORDER_NO
	,	ORDER_DETAIL.ROW_NO
	,	ORDER_HEAD.ORDER_DIVISION
	,	ORDER_DIVISION.DIVISION_NAME
	,	DELIVERY.DELIVERY_CD
	,	DELIVERY.DELIVERY_NAME1 || DELIVERY_NAME2 AS DELIVERY_NAME
	,	DELIVERY.ADDRESS1 || DELIVERY.ADDRESS2 || DELIVERY.ADDRESS3 AS DELIVERY_ADDRESS_ALL
	,	DELIVERY.TEL_NO AS DELIVERY_TEL_NO
	,	VENDER.VENDER_CD
	,	VENDER.VENDER_NAME1 || VENDER.VENDER_NAME2 AS VENDER_NAME
	,	VENDER.ORGANIZATION_CD
	,	ORGANIZATION.ORGANIZATION_NAME
	,	ORDER_HEAD.SALES_TANTO_CD
	,	SALES_TANTO.SALES_TANTO_NAME
	,	ORDER_HEAD.INPUT_TANTO_CD
	,	INPUT_TANTO.INPUT_TANTO_NAME
	,	ITEM_QUEUE.ITEM_CD
	,	ITEM_QUEUE.ITEM_NAME
	,	ITEM_QUEUE.STYLE_OF_PACKING
	,	ITEM_QUEUE.OTHER_COMPANY_CD1
	,	ORDER_HEAD.ORDER_DATE
	,	ORDER_HEAD.SCHEDULED_SHIPPING_DATE
	,	NVL(SHIPPING_STATUS.STATUS_CD,'99') AS SHIPPING_STATUS_CD
	,	NVL(SHIPPING_STATUS.SHIPPING_STATUS_NAME,'受注登録') AS SHIPPING_STATUS_NAME
	,	NVL(PURCHASE_STATUS.STATUS_CD,'99') AS PURCHASE_STATUS_CD
	,	NVL(PURCHASE_STATUS.PURCHASE_STATUS_NAME,'受注登録') AS PURCHASE_STATUS_NAME
	-- 運送会社を検索条件に追加
	,	ORDER_HEAD.CARRY_CD 
	FROM 
		ORDER_HEAD
	,	ORDER_DETAIL
	,	DELIVERY
	,	VENDER
	-- > 2009/12/16 修正 ETO
	--,   (SELECT ITEM_CD AS ITEM_CD,MAX(VERSION) AS VERSION FROM ITEM_QUEUE GROUP BY ITEM_CD) ITEM_QUEUE_MAX
	,       VALID_ITEM_QUEUE  ITEM_QUEUE_MAX
	-- < 2009/12/16
	,	VALID_ITEM_QUEUE ITEM_QUEUE
	,	SHIPPING
	,	(SELECT ORDER_NO,ORDER_ROW_NO,STATUS FROM PURCHASE_SUBCONTRACT WHERE ORDER_NO IS NOT NULL GROUP BY ORDER_NO,ORDER_ROW_NO,STATUS) PURCHASE_SUBCONTRACT
	,	ORGANIZATION
	,	(SELECT ORDER_HEAD.ORDER_NO AS ORDER_NO,LOGIN.TANTO_CD AS TANTO_CD,LOGIN.TANTO_NM AS SALES_TANTO_NAME FROM ORDER_HEAD,LOGIN WHERE ORDER_HEAD.SALES_TANTO_CD = LOGIN.TANTO_CD) SALES_TANTO
	,	(SELECT ORDER_HEAD.ORDER_NO AS ORDER_NO,LOGIN.TANTO_CD AS TANTO_CD,LOGIN.TANTO_NM AS INPUT_TANTO_NAME FROM ORDER_HEAD,LOGIN WHERE ORDER_HEAD.INPUT_TANTO_CD = LOGIN.TANTO_CD) INPUT_TANTO
	,	(SELECT NAMES.NAME_CD AS DIVISION_CD ,NAMES.NAME01 AS DIVISION_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'ORDR') ORDER_DIVISION
	,	(SELECT NAMES.NAME_CD AS STATUS_CD ,NAMES.NAME01 AS SHIPPING_STATUS_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'ORST') SHIPPING_STATUS
	,	(SELECT NAMES.NAME_CD AS STATUS_CD ,NAMES.NAME01 AS PURCHASE_STATUS_NAME FROM NAMES WHERE NAMES.NAME_DIVISION = 'PUST') PURCHASE_STATUS
	WHERE 
		ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
	AND	ORDER_HEAD.ORDER_DIVISION = ORDER_DIVISION.DIVISION_CD
	AND	ORDER_HEAD.DELIVERY_CD = DELIVERY.DELIVERY_CD(+)
	AND	ORDER_HEAD.VENDER_CD = VENDER.VENDER_CD(+) AND VENDER.VENDER_DIVISION(+) = 'TS'
	
	AND 	ITEM_QUEUE_MAX.ITEM_CD(+) = ITEM_QUEUE.ITEM_CD
	AND 	ITEM_QUEUE_MAX.VERSION(+) = ITEM_QUEUE.VERSION
	
	AND	ORDER_DETAIL.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
	AND	ORDER_HEAD.ORGANIZATION_CD = ORGANIZATION.ORGANIZATION_CD(+)
	AND	ORDER_HEAD.ORDER_NO = SALES_TANTO.ORDER_NO(+)
	AND	ORDER_HEAD.ORDER_NO = INPUT_TANTO.ORDER_NO(+)
	AND	ORDER_DETAIL.SHIPPING_NO = SHIPPING.SHIPPING_NO(+)
	AND	SHIPPING.SHIPPING_STATUS = SHIPPING_STATUS.STATUS_CD(+)
	AND	ORDER_DETAIL.ORDER_NO = PURCHASE_SUBCONTRACT.ORDER_NO(+) 
	AND	ORDER_DETAIL.ROW_NO = PURCHASE_SUBCONTRACT.ORDER_ROW_NO(+) 
	AND	PURCHASE_SUBCONTRACT.STATUS = PURCHASE_STATUS.STATUS_CD(+)
	) ORDER_LIST
,	ORDER_DETAIL
,	LOGIN INPUTOR
,	LOGIN UPDATOR
WHERE ORDER_LIST.ORDER_NO IS NOT NULL
AND	ORDER_LIST.ORDER_NO = ORDER_DETAIL.ORDER_NO
AND	ORDER_LIST.ROW_NO = ORDER_DETAIL.ROW_NO
AND	ORDER_DETAIL.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND	ORDER_DETAIL.UPDATOR_CD = UPDATOR.TANTO_CD(+)
/
COMMENT ON TABLE REP_SLIP_ORDER_DETAIL IS '受注一覧表詳細'
/
