/*
 * 在庫出庫入力詳細用SQL文
 *
 * entityName=InventoryShippingoutDetail
 * packageName=inventoryshippingoutdetail
 * methodName=getEntity
 */

SELECT LOT_INVENTORY.ITEM_CD, ITEM_NAME, OTHER_COMPANY_CD1, STYLE_OF_PACKING, LOT_INVENTORY.LOCATION_CD, LOCATION_NAME, LOT_NO, ALIAS_LOT_NO,
KG_OF_FRACTION_MANAGEMENT, KG_CONVERSION_COEFFICIENT, SMALLNUM_LENGTH, ROUND_DIVISION,

DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1),
DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1),
CASE TYPE_DIVISION
    WHEN 1 THEN FLOOR(NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    WHEN 3 THEN FLOOR(NVL(INVENTORY_QTY, 0) / NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    ELSE NVL(INVENTORY_QTY, 0)
END)) DISP_PACK_QTY,

NULL PACK_QTY,

UNIT_OF_OPERATION_MANAGEMENT, OPERATION_NAMES.NAME01 PACK_UNIT,

DECODE(UNIT_OF_OPERATION_MANAGEMENT, '1', 0, DECODE(UNIT_OF_OPERATION_MANAGEMENT, '5', 0,
CASE TYPE_DIVISION
    WHEN 1 THEN MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    WHEN 3 THEN MOD(NVL(INVENTORY_QTY, 0), NVL(KG_OF_FRACTION_MANAGEMENT, 1))
    ELSE 0
END)) DISP_FRACTION,

NULL FRACTION,

UNIT_OF_FRACTION_MANAGEMENT, FRACTION_NAMES.NAME01 FRACTION_UNIT,

CASE TYPE_DIVISION
    WHEN 1 THEN NVL(INVENTORY_QTY, 0)
    WHEN 3 THEN NVL(INVENTORY_QTY, 0)
    ELSE NVL(INVENTORY_QTY, 0) * NVL(KG_OF_FRACTION_MANAGEMENT, 1)
END INVENTORY_QTY

FROM LOT_INVENTORY, VALID_ITEM_QUEUE ITEM_QUEUE, LOCATION, NAMES OPERATION_NAMES, NAMES FRACTION_NAMES, NUMBER_CHKDISIT
WHERE LOT_INVENTORY.LOCATION_CD = /*locationCd*/'%'
AND LOT_INVENTORY.ITEM_CD = /*itemCd*/'%'
AND LOT_NO = /*lotNo*/'%'

AND LOT_INVENTORY.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND LOT_INVENTORY.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)
AND OPERATION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_OPERATION_MANAGEMENT = OPERATION_NAMES.NAME_CD(+)
AND FRACTION_NAMES.NAME_DIVISION(+) = 'UNIT'
AND UNIT_OF_FRACTION_MANAGEMENT = FRACTION_NAMES.NAME_CD(+)
AND UNIT_OF_OPERATION_MANAGEMENT = UNIT_DIVISION(+)
AND VENDER_DIVISION(+) = ' '
AND VENDER_CD(+) = ' '
