/*
 * 受払検索(ポップアップ)
 * entityName=BuyingInoutSearchList
 * packageName=buyinginout
 * methodName=getSearchList
 *
 */
SELECT
	INOUT_RECORD.INOUT_NO
,	INOUT_RECORD.LOT_NO
,	(CASE WHEN ITEM.TYPE_DIVISION = 1
		THEN
			(CASE WHEN ITEM.KG_OF_FRACTION_MANAGEMENT IS NULL OR ITEM.KG_OF_FRACTION_MANAGEMENT = 0
				THEN
					INOUT_RECORD.INOUT_QTY / 1
				ELSE 
					INOUT_RECORD.INOUT_QTY / ITEM.KG_OF_FRACTION_MANAGEMENT
			END)
		ELSE
			INOUT_RECORD.INOUT_QTY
	END) AS INOUT_QTY
,	(CASE WHEN
		ITEM.TYPE_DIVISION = 1
		THEN 
			INOUT_RECORD.INOUT_QTY
		ELSE
			(CASE WHEN ITEM.KG_OF_FRACTION_MANAGEMENT IS NULL OR ITEM.KG_OF_FRACTION_MANAGEMENT = 0
				THEN
					INOUT_RECORD.INOUT_QTY * 1
				ELSE 
					INOUT_RECORD.INOUT_QTY * ITEM.KG_OF_FRACTION_MANAGEMENT
			END)
	END) AS INOUT_WEIGHT
,	TO_CHAR(INOUT_RECORD.INOUT_DATE,'YYYY/MM/DD') AS INOUT_DATE
,	REASON.RY_DESCRIPTION RY_NAME
,	LOGIN.TANTO_NM AS INPUTOR_NAME
FROM
	INOUT_RECORD
,	LOGIN
,	REASON
,	ITEM
WHERE
	INOUT_RECORD.INOUT_DIVISION = 10
AND	INOUT_RECORD.ODER_NO IS NULL
AND	(INOUT_RECORD.RY_CD BETWEEN 900 AND 998)
AND	INOUT_RECORD.INPUTOR_CD = LOGIN.TANTO_CD(+)
AND	INOUT_RECORD.RY_CD = REASON.RY_CD(+)
AND	INOUT_RECORD.ITEM_CD = /*condition.srhItemCd*/'07000367'
AND	INOUT_RECORD.ITEM_CD = ITEM.ITEM_CD
ORDER BY INOUT_RECORD.INOUT_DATE DESC,INOUT_RECORD.LOT_NO ASC
