/*
 * 工程帳票用SQL
 *
 * entityName=OperationListForReport
 * packageName=operationlistforreport
 * methodName=getListForReport
 *
 */

SELECT OPERATION.*

, CASE
	WHEN OPERATION.RECIPE_USE = 3 THEN '製造'
	WHEN OPERATION.RECIPE_USE = 4 THEN '包装'
	ELSE ''
END RECIPE_USE_NAME

, OPERATION_GROUP.OPERATION_GROUP_NAME
, INPUTOR.TANTO_NM INPUTOR_NAME
, UPDATOR.TANTO_NM UPDATOR_NAME

FROM OPERATION
, OPERATION_GROUP
, LOGIN INPUTOR
, LOGIN UPDATOR

WHERE OPERATION.OPERATION_CD IS NOT NULL

/*IF (condition.srhOperationCd != null) && (condition.srhOperationCd != "")*/
AND (OPERATION.OPERATION_CD LIKE /*condition.srhOperationCd*/'%' OR OPERATION.OPERATION_NAME LIKE /*condition.srhOperationCd*/'%')
/*END*/

AND OPERATION.OPERATION_GROUP_CD = OPERATION_GROUP.OPERATION_GROUP_CD(+)
AND OPERATION.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND OPERATION.UPDATOR_CD = UPDATOR.TANTO_CD(+)

ORDER BY OPERATION.OPERATION_CD


