/*
 * 関連情報基本処方一覧用SQL
 *
 * entityName=ItemRelatedMgrecipeList
 * packageName=itemrelatedmgrecipelist
 * methodName=getList
 */

SELECT HEADER.RECIPE_ID
, HEADER.RECIPE_CD MGRECIPE_CD
, HEADER.RECIPE_VERSION MGRECIPE_VERSION
, HEADER.ITEM_CD MGRECIPE_ITEM_CD
, HEADER.RECIPE_NAME MGRECIPE_ITEM_NAME
, HEADER.UPDATE_DATE MGRECIPE_UPDATE_DATE

, CASE HEADER.APPROVAL_STATUS
    WHEN 1 THEN '入力中'
    WHEN 2 THEN '承認依頼中'
    WHEN 3 THEN '承認済み'
    ELSE NULL
END MGRECIPE_STATUS_NAME

FROM RECIPE_HEADER HEADER
, VALID_ITEM_QUEUE ITEM_QUEUE

WHERE HEADER.ITEM_CD = /*itemCd*/'%'
AND HEADER.RECIPE_TYPE = 3 --基本処方
AND HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)

UNION

SELECT HEADER.RECIPE_ID
, HEADER.RECIPE_CD MGRECIPE_CD
, HEADER.RECIPE_VERSION MGRECIPE_VERSION
, HEADER.ITEM_CD MGRECIPE_ITEM_CD
, HEADER.RECIPE_NAME MGRECIPE_ITEM_NAME
, HEADER.UPDATE_DATE MGRECIPE_UPDATE_DATE

, CASE HEADER.APPROVAL_STATUS
    WHEN 1 THEN '入力中'
    WHEN 2 THEN '承認依頼中'
    WHEN 3 THEN '承認済み'
    ELSE NULL
END MGRECIPE_STATUS_NAME

FROM RECIPE_HEADER HEADER
, RECIPE_FORMULA FORMULA
, VALID_ITEM_QUEUE ITEM_QUEUE

WHERE FORMULA.ITEM_CD = /*itemCd*/'%'
AND HEADER.RECIPE_TYPE = 3 --基本処方
AND FORMULA.LINE_NO <= 1000 --配合のみ
AND HEADER.RECIPE_ID = FORMULA.RECIPE_ID
AND HEADER.ITEM_CD = ITEM_QUEUE.ITEM_CD(+)

ORDER BY RECIPE_ID
