/*
 * Created on 2009/03/23
 *
 * $copyright$
 *
*/

/**
 * 処方フォーミュラ-詳細検索用SQL
 *
 * @author tosco
 *
 * entityName=GrecipeRecipeFormulaList
 * packageName=grecipe
 * methodName=getEntity
 *
 */
SELECT
	FORMULA.RECIPE_ID
,	FORMULA.STEP_NO
,	FORMULA.LINE_NO
,	FORMULA.SEQ
,	FORMULA.LINE_TYPE
,	FORMULA.ITEM_CD
,	FORMULA.QTY
,	FORMULA.COST
,	FORMULA.COST_UNIT
,	FORMULA.REMARK
,	FORMULA.NOTES
,	FORMULA.TONYU
,	FORMULA.TONYUSOKUDO
,	FORMULA.DATAREAD
,	FORMULA.INPUTOR_CD
,	FORMULA.INPUT_DATE
,	FORMULA.UPDATOR_CD
,	FORMULA.UPDATE_DATE
,   ITEM.ITEM_NAME                    AS ITEM_NAME
,   ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION
,   NAME.NAME01                       AS UNIT_NAME
FROM
    RECIPE_FORMULA FORMULA,
    VALID_ITEM_QUEUE ITEM,
    NAMES NAME
WHERE
	    FORMULA.RECIPE_ID = /*recipeId*/30809
	AND FORMULA.STEP_NO = /*stepNo*/1
	AND FORMULA.LINE_NO = /*lineNo*/1
    AND ITEM.ITEM_CD(+) = FORMULA.ITEM_CD
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
