/*
 * Created on 2009/03/23
 *
 * $copyright$
 *
*/

/**
 * 品目マスタキュー検索用SQL
 *
 * @author tosco
 *
 * entityName=GrecipeItemQueueList
 * packageName=grecipe
 * methodName=getSearchList
 *
 */
SELECT
	ITEM.ITEM_CD AS                          ITEM_CD
,	ITEM.VERSION AS                          VERSION
,	ITEM.ITEM_TYPE AS                        ITEM_TYPE
,	ITEM.ACTIVE_DATE AS                      ACTIVE_DATE
,	ITEM.STATUS AS                           STATUS
,	ITEM.ITEM_NAME AS                        ITEM_NAME
,	ITEM.ITEM_SUB_NAME AS                    ITEM_SUB_NAME
,	ITEM.PRODUCT_DIVISION AS                 PRODUCT_DIVISION
,	ITEM.ARTICLE_DIVISION AS                 ARTICLE_DIVISION
,	ITEM.PURCHASE_DIVISION AS                PURCHASE_DIVISION
,	ITEM.PARENT_ITEM_CD AS                   PARENT_ITEM_CD
,	ITEM.ITEM_CATEGORY AS                    ITEM_CATEGORY
,	ITEM.PHANTOM_DIVISION AS                 PHANTOM_DIVISION
,	ITEM.SPOT_DIVISION AS                    SPOT_DIVISION
,	ITEM.STOCK_DIVISION AS                   STOCK_DIVISION
,	ITEM.BULK_DIVISION AS                    BULK_DIVISION
,	ITEM.DEFAULT_LOCATION AS                 DEFAULT_LOCATION
,	ITEM.COST_DIVISION AS                    COST_DIVISION
,	ITEM.LOT_DIVISION AS                     LOT_DIVISION
,	ITEM.NEW_FLG AS                          NEW_FLG
,	ITEM.RESEARCH_ITEM AS                    RESEARCH_ITEM
,	ITEM.SHIPPER_DIVISION AS                 SHIPPER_DIVISION
,	ITEM.TYPE_DIVISION AS                    TYPE_DIVISION
,	ITEM.OTHER_COMPANY_CD1 AS                OTHER_COMPANY_CD1
,	ITEM.ORDER_LOCATION AS                   ORDER_LOCATION
,	ITEM.STYLE_OF_PACKING AS                 STYLE_OF_PACKING
,	ITEM.NUMBER_OF_INSERTIONS AS             NUMBER_OF_INSERTIONS
,	ITEM.ALL_UP_WEIGHT AS                    ALL_UP_WEIGHT
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT AS     UNIT_OF_OPERATION_MANAGEMENT
,	ITEM.UNIT_OF_STOCK_CONTROL AS            UNIT_OF_STOCK_CONTROL
,	ITEM.KG_OF_FRACTION_MANAGEMENT AS        KG_OF_FRACTION_MANAGEMENT
,	ITEM.UNIT_OF_FRACTION_MANAGEMENT AS      UNIT_OF_FRACTION_MANAGEMENT
,	ITEM.KG_CONVERSION_COEFFICIENT AS        KG_CONVERSION_COEFFICIENT
,	ITEM.WATER_DIVISION AS                   WATER_DIVISION
,	ITEM.INPUT_DATE AS                       INPUT_DATE
,	ITEM.INPUTOR_CD AS                       INPUTOR_CD
,	ITEM.UPDATE_DATE AS                      UPDATE_DATE
,	ITEM.UPDATOR_CD AS                       UPDATOR_CD
,	ITEM.DEVELOPMENT_REQUEST_NO AS           DEVELOPMENT_REQUEST_NO
FROM
	VALID_ITEM_QUEUE ITEM

WHERE
	ITEM.ITEM_CD IS NOT NULL
	
/*IF (( itemCd != null ) && ( itemCd != "" ))*/
	AND ITEM.ITEM_CD = /*itemCd*/'%'
/*END*/

ORDER BY ITEM.ITEM_CD
