/*
 * Created on 2009/03/23
 *
 * $copyright$
 *
*/

/**
 * 配合詳細のヘッダーデータを主キーで処方ヘッダから取得用SQL
 *
 * @author tosco
 *
 * entityName=GrecipeRecipeHeaderList
 * packageName=grecipe
 * methodName=getFormulaHeader
 *
 */
SELECT
	 RHEAD.RECIPE_ID AS            RECIPE_ID
	,RHEAD.RECIPE_CD AS            RECIPE_CD
	,RHEAD.RECIPE_VERSION AS       RECIPE_VERSION
	,RHEAD.RECIPE_TYPE AS          RECIPE_TYPE
	,RHEAD.RECIPE_DESCRIPTION AS   RECIPE_DESCRIPTION
	,RHEAD.RECIPE_MEMO AS          RECIPE_MEMO
	,RHEAD.RECIPE_STATUS AS        RECIPE_STATUS
	,RHEAD.RECIPE_USE AS           RECIPE_USE
	,RHEAD.RECIPE_PRIORITY AS      RECIPE_PRIORITY
	,RHEAD.ORIGINAL_RECIPE_ID AS   ORIGINAL_RECIPE_ID
	,RHEAD.PRODUCTION_LINE AS      PRODUCTION_LINE
	,RHEAD.ITEM_CD AS              ITEM_CD
	,RHEAD.MIN_QTY AS              MIN_QTY
	,RHEAD.MAX_QTY AS              MAX_QTY
	,RHEAD.STD_QTY AS              STD_QTY
	,RHEAD.UNIT_QTY AS             UNIT_QTY
	,RHEAD.COST AS                 COST
	,RHEAD.PROCESS_LOSS AS         PROCESS_LOSS
	,RHEAD.START_DATE AS           START_DATE
	,RHEAD.END_DATE AS             END_DATE
	,RHEAD.DELETE_FLAG AS          DELETE_FLAG
	,RHEAD.PRINT_FLAG AS           PRINT_FLAG
	,RHEAD.PRINT_DATE AS           PRINT_DATE
	,RHEAD.PRINT_TANTO_CD AS       PRINT_TANTO_CD
	,RHEAD.APPROVAL_STATUS AS      APPROVAL_STATUS
	,RHEAD.APP_TANTO_CD AS         APP_TANTO_CD
	,RHEAD.APP_DATE AS             APP_DATE
	,RHEAD.LAST_APP_TANTO_CD AS    LAST_APP_TANTO_CD
	,RHEAD.LAST_APP_DATE AS        LAST_APP_DATE
	,RHEAD.RECIPE_NAME AS          RECIPE_NAME
	,RHEAD.INPUTOR_CD AS           INPUTOR_CD
	,RHEAD.INPUT_DATE AS           INPUT_DATE
	,RHEAD.UPDATOR_CD AS           UPDATOR_CD
	,RHEAD.UPDATE_DATE AS          UPDATE_DATE
    ,ITEM.ITEM_NAME AS             ITEM_NAME            -- 品目名称
    ,ITEM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIVISION -- 単位区分
    ,PROC.OPERATION_CD AS          OPERATION_CD         -- 工程コード
    ,OPE.OPERATION_NAME AS         OPERATION_NAME       -- 工程名称
    ,FORMULA.QTY AS                SUM_QTY              -- 配合量計
    ,ITEM.STYLE_OF_PACKING AS      STYLE_OF_PACKING     -- 荷姿
    ,NAME.NAME01 AS                UNIT_NAME            -- 単位

    ,CASE APPROVAL_STATUS
    	WHEN 1 THEN '入力中'
    	WHEN 2 THEN '承認依頼中'
    	WHEN 3 THEN '承認済み'
    	ELSE NULL
    END APPROVAL_STATUS_NAME
FROM
    (
        SELECT
             RECIPE_ID AS RECIPE_ID
            ,STEP_NO AS STEP_NO
            ,SUM(QTY) AS QTY
        FROM
            RECIPE_FORMULA
        WHERE
                RECIPE_ID = /*recipeId*/30809
            AND STEP_NO = /*stepNo*/1
            AND LINE_TYPE = -1
        GROUP BY
            RECIPE_ID
           ,STEP_NO
    ) FORMULA,
    VALID_ITEM_QUEUE ITEM,
    NAMES NAME,
    OPERATION OPE,
    RECIPE_PROCEDURE PROC,
    RECIPE_HEADER RHEAD
WHERE
        RHEAD.RECIPE_ID = /*recipeId*/30809
    AND RHEAD.RECIPE_TYPE = '1'        			--1:原処方
    AND ITEM.ITEM_CD(+) = RHEAD.ITEM_CD
    AND PROC.RECIPE_ID(+) = RHEAD.RECIPE_ID
    AND PROC.STEP_NO(+) = /*stepNo*/1
    AND OPE.OPERATION_CD(+) = PROC.OPERATION_CD
    AND FORMULA.RECIPE_ID(+) = RHEAD.RECIPE_ID
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT
