/*
 * Created on 2009/01/22
 *
 * $copyright$
 *
*/

/**
 * 処方検査詳細用SQL
 *
 * @author tosco
 *
 * entityName=GrecipeRecipeInspectionListDao
 * packageName=grecipe
 * methodName=findByRecipeId
 *
 */
SELECT
	RECIPE_INSPECTION.RECIPE_ID
,	RECIPE_INSPECTION.STEP_NO
,	RECIPE_INSPECTION.LINE_NO
,	RECIPE_INSPECTION.SEQ
,	RECIPE_INSPECTION.INSPECTION_CD
,	RECIPE_INSPECTION.DIVISION
,	RECIPE_INSPECTION.VALUE_TYPE
,	RECIPE_INSPECTION.VALUE1
,	RECIPE_INSPECTION.VALUE2
,	RECIPE_INSPECTION.CONDITION
,	RECIPE_INSPECTION.REMARK
,	RECIPE_INSPECTION.NOTES
,	RECIPE_INSPECTION.INPUTOR_CD
,	RECIPE_INSPECTION.INPUT_DATE
,	RECIPE_INSPECTION.UPDATOR_CD
,	RECIPE_INSPECTION.UPDATE_DATE
,	NAMES.NAME01 AS INSPECTION_NAME
FROM
	RECIPE_INSPECTION
,	NAMES
WHERE
	RECIPE_INSPECTION.RECIPE_ID IS NOT NULL
/*IF (( recipeId != null ) && ( recipeId != "" ))*/
	AND	RECIPE_INSPECTION.RECIPE_ID = /*recipeId*/
/*END*/

/*IF (( stepNo != null ) && ( stepNo != "" ))*/
	AND	RECIPE_INSPECTION.STEP_NO = /*stepNo*/
/*END*/

/*IF (( lineNo != null ) && ( lineNo != "" ))*/
	AND	RECIPE_INSPECTION.LINE_NO = /*lineNo*/
/*END*/
AND NAMES.NAME_DIVISION(+) = 'STDV'
AND RECIPE_INSPECTION.INSPECTION_CD = NAMES.NAME_CD(+)

ORDER BY
	 RECIPE_INSPECTION.RECIPE_ID
	,RECIPE_INSPECTION.STEP_NO
	,RECIPE_INSPECTION.LINE_NO
