/*
 * 棚卸入力一覧用SQL
 *
 * entityName=InquiryInputList
 * packageName=inquiryinputlist
 * methodName=getList
 *
 */

SELECT COUNT_DATE, INVENTORY_COUNT.COUNT_DIVISION, NAME01, SUBSTRB(NAME01, 0, 14) SHORT_NAME01, COUNT_LOCATION, INVENTORY_COUNT.ITEM_CD, ITEM_NAME, SUBSTRB(ITEM_NAME, 0, 10) SHORT_ITEM_NAME, LOT_NO, ALIAS_LOT_NO, NVL(COUNT_QTY, 0) COUNT_QTY, NVL(FRACTION_QTY, 0) FRACTION_QTY, NVL(DECODE(INPUT_QTY, NULL, COUNT_QTY, INPUT_QTY), 0) INPUT_QTY, NVL(DECODE(INPUTFRACTION, NULL, FRACTION_QTY, INPUTFRACTION), 0) INPUTFRACTION, INVENTORY_COUNT.UPDATE_DATE, UNIT_OF_OPERATION_MANAGEMENT, UNIT_OF_FRACTION_MANAGEMENT
FROM INVENTORY_COUNT, NAMES, LOCATION, ITEM,

(SELECT ITEM_CD, MAX(VERSION) VERSION
FROM ITEM
GROUP BY ITEM_CD) MAX_ITEM

WHERE COUNT_DATE = /*condition.srhCountDate*/'2008/12/07'

AND (COUNT_LOCATION LIKE /*condition.srhLocationCd*/'%' OR LOCATION_NAME LIKE /*condition.srhLocationCd*/'%')

/*IF(condition.srhCountDivision != null) && (condition.srhCountDivision != "")*/
AND INVENTORY_COUNT.COUNT_DIVISION = /*condition.srhCountDivision*/'%'
/*END*/

/*IF(condition.srhItemCd != null) && (condition.srhItemCd != "")*/
AND (INVENTORY_COUNT.ITEM_CD LIKE /*condition.srhItemCd*/'%' OR ITEM_NAME LIKE /*condition.srhItemCd*/'%')
/*END*/

/*IF(condition.srhOtherCompanyCd1 != null) && (condition.srhOtherCompanyCd1 != "")*/
AND OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/'%'
/*END*/

/*IF(condition.srhAliasLotNo != null) && (condition.srhAliasLotNo != "")*/
AND ALIAS_LOT_NO LIKE /*condition.srhAliasLotNo*/'%'
/*END*/

AND NAME_DIVISION(+) = 'TANA'
AND INVENTORY_COUNT.COUNT_DIVISION = NAME_CD(+)
AND INVENTORY_COUNT.COUNT_DIVISION = LOCATION.COUNT_DIVISION
AND COUNT_LOCATION = LOCATION_CD(+)
AND INVENTORY_COUNT.ITEM_CD = MAX_ITEM.ITEM_CD(+)
AND MAX_ITEM.ITEM_CD = ITEM.ITEM_CD(+)
AND MAX_ITEM.VERSION = ITEM.VERSION(+)

ORDER BY INVENTORY_COUNT.COUNT_DIVISION, COUNT_LOCATION, INVENTORY_COUNT.ITEM_CD, ALIAS_LOT_NO


