/**
 * @author tosco
 *
 * entityName=ProductInspectCompHeaderListForReport
 * packageName=productinspectcompforreport
 * methodName=getHeaderReportList
 *
 */
SELECT	

	HEAD.DIRECTION_DIVISION
,	HEAD.DIRECTION_NO
,	HEAD.DIRECTION_DATE
,	HEAD.ASP_ORDER_NO
,	HEAD.DIRECTION_STATUS
,	CASE HEAD.DIRECTION_STATUS
		WHEN 1 THEN '未確定'
		WHEN 2 THEN '指図書発行済'
		WHEN 3 THEN '包装実績入力'
		WHEN 4 THEN '包装記録出力済'
		WHEN 5 THEN '検査待ち在庫計上'
		WHEN 6 THEN '製品検査入力済'
		WHEN 7 THEN '完了'
	END AS DIRECTION_STATUS_NAME
,	HEAD.RECIPE_ID
,	HEAD.RECIPE_CD
,	HEAD.RECIPE_VERSION
,	HEAD.PRODUCTION_LINE
,	LINE.PRODUCTION_LINE_NAME
,	HEAD.COMPOUND_TANK_NO
,	COMPOUND_TANK.RESOUCE_NAME AS COMPOUND_TANK_NAME
,	HEAD.HOLD_TANK_NO
,	HOLD_TANK.RESOUCE_NAME AS HOLD_TANK_NAME
,	HEAD.DISSOLUTION_TANK_NO
,	DISSOLUTION_TANK.RESOUCE_NAME AS DISSOLUTION_TANK_NAME
,	HEAD.FILLTANK_NO
,	FILLTANK.RESOUCE_NAME AS FILLTANK_NAME
,	HEAD.PACKAGE_LINE
,	PACKAGE_LINE.RESOUCE_NAME AS PACKAGE_LINE_NAME
,	HEAD.CURRENT_STEP_NO
,	HEAD.ITEM_CD
,	ITEM_NAMES.ITEM_NAME
,	ITEM_NAMES.STYLE_OF_PACKING
,	UNIT_NAMES.NAME01
,	HEAD.PLANED_QTY
,	HEAD.RESULT_QTY
,	HEAD.DIVIDE_FLAG
,	HEAD.NEXT_PLANED_QTY
,	HEAD.PDW_RESULT
,	HEAD.PEOCESS_LOSS
,	HEAD.LOT_NO
,	HEAD.PLANED_SDATE
,	HEAD.PLANED_EDATE
,	HEAD.RESULT_SDATE
,	HEAD.RESULT_EDATE
,	HEAD.STERIT_SDATE
,	HEAD.STERIT_EDATE
,	HEAD.MEKKIN_TANK_TEMP_MIN
,	HEAD.MEKKIN_TANK_TEMP_MAX
,	HEAD.HAISUI_CHECK
,	HEAD.STAMP_FLAG
,	HEAD.STAMP_DATE
,	HEAD.STAMP_TANTO_CD
,	STAMP_TANTO.TANTO_NM AS STAMP_TANTO_NAME
,	HEAD.PRODUCT_LABEL_FLAG
,	HEAD.PRODUCT_LABEL_DATE
,	HEAD.PRODUCT_LABEL_TANTO_CD
,	PRODUCT_LABEL.TANTO_NM AS PRODUCT_LABEL_TANTO_NAME
,	HEAD.PRODUCT_RECORD_FLAG
,	HEAD.PRODUCT_RECORD_DATE
,	HEAD.PRODUCT_RECORD_TANTO_CD
,	PRODUCT_RECORD.TANTO_NM AS PRODUCT_RECORD_TANTO_NAME
,	HEAD.STOCKDISS_LABEL_FLAG
,	HEAD.STOCKDISS_LABEL_DATE
,	HEAD.STOCKDISS_LABEL_TANTO_CD
,	STOCKDISS_LABEL.TANTO_NM AS STOCKDISS_LABEL_TANTO_NAME
,	HEAD.CERTIFICATION_FLAG
,	HEAD.CERTIFICATION_DATE
,	HEAD.REMARK
,	HEAD.NOTES
,	HEAD.DELETE_FLAG
,	HEAD.SEIZOTANTOCODE
,	SEIZOTANTO.TANTO_NM AS SEIZOTANTO_NAME
,	HEAD.SENJOTANTOCODE
,	SENJOTANTO.TANTO_NM AS SENJOTANTO_NAME
,	HEAD.MEKKINTANTOCODE
,	MEKKINTANTO.TANTO_NM AS MEKKINTANTO_NAME
,	HEAD.CHOGOTANKCONDI
,	HEAD.YOBIYOKAICONDI
,	HEAD.HOLDTANKCONDI
,	HEAD.TOTAL_JOBTIME
,	HEAD.ENPLOY_JOBTIME
,	HEAD.COOPER_JOBTIME
,	HEAD.APP_TANTO_CD
,	APP.TANTO_NM AS APP_TANTO_NAME
,	HEAD.APP_DATE
,	HEAD.LAST_APP_TANTO_CD
,	LAST_APP.TANTO_NM AS LAST_APP_TANTO_NAME
,	HEAD.LAST_APP_DATE
,	HEAD.INPUT_DATE
,	HEAD.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	HEAD.UPDATE_DATE
,	HEAD.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME
,	LOT_INVENTORY.LOT_INVENTORY_QTY

FROM	DIRECTION_HEADER HEAD
,	(SELECT
	    ITEM2.ITEM_CD ,
	    ITEM2.ITEM_NAME,
	    ITEM2.OTHER_COMPANY_CD1,
	    ITEM2.UNIT_OF_OPERATION_MANAGEMENT,
            ITEM2.STYLE_OF_PACKING

	FROM
	    VALID_ITEM_QUEUE MAX_ITEM
	,   VALID_ITEM_QUEUE  ITEM2
	WHERE
	    ITEM2.ITEM_CD = MAX_ITEM.ITEM_CD AND
	    ITEM2.VERSION = MAX_ITEM.VERSION
	) ITEM_NAMES
,	(SELECT	NAMES.NAME_CD
	,	NAMES.NAME01
	FROM	NAMES
	WHERE	NAMES.NAME_DIVISION = 'UNIT'
	)UNIT_NAMES
,	LINE
,	OPERATION
,	RECIPE_RESOUCE
,	(SELECT ITEM_CD,
			LOT_NO, 
			SUM(NVL(INVENTORY_QTY, 0) + NVL(INSPECTION_QTY, 0)) LOT_INVENTORY_QTY
		FROM LOT_INVENTORY
		WHERE LOCATION_CD IS NOT NULL
/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
		AND	LOT_INVENTORY.LOT_NO LIKE /*condition.srhDirectionNo*/''
/*END*/
/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
		AND	LOT_INVENTORY.ITEM_CD LIKE /*condition.srhItemCd*/''
/*END*/
		GROUP BY ITEM_CD, LOT_NO
     ) LOT_INVENTORY

,	LOGIN INPUTOR
,	LOGIN UPDATOR

,	LOGIN STAMP_TANTO
,	LOGIN PRODUCT_LABEL
,	LOGIN PRODUCT_RECORD
,	LOGIN STOCKDISS_LABEL
,	LOGIN APP
,	LOGIN LAST_APP
,	LOGIN SEIZOTANTO
,	LOGIN MEKKINTANTO
,	LOGIN SENJOTANTO
,	RECIPE_RESOUCE COMPOUND_TANK
,	RECIPE_RESOUCE HOLD_TANK
,	RECIPE_RESOUCE DISSOLUTION_TANK
,	RECIPE_RESOUCE FILLTANK
,	RECIPE_RESOUCE PACKAGE_LINE




WHERE	HEAD.DIRECTION_DIVISION IN ('2','3')
AND		HEAD.DIRECTION_STATUS IN('5','6')

AND		HEAD.ITEM_CD = ITEM_NAMES.ITEM_CD(+)
AND		HEAD.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)
AND		HEAD.CURRENT_STEP_NO = OPERATION.OPERATION_CD(+)
AND		ITEM_NAMES.UNIT_OF_OPERATION_MANAGEMENT = UNIT_NAMES.NAME_CD(+)
AND		HEAD.PACKAGE_LINE = RECIPE_RESOUCE.RESOUCE_CD(+)
AND		HEAD.ITEM_CD = LOT_INVENTORY.ITEM_CD(+)
AND		HEAD.DIRECTION_NO = LOT_INVENTORY.LOT_NO(+)

AND	HEAD.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	HEAD.UPDATOR_CD = UPDATOR.TANTO_CD(+)

AND	HEAD.STAMP_TANTO_CD = STAMP_TANTO.TANTO_CD(+)
AND	HEAD.PRODUCT_LABEL_TANTO_CD = PRODUCT_LABEL.TANTO_CD(+)
AND	HEAD.PRODUCT_RECORD_TANTO_CD = PRODUCT_RECORD.TANTO_CD(+)
AND	HEAD.STOCKDISS_LABEL_TANTO_CD = STOCKDISS_LABEL.TANTO_CD(+)
AND	HEAD.APP_TANTO_CD = APP.TANTO_CD(+)
AND	HEAD.LAST_APP_TANTO_CD = LAST_APP.TANTO_CD(+)
AND	HEAD.SEIZOTANTOCODE = SEIZOTANTO.TANTO_CD(+)
AND	HEAD.MEKKINTANTOCODE = MEKKINTANTO.TANTO_CD(+)
AND	HEAD.SENJOTANTOCODE = SENJOTANTO.TANTO_CD(+)
AND	HEAD.COMPOUND_TANK_NO = COMPOUND_TANK.RESOUCE_CD(+)
AND	HEAD.HOLD_TANK_NO = HOLD_TANK.RESOUCE_CD(+)
AND	HEAD.DISSOLUTION_TANK_NO = DISSOLUTION_TANK.RESOUCE_CD(+)
AND	HEAD.FILLTANK_NO = FILLTANK.RESOUCE_CD(+)
AND	HEAD.PACKAGE_LINE = PACKAGE_LINE.RESOUCE_CD(+)

/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
	AND	HEAD.DIRECTION_NO LIKE /*condition.srhDirectionNo*/''
/*END*/

/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	/*IF (condition.srhProductionLine != "0")*/
			AND	HEAD.PRODUCTION_LINE = /*condition.srhProductionLine*/''
	/*END*/		
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	HEAD.ITEM_CD LIKE /*condition.srhItemCd*/''
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*condition.srhOtherCompanyCd1*/''
/*END*/

/*IF (( condition.srhResultSdateFrom != null ) && ( condition.srhResultSdateFrom != "" ))*/
	AND	HEAD.RESULT_SDATE >= /*condition.srhResultSdateFrom*/''
/*END*/

/*IF (( condition.srhResultSdateTo != null ) && ( condition.srhResultSdateTo != "" ))*/
	AND	HEAD.RESULT_SDATE <= /*condition.srhResultSdateTo*/''
/*END*/

/*IF (( condition.srhResultEdateFrom != null ) && ( condition.srhResultEdateFrom != "" ))*/
	AND	HEAD.RESULT_EDATE >= /*condition.srhResultEdateFrom*/''
/*END*/

/*IF (( condition.srhResultEdateTo != null ) && ( condition.srhResultEdateTo != "" ))*/
	AND	HEAD.RESULT_EDATE <= /*condition.srhResultEdateTo*/''
/*END*/

/*IF (( condition.srhDirectionStatus != null ) && ( condition.srhDirectionStatus != "" ))*/
	/*IF (condition.srhDirectionStatus == "0")*/
			AND	HEAD.DIRECTION_STATUS IN ('5','6')
	/*END*/
	/*IF (condition.srhDirectionStatus != "0")*/
			AND	HEAD.DIRECTION_STATUS = /*condition.srhDirectionStatus*/''
	/*END*/		
/*END*/

/*IF (( condition.srhPackageLine != null ) && ( condition.srhPackageLine != "" ))*/
	AND	HEAD.PACKAGE_LINE LIKE /*condition.srhPackageLine*/''
/*END*/

/*IF (( condition.srhCertificationDate != null ) && ( condition.srhCertificationDate != "" ))*/
	AND	TO_CHAR(HEAD.CERTIFICATION_DATE,'YYYY/MM/DD') = /*condition.srhCertificationDate*/''
/*END*/

/*IF (( condition.srhLotNo != null ) && ( condition.srhLotNo != "" ))*/
	AND	HEAD.LOT_NO LIKE /*condition.srhLotNo*/''
/*END*/

ORDER BY	HEAD.RESULT_SDATE
,			HEAD.DIRECTION_NO


