/**
 * @author t1344224
 *
 * entityName=BeforehandMeltLblFormulaListForReport
 * packageName=beforehandmeltlblforreport
 * methodName=getFormulaReportList
 *
 */
SELECT	
	FORMULA.DIRECTION_DIVISION
,	FORMULA.DIRECTION_NO
,	FORMULA.STEP_NO
,	FORMULA.LINE_NO
,	FORMULA.SEQ
,	FORMULA.LINE_TYPE
,	FORMULA.ITEM_CD
,	ITEM_FORMULA.ITEM_NAME
,	NAME_FORMULA.NAME01
,	FORMULA.TONYU
,	FORMULA.DATAREAD
,	FORMULA.TONYUSOKUDO
,	FORMULA.QTY
,	FORMULA.STOCKPD_QTY
,	FORMULA.RESULT_QTY
,	FORMULA.SAMPLE_QTY
,	FORMULA.LOSS_QTY
,	FORMULA.DEFECT_QTY
,	FORMULA.ADJUST_QTY
,	FORMULA.COST
,	FORMULA.STEP_CONDITION
,	FORMULA.NOTES
,	FORMULA.LOCATION_CD
,	FIRST_LOCATION.LOCATION_NAME AS FIRST_LOCATION_NAME
,	FORMULA.NEXT_LOCATION_CD
,	SECOND_LOCATION.LOCATION_NAME AS SECOND_LOCATION_NAME
,	FORMULA.NEXT_AFTER_LOCATION_CD
,	THIRD_LOCATION.LOCATION_NAME AS THIRD_LOCATION_NAME
,	FORMULA.LOT_NO
,	FORMULA.MANUFACTURER_LOT_NO
,	FORMULA.FILL_QTY
,	FORMULA.FILL_RESULT_QTY
,	FORMULA.REMARK
,	FORMULA.INPUT_DATE
,	FORMULA.INPUTOR_CD
,	INPUTOR.TANTO_NM AS INPUTOR_NAME
,	FORMULA.UPDATE_DATE
,	FORMULA.UPDATOR_CD
,	UPDATOR.TANTO_NM AS UPDATOR_NAME

FROM	DIRECTION_HEADER
,	(SELECT
	    ITEM2.ITEM_CD ,
	    ITEM2.ITEM_NAME,
	    OTHER_COMPANY_CD1
	FROM
		VALID_ITEM_QUEUE ITEM2
	) ITEM_NAMES
,	LINE
,	(SELECT	DIRECTION_PROCEDURE.DIRECTION_DIVISION
	,	DIRECTION_PROCEDURE.DIRECTION_NO
	,	COUNT(*) as MAIN_STREAM_COUNT
	FROM	DIRECTION_PROCEDURE
	
	WHERE	TO_NUMBER(DIRECTION_PROCEDURE.OPERATION_CD) >= 31
	AND	TO_NUMBER(DIRECTION_PROCEDURE.OPERATION_CD) <= 36
	
	GROUP BY	DIRECTION_PROCEDURE.DIRECTION_DIVISION
	,		DIRECTION_PROCEDURE.DIRECTION_NO
	)DIRECTION_PROCEDURE_COUNT
,	LOGIN INPUTOR
,	LOGIN UPDATOR
,	LOCATION FIRST_LOCATION
,	LOCATION SECOND_LOCATION
,	LOCATION THIRD_LOCATION
,	DIRECTION_FORMULA FORMULA
,	ITEM ITEM_FORMULA
,	NAMES NAME_FORMULA

WHERE	DIRECTION_HEADER.DIRECTION_DIVISION = '1'
AND		FORMULA.DIRECTION_NO = DIRECTION_HEADER.DIRECTION_NO
AND		DIRECTION_HEADER.DIRECTION_STATUS in( '2','3')

AND		DIRECTION_HEADER.ITEM_CD = ITEM_NAMES.ITEM_CD(+)

AND		DIRECTION_HEADER.PRODUCTION_LINE = LINE.PRODUCTION_LINE(+)

AND		DIRECTION_HEADER.DIRECTION_DIVISION = DIRECTION_PROCEDURE_COUNT.DIRECTION_DIVISION(+)
AND		DIRECTION_HEADER.DIRECTION_NO = DIRECTION_PROCEDURE_COUNT.DIRECTION_NO(+)
AND		DIRECTION_PROCEDURE_COUNT.MAIN_STREAM_COUNT >= 1

AND	FORMULA.INPUTOR_CD = INPUTOR.TANTO_CD(+)
AND 	FORMULA.UPDATOR_CD = UPDATOR.TANTO_CD(+)
AND	FORMULA.ITEM_CD = ITEM_FORMULA.ITEM_CD(+)
AND	NAME_FORMULA.NAME_DIVISION(+) = 'UNIT'
AND	NAME_FORMULA.NAME_CD(+) = ITEM_FORMULA.UNIT_OF_OPERATION_MANAGEMENT
AND	FORMULA.LOCATION_CD = FIRST_LOCATION.LOCATION_CD(+)
AND	FORMULA.NEXT_LOCATION_CD = SECOND_LOCATION.LOCATION_CD(+)
AND	FORMULA.NEXT_AFTER_LOCATION_CD = THIRD_LOCATION.LOCATION_CD(+)

/*IF (( condition.srhDirectionNo != null ) && ( condition.srhDirectionNo != "" ))*/
	AND	DIRECTION_HEADER.DIRECTION_NO LIKE /*condition.srhDirectionNo*/'%'
/*END*/

/*IF (( condition.srhProductionLine != null ) && ( condition.srhProductionLine != "" ))*/
	AND	DIRECTION_HEADER.PRODUCTION_LINE = /*condition.srhProductionLine*/'%'
/*END*/

/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
	AND	DIRECTION_HEADER.ITEM_CD LIKE /*condition.srhItemCd*/'%'
/*END*/

/*IF (( condition.srhOtherCompanyCd1 != null ) && ( condition.srhOtherCompanyCd1 != "" ))*/
	AND	ITEM_NAMES.OTHER_COMPANY_CD1 LIKE /*conditi��on.srhOtherCompanyCd1*/'%'
/*END*/

/*IF (( condition.srhPlanedSdateFrom != null ) && ( condition.srhPlanedSdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE >= /*condition.srhPlanedSdateFrom*/'2009/01/01'
/*END*/

/*IF (( condition.srhPlanedSdateTo != null ) && ( condition.srhPlanedSdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_SDATE <= /*condition.srhPlanedSdateTo*/'2009/12/31'
/*END*/

/*IF (( condition.srhPlanedEdateFrom != null ) && ( condition.srhPlanedEdateFrom != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE >= /*condition.srhPlanedEdateFrom*/'2009/01/01'
/*END*/

/*IF (( condition.srhPlanedEdateTo != null ) && ( condition.srhPlanedEdateTo != "" ))*/
	AND	DIRECTION_HEADER.PLANED_EDATE <= /*condition.srhPlanedEdateTo*/'2009/12/31'
/*END*/

ORDER BY	DIRECTION_HEADER.PLANED_SDATE
,		DIRECTION_HEADER.DIRECTION_NO
,		DIRECTION_HEADER.ITEM_CD
,		FORMULA.STEP_NO
,		FORMULA.LINE_NO
