/*
 * Created on 2009/01/13
 *
 * $copyright$
 *
*/

/**
 * 発注書一覧用SQL
 *
 * @author tosco
 *
 * entityName=PurchaseOrderList
 * packageName=purchaseorder
 * methodName=getSearchList
 *
 */
SELECT	PSUB.PURCHASE_NO
,	PSUB.BUY_SUBCONTRACT_ORDER_NO
,	PSUB.ORDER_DIVIDE_NO
,	PSUB.ORDER_NO
,	PSUB.ORDER_ROW_NO
,	PSUB.ASP_ORDER_NO
,	PSUB.MATERIAL_DIVISION
,	PSUB.SI_ORDER_NO
,	PSUB.ORDER_DATE
,	PSUB.CHARGE_ORGANIZATION_CD
,	PSUB.ORGANIZATION_CD
,	PSUB.TANTO_CD
,	PSUB.ORDER_DIVISION
,	PSUB.VENDER_CD
,	PSUB.ITEM_CD
,	DECODE(PSUB.ORDER_DIVISION, 4, PSUB.ITEM_NAME, ITM.ITEM_NAME) AS ITM_NAME	-- 品目名称
,	PSUB.ORDER_QUANTITY
,	PSUB.ORDER_CONVERT_QUANTITY
,	PSUB.ORDER_UNITPRICE
,	PSUB.UNITPRICE_DEFINEUNIT
,	PSUB.SUPPLIER_ORD_AMOUNT
,	PSUB.SUGGESTED_DELIVERLIMIT_DATE
,	PSUB.ORDER_SHEET_REMARK
,	PSUB.REMARK
,	PSUB.NOTES
,	PSUB.LOCATION_CD
,	PSUB.STATUS
,	PSUB.ORDER_SHEET_NO
,	PSUB.ORDER_SHEE_FLAG
,	PSUB.ORDER_SHEE_DATE
,	PSUB.ORDER_SHEEL_TANTO_CD
,	PSUB.GOOD_HOUSING_SUM
,	PSUB.REPLY_CONTENTS_DIVISION
,	PSUB.DELIVERY_COMP
,	PSUB.NEXT_DELIVERLIMIT_DATE
,	PSUB.DATA_TYPE
,	PSUB.DATA_TOTAL_DIVISION
,	PSUB.CATEGORY_DIVISION
,	PSUB.STOCKING_DATE
,	PSUB.ACCOUNT_YEARS
,	PSUB.SLIP_NO
,	PSUB.ROW_NO
,	PSUB.CANCEL_SLIP_NO
,	PSUB.CANCEL_ROW_NO
,	PSUB.SUPPLIER_LOTNO
,	PSUB.LOT_NO
,	PSUB.STOCK_LOCATION_CD
,	PSUB.HOUSING_LOCATION_CD
,	PSUB.ARRIVAL_QUANTITY
,	PSUB.STOCK_QUANTITY
,	PSUB.ACCEPT_QUANTITY
,	PSUB.ACCEPT_CONVERT_QUANTITY
,	PSUB.INCREASE_QUANTITY
,	PSUB.STOCKING_QUANTITY
,	PSUB.HOUSING_UNITPRICE
,	PSUB.FARE_AMOUNT
,	PSUB.STOCKING_AMOUNT
,	PSUB.ACCEPT_DATE
,	PSUB.ORDER_SHEET_REMARK2
,	PSUB.REMARK2
,	PSUB.NOTES2
,	PSUB.STATUS2
,	PSUB.TAX_DIVISION
,	PSUB.TAX_AMOUNT
,	PSUB.PAYEE_CD
,	PSUB.ACCOUNT_DEBIT_SECTION_CD
,	PSUB.ACCOUNT_CREDIT_SECTION_CD
,	PSUB.DEBIT_TITLE_CD
,	PSUB.DEBIT_SUB_TITLE_CD
,	PSUB.CREDIT_TITLE_CD
,	PSUB.CREDIT_SUB_TITLE_CD
,	PSUB.PAYABLE_TARGET_DIVISION
,	PSUB.PAYMENT_TARGET_DIVISION
,	PSUB.PAYABLE_UPDATE_DIVISION
,	PSUB.PAYABLE_NO
,	PSUB.PAYMENT_UPDATE_DIVISION
,	PSUB.PAYMENT_NO
,	PSUB.SUMMARY_CD
,	PSUB.SUMMARY
,	PSUB.PAYMENT_UPDATE_DATE
,	PSUB.PAYABLE_UPDATE_DATE
,	PSUB.TRANSMISSION_DATE
,	PSUB.LABEL_FLAG
,	PSUB.LABEL_DATE
,	PSUB.LABEL_TANTO_CD
,	PSUB.TMP_UNITPRICE_FLG
,	PSUB.INSPECT_METHOD
,	PSUB.MORTGAGE_DETAIL_FLG
,	PSUB.INSPRECEIPT_WAIT_QUANTITY
,	PSUB.BAD_QUANTITY
,	PSUB.COST_ENTRY
,	PSUB.ADV_PUR_NOTICE_DECIDE_DIVISION
,	PSUB.ORDER_MORTGAGED_QUANTITY
,	PSUB.SUM_HOUSING_CONVERT_QUANT
,	PSUB.INSPECT_WAIT_CONVERT_QUANTITY
,	PSUB.EXTRACTIONS_QUANTITY
,	PSUB.DEFECTIVE_QUANTITY
,	PSUB.CHECK_TANTO_CD
,	PSUB.LABORATORY_METHOD
,	PSUB.PROVISION_DIVISION
,	PSUB.CHECK_DATE
,	PSUB.TAX_RATIO
,	PSUB.CHECK_QUANTITY
,	PSUB.SLIP_ISSUE_DIVISION
,	PSUB.SLIP_ISSUE_DATE
,	PSUB.APPROVAL_STATUS
,	PSUB.APPROVEDBY
,	PSUB.APPROVALDATE
,	PSUB.INPUT_DATE
,	PSUB.INPUTOR_CD
,	PSUB.UPDATE_DATE
,	PSUB.UPDATOR_CD
,	VEN.VENDER_SHORTED_NAME AS SUPPLIER_NAME
,	NAME.NAME01 AS ORDER_UNIT
,	ITM.STYLE_OF_PACKING AS LOAD_FORM
,	ITM.UNIT_OF_OPERATION_MANAGEMENT AS UNIT_DIV
,	(CASE								--納入先名称、オーダー区分により名称取得先を変える
		WHEN PSUB.ORDER_DIVISION IN (1, 2, 3, 6) THEN LOC.LOCATION_NAME
		WHEN PSUB.ORDER_DIVISION IN (4, 5) THEN DEL.SEARCH_KANA
		ELSE NULL
	END ) AS DELIVERY_NAME
,	DECODE
	(
		ITM.ORDER_LOCATION, null, PSUB.LOCATION_CD, ITM.ORDER_LOCATION
	) LOCATION
,	ORDER_H.DELIVERY_CD
FROM
	VENDER VEN
    ,VALID_ITEM_QUEUE MAX_ITEM
	,VALID_ITEM_QUEUE ITM
	,DELIVERY DEL
	,LOCATION LOC
	,NAMES NAME
	,PURCHASE_SUBCONTRACT PSUB
	,ORDER_HEAD ORDER_H
WHERE
		VEN.VENDER_DIVISION(+) = 'SI'
	AND VEN.VENDER_CD(+) = PSUB.VENDER_CD
    AND MAX_ITEM.ITEM_CD(+) = PSUB.ITEM_CD
    AND ITM.ITEM_CD(+) = MAX_ITEM.ITEM_CD
    AND ITM.VERSION(+) = MAX_ITEM.VERSION
    AND NAME.NAME_DIVISION(+) = 'UNIT'
    AND NAME.NAME_CD(+) = ITM.UNIT_OF_OPERATION_MANAGEMENT
    AND DEL.DELIVERY_CD(+) = PSUB.LOCATION_CD
    AND LOC.LOCATION_CD(+) = PSUB.LOCATION_CD
    AND PSUB.ORDER_DIVIDE_NO IS NULL
    AND	ORDER_H.ORDER_NO(+) = PSUB.ORDER_NO 
/*IF ( condition.searchType == 2 )*/
    AND PSUB.STATUS = 2
    AND (TO_CHAR(SYSDATE-7,'YYYY/MM/DD') <= PSUB.ORDER_SHEE_DATE AND PSUB.ORDER_SHEE_DATE <= TO_CHAR(SYSDATE+1,'YYYY/MM/DD'))
/*END*/	
/*IF ( condition.searchType != 2 )*/

	/*IF (( condition.srhBuySubcontractOrderNo != null ) && ( condition.srhBuySubcontractOrderNo != "" ))*/
		AND	PSUB.BUY_SUBCONTRACT_ORDER_NO LIKE /*condition.srhBuySubcontractOrderNo*/1
	/*END*/
	/*IF (condition.srhOrderDateFrom != null) && (condition.srhOrderDateFrom != "")*/
	    AND TO_CHAR(PSUB.ORDER_DATE, 'YYYY/MM/DD') >= /*condition.srhOrderDateFrom*/'2001/01/01'
	/*END*/
	/*IF (condition.srhOrderDateTo != null) && (condition.srhOrderDateTo != "")*/
	    AND TO_CHAR(PSUB.ORDER_DATE, 'YYYY/MM/DD') <= /*condition.srhOrderDateTo*/'2010/01/01'
	/*END*/
	/*IF (( condition.srhChargeOrganizationCd != null ) && ( condition.srhChargeOrganizationCd != "" ))*/
		AND	PSUB.CHARGE_ORGANIZATION_CD LIKE /*condition.srhChargeOrganizationCd*/
	/*END*/
	/*IF (( condition.srhOrganizationCd != null ) && ( condition.srhOrganizationCd != "" ))*/
		AND	PSUB.ORGANIZATION_CD LIKE /*condition.srhOrganizationCd*/
	/*END*/
	/*IF (( condition.srhTantoCd != null ) && ( condition.srhTantoCd != "" ))*/
		AND	PSUB.TANTO_CD LIKE /*condition.srhTantoCd*/
	/*END*/
	/*IF (( condition.srhOrderDivision != null ) && ( condition.srhOrderDivision != "" ) && ( condition.srhOrderDivision != "0"))*/
		AND	PSUB.ORDER_DIVISION = /*condition.srhOrderDivision*/
	/*END*/
	/*IF (( condition.srhVenderCd != null ) && ( condition.srhVenderCd != "" ))*/
		AND	PSUB.VENDER_CD LIKE /*condition.srhVenderCd*/
	/*END*/
	/*IF (( condition.srhItemCd != null ) && ( condition.srhItemCd != "" ))*/
		AND	PSUB.ITEM_CD LIKE /*condition.srhItemCd*/
	/*END*/
	/*IF (condition.srhSuggestedDeliverlimitDateFrom != null) && (condition.srhSuggestedDeliverlimitDateFrom != "")*/
	    AND TO_CHAR(PSUB.SUGGESTED_DELIVERLIMIT_DATE, 'YYYY/MM/DD') >= /*condition.srhSuggestedDeliverlimitDateFrom*/'2001/01/01'
	/*END*/
	/*IF (condition.srhSuggestedDeliverlimitDateTo != null) && (condition.srhSuggestedDeliverlimitDateTo != "")*/
	    AND TO_CHAR(PSUB.SUGGESTED_DELIVERLIMIT_DATE, 'YYYY/MM/DD') <= /*condition.srhSuggestedDeliverlimitDateTo*/'2010/01/01'
	/*END*/
	/*IF (( condition.srhLocationCd != null ) && ( condition.srhLocationCd != "" ))*/
		AND	PSUB.LOCATION_CD LIKE /*condition.srhLocationCd*/
	/*END*/
	/*IF (( condition.srhStatus != null ) && ( condition.srhStatus != "" ))*/
		/*IF (condition.srhStatus == "0")*/
				AND	PSUB.STATUS IN ('7','2','3','4')
		/*END*/
		/*IF (condition.srhStatus != "0")*/
				AND	PSUB.STATUS = /*condition.srhStatus*/
		/*END*/		
	/*END*/
	/*IF (( condition.srhOrderSheetNo != null ) && ( condition.srhOrderSheetNo != "" ))*/
		AND	PSUB.ORDER_SHEET_NO LIKE /*condition.srhOrderSheetNo*/
	/*END*/
	/*IF (( condition.srhTashaCd != null ) && ( condition.srhTashaCd != "" ))*/
		AND	ITM.OTHER_COMPANY_CD1 LIKE /*condition.srhTashaCd*/
	/*END*/
/*END*/
ORDER BY
	 PSUB.ORDER_SHEET_NO NULLS FIRST
	,TO_CHAR(PSUB.ORDER_DATE, 'YYYYMMDD')
	,PSUB.VENDER_CD	
	,LOCATION_CD
	,ITEM_CD	
	,PSUB.SUGGESTED_DELIVERLIMIT_DATE
	,ORDER_H.ORDER_NO
