/*
 * Created on 2009/03/19
 *
 * $copyright$
 *
*/

/**
 * 出荷実績－出荷詳細データ取得SQL
 *
 * @author tosco
 *
 * entityName=ShippingResultDetailList
 * packageName=shippingresult
 * methodName=getEntity
 *
 */
SELECT
    SDETAIL.SHIPPING_NO
,   SDETAIL.SHIPPING_ROW_NO
,   SDETAIL.ROW_NO
,   SDETAIL.LOT_NO
,   SDETAIL.SHIPPING_INSTRUCTION
,   SDETAIL.SHIPPING_RESULT_DATE
,   SDETAIL.SHIPPING_RESULT_QUANTITY
,   SDETAIL.SHIPPING_STATUS
,   SDETAIL.SUMMERY
,   SDETAIL.LOCATION_CD
,   SDETAIL.DELIVERY_COMP
,   SDETAIL.PRODUCT_OUT_ORDER_BC
,   SDETAIL.INPUT_DATE
,   SDETAIL.INPUTOR_CD
,   SDETAIL.UPDATE_DATE
,   SDETAIL.UPDATOR_CD
,   LOCATION.LOCATION_NAME
,   LOT_INVENTORY.INVENTORY_QTY
FROM
    (SELECT
    	SDETAIL.*
    ,   SHEAD.ITEM_CD
     FROM
     	SHIPPING_DETAIL SDETAIL
	,   SHIPPING SHEAD
	 WHERE
		 SDETAIL.SHIPPING_NO = /*shippingNo*/
	 AND SDETAIL.SHIPPING_NO = SHEAD.SHIPPING_NO 
	) SDETAIL
,   LOCATION LOCATION
,   LOT_INVENTORY LOT_INVENTORY
WHERE
    SDETAIL.LOCATION_CD = LOCATION.LOCATION_CD(+)
AND LOT_INVENTORY.LOCATION_CD(+) = SDETAIL.LOCATION_CD
AND LOT_INVENTORY.ITEM_CD(+) = SDETAIL.ITEM_CD
AND LOT_INVENTORY.LOT_NO(+) = SDETAIL.LOT_NO
ORDER BY SHIPPING_ROW_NO
