/*
 * Created on 2009/02/17
 *
 * $copyright$
 *
*/

/**
 * 運送店別出荷指図画面一覧用SQL
 *
 * @author tosco
 *
 * entityName=CarryShippingList
 * packageName=carryshipping
 * methodName=getSearchList
 *
 */
SELECT	SHIPPING_TEMP.SHIPPING_INSTRUCT_DATE
,	SHIPPING_TEMP.VENDER_CD
,	SHIPPING_TEMP.DELIVERY_CD
,	SHIPPING_TEMP.DELIVERY_NAME
,	SHIPPING_TEMP.CARRY_CD
,	SHIPPING_TEMP.SENDING_OFF_NUMBER
,	SHIPPING_TEMP.SHIPPING_ORDER_SEND_COMP_FLAG
,	SHIPPING_TEMP.ITEM_CD
,	SHIPPING_TEMP.ITEM_NAME
,	SHIPPING_TEMP.ITEM_UNIT
,	SHIPPING_TEMP.SHIPPING_RESULT_DATE
,	SHIPPING_TEMP.INPUT_DATE
,	SHIPPING_TEMP.INPUTOR_CD
,	SHIPPING_TEMP.UPDATE_DATE
,	SHIPPING_TEMP.UPDATOR_CD

,	CARRY.CARRY_NAME1
,	CARRY.CARRY_NAME2
FROM	SHIPPING_TEMP
,	CARRY

WHERE	SHIPPING_TEMP.CARRY_CD = CARRY.CARRY_CD(+)
/*IF (( condition.srhShippingInstructDate != null ) && ( condition.srhShippingInstructDate != "" ))*/
	AND	TO_CHAR(SHIPPING_TEMP.SHIPPING_INSTRUCT_DATE,'YYYY/MM/DD') = /*condition.srhShippingInstructDate*/
/*END*/

ORDER BY SENDING_OFF_NUMBER