/*
 * 受注詳細品目リスト用SQL
 *
 * entityName=OrderDetailList
 * packageName=orderdetaillist
 * methodName=getDetailList
 *
 */
SELECT 
	ORDER_HEAD.ORDER_DIVISION
,	ORDER_DETAIL.ROW_NO
,	ORDER_DETAIL.ITEM_CD
,	ITEM.VERSION
,	ITEM.OTHER_COMPANY_CD1
,	ITEM.STYLE_OF_PACKING
,	ITEM.ITEM_NAME
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT
,	ORDER_DETAIL.ORDER_QTY
,	ORDER_DETAIL.ORDER_UNITPRICE
,	ORDER_DETAIL.STANDARD_UNITPRICE
,	ORDER_DETAIL.STANDARD_DISCOUNT
,	ORDER_DETAIL.SPECIAL_DISCOUNT
,	(ORDER_DETAIL.ORDER_QTY * ORDER_DETAIL.ORDER_UNITPRICE) AS ORDER_AMOUNT
,	ORDER_DETAIL.TMP_UNITPRICE_FLG
,	ORDER_DETAIL.MATSS
,	ORDER_DETAIL.ESTIMATE_STANDARD_AMOUNT
,	ORDER_DETAIL.ESTIMATE_MATSS    
,	SHIPPING.SHIPPING_STATUS as SHIPPING_STATUS
,	PURCHASE_SUBCONTRACT.STATUS as PURCHASE_STATUS
,	ASP_ORDER.WORK_STATUS as ASP_STATUS
,	NVL(
		CASE ORDER_HEAD.ORDER_DIVISION
			WHEN 3 THEN PURCHASE_STATUS.STATUS_CD
			ELSE SHIPPING_STATUS.STATUS_CD
		END,'99') AS STATUS_CD
,	NVL(
		CASE ORDER_HEAD.ORDER_DIVISION
			WHEN 3 THEN PURCHASE_STATUS.PURCHASE_STATUS_NAME
			ELSE SHIPPING_STATUS.SHIPPING_STATUS_NAME
		END,'受注登録') AS STATUS_NAME
,	ORDER_DETAIL.UPDATE_DATE

FROM
	ORDER_HEAD
,	ORDER_DETAIL
,	ITEM 
,	SHIPPING
,	(SELECT ORDER_NO,ORDER_ROW_NO,STATUS FROM PURCHASE_SUBCONTRACT WHERE ORDER_NO IS NOT NULL GROUP BY ORDER_NO,ORDER_ROW_NO,STATUS) PURCHASE_SUBCONTRACT
,	(SELECT NAMES.NAME_CD AS STATUS_CD
	,		NAMES.NAME01 AS SHIPPING_STATUS_NAME
	FROM	NAMES
	WHERE	NAMES.NAME_DIVISION = 'ORST'
	) SHIPPING_STATUS
,	(SELECT	NAMES.NAME_CD AS STATUS_CD
	,		NAMES.NAME01 AS PURCHASE_STATUS_NAME
	FROM	NAMES
	WHERE	NAMES.NAME_DIVISION = 'PUST'
	) PURCHASE_STATUS
,	ASP_PRODUCTION
,	ASP_ORDER
WHERE
	ORDER_HEAD.ORDER_NO = ORDER_DETAIL.ORDER_NO
AND	ORDER_DETAIL.ITEM_CD = ITEM.ITEM_CD(+)

AND	ORDER_DETAIL.SHIPPING_NO = SHIPPING.SHIPPING_NO(+)
AND	SHIPPING.SHIPPING_STATUS = SHIPPING_STATUS.STATUS_CD(+)

AND	ORDER_DETAIL.ORDER_NO = PURCHASE_SUBCONTRACT.ORDER_NO(+) 
AND	ORDER_DETAIL.ROW_NO = PURCHASE_SUBCONTRACT.ORDER_ROW_NO(+)
AND	PURCHASE_SUBCONTRACT.STATUS = PURCHASE_STATUS.STATUS_CD(+)

AND	ORDER_DETAIL.ORDER_NO = ASP_PRODUCTION.ORDER_NO(+)
AND	ORDER_DETAIL.ROW_NO = ASP_PRODUCTION.ORDER_ROW_NO(+)
AND	ASP_PRODUCTION.ORDER_CD = ASP_ORDER.ORDER_CD(+)

AND	ORDER_DETAIL.ORDER_NO = /*orderNo*/'JU999990002'

ORDER BY ORDER_DETAIL.ROW_NO ASC


