/*
 * 包装指図プロシージャ 工程名称 取得SQL
 *
 * entityName=PkgDirectionDirectionProcedureList
 * packageName=pkgdirection
 * methodName=getOperationName
 *
 */

SELECT
	DIRECTION_PROCEDURE.OPERATION_CD
,	OPERATION.OPERATION_NAME
FROM
	DIRECTION_PROCEDURE
,	OPERATION
WHERE
	DIRECTION_PROCEDURE.DIRECTION_DIVISION IN (2,3)
AND	DIRECTION_PROCEDURE.DIRECTION_NO = /*directionNo*/
AND DIRECTION_PROCEDURE.STEP_NO = /*stepNo*/
AND DIRECTION_PROCEDURE.OPERATION_CD = OPERATION.OPERATION_CD(+)
