/*
 * Created on 2009/02/26
 *
 * $copyright$
 *
*/

/**
 * 包装指図－処方ASPROVA－設備リスト検索用SQL
 *
 * @author tosco
 *
 * entityName=PkgDirectionRecipeAsprovaList
 * packageName=pkgdirection
 * methodName=getResouceList
 *
 */
SELECT
	RECIPE_ASPROVA.RECIPE_ID
,	RECIPE_ASPROVA.RESOUCE_GROUP_CD
,	RECIPE_ASPROVA.OPERATION_GROUP_CD
,	RECIPE_ASPROVA.RESOUCE_CD
,	RECIPE_RESOUCE.RESOUCE_NAME
FROM
	RECIPE_ASPROVA
,	RECIPE_RESOUCE

WHERE
	RECIPE_ASPROVA.RECIPE_ID = /*recipeId*/ AND
	RECIPE_ASPROVA.RESOUCE_CD = /*resouceCd*/ AND
	RECIPE_ASPROVA.RESOUCE_CD = RECIPE_RESOUCE.RESOUCE_CD(+)

ORDER BY
	RECIPE_ASPROVA.RESOUCE_GROUP_CD
,	RECIPE_ASPROVA.OPERATION_GROUP_CD
