/*
 * Created on 2009/03/16
 *
 * $copyright$
 *
*/

/**
 * 包装指図－製造指図フォーミュラ－配合詳細検索用SQL
 *
 * @author tosco
 *
 * entityName=PkgDirectionDirectionFormulaList
 * packageName=pkgdirection
 * methodName=getEntity
 *
 */
SELECT
	DIRECTION_FORMULA.DIRECTION_DIVISION
,	DIRECTION_FORMULA.DIRECTION_NO
,	DIRECTION_FORMULA.STEP_NO
,	DIRECTION_FORMULA.LINE_NO
,	DIRECTION_FORMULA.SEQ
,	DIRECTION_FORMULA.LINE_TYPE
,	DIRECTION_FORMULA.ITEM_CD
,	DIRECTION_FORMULA.TONYU
,	DIRECTION_FORMULA.DATAREAD
,	DIRECTION_FORMULA.TONYUSOKUDO
,	DIRECTION_FORMULA.QTY
,	DIRECTION_FORMULA.STOCKPD_QTY
,	DIRECTION_FORMULA.RESULT_QTY
,	DIRECTION_FORMULA.SAMPLE_QTY
,	DIRECTION_FORMULA.LOSS_QTY
,	DIRECTION_FORMULA.DEFECT_QTY
,	DIRECTION_FORMULA.ADJUST_QTY
,	DIRECTION_FORMULA.COST
,	DIRECTION_FORMULA.STEP_CONDITION
,	DIRECTION_FORMULA.NOTES
,	DIRECTION_FORMULA.LOCATION_CD
,	DIRECTION_FORMULA.NEXT_LOCATION_CD
,	DIRECTION_FORMULA.NEXT_AFTER_LOCATION_CD
,	DIRECTION_FORMULA.LOT_NO
,	DIRECTION_FORMULA.MANUFACTURER_LOT_NO
,	DIRECTION_FORMULA.FILL_QTY
,	DIRECTION_FORMULA.FILL_RESULT_QTY
,	DIRECTION_FORMULA.REMARK
,	DIRECTION_FORMULA.INPUT_DATE
,	DIRECTION_FORMULA.INPUTOR_CD
,	DIRECTION_FORMULA.UPDATE_DATE
,	DIRECTION_FORMULA.UPDATOR_CD
,	OPERATION.OPERATION_CD
,	OPERATION.OPERATION_NAME
,	ITEM.ITEM_NAME
,	ITEM.UNIT_OF_OPERATION_MANAGEMENT UNIT_DIVISION
,   NAME.NAME01 UNIT_NAME
FROM
	DIRECTION_FORMULA
,	DIRECTION_PROCEDURE
,   OPERATION
,	ITEM
,	NAMES NAME
WHERE
    DIRECTION_FORMULA.DIRECTION_DIVISION = /*directionDivision*/2
AND DIRECTION_FORMULA.DIRECTION_NO = /*directionNo*/'H0903060001'
AND DIRECTION_FORMULA.STEP_NO = /*stepNo*/1
AND DIRECTION_FORMULA.LINE_NO = /*lineNo*/1
AND DIRECTION_FORMULA.DIRECTION_DIVISION = DIRECTION_PROCEDURE.DIRECTION_DIVISION
AND DIRECTION_FORMULA.DIRECTION_NO = DIRECTION_PROCEDURE.DIRECTION_NO
AND DIRECTION_FORMULA.STEP_NO = DIRECTION_PROCEDURE.STEP_NO
AND DIRECTION_PROCEDURE.OPERATION_CD = OPERATION.OPERATION_CD(+)
AND DIRECTION_FORMULA.ITEM_CD = ITEM.ITEM_CD(+)
AND NAME.NAME_DIVISION(+) = 'UNIT'
AND NAME.NAME_CD(+) = ITEM.UNIT_OF_OPERATION_MANAGEMENT

