/*
 * 包装指図－製造指図明細ポップアップ画面検索用SQL
 *
 * entityName=PkgDirectionDirectionDetailSearchList
 * packageName=pkgdirection
 * methodName=getList
 *
 */

SELECT	DIRECTION_DETAIL.PKG_DIRECTION_NO		-- 包装指図番号
,		DIRECTION_DETAIL.ROW_NO					-- 行番号
,		DIRECTION_DETAIL.DIRECTION_NO			-- 製造指図番号
,		ITEM_PKG.ITEM_CD AS PKG_ITEM_CD			-- 品目コード(包装)
,		ITEM_PKG.ITEM_NAME AS PKG_ITEM_NAME		-- 品目名称(包装)
,		ITEM_DIR.ITEM_CD AS DIR_ITEM_CD			-- 品目コード(製造)
,		ITEM_DIR.ITEM_NAME AS DIR_ITEM_NAME		-- 品目名称(製造）
,		ITEM_DIR.UNIT_OF_OPERATION_MANAGEMENT	-- 運用管理単位(製造)
,		DIRH.PLANED_QTY							-- 予定生産量|仕込数量
,		DIRH.RESULT_QTY							-- 実績生産量
,		DIRH.COMPOUND_TANK_NO					-- 調合タンクNO
FROM	DIRECTION_DETAIL
,		DIRECTION_HEADER DIRH
,		DIRECTION_HEADER PKGH
,		ITEM ITEM_PKG
,		ITEM ITEM_DIR
WHERE	DIRECTION_DETAIL.PKG_DIRECTION_NO = /*condition.pkgDirectionNo*/'H0903100001'
  AND	PKGH.DIRECTION_DIVISION = /*condition.directionDivision*/2
  AND	DIRECTION_DETAIL.PKG_DIRECTION_NO = PKGH.DIRECTION_NO
  AND	DIRH.DIRECTION_DIVISION = 1
  AND	DIRECTION_DETAIL.DIRECTION_NO = DIRH.DIRECTION_NO
  AND	PKGH.ITEM_CD = ITEM_PKG.ITEM_CD(+)
  AND	DIRH.ITEM_CD = ITEM_DIR.ITEM_CD(+)
ORDER BY DIRECTION_DETAIL.DIRECTION_NO