/*
 * Created on 2009/03/02
 *
 * $copyright$
 *
*/

/**
 * 包装指図－製品入出庫実績一覧取得用SQL
 *
 * @author tosco
 *
 * entityName=PkgDirectionJissekiSeihinList
 * packageName=pkgdirection
 * methodName=getList
 *
 */
SELECT
	JISSEKI_SEIHIN.SEIHINCODE
,	JISSEKI_SEIHIN.IOCODE
,	JISSEKI_SEIHIN.JISHAFLAG
,	JISSEKI_SEIHIN.SEIHINLOT
,	JISSEKI_SEIHIN.HOSOSASHIZUNO
,	JISSEKI_SEIHIN.ZAIKOKUBUN
,	JISSEKI_SEIHIN.SEIHINKUBUN
,	JISSEKI_SEIHIN.LOCATION
,	JISSEKI_SEIHIN.SUURYOU
,	JISSEKI_SEIHIN.NYUKANO
,	JISSEKI_SEIHIN.NYUKABC
,	JISSEKI_SEIHIN.JUCHUNO
,	JISSEKI_SEIHIN.JUCHUEDABAN
,	JISSEKI_SEIHIN.TORIHIKICODE
,	JISSEKI_SEIHIN.HACCHUNO
,	JISSEKI_SEIHIN.JIKOKU
,	JISSEKI_SEIHIN.NYUUSYUKKO
,	JISSEKI_SEIHIN.SUMI
FROM
	JISSEKI_SEIHIN
WHERE
	JISSEKI_SEIHIN.SEIHINCODE = /*itemCd*/ AND
	JISSEKI_SEIHIN.HOSOSASHIZUNO = /*pkgDirectionNo*/
