/*
 * 
 *
 * entityName=RepSlipShippingNewTagHeader
 * packageName=repSlipShippingNewTagHeader
 * methodName=getSlipShippingList
 *
 */

SELECT
	 KEY
,    ORDER_NO
,    DELIVERY_ADDRESS_ALL
,    DELIVERY_NAME1
,    DELIVERY_NAME2
,    DELIVERY_TEL_NO
,    SCHEDULED_SHIPPING_DATE
,    DELIVERY_EXPECTED_DATE
,    DELIVERY_EXPECTED_TIME
,    SHIP_FROM_ADDRESS
,    SHIP_FROM_NAME
,    SHIP_FROM_TEL_NO
,    DELIVERY_CD
,    MIN(SHIPPING_SLIP_NO) AS SHIPPING_SLIP_NO
,    CARRY_CD
,    REPOTR_OUTPUT_NUM

FROM  REP_SLIP_SHIP_NEW_TAG_HEAD

WHERE 
	　　SHIPPING_NO IN /*shippingNo*/('SK000000001')
AND
	LABEL_PUBLISH = 2 --2:荷札
	
GROUP BY
	 KEY
,    ORDER_NO
,    DELIVERY_ADDRESS_ALL
,    DELIVERY_NAME1
,    DELIVERY_NAME2
,    DELIVERY_TEL_NO
,    SCHEDULED_SHIPPING_DATE
,    DELIVERY_EXPECTED_DATE
,    DELIVERY_EXPECTED_TIME
,    SHIP_FROM_ADDRESS
,    SHIP_FROM_NAME
,    SHIP_FROM_TEL_NO
,    DELIVERY_CD
,    CARRY_CD
,    REPOTR_OUTPUT_NUM

ORDER BY
	  KEY
	 ,REPOTR_OUTPUT_NUM
	 ,CARRY_CD
	 ,SHIPPING_SLIP_NO